ban user for post more than 5
CorporationX/post_service pull request #1003
Opened 2024-10-21 12:07 UTC by aassylkhan

2024-10-21 14:28 UTC, SharkB38 commented on src/main/java/faang/school/postservice/scheduler/AuthorBannerScheduler.java
> +    @Retryable(retryFor = {UserBanException.class}, backoff = @Backoff(delay = 5000))
Можно delay в конфиг вынести

2024-10-21 14:28 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    }
А сам бан в user_service у Арстана происходит получается?

2024-10-21 17:06 UTC, ArstanSubanov approved these changes
👍

2024-10-22 05:42 UTC, aassylkhan commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    }
> А сам бан в user_service у Арстана происходит получается?

Даа, у него есть user_ban_channel

2024-10-22 06:02 UTC, SharkB38 approved these changes

2024-10-22 12:01 UTC, wmwmaks commented on src/main/java/faang/school/postservice/scheduler/AuthorBannerScheduler.java
> +            postService.banAuthorsWithUnverifiedPostsMoreThan(banPostLimit);
может, сюда тоже добавить лог об успешном бане?

2024-10-22 12:04 UTC, wmwmaks commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    }
Может, в лог добавить еще сам список id юзеров для бана?
log.info("Found {} authors to ban: {}", authorIds.size(), authorIds);

2024-10-22 12:06 UTC, wmwmaks approved these changes
👍

2024-10-22 21:05 UTC, mysosnovskaya requested changes
У тебя прям совсем компактная работа получилась) Но и круто! Уже пользуешься кодом, который был написан ранее другим разработчиком. Чем дальше, тем всё более реальная разработка у нас получается)

2024-10-22 21:05 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    }
Да, хорошая идея)

2024-10-22 21:05 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/post_V004_ad_verified.sql
> +    ADD COLUMN IF NOT EXISTS verified boolean DEFAULT false NOT NULL,
Ой-ой-ой, существующие миграции нельзя менять ни в коем случае. Тут нужно подробнее знакомиться с механизмом миграций, но если сделать так и попытаться запустить сервис, например, в продакшне, где уже была применена предыдущая версия миграции, то сервис не запустится из-за несовпадения чексуммы файла post_V004_ad_verified.sql

2024-10-22 21:05 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/AuthorBannerScheduler.java
> +            postService.banAuthorsWithUnverifiedPostsMoreThan(banPostLimit);
Я бы добавила лог о том, что шедулер проснулся и начал свою работу - вот это в данном контексте важно. А за успешный бан отвечает не этот класс)

2024-10-23 10:38 UTC, aassylkhan commented on src/main/resources/db/changelog/changeset/post_V004_ad_verified.sql
> +    ADD COLUMN IF NOT EXISTS verified boolean DEFAULT false NOT NULL,
@mysosnovskaya  Когда запулил, у меня проект не запускался из за версии. Там V004 2 штуки были. Что мне сделать? Ждать когда пофиксят в главной ветке или так пушить?

2024-10-24 06:11 UTC, aassylkhan commented on src/main/resources/db/changelog/changeset/post_V004_ad_verified.sql
> +    ADD COLUMN IF NOT EXISTS verified boolean DEFAULT false NOT NULL,
Откатил обратно. Но в главной ветке кому то надо исправить. V004 Руслан и Арстан написали.

2024-10-24 17:52 UTC, mysosnovskaya commented
@aassylkhan Сборка завалилась, тесты не проходят. Поправь, пожалуйста

2024-10-28 18:54 UTC, mysosnovskaya approved these changes

2024-10-28 18:55 UTC, merged