BJS2-27144   Уведомление о получении комментария
CorporationX/post_service pull request #1005
Opened 2024-10-24 14:46 UTC by ilu23ilu23

Создан публишер для отправки данных через редис в сервис нотификаций при создании коммента.

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +    public void publishCommentNotificationEventAdvice(JoinPoint joinPoint, Object savedComment) {
Я посмотрел где эа аннотация ипользуется
```
PublishEvent(eventType = CommentEvent.class)
    @Transactional
    public Comment createComment(Long postId, Comment comment)
```
Если идея была использовать одну аннотацию, а параметризовать тем что в скобках, то как спринг узнает каким аспектом тлавливать.

То есть если есть
@PublishEvent(eventType = CommentEvent.class)
и
@PublishEvent(eventType = PostEvent.class)

то как спринг отработает и пошлет CommentEvent в CommentEventAspect а PostEvent в PostEventApect?

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +        }
Этот ивент во все аспекты прилетит, просто тут отсекаться будет?

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +            pointcut = "@annotation(faang.school.postservice.annotations.PublishEvent)",
Я бы переименовал 
@PublishEvent(eventType = CommentEvent.class)
в
CreateCommentEvent

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +@Component
Дима говорил, чтобы аннотации restcontroller, component и т.п. сразу над классом шли

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +public class CommentNotificationEventPublishingAspect {
В дискорде писал уже. Что мы просто поосылаем какой-то ивент в редис. А что там с им будет происходить - это уже ллистенеры будет подключаться.
То есть тут просто CommentEventPublishingAspect
а уже из редиса и в нотификации, и в аналитику, и в ачивменты

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +            pointcut = "@annotation(faang.school.postservice.annotations.PublishEvent)",
И ещё в коде найди
```
        Comment savedComment = commentRepository.save(comment);
        return savedComment;
    }
```
и поменяй на 
```
        return commentRepository.save(comment);
    }
```

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +        if (!(savedComment instanceof Comment)) {
В Java 17 можно написать
savedComment instanceof Comment comment)

можно исползовать comment без приведения

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +        if (!(savedComment instanceof Comment)) {
И ещё продебажь, а comment.getPost() - можно взять или там лэйзи экзепшн

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/service/comment/CommentNotificationEventService.java
> +            CommentNotificationEvent event = new CommentNotificationEvent(
CreateCommentEvent

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/service/comment/CommentNotificationEventService.java
> +    private final RedisCommentNotificationEventPublisher commentNotificationEventPublisher;
В общем я бы везде 
CommentNotificationEvent
поменял бы на 
CreateCommentEvent

2024-10-24 15:50 UTC, amilosh commented on src/main/resources/application.yaml
> +          name: comment_notification_event
тут подчисти чтобы был один create_comment_topic
а его будут два слушателя - нтификейше и ачивмент

то есть нам не надо оздавать
comment_notification_event
comment_achievement_event

и comment_event посмотри для каких нужд

2024-10-24 15:50 UTC, amilosh commented on src/main/java/faang/school/postservice/publisher/comment/RedisCommentNotificationEventPublisher.java
> +    private final Topic commentNotificationTopic;
Мы разбирались и выснили, что для паблишера не нужно топик создавать. Можно просто стрингу отправлять.

Это для листенера обязательно.

2024-10-24 15:50 UTC, amilosh commented on src/test/java/faang/school/postservice/publisher/comment/RedisCommentNotificationEventPublisherTest.java
> +        RedisTopicsFactory redisTopicsFactory = mock(RedisTopicsFactory.class);
Это вроде то же саме что и
```
    @Mock
    private RedisTopicsFactory redisTopicsFactory;
```

2024-10-24 15:50 UTC, amilosh commented on src/test/java/faang/school/postservice/publisher/comment/RedisCommentNotificationEventPublisherTest.java
> +        when(redisTopicsFactory.getTopic("comment_notification_event_channel"))
"comment_notification_event_channel" - в статическое поле вынеси

2024-10-24 16:15 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +    public void publishCommentNotificationEventAdvice(JoinPoint joinPoint, Object savedComment) {
Да, недоглядел, придумаю что-нибудь

2024-10-24 16:16 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +            pointcut = "@annotation(faang.school.postservice.annotations.PublishEvent)",
Была задумка одну общую аннотацию сделать

2024-10-24 16:32 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +    public void publishCommentNotificationEventAdvice(JoinPoint joinPoint, Object savedComment) {
Решил просто отдельные аннотации сделать, так проще

2024-10-24 16:35 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/aop/aspects/CommentNotificationEventPublishingAspect.java
> +public class CommentNotificationEventPublishingAspect {
Данные разные требуются, до этого задание просило одно в дто указывать, в текущем уже другие данные, решил, чтобы в сервисах снова всё не менять, отдельную напишу реализацию

2024-10-24 16:37 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/comment/CommentNotificationEventService.java
> +    private final RedisCommentNotificationEventPublisher commentNotificationEventPublisher;
Пока оставлю, так понятнее будет, что в нотификацию отправляется

2024-10-24 16:38 UTC, ilu23ilu23 commented on src/main/resources/application.yaml
> +          name: comment_notification_event
Там разные данные, я выше отвечал

2024-10-29 19:29 UTC, 20cognosce requested changes
Объясни несовместимость формата событий комментария, требующую два топика

2024-10-29 19:29 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/comment/CommentNotificationEventService.java
> +            CommentNotificationEvent event = new CommentNotificationEvent(
Можно в мапперы / отдельный класс билдера выносить все эти создания, много места занимают

2024-10-29 19:29 UTC, 20cognosce commented on src/main/java/faang/school/postservice/aop/aspects/CommentEventPublishingAspect.java
> +            pointcut = "@annotation(faang.school.postservice.annotations.PublishCommentEvent)",
Чем отличается от NotificationEvent?

2024-10-29 19:29 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/comment/CommentNotificationEventService.java
> +    public void handleCommentEvent(Long postId, Comment savedComment) {
В чем разница CommentEventService.handleCommentEvent, зачем второго паблишера создал?

2024-10-29 19:29 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/comment/CommentNotificationEvent.java
> +    private String content;
CommentEvent нельзя было дополнить, лучше второго паблишера создать, серьёзно?

2024-10-31 05:57 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/dto/comment/CommentNotificationEvent.java
> +    private String content;
Там совсем разная инфа, одним паблишером я отправляю в аналитик сервис, другим в нотификейшн сервис, и везде требуется нужная информация, ты же говорил, что нужно только нужную информацию отправлять, так я и сделал, ничего же страшного в этом не случилось?) Чтобы не запутаться, сделал отдельно

2024-10-31 05:59 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/dto/comment/CommentNotificationEvent.java
> +    private String content;
Мне тогда пришлось бы менять дто в аналитик сервисе(создавать новую ветку, новый пр, снова всё сливать, а тут просто пару классов добавил в этой задаче.

2024-11-01 21:15 UTC, 20cognosce approved these changes

2024-11-01 21:16 UTC, merged