feature/BJS2-40843
CorporationX/post_service pull request #1024
Opened 2024-11-11 12:45 UTC by m1rroxxx

система лайков

2024-11-15 15:16 UTC, MiraGlaceon requested changes

2024-11-15 15:16 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/validator/LikeValidator.java
> +        if ((dto.getCommentId() == null) == (dto.getPostId() == null)) {
Такие моменты разве не сможем провалидировать через аннотацию @Valid? Посмотри, может этот код можно заменить на эти аннотации

2024-11-15 15:36 UTC, m1rroxxx commented on src/main/java/faang/school/postservice/validator/LikeValidator.java
> +        if ((dto.getCommentId() == null) == (dto.getPostId() == null)) {
я пробовал, эта библиотека не может делать сравнения между полями, тут я сравниваю либо оба поля нулл, либо оба не нулл ( потому что должно быть одно нулл второе не нулл )  
можно сделать свою анатацию только, но мне показалось что это лишнее)

2024-11-18 15:50 UTC, MiraGlaceon approved these changes

2024-11-19 08:00 UTC, merged