Task BJS2-40820 is done
CorporationX/post_service pull request #1034
Opened 2024-11-12 17:46 UTC by Memoreks

2024-11-14 05:45 UTC, abdddev approved these changes
А вопросов как бы и нет, все оч круто)
Только @Data и @Slf4 поднял бы наверх, но это так мелочи)
и тут не понял
    @GetMapping("/api/v1/users/{userId}")
    UserDto getUser(@PathVariable Long userId);

    @PostMapping("/users")
    @PostMapping("/users/by-ids")
    
сервис вроде один, там есть /api/v1, а там нет
ну и вынести бы) как в настройки клиента мб, ну они выпустили v2 апишки и все мы поплыли)

2024-11-14 06:21 UTC, abzalkhan00 reviewed
Отличный код, для себя даже нашел кое-что полезное, что можно использовать. Есть только один комментарий по поводу именований в маппингах

2024-11-14 06:21 UTC, abzalkhan00 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/user_drafts/{userId}")
Я не совсем уверен, но, по-моему, имена в mapping лучше делать без нижних подчеркиваний  можно просто использовать дефис. Я видел такой стиль чаще

2024-11-14 06:40 UTC, mad1xx1dam reviewed
Всё круто и максимально понятно
По некоторым моментам предложения оставил, а так чётко

2024-11-14 06:40 UTC, mad1xx1dam commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Мне кажется, можно через ResponseBody явно указать статус created для 201 кода. По идее по умолчанию, несмотря на postMapping, вернет 200 просто

2024-11-14 06:40 UTC, mad1xx1dam commented on src/main/java/faang/school/postservice/validator/post/PostValidator.java
> +    public void checkCreator(PostDto postDto) {
Заметил, что, когда используем какую-то одну общую dto для ответов/запросов, при запросе на создание не проверяем, допустим, id (вдруг передали непустое значение, тогда при использовании save hibernate может просто перезаписать информацию о каком-то существующем посте)

+в dto могут накидать updatedAt, publishedAt, scheduledAt

Но я так понял, что принимаем, что не станут передавать такую информацию, используя подход с одним dto для разных запросов/ответов, поэтому, наверное, всё окк

2024-11-14 06:40 UTC, mad1xx1dam commented on src/main/java/faang/school/postservice/validator/post/PostValidator.java
> +            userServiceClient.getUser(postDto.getAuthorId());
Не знаю, как правильно надо будет делать, но такое ощущение, что можно пробовать тут в try catch ловить FeignException (NotFound или общий) и оборачивать его в кастомное исключение (те же EntityNotFoundException / DataValidationException, которые будут использоваться для exceptionHandler)

Могу быть не прав

2024-11-14 06:40 UTC, mad1xx1dam commented on src/main/java/faang/school/postservice/validator/post/PostValidator.java
> +            throw new PostException("Necessary indicate the author or project");
Наверное, можно, как в других сервисах, использовать DataValidationException для простоты обработки в будущем, чтобы еще не писать схожую логики обработки для PostException

2024-11-14 06:40 UTC, mad1xx1dam commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        post.setUpdatedAt(LocalDateTime.now());
Можно не проставлять, как я понял
Там в классе сущности над updatedAt стоит аннотация @UpdateTimestamp

С createdAt тот же момент, там @CreationStamp

2024-11-14 06:40 UTC, mad1xx1dam commented on src/test/java/faang/school/postservice/validator/post/PostValidatorTest.java
> +        postValidator.checkCreator(postDto);
можно assertDoesNotThrow для наглядности поставить

2024-11-14 06:40 UTC, mad1xx1dam commented on src/test/java/faang/school/postservice/validator/post/PostValidatorTest.java
> +    public void checkUpdatePostWithChangeAuthorTest() {
учитывая такие хорошие подробные тесты, можно еще было добавить тест, когда только id project меняется

2024-11-14 06:40 UTC, mad1xx1dam commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +public class PostServiceTest {
Все шикарно, единственное - можно аналогично тесту getPostById добавить тесты для других методов, в которых используется приватный getPost, чтобы выброс исключения проверять

2024-11-14 08:05 UTC, Memoreks commented
> А вопросов как бы и нет, все оч круто) Только @DaTa и @slf4 поднял бы наверх, но это так мелочи) и тут не понял @GetMapping("/api/v1/users/{userId}") UserDto getUser(@PathVariable Long userId);
> 
> ```
> @PostMapping("/users")
> @PostMapping("/users/by-ids")
> ```
> 
> сервис вроде один, там есть /api/v1, а там нет ну и вынести бы) как в настройки клиента мб, ну они выпустили v2 апишки и все мы поплыли)

@abdddev баловался с настройками users по задаче дергал, а users/by-ids не трогал и забыл API прописать
Вынес все в application.yaml

2024-11-14 08:05 UTC, Memoreks commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/user_drafts/{userId}")
Точно, спасибо

2024-11-14 08:18 UTC, Memoreks commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Лекций про это еще не было
Нашел такое решение - @ResponseStatus(HttpStatus.CREATED)
Добавил изменение

2024-11-14 08:20 UTC, mad1xx1dam commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        post.setUpdatedAt(LocalDateTime.now());
Хотя учитывая, что в dto не то могут передать, лучше так, конечно

2024-11-14 08:25 UTC, Memoreks commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        post.setUpdatedAt(LocalDateTime.now());
Спасибо, убрал

2024-11-14 08:27 UTC, Memoreks commented on src/test/java/faang/school/postservice/validator/post/PostValidatorTest.java
> +        postValidator.checkCreator(postDto);
Добавил

2024-11-14 08:29 UTC, Memoreks commented on src/test/java/faang/school/postservice/validator/post/PostValidatorTest.java
> +    public void checkUpdatePostWithChangeAuthorTest() {
Добавил

2024-11-14 08:33 UTC, Memoreks commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +public class PostServiceTest {
Как раз тестом getNoExistPostByIdTest покрываю выброс исключения из приватного getPost

2024-11-14 08:34 UTC, Memoreks commented
@mad1xx1dam , @abdddev , @abzalkhan00 спасибо за ревью)

2024-11-14 08:39 UTC, mad1xx1dam approved these changes

2024-11-14 15:23 UTC, VovaBuzivskyi commented
Хорошо написанный код! Оставил несколько комментариев.

2024-11-14 15:24 UTC, VovaBuzivskyi commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .orElseThrow(() -> new PostException("Post with id " + postId + " not found"));
Мне кажется здесь лучше выкидывать EntityNoyFoundException. Просто название PostException  не говорит из-за чего вызвано исключение.

2024-11-14 15:24 UTC, VovaBuzivskyi commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +    public void createPostTest() {
Нету вызовов verify(postValidator) и в updatePost тоже. Получается мы не можем быть уверены что валидация вызывается.

2024-11-14 15:55 UTC, Memoreks commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .orElseThrow(() -> new PostException("Post with id " + postId + " not found"));
Ага, изменю

2024-11-14 15:56 UTC, Memoreks commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +    public void createPostTest() {
Хорошо, добавлю

2024-11-15 10:15 UTC, BobrAll requested changes
Очень здорово все сделал, прям глаз радуется. Немного оставил комментариев

2024-11-15 10:15 UTC, BobrAll commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Для удаления есть специальный метод http-запроса - delete

2024-11-15 10:15 UTC, BobrAll commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        return postService.getAllNoPublishPostByUserId(userId);
Мы же посты ищем, а не пост
Тогда лучше posts в названии методов использовать

2024-11-15 10:15 UTC, BobrAll commented on src/main/java/faang/school/postservice/controller/PostController.java
> +public class PostController {
Я бы немного поменял:
/user-drafts/{userId}          -> /drafts/users/{userId}
/project-drafts/{projectId} -> /drafts/projects/{projectId}
В целом можно оставить как есть. Такой вариант просто выглядит более логично с точки зрения иерархии в url

2024-11-15 10:15 UTC, BobrAll commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
По аналогии с предыдущим комментарием можно тут поменять

2024-11-15 10:15 UTC, BobrAll commented on src/main/java/faang/school/postservice/mapper/PostMapper.java
> +    void update(PostDto postDto, @MappingTarget Post post);
Для читаемости при вызове метода можно добавить конкретики, updatePostFromDto

2024-11-15 10:15 UTC, BobrAll commented on src/main/java/faang/school/postservice/validator/post/PostValidator.java
> +    public void checkCreator(PostDto postDto) {
@mad1xx1dam ты прав тут 100%, если что-то можно сломать, пользователи обязательно сломают. Мы раньше использовали подход с 1 дто, когда у нас +- одинаковые запросы были. Сейчас лучше бы разделять для разных запросов @Memoreks

2024-11-15 10:34 UTC, Memoreks commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Поправил

2024-11-15 10:35 UTC, Memoreks commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        return postService.getAllNoPublishPostByUserId(userId);
Поправил

2024-11-15 10:37 UTC, Memoreks commented on src/main/java/faang/school/postservice/controller/PostController.java
> +public class PostController {
Поправил

2024-11-15 10:37 UTC, Memoreks commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Поправил

2024-11-15 10:38 UTC, Memoreks commented on src/main/java/faang/school/postservice/mapper/PostMapper.java
> +    void update(PostDto postDto, @MappingTarget Post post);
Поправил

2024-11-15 11:54 UTC, abzalkhan00 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Но он же не совсем удаляет, а меняет статус на isActive flase, или в этом случае тоже использовать Delete?

2024-11-15 12:00 UTC, BobrAll commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Тогда нужно метод назвать disablePostById (На гитхабе нельзя сразу проскочить в тело метода и глянуть код, а на вид тут именно как удаление)
И метод запроса тогда patch, как частичное обновление, а url /{postId}/disable

2024-11-16 05:10 UTC, Memoreks commented on src/main/java/faang/school/postservice/validator/post/PostValidator.java
> +    public void checkCreator(PostDto postDto) {
Поправил

2024-11-16 14:35 UTC, BobrAll approved these changes
Отлично

2024-11-16 14:36 UTC, merged