Bjs2 40848
CorporationX/post_service pull request #1051
Opened 2024-11-14 20:41 UTC by RuslanGabd

2024-11-15 10:55 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public ResponseEntity<Void> draftPost(@RequestBody PostDto postDto) {
Обертка не нужно. Раньше было, сейчас просто void.
Не знаю, в задании ли так написано, обычно при создании возвращают ИД с которым создали обьект в БД.

2024-11-15 10:56 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
Здесь не нужен return. Статус добавит Spring. 
Будет нужно, если решишь ИД вернуть.

2024-11-15 11:18 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public ResponseEntity<PostDto> getPost(@RequestParam(required = false) Long postId) {
Можно просто вернуть PostDto

2024-11-15 11:18 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/service/PostService.java
> +
Не критично, может нужно заключение Евгения, но так как есть несколько запросов: дайте то и дайте это, можно  подумать об абстракции. Создать интерфейс фильтра/поиска, а туда подкладывать реализации, при этом параметры можно обьединить в обин класс и его передавать, как набор для...

2024-11-15 13:48 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping(UrlUtils.ID + UrlUtils.UPDATE)
Put предлагаю заменить на PatchMapping

2024-11-15 13:48 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/utilities/UrlUtils.java
> +    public static final String DELETE = "/delete";
DELETE = "/delete", UPDATE = "/update"; и PUBLISH = "/publish"; ( если это добавить) - не нужны.
PutMapping, DeleteMapping и PatchMapping - заменяют это

2024-11-15 15:06 UTC, RuslanGabd commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public ResponseEntity<PostDto> getPost(@RequestParam(required = false) Long postId) {
Оставлю так) все так больше гибкости может в дальнейшем пригодиться

2024-11-15 18:51 UTC, jibulani requested changes
в целом все ок, есть несколько замечаний, которые нужно поправить
также не забудь написать тесты и проверить работу сервиса через постман - к задаче приложи скрин какого-нибудь запроса в постмане

2024-11-15 18:51 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                temp = "Project id: ";
если используешь переменную temp, то лучше сначала обновить ее текст, а потом уже получать проект, а то получается, что пытаешься получить проект, но вылетает ошибка, в итоге в переменной temp остается значение "User id:", хотя должно быть "Project id:"

2024-11-15 18:51 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        if (postRepository.findById(id).isEmpty()) {
зачем это делать тут, если ты это проверяешь еще и в сервисе?
то есть в случае наличия поста, ты за ним дважды в базу ходишь, создавая на нее лишнюю нагрузку и заставляя пользователя дольше ждать ответа

2024-11-15 18:51 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    private final PostRepository postRepository;
контроллеры должны быть максимально глупыми, достаточно в них проверить, что содержимое запроса валидное (не null, не empty и т.д. без походов в другие сервисы) и передать работу сервису-обработчику контроллера (PostService)
наличие тут зависимостей от других компонентов приложения, говорит, что контроллер делает больше, чем должен

2024-11-15 18:51 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +        post.setPublished(true);
не проверено условие задания:

> Нельзя ещё раз опубликовать пост, который уже был опубликован ранее.

2024-11-15 18:51 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        checkPostExistsById(postId);
этим должен заниматься сервис

2024-11-15 18:51 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +
хорошая идея, @RuslanGabd если есть время, рекомендую сделать через фильтры, так как методы однотипные и по сути дублируют код с разными условиями - по тому, как делать фильтры, Влад рассказывал в 5 и 6 спринтах в видеоуроках

2024-11-19 15:47 UTC, RuslanGabd commented
<img width="458" alt="image" src="https://github.com/user-attachments/assets/acc4db16-5f37-48de-aa69-d95a612895e8">
<img width="455" alt="image" src="https://github.com/user-attachments/assets/3f26bf16-d99e-4a36-b694-c24a9312e346">

2024-11-19 20:17 UTC, jibulani approved these changes
супер! тесты огонь! 🔥

2024-11-19 20:17 UTC, merged