Система комментариев
CorporationX/post_service pull request #1058
Opened 2024-11-15 13:58 UTC by dimaevseenko

2024-11-15 18:02 UTC, 24slavaK commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +        return commentMapper.toDto(commentRepository.findAllByPostId(postId).stream().sorted(Comparator.comparing(Comment::getCreatedAt).reversed()).toList());
тут точно потерялось пату /n

2024-11-15 19:31 UTC, dimaevseenko commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +        return commentMapper.toDto(commentRepository.findAllByPostId(postId).stream().sorted(Comparator.comparing(Comment::getCreatedAt).reversed()).toList());
Поправил

2024-11-18 16:01 UTC, MiraGlaceon requested changes

2024-11-18 16:01 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    CommentDto createComment(@RequestBody CommentDto commentDto) {
Тестировал через postman? У тебя нет модификатора доступа публичного. Не уверен, что с дефолтным работает

2024-11-18 16:06 UTC, dimaevseenko commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    CommentDto createComment(@RequestBody CommentDto commentDto) {
Да, тестировал, все работает. Сейчас поправлю.

2024-11-22 14:32 UTC, MiraGlaceon approved these changes

2024-11-22 14:33 UTC, merged