BJS2-40983 added PostDto validation
CorporationX/post_service pull request #1123
Opened 2024-11-20 12:07 UTC by RuslanGabd

Условия задачи
Нужно внедрить валидацию в Post Service org.springframework.boot:spring-boot-starter-validation.

Убрать приватные методы для проверки полей в dto, заменить их соответствующими аннотациями с кастовыми message при ошибке. Например: @NotBlank(message = "description should not be blank").

Для различных паттернов RequestFilter поставить ограничение по размеру длины строки паттерна — 255 символов.

Не забыть проставить аннотации @Validated, для проверки dto и выброса исключения.

2024-11-20 12:07 UTC, RuslanGabd commented
<img width="595" alt="image" src="https://github.com/user-attachments/assets/6c79ebe3-d511-4874-a4fa-0330e507b6a7">

2024-11-20 16:55 UTC, Alex15265 approved these changes

2024-11-20 16:55 UTC, Alex15265 commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +        Long userId,
можно проверить айдишники на условие >1 (@ Min(1))

2024-11-20 16:55 UTC, Alex15265 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public Long createDraftPost(@Valid PostDto postDto) {
как будто можно все эти проверки уже на уровне контроллера выполнить

2024-11-20 16:55 UTC, Alex15265 commented on src/main/java/faang/school/postservice/service/PostService.java
> +@Validated
Если используется аннотация @ Valid для проверки параметров запроса или тела запроса, то в добавлении аннотации @ Validated на уровне класса нет необходимости.

2024-11-21 16:34 UTC, jibulani requested changes
хорошо, но не забывай удалять ненужные больше методы
также проверь, что тесты проходят, скорее всего некоторые тесты на контроллер надо актуализировать

2024-11-21 16:34 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/PostController.java
>          checkPostDtoContainsContent(postDto);
получается, этот метод больше не нужен, раз есть проверка через аннотации

2024-11-22 20:38 UTC, jibulani approved these changes
супер!

2024-11-22 20:38 UTC, merged