BJS2-27175 Публикация эвента поста в Kafka
CorporationX/post_service pull request #1177
Opened 2024-11-24 13:51 UTC by cemeh666

2024-11-24 14:50 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +    public void sendPostEvent(Post post) {
Если следовать видео лекциям, нужно отправку событий реализовывать таким образом, что у нас подписчиков может быть несколько миллионов. То есть, у тебя в PostFeedEventDto будет в списке подписчиков очень много айдишников, и в таких случаях нужно посылать не один ивент, а разделять на несколько сообщений. Ну если я правильно понял лекции

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +@EnableKafka
У меня без этой аннотации работает

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/config/kafka/KafkaPublisherConfig.java
> +public class KafkaPublisherConfig {
В контексте кафки они свои сервисы назвают producer и consumer

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/config/kafka/KafkaPublisherConfig.java
> +    }
если в одном классе, я обычно так делаю
```
    @Bean
    public KafkaTemplate<String, Object> kafkaTemplate() {
        return new KafkaTemplate<>(producerFactory());
    }
```

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/PostFeedEventDto.java
> +    List<Long> subscribersIds;
private

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +    private String topic;
вроде как в кафке не ипользуют понятие channel - только топики
и советуют назвать топик типа post-created-topic, comment-liked-topic

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/PostFeedEventDto.java
> +    List<Long> subscribersIds;
private Long authorId; - я это не передавал
мы всё равно в фиде будем хранить только postId
а когда будем в /feed возарщать, то по этим postId будем брать посты из таблицы posts редиса, и уже в ни будет authorId

2024-11-24 15:03 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/PostFeedEventDto.java
> +    List<Long> subscribersIds;
и private LocalDateTime publishedAt; - тут ообязательно нужно переддать
мы будем посты в фид скзалдывать и сортировать по дате публикации

2024-11-24 16:11 UTC, cemeh666 commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +@EnableKafka
это больше для информации, что подключена и работает Kafka

2024-11-24 16:13 UTC, cemeh666 commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +    public void sendPostEvent(Post post) {
ну вот это нужно будет уточнить конечно

2024-11-27 19:18 UTC, 20cognosce requested changes

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/async/SingleThreadAsyncConfig.java
> +    }
Для Async можно не заводить, по умолчанию, насколько я помню, в Async дефолтный пул
ThreadPoolTaskExecutor / SimpleAsyncTaskExecutor 
Имеющий 1 поток всегда и MAX_INT в пределе

Есть ли необходимость в этой задаче жестко ограничиваться одним потоком

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/PostFeedEventDto.java
> +@Data
Посмотри, что включается в себя эта аннотация

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +    public void sendPostEvent(Post post) {
Да, нужно разбивать на 100 юзеров максимум события
И Async над этим методом - бутылочное горлышко, так как все посты будут утыкаться в один поток

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +    }
Это плохо, потому что слишком много запросов к user_service, когда тебе нужно только id пользователей

Доработать user_service, чтобы получать сразу весь список ID, только ID

2,147,483,647 - максимальный размер arraylist, думаю, >2 миллиарда подписчиков невозможное событие

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +            int finalPage = page;
Вот это заменить на ListUtil.sublist

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +                setTechnicalUserInContext();
Зачем два раза
И почему это каждый раз вызывает в этом методе? При старте приложения пропиши техническую учетную запись в пропертях и устанавливай её всем запросам

2024-11-27 19:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +        } catch (Exception exception) {
А какие тут могут быть ошибки? Только сетевые?
Может тоже ретрай необходим

2024-12-01 09:55 UTC, 20cognosce approved these changes

2024-12-01 09:55 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/KafkaPostProducer.java
> +        for (List<Long> batchFollowers : partitionsFollowers) {
forEach

2024-12-01 09:55 UTC, merged