BJS2-41075 completed without tests
CorporationX/post_service pull request #1179
Opened 2024-11-24 15:37 UTC by RuslanGabd

Условия задачи
Необходимо настроить добавление картинок к постам.

Когда пользователь создаёт пост, то у него должна быть возможность добавить к этому посту не только текст, но и картинки. Максимум 10 штук. Эти картинки не должны храниться в БД сами.

Все файлы храним в файловом хранилище Minio, используем Amazon S3 API для манипулировали файлами (Minio полностью совместимо с Amazon S3 API), в основной базе PostgreSQL — только id файлов для нахождения их в бакетах.

Нужно добавить ограничение на размер загружаемого файла (не должен превышать 5 МБ). При загрузке если разрешение выше при горизонтальном изображении — 1080×566 пикселей, квадратном — 1080×1080 пикселей, то картинка должна ужиматься. Количество*:* до 10 картинок в одном посте.

Также нужно предусмотреть возможность изменения поста, где могут добавиться/удалиться определённые картинки.

2024-11-25 15:30 UTC, RuslanGabd commented
<img width="608" alt="image" src="https://github.com/user-attachments/assets/cf154363-fe30-425b-ac14-6d59589dd13a">
<img width="695" alt="image" src="https://github.com/user-attachments/assets/d1b15f44-4057-4a80-9056-8a719d2e1d39">

2024-11-25 15:32 UTC, RuslanGabd commented
<img width="713" alt="image" src="https://github.com/user-attachments/assets/f71623c8-8c0f-4059-ac53-6a872c3b1d0c">

2024-11-25 15:39 UTC, RuslanGabd commented
<img width="754" alt="image" src="https://github.com/user-attachments/assets/84916270-f7a0-40e8-bc3a-fbda73040d62">

2024-11-26 16:35 UTC, jibulani requested changes
хорошо, нужны небольшие исправления, тесты и задача со звездочкой, если успеешь

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/ResourceController.java
> +public class ResourceController {
у тебя же задача именно про добавление картинок к посту, кажется нужны доработки в PostController

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +    private final S3ServiceImpl s3Service;
у тебя же есть интерфейс S3Service, сделай переменную этого типа, лучше зависеть от абстракции, а не от реализации

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +    private Post checkPostExist(Long postId) {
у тебя же метод не только проверку существования поста делает, но и возвращает его в случае наличия, логичнее метод как-то так назвать: `getPostOrThrow`

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +    private void checkAndResizeImage(MultipartFile image) {
тут тоже лучше назвать resizeOrThrow и возвращать из метода измененную картинку, чтобы явно это показать

а так получается какая-то неявная подкапотная логика по изменению переданного аргумента, по возможности так лучше не делать

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +                if (width > 1080 || height > 566) {
магические числа, нужно вынести эти значения в константы с понятными именами

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +public class ResourceService {
поскольку логика относится к постам, я бы сделал ее в PostService или вынес в сервис с названием PostResourceService, а так слишком общее название у класса, как будто он вообще с любыми ресурсами может работать

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +        try (InputStream inputStream = s3Service.downloadFile(key)) {
лайк за try-with-resources

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/s3/S3ServiceImpl.java
> +        Resource resource = new Resource();
по-хорошему S3Service не должен знать ни о каких ресурсах, это не его зона ответственности, а зона ответственности ResourceService
для S3Service достаточно вернуть из этого метода ключ загруженного файла, а сам ресурс пусть другой сервис создает

2024-11-26 16:35 UTC, jibulani commented on src/main/java/faang/school/postservice/service/s3/S3ServiceImpl.java
> +    public void uploadFile(String key, InputStream fileInputStream, ObjectMetadata metadata) {
зачем этот метод, если у него нет реализации?

2024-11-28 20:30 UTC, jibulani approved these changes
супер, очень хорошо сделано!
вопрос некритичный, поэтому аппрув

2024-11-28 20:30 UTC, jibulani commented on src/main/java/faang/school/postservice/repository/ResourceRepository.java
> +    Optional<List<String>> getAllKeysForPost(Long postId);
точно ли нужен Optional? разве не вернет просто пустой список, если не найдется значений?

2024-11-28 20:30 UTC, jibulani commented on src/test/resources/img.jpg
красивый :)

2024-11-28 20:31 UTC, merged