Feature bjs2 40846 (without tests)
CorporationX/post_service pull request #1210
Opened 2024-11-27 13:15 UTC by Alexey-Zimin

Скрины из постмана прилагаются
![post comment](https://github.com/user-attachments/assets/39422dd1-2701-4385-8eda-97afc7021267)
![put comment](https://github.com/user-attachments/assets/b83632fc-c576-4f29-ac12-7568339523b6)
![get comments by postId](https://github.com/user-attachments/assets/789b5d5b-fe5b-44b3-a462-861ecfc4c972)
![delete comment](https://github.com/user-attachments/assets/a66f32c6-bd20-4d54-9666-567096b8f196)

2024-11-28 13:34 UTC, roship commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +@Getter
Почти @Data
Кроме @ToString, @RequiredArgsConstructor

Интересно для чего сделано именно так.

2024-11-28 13:37 UTC, roship commented on src/main/java/faang/school/postservice/mapper/like/LikeMapper.java
> +    @Mapping(source = "createdAt", target = "createdAt", dateFormat = "yyyy-MM-dd HH:mm:ss a")
Если вообще не указывать @Mapping для поля, получается типа
"createdAt": "2024-11-18T15:50:49.442517" "из коробки". И вроде приемлемо.

2024-11-28 13:53 UTC, roship commented on src/main/java/faang/school/postservice/mapper/comment/CommentMapper.java
> +    @Mapping(target = "id", ignore = true)
Я сам еще не пробовал, но вроде можно применить ко всем полям, для которых @Mapping не задан, ignore = true.

@BeanMapping(ignoreByDefault = true)

2024-11-29 23:10 UTC, Alexey-Zimin commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +@Getter
Один раз попался c @Data на зацикливании, поэтому стараюсь избегать эту аннотацию, лучше буду сам контролировать, что мне нужно.

2024-11-29 23:11 UTC, Alexey-Zimin commented on src/main/java/faang/school/postservice/mapper/like/LikeMapper.java
> +    @Mapping(source = "createdAt", target = "createdAt", dateFormat = "yyyy-MM-dd HH:mm:ss a")
Сделал так из соображеий опробовать работоспособность этого способа

2024-11-29 23:14 UTC, Alexey-Zimin commented on src/main/java/faang/school/postservice/mapper/comment/CommentMapper.java
> +    @Mapping(target = "id", ignore = true)
Встречал такую аннотацию, нужно будет попробавать в следующий раз

2024-12-02 21:25 UTC, jibulani requested changes
супер! отличное покрытие тестами, молодец!
есть несколько небольших комментариев

2024-12-02 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +    public void validateContent(String content) {
зачем? можно же проверить аннотациями

2024-12-02 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +    private void validateAuthorId(Long authorId) {
и тут

2024-12-02 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +    private void validatePostId(Long postId) {
и тут

2024-12-02 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/UserValidator.java
> +                throw new EntityNotFoundException(String.format(INTERNAL_SERVER_ERROR,  userId, httpStatus.getReasonPhrase()));
EntityNotFoundException обработается как 404 ошибка, как будто это клиент передал несуществующую id, а у нас проблема на сервере из-за того, что внутренний сервис пятисотит, логичнее пятисотку и возвращать

2024-12-02 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +            throw new IllegalArgumentException(error);
лучше для единообразия тоже EntityNotFoundException возвращать

2024-12-02 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentValidator.validateCommentExist(commentDto.getId());
видимо не нужен вызов валидатора, раз ты на следующей строке еще раз по сути то же самое делаешь, но с сохранением коммента в переменную

2024-12-03 20:09 UTC, jibulani requested changes
совсем чуть-чуть осталось :)

2024-12-03 20:09 UTC, jibulani commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +    @NotBlank(message = "Content should not be null")
зачем два NotBlank? надо оставить один

2024-12-04 21:17 UTC, jibulani approved these changes
супер!

2024-12-04 21:18 UTC, merged