NEWS FEED
CorporationX/post_service pull request #1218
Opened 2024-11-27 19:30 UTC by sultan-inked

2024-11-27 19:53 UTC, sultan-inked commented on src/main/java/faang/school/postservice/repository/cache/CommentCacheRepository.java
> +}
Храню коментарии отдельно как json, и ZSET с id коментариев, ключ для ZSET id поста с префиксом

2024-11-27 19:53 UTC, sultan-inked commented on src/main/java/faang/school/postservice/repository/cache/CommentCacheRepository.java
> +}
Можно получить id трех последних комментариев по id поста, и получить сразу все коменты по списку id

2024-11-27 19:53 UTC, sultan-inked commented on src/main/java/faang/school/postservice/repository/cache/CommentCacheRepository.java
> +}
Лайки копятся в счетчике, шедулер собирает все ключи счетчиков, делит на подсписки и отправляет в кафку, листнер принимает пачку ключей счетчков и передает на перераспределение количества лайков из счетчика в поле с количеством лайков коментария

2024-11-28 14:58 UTC, 20cognosce requested changes
Хочу увидеть демо

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/message/CommentPostMessage.java
> +@Data
Для чего используешь эту аннотацию

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/message/LikeCommentMessage.java
> +@Data
.

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/message/CommentPostMessage.java
> +public class CommentPostMessage {
Это сообщение для коммента или для поста, почему две сущности в нейминге

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/message/LikeCommentMessage.java
> +public class LikeCommentMessage {
И тут аналогично, не понятно, чей это эвент

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/message/LikePostMessage.java
> +public class LikePostMessage {
.

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/message/LikeCommentMessage.java
> +public class LikeCommentMessage {
LikeForCommentMessage
LikeForPostMessage

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/serializable/PostViewEventParticipant.java
> +}
?)

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +    @PublishEvent(type = LIKE_POST)
Придумай одно название для сущности во всех местах

createPostLike - POST_LIKE (а не LIKE_POST)
createCommentLike - COMMENT_LIKE (а не LIKE_POST_COMMENT)

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +    private static final Object MOCK = new Object();
Сомнительный дизайн

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +        String feedUserKey = feedUserKey(userId);
Зачем называть переменную и метод одинаково

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +    }
В отдельный сервис и так сильно методы не дробить

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +            return findPostsInCache(postIds);
А возможна ситуация, когда айдишники постов есть, а в кэше постов нет?
Что тогда

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> posts = postRepository.findSetOfPostsByAuthorsId(offset, limit, subscribesIds);
Не понял, мы ищем посты по userId, где userId - подписчик авторов постов

subscribesIds - это кто, авторы?

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        if (post.getAuthorId() != null) {
А бывает пост без автора?

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postCacheProcessExecutor.executeNewPostProcess(postCacheDto);
Не понял, почему ты сначала отправляешь эвент, а потом заполняешь сообщение инфой об авторе

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            UserDto userDto = userServiceClient.getUser(post.getAuthorId());
Это не userDto, это автор поста
Давай нормальные имена переменным

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +                .collect(Collectors.toSet());
Почему здесь происходит маппинг на ключи из редиса, это ответственность должна быть в другом сервисе, отвечающем за круд данных в редисе, а не за ленту новостей

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +                .filter(post -> FALSE.equals(redisTemplate.hasKey(postIdKey(post.getId()))))
Что здесь происходит, почему так сложно и в одной куче

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +    }
Вынести в другой сервис
Разделить обновление кэша по сущностям - посты, комменты, юзеры
Выполнять это асинхронно и не блокировать фид

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +        List<PostCacheDto> postDtoList = enrichAuthors(setOfPosts);
На этом этапе уже потеряется понимание стадии получения фида, почему так много связанных действий, уводящий в другие переплетенные методы
Разрывай связи, выноси в другие бины, выполняй асинхронно

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +                .collect(Collectors.toSet());
Упростить

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +        feedIsUpdating.put(feedUserKey, MOCK);
Ну а удаляется твой мок когда?
Не понимаю, что ты делаешь

Если нужны локи по юзеру - сделай в мапе соотношение 
юзер ид - лок

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +public class FeedService {
Черт ногу сломит в том что каждый из методов делает
Нужен глубокий рефакторинг

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/util/ListPartitioner.java
> +    }
Пожалуйста... заюзай ListUtil.sublist от apache...

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/util/EventsPartitioner.java
> +    }
Почему столько дублирования кода, обобщить

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/CacheUpdateService.java
> +    }
Я это уже видел в другом сервисе

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/feed/CacheUpdateService.java
> +    }
Выглядит странно, это раз
Лучше переименовать тогда уж на mapPostIdToRedisKey, типо того

И обобщить это всё в один метод, код одинаковый

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/post/PostLikeCounterKeysCollector.java
> +public class PostLikeCounterKeysCollector {
Может все счётчики можно было объединить в один класс?
Они тоже одинаковые, и изменяться вряд ли будут

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/PostCacheRepository.java
> +    }
.

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/PostCacheRepository.java
> +    }
Ну это же одно и тоже, не плоди столько кода, глаза разбегаются

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/PostCacheRepository.java
> +    }
.

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/CommentCacheRepository.java
> +    }
.

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/CommentCacheRepository.java
> +        long limit = (numberOfCommentsInPostCacheDtoLimit + 1) * -1;
Магические числа

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/publishers/ViewPostsToKafkaPublisher.java
> +    }
Билдеры в другой класс
Все паблишеры поста объединить в один - на лайк, просмотр, публикацию
И по параметру, передаваемом в аннотации решать, в какой топик что отсылать

Тут надо объединить, потому что это всё относится к посту и тоже много дублирования

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/publishers/NewPostToKafkaPublisher.java
> +    }
В отдельный класс

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/aop/aspects/publisher/AspectPublisher.java
> +        publisher.publish(joinPoint, returnedValue);
По главным сущностям делай по одному паблишеру
Пост - создание, просмотр, лайк
Комментарий - создание, лайк, бан

И внутри них мапь на конкретный топик

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/RedisOperations.java
> +        redisTransaction.execute(redisTemplate, key, operations -> {
redisTransaction.execute разве сам не выполняет все уже внутри транзакции?
Это похоже на транзакцию внутри транзакции

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/RedisOperations.java
> +        });
Разделить на понятные методы, непонятный код

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/RedisTransaction.java
> +    @SuppressWarnings("unchecked")
Не пиши это

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/UserCacheRepository.java
> +        redisOperations.executeInMulti(userDtoRedisTemplate, key, () ->
executeInTransaction лучше назвать метод

2024-11-28 14:58 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/cache/UserCacheRepository.java
> +    }
.

2024-11-28 17:06 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +public class FeedService {
Ох, ты не видел изначальный вариант)
Да, постораюсь сделать более понятно

2024-11-30 14:54 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/feed/FeedService.java
> +            return findPostsInCache(postIds);
Возможна, сделал проверку, если нет то лезу в БД

2024-11-30 15:30 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        if (post.getAuthorId() != null) {
Да, у поста может не быть автора, вместо атора проект

2024-11-30 16:21 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> posts = postRepository.findSetOfPostsByAuthorsId(offset, limit, subscribesIds);
1. Получить id всех на кого подписан пользователь:
```java
List<Long> subscribesIds = userServiceClient.getSubscribesIds(userId);
```
2. Получить все посты авторов, входящих в список id из первого пункта:
```java
List<Post> posts = postRepository.findSetOfPostsByAuthorsIds(offset, limit, subscribesIds);
```

2024-11-30 16:23 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postCacheProcessExecutor.executeNewPostProcess(postCacheDto);
Это из задачи хештеги постов, там другая логика:
```java
postCacheProcessExecutor.executeNewPostProcess(postCacheDto);
```

2024-11-30 16:27 UTC, sultan-inked commented on src/main/java/faang/school/postservice/repository/cache/PostCacheRepository.java
> +    }
А как иначе? Это же разные методы, которые передают в теплейт разный паттерн ключей счетчиков

2024-11-30 16:47 UTC, sultan-inked commented on src/main/java/faang/school/postservice/aop/aspects/publisher/AspectPublisher.java
> +        publisher.publish(joinPoint, returnedValue);
У нас же три сущности. Действия с постом только просмотр и создание поста, лайк и коммент это отдельные сущности, и если даже объединю то придется использовать if else или switch, и класс будет делать пять действий, отправлять пять разных сообщений в пять топиков, мне не нравиться эта идея (

2024-11-30 16:50 UTC, sultan-inked commented on src/main/java/faang/school/postservice/dto/post/serializable/PostViewEventParticipant.java
> +}
Создал общий интерфейс для поста и дто поста, что бы при просмотре не делать два метода в которые передаются дто и пост, когда от поста требуется только id.
Такое делать плохо?

2024-11-30 17:19 UTC, sultan-inked commented on src/main/java/faang/school/postservice/aop/aspects/publisher/AspectPublisher.java
> +        publisher.publish(joinPoint, returnedValue);
Или ты имел в виду две аннотации и аспекта по сущностям пост и коммент?  Тогда надо три, лайк тоже отлельная сущность, не вижу смысла делать классы которые отличаются только по типу паблишера

2024-12-01 10:30 UTC, 20cognosce approved these changes

2024-12-01 10:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/listener/kafka/KafkaListeners.java
> +public class KafkaListeners {
Прям все в один класс не надо было класть, нужно было по сущностям сгруппировать
Листенеры постов, комментов, лайков

2024-12-01 10:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/publishers/CommentPostToKafkaPublisher.java
> +public class CommentPostToKafkaPublisher implements Publisher {
А паблишеры так и оставил по разным классам с дублированным кодом

2024-12-01 10:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/kafka/publishers/NewPostToKafkaPublisher.java
> +    private String topicName;
Сделал бы мапу типа события на топик и билдер, и сгруппировал всё компактно
publish везде одинаковый, зависимости одинаковые

2024-12-01 10:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +//    @PublishCommentNotificationEvent
Артефактов в коде не должно оставаться

2024-12-01 10:30 UTC, merged