BJS2-40805
CorporationX/post_service pull request #1231
Opened 2024-11-28 21:04 UTC by davidx5x5

2024-11-29 22:59 UTC, jibulani requested changes
есть несколько непонятных моментов, написал вопросы

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        if (id <= 0 || likeDto.userId() == null) {
можно вынести в отдельный метод и переиспользовать его в createLikePost

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/dto/payment/PaymentRequest.java
> +public interface PaymentRequest {
зачем?

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/dto/payment/PaymentResponse.java
> +public class PaymentResponse {
зачем?

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/dto/project/ProjectDto.java
> +public class ProjectDto {
зачем?

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +        if (likeOnPost.isPresent() && likeOnComment.isPresent()) {
ты же уже это сделал выше:
```
        Optional<Like> existingLikeOnComment = likeRepository.findByCommentIdAndUserId(comment.getId(), likeDto.userId());
        if (existingLikeOnComment.isPresent()) {
            throw new DataValidationException("User has already liked this comment");
        }
        Post post = comment.getPost();
        existingLikeOnPost(post, likeDto);
```

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +        if (LikeOnPost.isPresent() && LikeOnComment.isPresent()) {
опять какие-то дублирующиеся проверки

2024-11-29 22:59 UTC, jibulani commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +}
не забудь о требовании:

> Для реализации требования 5 нужно расширить уже ранее созданный класс PostDto и добавить в него информацию о количестве лайков для этого поста. Далее нужно поправить логику PostService для включения информации о лайках в логике методов, возвращающих опубликованные посты пользователя или проекта. Для этого нужно заменить в них вызовы методы PostRepository на подходящие. 

или сам сделай, или попроси Женю, если быстрее него доделаешь свой пр, потому что он делает систему постов в своем

2024-12-01 19:52 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +}
да он как раз доделал и как что, я уже понял где дописать

2024-12-01 19:53 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +        if (LikeOnPost.isPresent() && LikeOnComment.isPresent()) {
согласен когда я код писал мне казалось так нужно, а сейчас понял что дубль)))

2024-12-01 19:56 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +        if (likeOnPost.isPresent() && likeOnComment.isPresent()) {
ок)))

2024-12-01 19:59 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        if (id <= 0 || likeDto.userId() == null) {
ок исправляю

2024-12-01 20:03 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/dto/payment/PaymentResponse.java
> +public class PaymentResponse {
без этого не работает'

2024-12-01 20:03 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/dto/payment/PaymentRequest.java
> +public interface PaymentRequest {
без этого не работает

2024-12-01 20:04 UTC, davidx5x5 commented on src/main/java/faang/school/postservice/dto/project/ProjectDto.java
> +public class ProjectDto {
без этого не запускается

2024-12-02 15:59 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +@RequestMapping("/api/v1")
во всех методах повторяется "/likes". Можно вынести его сюда

2024-12-02 17:48 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/dto/LikeDto.java
> +        Long authorId,
похоже, что authorId и userId - это одно и то же

2024-12-02 17:55 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    public LikeDto createLikeComment(@PathVariable("id") long id, @RequestBody LikeDto likeDto) {
В @PathVariable не обязательно указывать название ("id"), если переменная одна

2024-12-02 17:59 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        validateUserId(id, likeDto);
название метода не соответствует содержанию. Я бы переименовал

2024-12-02 18:46 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/dto/UserDto.java
> +@NoArgsConstructor
мне кажется, здесь не нужен конструктор без аргументов. Зачем нужен userDto, в котором нет id?

2024-12-02 18:47 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +@Component
можно заменить на аннотацию @Service

2024-12-02 18:50 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +    private final PostRepository postRepository;
Когда стянешь себе мои изменения, здесь нужно будет использовать PostService и его методы. Если какого-то метода будет не хватать, то его именно в PostService нужно будет добавить

2024-12-02 21:07 UTC, jibulani requested changes
хорошо, написал небольшой комментарий + поправь по комментариям Жени

2024-12-02 21:07 UTC, jibulani commented on src/main/java/faang/school/postservice/service/impl/like/LikeServiceImpl.java
> +    private void existingLikeOnPost(Post post, LikeDto likeDto) {
неочень понятное название метода, я бы назвал: validateLikeOnPostDoesNotExist

2024-12-07 21:12 UTC, jibulani approved these changes
супер!

2024-12-07 21:12 UTC, merged