done
CorporationX/post_service pull request #1251
Opened 2024-11-30 14:14 UTC by klin57

2024-12-08 22:47 UTC, mysosnovskaya requested changes
Необходимо хорошо проработать вопросы, связанные с многопоточным выполнением кода. Ну и также нужно весь код покрыть тестами

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/client/UserServiceClient.java
> +    List<UserDto> getAllUsers();
А если у нас пользователей миллионы? Лучше предусмотреть пагинацию и вытаскивать юзеров порциями)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaConsumerConfig.java
> +                JsonDeserializer.class);
Это круто! 👍

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaProducerConfig.java
> +    private String bootstrapAddress;
Мне нравится, что ты разделил настройки кафки на два класса - для консьюмера и для продюсера отдельно. Но вот это повторяющееся поле... Не то чтобы проблема, но я вижу риск в том, что дефолтное значение в одном месте поменяем, а в другом забудем. Может получится довольно непростой в отлове баг, особенно если по обоим дефолтным значениям кафка будет доступна) Не настаиваю, но мягко рекомендую подумать, как можно было бы избежать дублирование этого параметра

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaTopicConfig.java
> +    private String bootstrapAddress;
О, ещё и здесь тоже оно. Тогда мой комментарий выше ещё более актуален)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaTopicConfig.java
> +    private String POSTS_TOPIC;
Почему поля называются как константы? Это обычные поля, должны называться в camelCase

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaTopicConfig.java
> +        return new NewTopic(POSTS_TOPIC, 1, (short) 1);
Эти единички тоже должны быть в конфигах. Для всех топиков.

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaCommentConsumer.java
> +            acknowledgment.acknowledge();
А если строка выше выбросила исключение и мы сразу перешли в catch, то мы не сделаем acknowledge?

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaCommentConsumer.java
> +            log.error("Comment is not added to post with id: " + event.getPostId());
commentId тоже можно добавить

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaFeedHeaterConsumer.java
> +    @Async("feedHeaterExecutor")
А эти аннотации нельзя вместе, т.к. метод listener запустится в транзакции, а затем будет запущен отдельный асинхронный поток, на который транзакция не распространяется. В результате транзакция в любом случае завершится успешно (вместе с завершением основного метода), а запущенный асинхронный поток продолжит жить своей жизнью без транзакции. 
Почитать можно здесь (отдельный пункт **@Async and @Transcational don’t play well)**:
https://medium.com/@dvikash1001/springboot-async-the-magic-and-the-gotchas-17f9471c6fe4
и здесь
https://www.baeldung.com/spring-transactional-async-annotation

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaFeedHeaterConsumer.java
> +            acknowledgment.acknowledge();
То же самое, что и в KafkaCommentConsumer. Дублировать этот коммент больше не буду, в остальных классах аналогично)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaFeedHeaterConsumer.java
> +        feedService.getFeedByUserId(null, userId);
Нужно сделать что-то, чтобы не было этого null. Можно создать ещё один метод getFeedByUserId, который бы принимал только userId (хотя из названия метода как будто бы следует, что он должен только userId принимать)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaPostConsumer.java
> +            log.error("Post with id:{} is not added to subscribers feeds.", event.getId());
Почему-то в KafkaLikeConsumer для логирования используется конкатенация, а здесь по-другому. Лучше делать единообразно)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaLikeConsumer.java
> +            log.error("Like is not added to post with id: " + event.getPostId());
В логи лучше добавлять полную информацию. Здесь хорошо было бы добавить, от кого этот лайк. В других консьюмерах аналогично

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/FeedController.java
> +@RequestMapping("/api")
Наверное, ещё хотелось версионирование добавить? /api/v1? Кстати, такое лучше делать через application.yaml, добавив туда
spring.mvc.servlet.path=/api/v1
Тогда доступ ко всем эндпоинтам будет, например, по localhost:8080/api/v1/feed и не придется это прописывать над каждым контроллером в RequestMapping

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaCommentDto.java
> +    private Long authorId;
final?

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaCommentDto.java
> +@Data
Точно всё из Data нужно?

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaCommentDto.java
> +@NoArgsConstructor
Точно нужен?

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaCommentDto.java
> +@Builder
Точно ли нужен билдер? По-моему класс всегда должен создаваться со всеми полями и никак иначе, разве не так? Если билдер нужен только для тестов, то билдер не нужен)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaFeedHeaterDto.java
> +public class KafkaFeedHeaterDto {
Здесь и в других dto комментарии аналогичны KafkaCommentDto

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/model/redis/CachePost.java
> +@RedisHash(value = "posts", timeToLive = 86400L)
timeToLive должно быть настраиваемым параметром

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/model/redis/CachePost.java
> +public class CachePost {
Нужно пересмотреть поля этого класса. Нам точно не нужны все из них для ленты новостей. Например, поля scheduledAt или deleted. Про все остальные тоже нужно подумать и оставить только необходимые)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    @Transactional
Зачем? Это же просто select запрос

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +        return null;
Не нужно возвращать null. Верни пустой Set или исключение. Иначе это неочевидная логика реализации и легко будет поймать NPE

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +        if (!(objects == null)) {
objects != null

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +    private static final String KEY = "feed:";
Можно было бы это значение тоже вынести в параметры. Параметры всегда гибче, чем жестко зашитое в код значение)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +        posts.forEach(post -> operations.add(KEY + id, post.getId(), System.currentTimeMillis()));
Через ZSetOperations.TypedTuple можно сохранять не по одной записи, а сразу пачкой. Рекомендую ознакомиться, так будет эффективнее)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +        operations.add(KEY + followerId, postId, System.currentTimeMillis());
Не видно проверки на то, что не превышено maxFeedSize

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/FeedService.java
> +    }
Этот код не будет работать в многопоточной среде. Несколько потоков одновременно могут хотеть добавить новую новость в кэш -> несколько потоков одновременно увидят, что в кэше меньше 500 записей -> несколько потоков одновременно добавят свои новости -> в кэше станет больше 500 записей. А т.к. условие у тебя на строгое равенство, то значит больше никто и никогда не удалит лишние записи

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +public class CacheRedisRepository implements RedisRepository {
CacheFeedRepository?

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/FeedService.java
> +            log.info("There are no more posts in the feed. Let's go to the database.");
Нам точно нужен этот лог? Я же правильно понимаю, что это будет частая ситуация? Так может и не нужно это логировать?

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/FeedService.java
> +        return result.stream().map(obj -> Long.valueOf(String.valueOf(obj))).toList();
result.stream().map(String::valueOf).map(Long::valueOf).toList();

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/FeedService.java
> +    private List<List<Long>> splitList(List<Long> userIds) {
Рекомендую использовать уже готовые решения, а не писать это самостоятельно) Например, в apache commons есть Lists.partition

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/FeedService.java
> +        List<Long> userIds = allUsers.stream().map(UserDto::getId).toList();
Попробуй это всё объединить в один стрим. По-моему должно получиться

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostCacheService.java
> +        cachePostRepository.save(cachePost);
Это не будет работать в многопоточной среде. Несколько потоков одновременно могут получить один и тот же cachePost, несколько потоков одновременно могут у себя в оперативной памяти увеличить значение лайков для этого поста на 1 и затем они все пойдут сохранять обновленное значение в базу данных. Но т.к. все потоки делали инкремент к одному и тому же значению (например, к 3), то и в итоге в редисе будет сохранено, что всего 4 лайка, хотя их может быть гораздо больше. 
Кстати, в задачах писали про то, что необходимо подумать про транзакционность этих изменений.

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostCacheService.java
> +        cachePost.incrementNumViews();
Аналогично комментарию выше

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostCacheService.java
> +    }
Это не будет работать в многопоточной среде (писала уже аналогичный комментарий про посты, дублировать не буду)

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostCacheService.java
> +                        .orElseThrow(() -> new RuntimeException("There is no such post")))));
В ошибку нужно добавить id поста

2024-12-08 22:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/model/redis/CachePost.java
> +    private CopyOnWriteArraySet<CommentDto> comments;
CopyOnWriteArraySet нам не поможет, т.к. подразумевается, что будет запущено сразу несколько экземпляров одного микросервиса, а CopyOnWriteArraySet будет потокобезопасным только в рамках одного микросервиса

2024-12-09 19:18 UTC, klin57 commented on src/main/java/faang/school/postservice/consumer/KafkaCommentConsumer.java
> +            acknowledgment.acknowledge();
Да. Если мы не обработали event из kafka (вылетело исключение), то acknowledge не отправится и kafka повторно отправит нам этот event. Или я что-то не так понял по логике работы?

2024-12-12 18:07 UTC, klin57 commented on src/main/java/faang/school/postservice/service/FeedService.java
> +            log.info("There are no more posts in the feed. Let's go to the database.");
Согласен

2024-12-12 18:27 UTC, klin57 commented on src/main/java/faang/school/postservice/service/FeedService.java
> +        List<Long> userIds = allUsers.stream().map(UserDto::getId).toList();
Если объединить в один стрим, то получится каждый объект сохранять в кеш отдельным запросом. На мой взгляд это будет более затратно, с точки зрения ресурсов компьютера.

2024-12-14 09:39 UTC, klin57 commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +        posts.forEach(post -> operations.add(KEY + id, post.getId(), System.currentTimeMillis()));
RedisTemplate<String, Object> redisTemplate принимает только Set<ZSetOperations.TypedTuple<Object>>, а в данном случае при использовании ZSetOperations.TypedTuple.of(post.getId(), System.currentTimeMillis())) получается Set<ZSetOperations.TypedTuple<Long>>. У меня в Redis хранятся по мимо id еще и сами объекты. Так что не могу поменять Object  на Long в объявлении redisTemplate. Как тут быть?

2024-12-14 16:29 UTC, klin57 commented on src/main/java/faang/school/postservice/model/redis/CachePost.java
> +    private CopyOnWriteArraySet<CommentDto> comments;
Думал что эту проблему решит @Version, но оказалось он только для реляционных баз данных. 
Тут нужно использовать что-то типа оптимистической блокировки Redis? (watch и multi/exec, изменение поля версии в ручную)

2024-12-14 18:23 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/consumer/KafkaCommentConsumer.java
> +            acknowledgment.acknowledge();
Нет, всё верно, это я ошиблась) Оставляем так

2024-12-14 18:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/redis/CacheRedisRepository.java
> +        posts.forEach(post -> operations.add(KEY + id, post.getId(), System.currentTimeMillis()));
Не до конца вопрос поняла, ты пишешь `принимает только Set<ZSetOperations.TypedTuple>, а в данном случае ... получается Set<ZSetOperations.TypedTuple>` - одно и то же :) Может быть поможет создание нескольких RedisTemplate с разными типами? Один `RedisTemplate<String, Object>`, а другой - `RedisTemplate<String, Long>`. Если не получится - присылай на проверку без этого исправления, посмотрю ещё.

2024-12-14 18:47 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/model/redis/CachePost.java
> +    private CopyOnWriteArraySet<CommentDto> comments;
Да, Version не поможет, распределенный лок нужен) Можешь посмотреть на библиотеку redisson, с ней это можно сделать. Может ещё какие-то другие варианты найдешь. Главное, чтобы работало корректно)

2024-12-14 18:51 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/FeedService.java
> +        List<Long> userIds = allUsers.stream().map(UserDto::getId).toList();
Да, похоже, так. Код выглядит как будто немного сложнее, чем должен быть. Давай пока без изменений, при следующей проверке ещё подумаю, можно ли как-то отрефакторить. Пока не придумала :)

2025-01-14 22:34 UTC, mysosnovskaya approved these changes
Проделал огромную работу, молодец! Задача и правда очень сложная, но ты справился 👍 От меня аппрув и мердж) От Саши - жди сертификат!)

2025-01-14 22:34 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/DefaultKafkaConfig.java
> +public class DefaultKafkaConfig {
Его ещё абстрактным можно сделать)

2025-01-14 22:34 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaCommentDto.java
>  public class KafkaCommentDto {
Тут не до конца понимаю, почему не record, поля не финальные и Data присутствует. Но на твоё усмотрение - если в коде это действительно нужно, пусть остается.

2025-01-14 22:34 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/event/KafkaPostViewDto.java
> +public record KafkaPostViewDto(Long postId) {
Красиво с record 👍

2025-01-14 22:34 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostCacheService.java
> +        RLock lock = redissonClient.getLock(lockCachePost + cachePost.getId());
Вот теперь вижу работу с многопоточностью 👍

2025-01-14 22:34 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostCacheService.java
> +            if (lock.tryLock(2,1, TimeUnit.SECONDS)) {
2, 1 по-хорошему тоже нужно вынести в параметры или в константы класса)

2025-01-14 22:35 UTC, merged