feature/BJS2-41067 Добавление картинок к посту
CorporationX/post_service pull request #1256
Opened 2024-11-30 16:30 UTC by frs717

2024-12-03 21:09 UTC, MiraGlaceon requested changes

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/client/ProjectServiceClient.java
> +    @PostMapping("/projects")
Метод для получения проектов, но ты используешь Post. Post для сохранения, нужно переписать, либо проверить, это точно для получения или может сохранения проектов? Загляни в проджект сервис, что там происходит, подправь

Второе: давай все ресурсы прописывать существительны множественного числа. Например, не project, а projects

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PostMapping("/{postId}/media")
У тебя медиа сохраняется к посту ? Тогда тут лучше метод Put для обновления сущности

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public class ResourceDto {
Что конкретно за ресурс? Добавь уточнения или речь в общем о ресурсе и грузить можно что угодно? Я думаю у тебя речь о картинках идет

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/dto/resource/ResourceInfoDto.java
> +public class ResourceInfoDto {
То же самое, инфо какого ресурса

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postValidator.validateAddedMedia(post, files);
Тут просто можно обозвать метод validateMedia, ты же его не добавил еще, а окрестить его "Добавляемая медиа" излишне

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/{postId}/publish")
Не используй глаголы в url по возможности. Например publish можно передать через параметр. Published/unpubleshed тоже, типа status или state. Попробуй. Вообще покопай дополнительно про формирование эндпоинтов в rest api

И этот метод скорее всего не put, а patch нужно сделать. У тебя получается  частичное обновление ресурса, только статус меняется

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +        if (post.getId() == null) {
Попробуй переписать проверку на аннотацию @Valid в методе

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +        List<Resource> resources = resourcesDto.stream().map(r -> upload(post, r)).toList();
Когда работаешь со стримами, то старайся переносить вызовы методов на новую строку, чтобы был столбик действий, так читабельнее, даже в таких простых вещах

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/image/ImageResizeService.java
> +        try {
Вынеси в отдельный метод запись. Логически это можно вынести как отдельное действие

2024-12-03 21:09 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/image/ImageResizeService.java
> +            log.error("Image read error", e);
Ошибка чтения файла или запись? Вызываешь метод write, а логгируешь read

2024-12-15 09:14 UTC, frs717 commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +        if (post.getId() == null) {
PostDto используется также в методе для создания поста, где id не должно быть. 
Только если создать отдельное dto для этого метода?

2024-12-15 09:18 UTC, frs717 commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public class ResourceDto {
Уже созданная Entity называется Resource. В БД оно в одном месте лежит. 
Данная dto в принципе подойдет для любых форматов
Я бы оставил так?

2024-12-15 13:07 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public class ResourceDto {
Оставь, если завели так изначально

2024-12-15 13:08 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/ResourceService.java
> +        if (post.getId() == null) {
Оставь, если не создать отдельный ДТО для этого случая и бизнес-логика располагает

2024-12-15 13:08 UTC, MiraGlaceon approved these changes

2024-12-15 14:00 UTC, merged