BJS2-40803 функционал работы с постами
CorporationX/post_service pull request #1263
Opened 2024-12-01 12:56 UTC by evgen-backend-rostov

2024-12-01 18:57 UTC, AlexLogino reviewed
Посмотрел все кроме тестов и FeignClient

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/{id}/delete")
Я бы тут DeleteMapping использовал, даже не смотря на то, что удаление мягкое. Ну или PutMapping

И path как будто бы тогда напрашивается просто "/{id}"

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/controller/PostController.java
> +@RequestMapping("/post")
path "/api/v1/post" будем использовать?

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/dto/payment/PaymentRequest.java
> +public record PaymentRequest() {
что это и зачем?
и PaymentResponse

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body("Непредвиденный RuntimeException: " + ex.getMessage());
здесь не internalServerError() должен быть?

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
Женя говорит, что эти методы можно сделать просто статическими без использования Component, и это вроде работает

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +    @Retryable(retryFor = FeignException.class, maxAttempts = 5, backoff = @Backoff(delay = 1000))
не разбирался еще с FeignClient, поэтому подразумеваю что все, что связано с ним, сделано правильно

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +        return postRepository.findById(id)
этот метод в PostServiceValidator можно перенести

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +        if(postDto.id() != null) {
проверка на null уже в Controller выполнялась

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +                return postMapper.toDto(postRepository.save(oldPost));
здесь можно просто "postRepository.save(oldPost)" оставить

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +            throw new DataValidationException("Нельзя менять автора поста");
во-первых переносы лучше делать по логическому оператору в данном случае:
"...
&& newPost.authorId() != null
&& !oldPost.getAuthorId().equals(newPost.authorId())
|| oldPost.getProjectId() != null
&& newPost.projectId() != null
..."

во-вторых вроде как здесь достаточно только двух условий:
!oldPost.getAuthorId().equals(newPost.authorId())
|| !oldPost.getProjectId().equals(newPost.projectId())

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +        }
гиде сохранение в репозиторий?)

2024-12-01 18:57 UTC, AlexLogino commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +                .sorted(comparePostByCreateDateDesc)
компаратор правильно написан, только надо добавить обратный порядок:
comparePostByCreateDateDesc.reversed()
и в другом методе тоже

2024-12-01 19:21 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/dto/payment/PaymentRequest.java
> +public record PaymentRequest() {
Эти сущности используются в FeignClient, без них проект не компилится. Типа заглушки получились. Видимо, в каких-то других задачах пригодятся

2024-12-01 19:28 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body("Непредвиденный RuntimeException: " + ex.getMessage());
Вот не знаю... По моей логике, этот метод перехватывает все непредвиденные ошибки, поэтому решил использовать RuntimeException как самое широкое исключени после Exception. Думаю, для internalServerError() лучше создать отдельный метод. @jibulani, нужен твой совет

2024-12-01 19:30 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
делаю их обычными классами и выношу отдельно, чтобы тестировать можно было удобнее. @jibulani, их же нужно тестировать?

2024-12-01 19:33 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +        return postRepository.findById(id)
метод не валидирует наличие поста, а возвращает его. Просто из-за того, что метод репозитория возвращает Optional, приходится обрабатывать возможное отсутсвие значения и бросать исключение

2024-12-01 19:41 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +        if(postDto.id() != null) {
да, тоже об этом подумал. Но из-за того, что и для создания, и для обновления используется одна и та же PostDto, в которой поле id необязательное (помечено аннотацией @Nullable), то ИДЕЯ ругается, что в этом месте может возникнуть NullPointerException. Предполагаю, что нужно создать PostCreateDto и PostUpdateDto с разными наборами полей и использовать каждый в своём месте. @jibulani Жень, тут тоже нужен твой комментарий 🙏

2024-12-01 19:46 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +                return postMapper.toDto(postRepository.save(oldPost));
да, можно, но решил вернуть актуальную версию, которая сохранилась в базе. Ну типа для надёжности 😁

2024-12-02 14:51 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +            throw new DataValidationException("Нельзя менять автора поста");
что-то и правда лишних условий навтыкал. Спасибо)

2024-12-02 15:00 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +                .sorted(comparePostByCreateDateDesc)
через тесты проверил, компаратор сортирует правильно. Я сравниваю второй элемент с первым, поэтому элементы изначально сортируются по убыванию и reversed() не нужен

2024-12-02 17:22 UTC, AlexLogino commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +                return postMapper.toDto(postRepository.save(oldPost));
ну так если прога зайдет в if, то эта актуальная версия все равно вернется на 62 строке

2024-12-02 20:40 UTC, jibulani commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +        if(postDto.id() != null) {
согласен, давай разные дто использовать в такой ситуации

2024-12-02 21:01 UTC, jibulani requested changes
есть замечания, а в целом код хороший, молодец!

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/{id}/public")
если  это публикация поста, то почему она выполняется get-запросом?

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
а в чем неудобство тестирования статических методов?
ну и в целом, если тяжело со временем, можно ограничиться тестированием контроллера, который использует методы отсюда

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +    public void validateId(Long id) {
по идее вместо этой валидации можно использовать аннотации `@NotNull` и `@Min(1)`

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body("Непредвиденный RuntimeException: " + ex.getMessage());
логично выкидывать тут 500, раз ты обрабатываешь все подряд RuntimeException, то есть ты не знаешь, что именно случилось в сервисе и ошибка вполне себе может быть на сервере

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        projectServiceClient.getProject(id);
а если проекта нет, то тут 404 возвращается и вылетает ошибка из сервиса?
если так, то хорошо бы именно ее обернуть в DataValidationException

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        throw new DataValidationException("Превышен лимит запросов в ProjectService: " + ex.getMessage());
а тут уже сервисные проблемы, раз ты внутри сервиса не можешь до другого сервиса достучаться, почему кидаешь DataValidationException? логичнее кинуть новую кастомную ошибку или просто RuntimeException, который потом в 500 ошибку превратится

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/service/postService/PostServiceImpl.java
> +    // правильно ли сделан компаратор и не нужно ли его вынести в отдельный файл куда-нибудь?
выглядит норм, если по тестам все ок, значит правильно :D
я бы только вынес их наверх к другим полям класса и сделал их private final полями

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        userServiceClient.getUser(id);
аналогично с validateProjectId

2024-12-02 21:01 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        throw new DataValidationException("Превышен лимит запросов в UserService: " + ex.getMessage());
аналогично с getProjectRecover

2024-12-03 21:02 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        projectServiceClient.getProject(id);
попробовал обернуть это строчку в try-catch, чтобы более осмысленную ошибку кидать, но тогда не срабатывает аннотация @Retryable. И пока не разобрался, как отлавливать статусы ошибок, поэтому оставил пока как есть

2024-12-04 08:58 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/{id}/public")
В голове сработала логика, что мы не передаём тело запроса, поэтому гет

2024-12-04 09:05 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
По моей логике, статические методы приходится тестировать неявно внутри кода, где они используются. Код теста разрастается, появляется больше методов, если обрабатывать разные кейсы, ну и разбираться в логике теста становится сложнее. А так, мы тестируем валидаторы в отдельных файлах, а в самом тесте сервиса их мокаем и тестируем только логику сервиса

2024-12-04 21:21 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
можно же и явно сам статический метод тестами покрыть

2024-12-04 21:25 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        projectServiceClient.getProject(id);
а зачем нам ретраить успешный запрос? мы сразу поняли, что сущности нет, можно не повторять запрос
ретраить нужно, если от внешнего сервиса не пришел ответ или он ответил невалидно (пятисотнул)

2024-12-04 21:33 UTC, jibulani requested changes
еще немного и в прод!

2024-12-04 21:33 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        projectServiceClient.getProject(id);
так что лучше явно выкинуть исключение в случае 404 и пробовать ретраить в случае 500

2024-12-04 21:33 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        userServiceClient.getUser(id);
тоже надо кинуть ошибку в случае 404

2024-12-04 21:33 UTC, jibulani commented on src/test/java/faang/school/postservice/validator/PostServiceValidatorTest.java
> +class PostServiceValidatorTest {
хорошие тесты, молодец!

2024-12-05 13:03 UTC, evgen-backend-rostov commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
я наверное что-то не так понял, когда слышал, что статические методы либо тяжело тестировать, либо их нельзя замокать для тестирования, поэтому решил сделать класс с обычными методами. Уточни пожалуйста, как в итоге будет правильнее сделать, я исправлю. А то я слегка запутался)

2024-12-05 21:41 UTC, jibulani approved these changes
по валидатору не суперкритичное замечание, надеюсь, понятно расписал там ответ, если что, на командном созвоне еще обсудим

в прод!

2024-12-05 21:41 UTC, jibulani commented on src/main/java/faang/school/postservice/validator/PostControllerValidator.java
> +@Component
а тебе его и не надо мокать, если хочешь, чтобы контроллер правильно отработал, то передаешь в параметры запроса нормальные данные, которые проходят валидатор, и дальше уже мокаешь работу сервиса
если хочешь проверить, как контроллер возвращает ответ в случае невалидных данных, то передаешь невалидные данные, валидатор выкидывает ошибку, которая обрабатывается на 400 код ответа, который в тесте и проверяешь

ты же не мокаешь никак поля dto, помеченные аннотацией NotNull, ты просто передаешь правильное ненуловое значение

ну и про тестирование этого метода, если бы он был статическим, тест мог бы выглядеть как-то так (могут быть ошибки синтаксиса, в компиляторе не проверял, но думаю, что общая суть будет понятна):
`assertThrows(DataValidationException.class, () -> PostControllerValidator.validatePostCreators(null, null));`

2024-12-05 21:41 UTC, merged