BJS2-41323 completed without test? and fixed method getUserId
CorporationX/post_service pull request #1270
Opened 2024-12-01 19:53 UTC by RuslanGabd

2024-12-02 21:39 UTC, jibulani requested changes
хорошо, но требуется еще доработать

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostCorrector.java
> +        postService.checkGrammarPostContentAndChangeIfNeed();
сталкивался с таким, что если в шедулере вылетело необработанное исключение, то он ломается и больше не выполняет задачи, я бы добавил try-catch и логировал ошибки, не выкидывая их в шедулере

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                result = extractTextFromRequest(response);
сначала пытаешься спарсить ответ, как будто он пришел корректный, а потом вызываешь extractBooleanSafely и проверяешь, корректный ли ответ по статусу, выглядит логичным засунуть внутрь if строку `result = extractTextFromRequest(response); `

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +        System.out.println(unpublishedPosts.size());
не надо

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +    HttpResponse<String> getResponsesWithCorrectText(String text) throws IOException, InterruptedException {
лучше вынести логику по работе со сторонним сервисом в отдельный класс

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +        HttpRequest request = HttpRequest.newBuilder()
почему не использовал Feign для запросов вовне?

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .uri(URI.create("https://textgears-textgears-v1.p.rapidapi.com/correct"))
напрашивается на вынос в конфиг или хотя бы в константу

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .header("x-rapidapi-key", "52b8fb4f25msh122fa7902a41e9bp1105cejsn54289f3bb474")
это точно в конфиг

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .header("x-rapidapi-host", "textgears-textgears-v1.p.rapidapi.com")
и это

2024-12-02 21:39 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .header("Content-Type", "application/x-www-form-urlencoded")
есть такая константа в org.springframework.http.MediaType.APPLICATION_FORM_URLENCODED_VALUE

2024-12-02 21:39 UTC, jibulani commented on src/main/resources/application.yaml
> +        thread-name-prefix: my-executor
лучше дать более осмысленное имя, которое будет отображать, что этот экзекьютор делает

2024-12-05 21:20 UTC, jibulani requested changes
давай еще немного докрутим решение, чтобы совсем хорошо стало :)

2024-12-05 21:20 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
> +                HttpResponse<String> response = responseTextGears.getResponsesWithCorrectText(content);
Наверное, неочень понятно откомментил - имел в виду вынести в отдельный класс вообще все, что связано с внешним сервисом, то есть у тебя был бы класс OrthographyService, внутри которого были бы приватные методы extractTextFromRequest и extractBooleanSafely

Также там был бы публичный класс String getCorrectContent(String content), который выкидывал бы исключение в случае ошибки или отдавал исправленный контент, если все ок

Таким образом, ты бы отделил зону ответственности по работе с орфографией и запросами в сеть в отдельный сервис OrthographyService, а PostService мог бы просто внутри forEach делать что-то подобное:
```
post.setContent(orthographyService.getCorrectContent(post.getContent()));
postRepository.save(post);
```

2024-12-05 21:20 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostService.java
>                  if (extractBooleanSafely(response)) {
какое-то неочень понятное название у метода extractBooleanSafely, давай лучше назовем extractStatus

2024-12-05 21:20 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResponseTextGears.java
> +public class ResponseTextGears {
предлагаю назвать OrthographyService и провести рефакторинг, как описал выше

2024-12-05 21:20 UTC, jibulani commented on src/main/java/faang/school/postservice/service/ResponseTextGears.java
> +        System.out.println("Input to getResponsesWithCorrectText: " + text);
коварные println продолжают проникать в код :D

2024-12-05 21:20 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostCorrector.java
>      @Async("my-executor")
тут остался my-executor
а зачем тут вообще `@Async`? насколько я помню у шедулера автоматом свой пул потоков есть

2024-12-06 14:44 UTC, RuslanGabd commented on src/main/java/faang/school/postservice/service/PostCorrector.java
>      @Async("my-executor")
Vlad говорил что по умолчанию на дефолтный пул потоков будет вешаться задача. 
Гугл тоже говорит что на дефолтный пул потоков задача пойдет без @Async.

2024-12-06 22:03 UTC, jibulani commented on src/main/java/faang/school/postservice/service/PostCorrector.java
>      @Async("my-executor")
ну да, там отдельный пул потоков для шедулеров
https://stackoverflow.com/questions/21993464/does-spring-scheduled-annotated-methods-runs-on-different-threads
ни разу не видел, чтобы его приходилось кастомизировать на самом деле
думаю, некритично

2024-12-06 22:05 UTC, jibulani approved these changes
супер!
осталось зарезолвить конфликты

2024-12-07 08:09 UTC, merged