Exception Handler
CorporationX/post_service pull request #1278
Opened 2024-12-03 06:34 UTC by bozhedar

2024-12-03 08:15 UTC, aplavina reviewed
Привет, можео еще добавить обработчики для MethodArgumentTypeMismatchException и HttpMessageNotReadableException

2024-12-03 08:58 UTC, flornana approved these changes

2024-12-06 14:39 UTC, MiraGlaceon requested changes

2024-12-06 14:39 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/client/ProjectServiceClient.java
> +    public void getProject(long projectId) {
Какую проблему решает эта заглушка? Если этот метод где-то используется в проекте, то давай подсветим проблему в команде. И у тебя задача про обработчики исключений, проверь, точно ли должно было попасть в коммит

2024-12-06 14:39 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/exception/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Давай переименуем на GlobalExceptionAdvice, чтобы класс говорил сам за себя какую роль выполняет

2024-12-06 14:39 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/exception/handler/GlobalExceptionHandler.java
> +        ex.getBindingResult().getAllErrors().forEach((error) -> {
Давай цепочку методов выводить с новой строки, чтобы было читабельнее

2024-12-06 14:39 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/exception/handler/GlobalExceptionHandler.java
> +        return ResponseEntity.badRequest().body(errors);
Spring умеет оборачивать объекты в ResponseEntity самостоятельно. Попробуй избавиться от раппинга (wrapping). BadRequest ты уже передаешь через аннотацию

2024-12-06 14:39 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/exception/handler/GlobalExceptionHandler.java
> +        String errorMessage = "Тело запроса имеет недопустимый формат.";
Избавься от лишнего создания объекта, передавай строку сразу в return

2024-12-06 15:03 UTC, bozhedar commented on src/main/java/faang/school/postservice/client/ProjectServiceClient.java
> +    public void getProject(long projectId) {
у меня почему-то при -git pull не подтянулся этот класс, в проекте он реализован, просто при мердже выберу ту версию которая есть в проекте

2024-12-06 15:24 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/client/ProjectServiceClient.java
> +    public void getProject(long projectId) {
Тогда проверь, чтобы не продублировался класс в проекте после мержа и тщательно реши конфликты

2024-12-06 15:25 UTC, MiraGlaceon approved these changes

2024-12-06 15:29 UTC, merged