Проверка комментариев на оскорбительный контент
CorporationX/post_service pull request #1279
Opened 2024-12-03 08:04 UTC by SergeyZhitenev

Комментарии до модерации
![image](https://github.com/user-attachments/assets/6b2dc269-e921-493a-8210-02f14b34dd69)
10:00 в фоне запустился процесс модерации комментариев 
![image](https://github.com/user-attachments/assets/6a5cb426-86dc-4f68-94b7-56ed11b8bb9c)
Все комментарии были успешно проверифицированы
![image](https://github.com/user-attachments/assets/a38ddbd3-32c7-42ed-8549-eb0a8cd9ade8)
2 последних комментария помечены как неприемлемые 
![image](https://github.com/user-attachments/assets/060fb6fe-cb30-4390-b9e5-8daf62aa1c0b)

2024-12-04 14:09 UTC, Sanasar1 requested changes
По код стайлу все отлично, никаких замечаний нет

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/repository/CommentRepository.java
> +    List<Comment> findByVerifiedIsNull();
Необязательно явно прописывать запрос через `@Query`. Spring Data по ключевым словам в названии метода переведет его в SQL запрос у себя под капотом и будет делать то, что ты от него и хотел. Можешь оставить как есть, ничего плохого в этом нету, просто хотел подчеркнуть)
Подробнее можешь прочитать об этом тут: https://docs.spring.io/spring-data/jpa/reference/repositories/query-keywords-reference.html

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +                .doOnError(e -> log.error("Error during overall comment processing: {}", e.getMessage()))
- В log.error() лучше передавать всю ошибку, а не только сообщение. То же самое с логом выше
- Я бы убрал log.info(). У нас в теории allNotVerifiedComments может быть огромным. И тогда у нас в логах будет огромный объем однотипных сообщений, из-за чего, в дальнейшем, будет тяжелее в логах ориентироваться. log.error() оставляем потому что это критический момент, который мы не хотим упускать

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        List<Comment> allNotVerifiedComments = commentRepository.findByVerifiedIsNull();
Можно просто notVerifiedComments написать, менее понятным не станет)

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/sheduler/CommentModerator.java
> +    }
Я бы сделал этот метод асинхронным, а не метод в сервисе. По сути оно и так, и так работать одинаково будет, но мне кажется логичным, что мы хотим, чтобы именно таска по расписанию в отдельном потоке запускалась, а не метод в сервисе. Если бы тут был не один вызов commentService.moderationOfComments(), то:
- Пришлось бы каждый метод аннотировать с `@Async`, чтобы у нас ничего в основном потоке не запускалось
- Пришлось бы потенциально прописывать логику ожидания потоков, чтобы не переходить к следующему шагу, не закончив предыдущий

Чтобы твои `@Scheduled` таски запускались в отдельном потоке можно:
- В конфигурации создать бин TaskScheduler и поставить ему количество потоков
- В application.yaml прописать spring.task.scheduling.pool.size и поставить кол-во потоков

С обоими подходами тебе не нужно явно указывать `@Async` в методе startModeration. Спринг сам запустит метод в отдельном потоке

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        List<Comment> allNotVerifiedComments = commentRepository.findByVerifiedIsNull();
Тут можешь убрать `@Async`, если в шедулере сделаешь метод асинхронным

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        List<Comment> allNotVerifiedComments = commentRepository.findByVerifiedIsNull();
А еще по хорошему бы поменять название метода, а то оно с существительного начинается)
Например, у Коли в задачке похожий метод называется verifyPosts. Можешь переименовать на verifyComments

2024-12-04 14:09 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
Будто бы метод в другом классе должен находиться (TextAnalysisService как вариант). А то у нас в CommentService совсем что-то инородное, что не имеет никакого отношения с комментариями

2024-12-04 17:46 UTC, Sanasar1 approved these changes

2024-12-06 13:53 UTC, ipasynkov-epam approved these changes

2024-12-06 13:53 UTC, ipasynkov-epam commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        List<Comment> notVerifiedComments = commentRepository.findByVerifiedIsNull();
А почему, если тип Boolean, ты выбираешь непроверенные сообщения по нуловым значениям? Мне кажется, что если сообщение проверено - значение true, если не проверено - значение false.

2024-12-06 13:54 UTC, ipasynkov-epam commented
Аппрув. Но оставил вопрос в комментариях)

2024-12-06 13:54 UTC, merged

2024-12-06 17:37 UTC, SergeyZhitenev commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        List<Comment> notVerifiedComments = commentRepository.findByVerifiedIsNull();
Исходя из условия задачи, сообщение которое успешно верифицировано, помечается true, а сообщение, которое содержит неприемлемый контент и подлежит удалению, считается не прошедшим верификацию и помечается как false. Соответственно еще не модерируемые сообщения - null
![image](https://github.com/user-attachments/assets/68ecff32-82e5-4803-95de-52d9f7aa49a0)