[Experienced] Проверка постов на оскорбительный контент
CorporationX/post_service pull request #1285
Opened 2024-12-03 21:04 UTC by YaKokin

2024-12-04 13:18 UTC, Sanasar1 requested changes
По код стайлу лютейший кайф, никаких замечаний тут нету, было удобно и приятно читать

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/config/verification/content/VerificationContentConfig.java
> +    }
Я бы вынес все это в условный ThreadPoolConfig. Не будем же мы под каждую отдельную задачу создавать свой тред пул

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
Кажется, что лог немного не про то. Должно быть что-то из разряда "Not reviewed posts not found" или "All the posts have already been reviewed". У нас же метод .findNotReviewedPost() ищет посты, которые не прошли верификацию. Следовательно, если список пустой, то все посты прошли верификацию.

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    }
- Метод возвращает список постов, а не один пост. Так что лучше переименовать на .findNotReviewedPosts
- Лог как-то тяжело читается. Сейчас получается: "Начать чтение постов, которые не прошли ревью". Я бы переписал следующим образом: "Trying to get posts that have not been reviewed"

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public void verifyPostAsync(List<Post> posts) {
Так же, лучше сделать verifyPostsAsync, чтобы подчеркнуть, что работаем тут мы не с одним постом, а со списком постов

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public void verifyPostAsync(List<Post> posts) {
А еще я хотел бы услышать мотивацию явно указывать Async в имени метода. Это не замечание, просто интересно послушать твои мысли по этому поводу. Вроде, с одной стороны, понятно, что метод вызывается асинхронно по аннотации. Но с другой стороны, теперь, если вызывать метод из другого класса, то сразу становится понятно, что метод будет запущен в другом потоке, без необходимости заглядывать в сам метод

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/PostService.java
> +            log.info("start verifying post with id {}", post.getId());
А стоит ли каждый пост отдельно логировать? У нас просто может быть огромный объем логов отсюда, из-за чего потом будет сложнее по ним ориентироваться
Я предлагаю убрать этот и следующий лог (который на уровне debug). Оставить только лог с ошибкой. Таким образом мы сильно сократим количество логов, но при этом, если что-то где-то пошло не так, мы будем знать об этом

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/PostService.java
> +                                log.error("Text analyzer client return error {}", ex.getMessage(), ex);
- Есть какая-то мотивация отдельно передавать и ex.getMessage() в сообщение лога, и отдельно саму ошибку? У нас же в ошибке и так есть сообщение об ошибке
- Если по итогу будешь убирать два лога выше, то сюда, наверное, стоит добавить на каком посте упала ошибка

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/moderation/ModerationDictionary.java
> +    }
Я бы переименовал название метода. Например: containsModeratedWords или hasNoRestrictedWords. 
- Таким образом, название метода больше отображает то, что он делает
- Не знаю, как у остальных, но приставка is у меня обычно ассоциируется с геттерами булевых значений объектов класса

Не то, чтобы это мега сильно убивало читаемость кода. Если хочешь, можешь оставить так, просто, лично мне, немного глаз мозолит)
И то же самое с методом isVerified в postService()

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    private boolean isVerified(TextAnalysisResponse textAnalysisResponse, Post post) {
То же самое, что и с методом isVerified в ModerationDictionary (опционально)

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/moderation/sightengine/check/impl/BaseCheck.java
> +    private final double target;
Я что-то совсем в этом классе потерялся)
Непонятно, что за переменные и где вообще этот класс используется)

2024-12-04 13:18 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
А еще можно сделать, чтобы метод вызывался в другом потоке. Я вижу, что у тебя батчи постов проходят верификацию в отдельном потоке, но будто бы и этот метод можно запустить в отдельном потоке, чтобы никак не задерживать главный поток
Можно, например, в конфигурации создать бин TaskScheduler, внутри него создать ThreadPoolTaskScheduler и поставить с помощью .setThreadPoolSize кол-во тредов. А еще проще (как я делаю), можно в application.yaml прописать spring.task.scheduling.pool.size, прописать кол-во тредов. В обоих случаях спринг сам будет все `@Scheduled` задачки запускать из этого пула потоков, и не нужно помечать методы `@Async`

2024-12-04 18:22 UTC, YaKokin commented on src/main/java/faang/school/postservice/config/verification/content/VerificationContentConfig.java
> +    }
Да, тут согл. Хорошо заметил

2024-12-04 18:28 UTC, YaKokin commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
Да, в сообщении лога опечатка, сори

2024-12-04 18:44 UTC, YaKokin commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
насчет сообщения ThreadPoolTaskScheduler не совсем понял, для чего это.

метод verifyPosts в ModerationScheduler никак не блокирует главный поток, потому что на нем аннотация Scheduled. за счет нее данный метод выполняется в отдельном потоке по тому же принципу, когда мы задачу закидываем в ScheduledThreadPool и она с заданной периодичностью выполняется.

метод verifyPostAsync тоже никак не блочит поток в котором выполняется verifyPosts, потому что на нем Async висит.

также не понял, как Scheduled и Async пересекаются здесь? у них же разное назначение.
Scheduled - для планирования задач по расписанию
Async - для асинхронного выполнения прямо сейчас, но при этом без блокировки вызывающего потока

2024-12-04 18:48 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public void verifyPostAsync(List<Post> posts) {
да, именно такая мотивация и была)
когда мы читаем код, в котором вызывается этот метод, сразу будет понятно, что данный метод выполняет свою работу асинхронно и главный поток он не блокирует

2024-12-04 18:56 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/PostService.java
> +            log.info("start verifying post with id {}", post.getId());
я считаю, что точно стоит логировать каждый пост, потому что это ключевой этап здесь. такой лог как по мне позволит точечно проверить ситуацию по каждому посту, если вдруг появятся какие-либо вопросы. например почему пост с руганью не был помечен как verified = false. если не залогировать точку, где начинается верификация, тяжело будет понять, что он даже проходил этап верификации

2024-12-04 18:59 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/PostService.java
> +            log.info("start verifying post with id {}", post.getId());
к тому же мне кажется, что тейк про сильное сокращение логов очень абстрактный.
я придерживаюсь такой позиции, что логировать нужно все, что потенциально может пригодиться для отладки или анализа конкретных кейсов.
и только потом нужно думать о сокращении логов (память дешевая, а вот время программиста, который будет дебажить код - нет)

2024-12-04 19:04 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/PostService.java
> +                                log.error("Text analyzer client return error {}", ex.getMessage(), ex);
да, мотивация есть. сообщение мы добавляем для того чтобы логи были читабельными. так читая логи в которых есть сообщение, мы быстро погружаемся в контекст и сразу можем понять, какую ошибку вернул нам реактивный клиент.
сообщение же мы передаем, чтобы залогировать стектрейс

насчет информации о посте, на котором ошибка упала хорошая идея. добавлю инфу про это в лог

2024-12-04 19:10 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/moderation/ModerationDictionary.java
> +    }
здесь под isVerified подразумевается то, что написано)
проверяю на то, что пост прошел верификацию.
насчет словаря согл в целом. метод словаря тоже говорит нам, прошел он верификацию или нет, но возможно стоит действительно уточнить, что конкретно он проверяет

2024-12-04 19:12 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/moderation/ModerationDictionary.java
> +    }
решил название метода isVerified в PostService изменить на postIsVerified чтобы было понятно, что конкретно прошло проверку

2024-12-04 19:20 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/moderation/sightengine/check/impl/BaseCheck.java
> +    private final double target;
он нужен для класса ModerationVerifier.
когда я получаю ответ от сервиса, в нем находятся значения классов модерации (sexual, toxic и т.д.) в них содержатся значения, который определяют то, насколько сильно сообщение соответсвует классу модерации.
например если toxic = 0.9 то в содержимом поста очень много токсичных высказываний.

эти значения мне нужно проверять на соответствие таргетов. можно в тупую написать проверки через if, но мы нарушаем Open Closed принцип. поэтому я написал отдельный класс. который совершает проверку на соответствие таргетам модерации.

он основан на паттерне стратегия. по сути он позволяет добавлять в себя различные стратегии проверки, после чего при вызове метода verify пробегается по всем стратегиям проверки и выполняет саму проверку.

так как у меня пока что код всех стратегий проверки совпадает, но при этом он может в будующем измениться, я создал класс базовой проверки, который в себе содержит стандартный код проверки.

если мне нужно будет добавить алгоритм проверки, который отличается от стандартного, я создам новый класс который реализует интерфейс ModerationCheck и буду использовать его в месте, где требуется проверять таргет как-то иначе.

2024-12-04 20:46 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
Да, ты прав, тут май бэд. Мне гпт сказал, что по дефолту `@Scheduled` задачки выполняются в основном потоке 👍 
На всякий случай сам проверил в коде. Единственное, тред пул для scheduled задачек по дефолту ограничен одним потоком. Если хочешь, можешь сделать больше. Но типа уже не критично и можешь так оставить

2024-12-04 21:11 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/moderation/ModerationDictionary.java
> +    }
Так метод же не проверяет, что пост уже прошел верификацию, а проверяет, что в посте нет "плохих" слов, что, в свою очередь, является шагом верификации. Я не говорю, что isVerified плохое название, а скорее, что можно было бы лучше передать в названии метода, что именно он делает
Можешь оставить как есть, ничего катастрафического в нынешнем названии метода я не вижу, просто предложил как, в моем понимании, можно было бы лучше описать метод

2024-12-04 21:14 UTC, Sanasar1 approved these changes

2024-12-04 21:22 UTC, YaKokin commented on src/main/java/faang/school/postservice/service/moderation/ModerationDictionary.java
> +    }
да, насчет словаря согласен с тобой

2024-12-04 21:24 UTC, YaKokin commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
думаю, пока смысла нет делать на большее число потоков. не уверен, как лучше поступить, если у нас будет несколько запланированных задач. тут нужно будет поресерчить

2024-12-04 22:16 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/service/moderation/ModerationDictionary.java
> +    }
А, сори, проглядел, что ты поправил)

2024-12-04 22:19 UTC, Sanasar1 commented on src/main/java/faang/school/postservice/scheduler/ModerationScheduler.java
> +            log.info("Reviewed posts not found");
В целом да. Вероятно, что нам без разницы, если какая-то джоба будет запущена с небольшим опозданием. Главное, что она регулярно запускается и не блокирует основной поток

2024-12-07 12:34 UTC, ipasynkov-epam approved these changes
отлично

2024-12-07 12:34 UTC, ipasynkov-epam commented on src/main/java/faang/school/postservice/config/thread/pool/ThreadPoolConfig.java
> +@Data
Не уверен, что здесь нужна эта аннотация.

2024-12-07 12:35 UTC, ipasynkov-epam commented
Исправь, пожалуйста, мерж-конфликты. И смержим все в ветку

2024-12-11 19:55 UTC, merged

2024-12-12 07:43 UTC, ipasynkov-epam commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .verify();
не очень нравится, что в одном методе ты делаешь разные вещи: проверяешь респонс и делаешь верификацию поста. При этом название метода эту верификацию не отражает. Может в будущих релизах как то поправить логику?)

2024-12-12 07:43 UTC, ipasynkov-epam commented on src/main/java/faang/school/postservice/service/moderation/sightengine/ModerationVerifier.java
> +        checks.add(new BaseCheck(value, sexual));
Уфф, я наконец разобрался, как это работает)).
Сано тоже спросил тебя чуть ниже в комментах, где ты написал пояснения. И про паттерн стратегия тоже. Но мне кажется, что OCP ты все же нарушил - здесь ты хардкодишь использование реализации BaseCheck. Т.е. каким образом ты будешь менять стратегию проверки?