Feature/bjs2 41282 moderation post content
CorporationX/post_service pull request #1287
Opened 2024-12-04 15:59 UTC by ZhubanyshZh

2024-12-05 09:13 UTC, aplavina approved these changes

2024-12-06 15:34 UTC, MiraGlaceon requested changes

2024-12-06 15:34 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/config/context/post/ModerationConfig.java
> +    private int fixedThreadPool;
Тут желательно добавить слово size, чтобы прояснить больше

2024-12-06 15:34 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/scheduler/post/ModerationScheduler.java
> +            log.info("not checked posts found!");
Тут not found

2024-12-06 15:34 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/service/post/ModerationDictionary.java
> +        }
Обработай ошибку, если не получилось загрузить словарь

2024-12-06 16:05 UTC, MiraGlaceon approved these changes

2024-12-06 16:05 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/config/context/post/ModerationConfig.java
> +    private int fixedThreadPool;
В имя переменной тоже следовало добавить, но так уже лучше

2024-12-06 16:09 UTC, merged