feature-BJS2-40840
CorporationX/post_service pull request #1288
Opened 2024-12-04 16:21 UTC by roship

- like/unlike on Comment or Post
- UnitTest on LikeService
- Modify PostService and PostDto to return likesCount 
- Modify Post components tests after modify PostDto

2024-12-04 20:41 UTC, RuslanGabd approved these changes
Все ок,  у меня только комментарии с рекомендациями.

2024-12-04 20:41 UTC, RuslanGabd commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private LocalDateTime createdAt;
я так понял лайк можно поставить или на пост или на коммент, поэтому эти поля не проверяются на null.
Можно добавить кастомный валидатор

   @AssertTrue(message = "Either postId or commentId must be provided")
    private boolean isValidLikeTarget() {
        return postId != null || commentId != null;
    }

2024-12-04 20:41 UTC, RuslanGabd commented on src/main/java/faang/school/postservice/service/LikeService.java
> +
я бы реализовал так checkForDuplicateLike(commentId, like.getUserId()));
а работу с репой перенес бы в метод. Проще читать становиться.

2024-12-04 20:41 UTC, RuslanGabd commented on src/main/java/faang/school/postservice/service/LikeService.java
> +                () -> {
как вариант можно возращать результат удален лайк или нет, что бы фронт получал результат операции.
   int deletedCount = likeRepository.deleteByPostIdAndUserId(postId, like.getUserId());
        if (deletedCount == 0) {
            throw new IllegalStateException("No like found for the given post and user");
        }
else {
return like.getId;
}

2024-12-07 19:07 UTC, roship commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private LocalDateTime createdAt;
Круто, такое не знал.
Но я в input DTO ловлю только UserId, чтобы от него поставить like на Entity (Post или Comment), в саму Entity беру из PathVariable. К нему добавлю @Min(1)

2024-12-07 20:01 UTC, roship commented on src/main/java/faang/school/postservice/service/LikeService.java
> +
Тоже не очень нравится, но в методе выше используется checkForDuplicateLike для postId. А тут commentId.

Если работу с репой перенести внутрь метода, то придется смотреть какой объект передан и ветвиться в условиях какой repository использовать.

2024-12-07 21:35 UTC, roship commented on src/main/java/faang/school/postservice/service/LikeService.java
> +                () -> {
Заставил задуматься )

LikeRepository.deleteByPostIdAndUserId возвращает void и его реализовал Влад.

Можно сделать чтобы возвращал кол-во удаленных строк:
@Modifying
@Transactional
@Query("DELETE FROM Like l WHERE l.postId = :postId AND l.userId = :userId")
int deleteByPostIdAndUserId(long postId, long userId);

И тогда обрабатывать (deletedCount == 0) как ты предлагаешь и звучит разумно, его рекомендует и ChatGPT )
Он предлагает 3 варианта:
1. Возвращать кол-во удаленных строк.
2. Делать предварительные проверки (существование, ..).
3. Возвращать удаленную сущность.

Можно не менять репу, и сначала проверяет существование like.
Но кажется, что может быть проблема: между проверкой существования и удалением другой вызов API, например, может удалить запись.
И это похоже на Exception, чтобы словить, нужно все же смотреть сколько записей удалено.
И в таком случае может даже не ясно что отдать в Response: для запроса задача выполнена - like удален, только не в этом запросе.

Хотя, скорее всего такого не будет.
@Transactional должно быть блокирует запись, и другой запрос не сможет ее удалить.


Евгений, подскажи как бы лучше делать в общем случае?
1. Модифицировать deleteByPostIdAndUserId чтобы отдавал кол-во записей?
2. Делать предварительные проверки? Я добавил likeRepository.existsByPostIdAndUserId
3. Возвращать удаленную сущность.
4. ?

И при возможности поясни про возможные конфликты, если будет попытка от нескольких пользователей удаления одного лайка.

2024-12-09 19:38 UTC, jibulani commented on src/main/java/faang/school/postservice/service/LikeService.java
> +                () -> {
насколько помню, обсуждали на планировании, давай еще раз тут зафиксирую

на мой взгляд, главное, что удаление прошло без ошибок, а сколько записей было удалено уже неочень важно

как обычно все зависит от задачи - если критично, чтобы запрос на удаление приходил только для существующего лайка, можно вернуть количество удаленных записей и если оно равно нулю, кинуть ошибку - это избавит нас от необходимости делать предварительный запрос на существование лайка

если неважно, существует ли такая запись или нет, а главное, чтобы ее точно не было, можно и не смотреть на количество удаленных записей, а довольствоваться тем, что метод удаления отработал успешно

по возможным конфликтам:
может быть такое, что два пользователя одновременно попытаются удалить лайк (хотя в данном случае у нас лайк может удалить только тот пользователь, который его поставил, но все же тогда можно предположить, что один пользователь с разных устройств одновременно решил удалить лайк) - тогда в случае с проверкой количества удаленных записей один запрос пройдет успешно, а второй с ошибкой, потому что такой лайк уже успел удалиться, а в случае с отсутствием проверки оба запроса пройдут успешно и это в целом будет соответствовать нашим требованиям, потому что для запроса достаточно, чтобы лайк точно перестал существовать

2024-12-09 20:16 UTC, jibulani requested changes
хорошо, молодец!
очень хорошее покрытие тестами
остались некритичные замечания, смотри сам по времени, насколько успеваешь их поправить + надо исправить мерж конфликт

2024-12-09 20:16 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    public void unlikePost(@PathVariable @Min(1) long id, @Valid @RequestBody LikeDto like) {
зачем тут `@RequestBody LikeDto like`?
для удаления лайка достаточно id поста, на котором он стоит

2024-12-09 20:16 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    public void unlikeComment(@PathVariable @Min(1) long commentId, @Valid @RequestBody LikeDto like) {
аналогично с удалением поста

2024-12-09 20:16 UTC, jibulani commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private Long postId;
на мой взгляд можно не передавать тут инфу о посте и комментарии, она определится вызовом соответствующего контроллера, если бы ты сделал один контроллер на лайк поста и коммента, тогда было бы важно в этой дто указать для чего именно лайк
некритично

2024-12-09 20:16 UTC, jibulani commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private LocalDateTime createdAt;
время лайка я бы на сервере определял как время получения запроса на создание лайка, чтобы не было разных проблем, что клиенты из разных таймзон свое время передают без указания таймзоны или просто неправильное время передают

2024-12-09 20:16 UTC, jibulani commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        Post post = getPostOrThrow(postId);
по-хорошему, работа с получением поста или коммента должна быть в соответствующих сервисах (PostService и CommentService), другие сервисы не должны напрямую в чужие репозитории ходить, это не их зона ответственности - вдруг перед получением поста нужно сделать дополнительное действие (например, проверить, что идентификатор в правильном формате передан - если сразу видно, что формат неправильный, то и не стоит базу запросом грузить). И обычно о таких особенностях знает только профильный сервис, который специализируется на работе с данной сущностью.

для нашей задачи не супер-критично, но лучше знать об этом

2024-12-09 20:16 UTC, jibulani commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        if (existingLike.isPresent()) {
можно упростить с помощью `ifPresent`

2024-12-09 20:16 UTC, jibulani commented on src/test/java/faang/school/postservice/mapper/LikeMapperTest.java
> +    // todo: how to check validation constraints?
обсудили на планировании, что валидацию дто можно в тестах на контроллер проверять

2024-12-09 20:16 UTC, jibulani commented on src/test/java/faang/school/postservice/mapper/LikeMapperTest.java
> +public class LikeMapperTest {
на маппер обычно пишут по одному тесту на каждый метод маппинга, который проверяет, что правильно смаппилось из одного объекта в другой, невалидные дто через запросы в тестах на контроллер проверяют

2024-12-09 20:16 UTC, jibulani commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +
круто, что так подробно тестами покрыл, молодец!

2025-01-27 19:36 UTC, roship commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    public void unlikePost(@PathVariable @Min(1) long id, @Valid @RequestBody LikeDto like) {
Из DTO беру userId и проверяю его на существование.

В задании такая формулировка:
"LikeDto тоже необходимо создать с минимальным набором необходимых полей для создания лайка. Возможные поля для этого класса можно посмотреть в классе Like."

2025-01-28 15:55 UTC, roship commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private LocalDateTime createdAt;
Сейчас оно определяется при создании в БД как @CreationTimestamp.
В идеале думаю нужно все даты хранить в UTC и отдавать тоже.

Т.е. сейчас оно игнорируется в DTO при запросе на создание Like, но передается в Response.

2025-01-28 15:58 UTC, roship commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private Long postId;
Да, действительно.
Когда делал, первично прочитал в постановке:
"LikeDto тоже необходимо создать с минимальным набором необходимых полей для создания лайка. Возможные поля для этого класса можно посмотреть в классе Like."
и так и перенес.

Но с другой стороны, если в последующем будут методы API для обращения к любому Like по id или по списку, эти данные будут полезны для ответа.

2025-01-29 20:02 UTC, jibulani requested changes
все хорошо, молодец!

осталось удалить лишние комментарии или раскомментить код, если он нужен

2025-01-29 20:02 UTC, jibulani commented on src/test/java/faang/school/postservice/mapper/like/LikeListMapperTest.java
> +//            assertThat(likeList.get(i).getId()).isEqualTo(likeDtoList.get(i).getId());
не надо закомменченный код оставлять

2025-01-30 08:30 UTC, roship commented on src/test/java/faang/school/postservice/mapper/like/LikeListMapperTest.java
> +//            assertThat(likeList.get(i).getId()).isEqualTo(likeDtoList.get(i).getId());
My bad, fixed.
Замахался на merge c master

2025-01-30 22:13 UTC, jibulani approved these changes
супер!

2025-01-30 22:13 UTC, merged