bjs2 41281 ban users
CorporationX/post_service pull request #1301
Opened 2024-12-08 14:39 UTC by ZhubanyshZh

2024-12-21 18:58 UTC, MiraGlaceon requested changes

2024-12-21 18:58 UTC, MiraGlaceon commented on .github/workflows/ci.yml
> +name: CIForMedusaMaster
Это ты решал добавить CI или как-то упустили? Мы же добавляли в post_service

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    @PostMapping("/post/{postId}/comment")
В эндпоинтах используем множественное число для именования ресурсов. Например, posts или comments

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    @PutMapping("/comment/{commentId}")
Если создается комментарий через пост, то его обновление и удаление делай через пост. Сделай заглавный RequestMapping("posts/comments/") на весь контроллер. Сейчас у тебя эндпоинты каждый с разным путем к ресурсу в url

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +@RequestMapping("/api/v1")
Это нужно вынести в конфигурационный файл приложения и определить бин для этого. Посмотри как подобное делал Дима в user_service

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +        if (comment.getId() != null) {
Все проверки делаем в сервисе. На стороне контроллера не делаем проверок. У каждого слоя приложения своя ответственность

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PostMapping("/posts")
Тут posts можно вынести в общий requestMapping. Author перевести во множественное число

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/album/AlbumController.java
> +    @PutMapping("/{albumId}/add")
PutMapping и DeleteMapping уже подразумевают действие. Не нужно добавлять в эндпоинт слова типа add или delete

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/controller/album/AlbumController.java
> +    @PostMapping("/toFavorites")
В url лучше не писать стилем camelCase, используй дефис to-favorites

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/dto/payment/PaymentStatus.java
> +    SUCCESS
Не только успешный статус может быть, добавь еще Failed как минимум

2024-12-21 18:58 UTC, MiraGlaceon commented on src/main/java/faang/school/postservice/exception/AlbumException.java
> +public class AlbumException extends RuntimeException {
Имя ошибки должно говорить о чем ошибка. Здесь понятно, что по альбомам, но какого типа ошибка?

2025-01-05 10:38 UTC, ZhubanyshZh commented on .github/workflows/ci.yml
> +name: CIForMedusaMaster
@MiraGlaceon Привет, весь ревью это не мой коммит. Я исправил, это из за пулл реквест в ветку дев. Сейчас все правильно

2025-01-08 15:23 UTC, MiraGlaceon approved these changes

2025-01-08 16:47 UTC, merged