Post service publishes PostViewEvent  for Analytics Service
CorporationX/post_service pull request #1331
Opened 2024-12-25 17:59 UTC by Amanyaz

(БЕЗ ТЕСТА) PostService публикует PostViewEvent в тopic postViewChannel в Redis. Был создан класс PostViewEvent. Соответствующие конфигурации Redis были добавлены.

2024-12-26 01:13 UTC, alexFromAC143937 approved these changes

2024-12-26 01:13 UTC, alexFromAC143937 commented on src/main/java/faang/school/postservice/dto/post/PostViewEvent.java
> +public class PostViewEvent {
Не критично. Можно представить, как record

2024-12-29 12:43 UTC, jibulani requested changes
хорошо, молодец!

нужно убрать лишние импорты и можно мержить

2024-12-29 12:43 UTC, jibulani commented on src/main/java/faang/school/postservice/controller/PostController.java
> +import io.swagger.v3.oas.annotations.Operation;
зачем?

2024-12-29 14:23 UTC, Amanyaz commented on src/main/java/faang/school/postservice/controller/PostController.java
> +import io.swagger.v3.oas.annotations.Operation;
Готово!

2024-12-29 21:28 UTC, jibulani approved these changes
отлично!

2024-12-29 21:28 UTC, merged