BC-4866 Создание, редактирование и удаление альбома постов
CorporationX/post_service pull request #165
Opened 2023-08-15 05:54 UTC by YuliaQueen

https://faang-school.atlassian.net/browse/BC-4866

2023-08-16 09:00 UTC, ipavelbel approved these changes
В целом всё хорошо, у меня возник вопрос по валидации стоит ли несколько раз проверять. Красиво тесты написаны, надо взять себе на заметку))

2023-08-18 08:44 UTC, InnMish requested changes

2023-09-01 09:58 UTC, InnMish requested changes

2023-09-04 11:35 UTC, InnMish approved these changes

2023-09-04 11:35 UTC, merged