Feature/bc 4868 add album to favourites
CorporationX/post_service pull request #232
Opened 2023-09-05 12:08 UTC by YuliaQueen

https://faang-school.atlassian.net/browse/BC-4868

2023-09-06 10:26 UTC, schonpink commented on src/main/resources/application.yaml
> +        comment_event-channel:
тут что-то непонятное с черточками

2023-09-06 10:26 UTC, schonpink commented on src/main/java/faang/school/postservice/controller/AlbumController.java
>      }
хоть и в предоставленной части проверки ПР нет кода Маппера, однако в коде в post_service не увидела как маппятся сущности List<Post> posts на List<Integer> postIds (и наоборот) в дто-шке?

2023-09-06 10:26 UTC, schonpink commented on src/main/java/faang/school/postservice/controller/AlbumController.java
>      }
и еще вопрос скорее к Инне:
 у сущности есть поле long authorId (post_service), в дто-шке объявляем уже Long authorId, можем ли мы проставлять другой тип переменной для dto и не критично ли это для кода вцелом?

2023-09-06 10:26 UTC, schonpink commented on src/main/java/faang/school/postservice/service/album/AlbumService.java
> +        albumRepository.deleteAlbumFromFavorites(album.getId(), userId);
такой вопрос - а если например БД по-какой-то причине недоступна или самого альбома в ней нет - будем ли мы как-то обрабатывать эту ситуацию?

2023-09-07 17:51 UTC, YuliaQueen commented on src/main/resources/application.yaml
> +        comment_event-channel:
это из мастера так приехало и проект не запускался, пришлось подправить

2023-09-07 17:52 UTC, YuliaQueen commented on src/main/java/faang/school/postservice/controller/AlbumController.java
>      }
> 

посты пишутся в List

2023-09-09 07:23 UTC, InnMish requested changes

2023-09-09 07:23 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/AlbumController.java
>      }
Вопрос хороший) 
Тут надо просто постановку тогда выяснить. Мы можем создать альбом сразу с постами внутри? Судя по дто - можем. Но тогда у нас метод createAlbum работает неверно сейчас. Если пользователь передаст в метод createAlbum айдишники постов, то маппер их не смаппит в сущности. И альбом сохранится без постов. 

Тут надо решить, мы будем создавать альбом без постов, а потом отдельно заполнять альбом постами, или будем сразу иметь возможность создать альбом с постами. Если второе, то надо в маппере дописать маппинг айдишников на сущности постов)

2023-09-09 07:23 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/AlbumController.java
>      }
> и еще вопрос скорее к Инне: у сущности есть поле long authorId (post_service), в дто-шке объявляем уже Long authorId, можем ли мы проставлять другой тип переменной для dto и не критично ли это для кода вцелом?

Тут не критично. У сущности поле long, то есть мы сразу ограничили - это поле не может быть null. Но в Dto мы делаем поле Long, потому что пользователь изначально это поле сам не заполняет - он не знает свой айдишник. И только потом, после проверки пользователя в user_service мы заполняем это поле. Так делать можно)

2023-09-09 07:23 UTC, InnMish commented on src/main/java/faang/school/postservice/service/album/AlbumService.java
> +        Album album = getAlbumByOwnerId(albumId, userId);
getAlbumByIdAndOwnerId, наверное, лучше назвать 
Чтобы отражало действительность)

2023-09-09 07:23 UTC, InnMish commented on src/main/java/faang/school/postservice/service/album/AlbumService.java
> +        albumRepository.deleteAlbumFromFavorites(album.getId(), userId);
Мы проверили на строчке выше, что такой альбом есть. А если сделать delete из таблицы несуществующей сущности, то такой запрос просто будет проигнорирован. То есть он "как будто" успешно выполнится, но на самом деле ничего не произойдет. 
А если база вдруг упадет, то у нас транзакция откатится просто, и ничего не произойдет. Пользователю придется снова попробовать

2023-09-10 14:04 UTC, InnMish approved these changes

2023-09-10 14:04 UTC, merged