Bc 4230
CorporationX/post_service pull request #244
Opened 2023-09-10 19:51 UTC by Abramovnv

2023-09-11 06:47 UTC, tarrasoff approved these changes

2023-09-11 06:47 UTC, tarrasoff commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    private List<UserDto> findUsersWhoLiked(List<Like> likes) {
нет тестов на этот метод

2023-09-11 06:47 UTC, tarrasoff commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        int subListSize = 100;
эту переменную можно вынести в конфиг

2023-09-11 13:58 UTC, Abramovnv commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    private List<UserDto> findUsersWhoLiked(List<Like> likes) {
Я вот хоть убей не понимаю, как его протестировать. Я над этим тестом сидел дольше, чем делал логику задачи. Через постман проверял, все работает. Я там набросал, как я хотел тест написать, но он не работает. help me please

2023-09-15 08:35 UTC, InnMish requested changes

2023-09-15 08:35 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    public List<UserDto> getLikesByPostId(Long postId) {
Транзакции на методы нужны)

2023-09-15 08:35 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        postService.getPostById(postId);
Если этот метод только для проверки используется, я бы предложила написать отдельный, который проверить exists или нет 
В целом так тоже норм, просто странно, что мы идем сделать get, но при этом не используем нигде результат

А вообще надо ли проверять? Что будет, если мы дернем метод findByPostId по такому postId, для которого поста не существует? Вернется просто пустой список, скорее всего, то есть ошибки не будет

2023-09-15 08:35 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    public List<UserDto> getLikesByPostId(@Min(0)@PathVariable Long postId) {
Названия методов не отражают того, что в сервисе происходит сейчас 
Название такое, как будто мы лайки вернем, а не пользователей 
Давай поправим)

2023-09-15 08:35 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            for (int j = i; j < i + maxSubListSize && j < usersId.size(); j++) {
У листа есть метод sublist, который положит нужные тебе подсписок в новый лист, и тебе не придется писать вложенный цикл

2023-09-15 08:35 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            for (int j = i; j < i + maxSubListSize && j < usersId.size(); j++) {
Тебе тут нужно будет посчитать endIndex каждого саблиста, можно использовать int endIndex = Math.min(i + maxSubListSize, usersId.size()); например 
И положить в саблист начальный индекс, который у тебя i, и конечный, который вот endIndex  

Так сложность этого метода будет не O(N^2), а просто линейной

2023-09-15 08:35 UTC, InnMish commented on src/main/resources/application.yaml
> +        maxSubListSize: 100
Нам тут не будет достаточно просто maxSubListSize? 
Я бы даже назвала maxUsersSubListSize, а все остальные префиксы убрала бы

2023-09-15 08:35 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    private List<UserDto> findUsersWhoLiked(List<Like> likes) {
Мы не тестируем межсервисную интеграцию - фейн мокнуть сложно 
Какие-то базовые тесты через вызывающий метод сделать, и достаточно

2023-09-19 08:46 UTC, Abramovnv commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            for (int j = i; j < i + maxSubListSize && j < usersId.size(); j++) {
я пытался тоже саблист воткнуть крутил крутил, но не догадался как end записать
а, так действительно гораздо лучше, в плане сложности!)

2023-09-20 07:58 UTC, InnMish approved these changes

2023-09-20 07:58 UTC, merged