Feature bc 4260
CorporationX/post_service pull request #247
Opened 2023-09-18 09:17 UTC by TowBoat39

2023-09-18 09:42 UTC, czar777 approved these changes

2023-09-18 09:42 UTC, czar777 commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +    private PostDto idDefinition(Long userId, Long projectId, PostDto postDto) {
методы это действия, поэтому их лучше начинать с глаголов

2023-09-18 09:42 UTC, czar777 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    }
у тебя есть класс валидации для этого

2023-09-18 09:42 UTC, czar777 commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +
}

2023-09-18 09:44 UTC, TowBoat39 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    }
Тут так надо)

2023-09-18 09:46 UTC, czar777 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    }
убедил)

2023-09-20 08:49 UTC, InnMish requested changes

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/dto/PostDto.java
> -}
А это нигде не использовалось? 
В системе лайков разве не нужен вот этот список likes?

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/mapper/PostMapper.java
> -        return likes.stream().map(Like::getId).toList();
И это тоже не использовалось? Для лайков нужно

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postRepository.save(post);
Если это изменение существующего поста, то save  необязательно делать, хибер отслеживает изменения и после завершения работы с сущностью все обновляется

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
>  @Transactional(readOnly = true)
Для всех на ридонли? Это же неправда 
Какие-то методы у нас на изменение работают

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
>  @Transactional(readOnly = true)
Лучше на каждый метод вешать аннотацию со своими параметрами

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postRepository.save(post);
То же, что и выше

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postRepository.save(post);
В общем-то везде

2023-09-20 08:49 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> filteredPosts = posts.stream().sorted((a, b) -> b.getPublishedAt().compareTo(a.getPublishedAt())).toList();
Ничем не отличается от метода выше 
Они ж у нас вообще абсолютно одинаковые, только названия полей разные) 
Помимо валидаций все можно в общий метод вытащить

2023-09-23 08:34 UTC, InnMish approved these changes

2023-09-23 08:34 UTC, merged