Werewolf master post by schedule
CorporationX/post_service pull request #273
Opened 2023-10-12 01:10 UTC by M437A

2023-10-12 15:27 UTC, czar777 approved these changes

2023-10-12 15:27 UTC, czar777 commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +        }
Не будет ли лучше это действие сделать через sublist?

2023-10-12 15:27 UTC, czar777 commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +        }
тут тоже я думаю лучше будет сделать через sublist

2023-10-13 08:36 UTC, InnMish requested changes

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/config/PostScheduleConfig.java
> +}
А ты не хочешь создать для кэша бин отдельный не в конфиге, а описать класс, где будешь работать внутри с методами мапы? 
Потому что инжектить во все сервисы, которые этот кэш используют выглядит непонятно. Кто-нибудь посмотрит на код и не поймет даже, что это кэш 

Плюс инкапсулируем так логику кэша именно в классе Cache - всякие обновления мапы, сохранение туда элементов и т.д

Строго говоря, кэш - это не конфиг

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/config/PostScheduleConfig.java
> +        return new ConcurrentHashMap<LocalDateTime, Set<PostDto>>();
LocalDateTime не учитывает таймзону 
Если пользователь живет в одной таймзоне и планирует паблиш своих постов в ней, а наш сервис работает в другой, то когда пост опубликуется? 
Не лучше ли здесь использовать ZonedDateTime?

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +    private LocalDateTime scheduledAt;
Также - не учитывается таймзона

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +import io.lettuce.core.dynamic.annotation.Param;
Точно этот импорт?

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            if (scheduleTime.isBefore(LocalDateTime.now().plus(timeForCacheUpdate, ChronoUnit.MINUTES))) {
LocalDateTime.now().plus(timeForCacheUpdate, ChronoUnit.MINUTES))

Если такая операцию нужна, ее стоит провести выше условия, а не в нем. Считаешь это значение до условия и присваиваешь его полю с говорящим названием, чтобы всем было понятно, что тут происходит 
Сейчас я вижу, что мы тут к текущему времени прибавляем какое-то еще время дл обновления кэша, но не понимаю, почему это сделано. 

Приходится много времени потратить, чтобы понять, что эта проверка для того, чтобы положить в кэш те посты, которые должны быть в течение часа опубликованы. Вот прям так и назвать можно это поле nextHour или вроде того

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            if (scheduleTime.isBefore(LocalDateTime.now().plus(timeForCacheUpdate, ChronoUnit.MINUTES))) {
Плюс тут тоже нужно учесть таймзоны

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                postMap.get(scheduleTime).add(postDto);
Вот эти две операции работы с мапой положить в класс кэш, а сюда дать только метод кэша - все должно быть инкапсулировано

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        LocalDateTime time = LocalDateTime.now().plus((long) (timeForCacheUpdate * 1.05), ChronoUnit.MINUTES);
таймзона

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +        if (postDtoSet != null) {
Значит ли это, что в мапе может храниться какой-то ключ, значение для которого == null? 
Насколько это целесообразно?

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +                currentGroup.clear();
А зачем мы дробим весь сет на листы? Затем каждый лист отправляем в эддату, там асинхронно обрабатываем события, а затем тут опять дробим... 
Не будет ли эффективнее сразу весь сет на асинхронное выполнение отправить?

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +                    postMap.remove(now);
вот эту штуку тоже в кэш

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +                    log.info("publish posts");
так уже закончили же) completed тогда?

2023-10-13 08:36 UTC, InnMish commented on src/main/java/faang/school/postservice/sheduler/ScheduledPostPublisher.java
> +        }));
Это все в методы кэша

2024-12-22 20:12 UTC, closed without merging