News Feed
CorporationX/post_service pull request #294
Opened 2023-10-31 17:50 UTC by M1hasMAD

2023-11-01 12:25 UTC, kkkooolllyyyaaa requested changes
Покомментил)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/config/RedisConfig.java
> +    public RedisTemplate<Long, LinkedHashSet<Long>> redisUsersTemplate(RedisConnectionFactory redisConnectionFactory) {
Наверное название в "" не надо писать, бин у тебя назовётся по имени метода просто

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/config/RedisConfig.java
> +    }
Можно вынести в отдельный метод buildRedisTemplate <K, V>, который принимает просто 2 типа или 2 класса например)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/config/kafka/KafkaConfig.java
> +                JsonDeserializer.class);
В 1 строчку же красиво влезает, не?)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/config/kafka/KafkaConfig.java
> +                JsonDeserializer.class);
В 1 строку?

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    @GetMapping("/all")
1) У тебя по идее "/comments", поэтому не нужно all, у тебя и так во множественном числе без никаких фильтров
2) Зачем тебе метод на получение ВСЕХ комментов? Я понимаю все комменты к посту (и то спорно, если это большой пост).

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    @GetMapping("/all-by/{postId}")
all-by -> by-post я бы назвал

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    @GetMapping("/all-by/{postId}")
+ Лучше Page возвращать, а то большой пост на 5к+ комментов за раз выгружать для каждого пользователя (который хочет посмотреть пост) слишком жестко. Тем более, что больше постов -> больше тех кто увидит скорее всего, так что не ложится как-то)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    @DeleteMapping("/{id}/delete")
/delete лишнее, у тебя метод delete

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/controller/CommentController.java
Я бы везде добавил лог, о факте вызова эндпоинта

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/controller/FeedController.java
> +        feedService.heatFeed(userDto);
логи)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/client/CommentDto.java
> +    private LocalDateTime updatedAt;
read only?

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/client/CommentDto.java
> +    private long id;
read only?

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/client/CommentDto.java
> +    private long id;
Ну и сделать Long, а при создании же ведь ничего не передадут

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/client/CommentDto.java
> +    private long postId;
Long authorId и postId

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaCommentEvent.java
> +public class KafkaCommentEvent {
Не обязательно Kafka же, ты же можешь это и в редис и в рэббит послать. Давай без Kafka

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaLikeEvent.java
> +public class KafkaLikeEvent {
Без кафка

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaPostEvent.java
> +public class KafkaPostEvent {
без кафка.

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaCommentEvent.java
> +public class KafkaCommentEvent {
NewCommentEvent или AddCommentToPostEvent

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaLikeEvent.java
> +public class KafkaLikeEvent {
LikePostEvent я бы назвал

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaPostEvent.java
> +public class KafkaPostEvent {
CreatePostEvent, NewPostEvent

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaPostViewEvent.java
> +    private Long authorId; // who viewed the post
коммент избыточен

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/dto/kafka/KafkaPostViewEvent.java
> +    private Long authorId; // who viewed the post
PostViewEvent давай)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/listener/KafkaCommentConsumer.java
> +        commentService.changeListComments(kafkaCommentEvent.getComment(), kafkaCommentEvent.getPostId());
лог бы) Что пришло сообщение

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/listener/KafkaLikeConsumer.java
> +        likeService.incrementLike(kafkaLikeEvent.getPostId());
лог)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/listener/KafkaLikeConsumer.java
> +        likeService.incrementLike(kafkaLikeEvent.getPostId());
\+ А если null?)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/listener/KafkaCommentConsumer.java
> +        commentService.changeListComments(kafkaCommentEvent.getComment(), kafkaCommentEvent.getPostId());
\+ А если comment null?)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/listener/KafkaPostConsumer.java
> +        PostDto postDto = postService.getPost(kafkaPostEvent.getPostId());
\+ А если postId null?)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/listener/KafkaPostViewConsumer.java
> +        postService.saveViewToRedis(kafkaPostViewEvent.getPostId());
\+ А если postId null?)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/mapper/redis/RedisCommentMapper.java
> +    }
IntStream.range + mapToObj какой-нибудь может подойти по идее

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/FeedService.java
> +        long userId = userContext.getUserId();
Если null у тебя будет NPE и выкинется 500-ка, надо 400

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/FeedService.java
> +    public List<FeedDto> getFeed(Long postId) {
На всякий Transactional стоит добавить

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/FeedService.java
> +                }
можно вынести вниз, а то слишком большая глубина вложенности скобок

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/FeedService.java
> +                    .build();
вынести бы то что в скобках)

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/FeedService.java
> +                redisPostRepository.save(redisPostMapper.toRedisPost(postDto));
А нельзя если что перезаписать? А то тут 2 вызова вместо одного

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/FeedService.java
> +            checkUserInRedis(postDto.getAuthorId()); // пост есть -> проверяем юзера в кэше, иначе сохраняем его
зачем?

2023-11-01 12:25 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/model/redis/RedisPost.java
> +    private Integer postLikes;
Лучше сделать AtomicInteger

2023-11-01 12:31 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/model/redis/RedisPost.java
> +@RedisHash(value = "Post", timeToLive = 86400)
ttl можно из конфига достать

2023-11-01 12:32 UTC, kkkooolllyyyaaa commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    }
Это в идеале в Redis транзакции сделать. А то у тебя будет чуть меньше чем по факту (2 потока прочитали X и записали X + 1)

2023-11-06 19:24 UTC, M1hasMAD commented on src/main/java/faang/school/postservice/model/redis/RedisPost.java
> +@RedisHash(value = "Post", timeToLive = 86400)
но ведь ttl принимает long следовательно не могу туда засунуть строку

2024-12-22 20:12 UTC, closed without merging