Werewolf bc2 bjs2 1669
CorporationX/post_service pull request #307
Opened 2024-01-29 16:37 UTC by ruslanator

2024-02-01 05:47 UTC, Edisolt5498 requested changes

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        if (postContent.isEmpty() || postContent.isBlank()) {
На сколько я знаю, isBlank это прокаченный isEmpty, т е он его заменяет и еще проверяет на пустые символы. Но при этом оба бросают NullPointerExc если postContent = null. Поэтому я думаю надо так: postContent == null || postContent.isBlank()

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(postMapper.toEntity(postDto));
А не нужно разве перед сохранением убедиться, что проект/пользователь существуют

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
Вроде как надо назначить время публикации

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
тут например, время обновления само обновиться из-за @UpdateTimestamp, а в publishPost вроде нет

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +
Получение поста по id не хватает

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        List<Post> sortedPosts = postRepository.findByAuthorId(authorId).stream()
тут бы метод .sortDrafts(), он же будет в методе getProjectDrafts использован

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        List<Post> sortedPosts = postRepository.findByAuthorId(authorId).stream()
а тут .sortPosts()

2024-02-01 05:47 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/update/{postId}")
Я бы сделал /posts/postId для delete и update, без слова-действия. Все равно у тебя только один putMapping и deleteMapping

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        postService.createPostDraft(dto);
А без Valid аннотации у тебя работает валидация на dto?

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postValidator.validatePost(postDto);
Здесь еще надо проверить, что пользователь или проект, который автором в дто передается, существует в бд
Иначе такой пост нельзя создать

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +        return postOpt.orElseThrow(() -> new DataValidationException("Post not found"));
объедини в одну строчку, можно postOpt не создавать отдельным полем

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +        Post post = postOpt.orElseThrow(() -> new DataValidationException("Post not found"));
это вызов метода на 63, а потом его результат смаппить уже 
А так дублирование получается

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        postService.publishPost(postId);
Через хедер тут нужно получить айди проекта или пользователя, от которых получаешь этот реквест 
И в зависимости от того, что получаешь: юзерайди или проджектайди, проверяешь, имеет ли пользователь/проект доступ к публикации поста или нет

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
Если используешь Transactional, то save уже можно не делать, если в рамках этой сессии получил данные из бд

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
Если используешь Transactional, то save уже можно не делать, если в рамках этой сессии получил данные из бд

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        postService.updatePost(postId, dto);
Через хедер тут нужно получить айди проекта или пользователя, от которых получаешь этот реквест
И в зависимости от того, что получаешь: юзерайди или проджектайди, проверяешь, имеет ли пользователь/проект доступ к публикации поста или нет

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        postService.deletePost(postId);
Через хедер тут нужно получить айди проекта или пользователя, от которых получаешь этот реквест
И в зависимости от того, что получаешь: юзерайди или проджектайди, проверяешь, имеет ли пользователь/проект доступ к публикации поста или нет

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
Если используешь Transactional, то save уже можно не делать, если в рамках этой сессии получил данные из бд. Проверь прям в бд как работает с save и без

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        userServiceClient.getUser(authorId);
здесь используй метод existsById, чтобы не тащить данные, которые не будут использоваться дальше

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        projectServiceClient.getProject(projectId);
здесь используй метод existsById, чтобы не тащить данные, которые не будут использоваться дальше

Проверь в связке работу всех 3 сервисов после исправлений, чтобы убедиться, что все пути правильно настроены

2024-02-08 09:52 UTC, InnMish commented on src/main/java/faang/school/postservice/service/PostService.java
> +    }
Получение всех черновиков не удаленных постов за авторством пользователя с данным id. Посты должны быть отсортированы по дате создания от новых к старым.

Получение всех черновиков не удаленных постов за авторством проекта с данным id. Посты должны быть отсортированы по дате создания от новых к старым.

Получение всех опубликованных не удаленных постов за авторством пользователя с данным id. Посты должны быть отсортированы по дате публикации от новых к старым.

Получение всех опубликованных не удаленных постов за авторством проекта с данным id. Посты должны быть отсортированы по дате публикации от новых к старым.

2024-02-08 09:52 UTC, InnMish commented on src/test/java/faang/school/postservice/controller/PostControllerTest.java
> +    }
Негативные кейсы надо проверить еще

2024-02-12 18:05 UTC, merged