BJS2-1898
CorporationX/post_service pull request #336
Opened 2024-02-18 10:02 UTC by mirayoo

2024-02-26 03:27 UTC, Edisolt5498 requested changes

2024-02-26 03:27 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/mapper/AdMapper.java
> +    @Mapping(source = "postId", target = "post")
а как из postId получить post

2024-02-26 03:27 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/AdService.java
> +        var batch = (size - 1) / BATCH_SIZE;
А не много ли var'ов. Вроде их используют когда какая-то специфичная переменная и особо не нужно знать, какая именно.
Например, с EntrySet каким-нибудь. А тут везде прям

Ну может это ок. Не знаю

2024-02-26 03:27 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/AdService.java
> +                            log.info(list.toString());
Может тут инфы добавить, типо, "Удаление порции просроченных постов : " lint.toString ()

2024-02-26 03:27 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/AdService.java
> +    public void removeExpiredAds() {
А еще мне Инна писала про @Async. Типо, в таком случае не нужно реализовывать многопоточность. 
Но это она уже скажет xD

2024-02-26 03:27 UTC, Edisolt5498 commented on src/main/java/faang/school/postservice/service/AdService.java
> +    private void removeAllById(List<AdDto> adDtos) {
думаю по названию метода логично передавать List<Long> ids

2024-03-07 15:27 UTC, mirayoo commented on src/main/java/faang/school/postservice/mapper/AdMapper.java
> +    @Mapping(source = "postId", target = "post")
я там прикрутил `uses: Postservice.class`, он этот момент должен обрабатывать

2024-03-07 15:28 UTC, mirayoo commented on src/main/java/faang/school/postservice/service/AdService.java
> +                            log.info(list.toString());
Вообще лишнее, сори, забыл убрать :D

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/controller/AdController.java
> +    public AdDto remove(@PathVariable Long id) {
а как через PathVariable  сюда придет айди? тестировал постменом?

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/mapper/AdMapper.java
> +    @Mapping(source = "postId", target = "post")
Должен или обрабатывает? Надо проверить

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/service/AdService.java
> +    }
Неверно метод назван 
remove должен удалить 
А у тебя он просто ищет сущность и возвращает ее

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/service/AdService.java
> +    public void removeExpiredAds() {
Да, делаем через @Async 
Про нее написано в той же лекции, что и Scheduler  

У тебя есть средство спринга, которое позволяет тебе не управлять потоками вручную - его надо использовать

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/service/AdService.java
> +                        "0"));
через @value получай это значение из конфига

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/service/AdService.java
> +                        .subList(i * BATCH_SIZE, i == batch ? size : (i + 1) * BATCH_SIZE)
Батч создавай через ListUtils.partition

2024-03-10 11:20 UTC, InnMish commented on src/main/java/faang/school/postservice/service/AdService.java
> +                .toList();
Вот это все ты передашь асинку в работу, не нужно руками ничего уже делать - полбзуемся спрингом

2024-12-22 20:12 UTC, closed without merging