Feature-BJS2-6540
CorporationX/post_service pull request #435
Opened 2024-05-17 15:48 UTC by VadimShibanov

2024-05-17 18:19 UTC, RickHammerson commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    CommentDto createComment(@PathVariable long postId, @Valid @RequestBody CommentDto commentDto) {
Лучше ставить Long вместо примитива в PathVariable. Примитив по умолчанию даст число 0

2024-05-17 18:21 UTC, RickHammerson commented on src/main/java/faang/school/postservice/exception/MessageForException.java
> +public enum MessageForException {
Если у тебя задача по комментам, лучше назвать класс эксепшнов специально для комментариев

2024-05-17 22:34 UTC, NadirCianid commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    CommentDto createComment(@PathVariable long postId, @Valid @RequestBody CommentDto commentDto) {
А разве в метод попадет пустой id? 
По идее, если в url не будет id, то и вызов метода не сработает, а будет четырехсотая ошибка.

2024-05-18 16:47 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    CommentDto createComment(@PathVariable long postId, @Valid @RequestBody CommentDto commentDto) {
Вызов метода не сработает, появится 404, если не передать id.

2024-05-19 16:18 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/exception/MessageForException.java
> +public enum MessageForException {
ok

2024-05-20 19:21 UTC, Sabina-Vishnya requested changes

2024-05-20 19:21 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public Post getPostById(long id) {
этот сервис без дто в отличии от остальных, какой смысл тогда в сервисе?

2024-05-20 19:21 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/CommentServiceValidator.java
> +public class CommentServiceValidator {
1. Методы возвращают данные, хотя называются validate или check - это неочевидно. Если ты возвращаешь что-то, так и стоит писать, иначе введёт в заблуждение. 
2. Для рефакторинга здесь, нужно привести в порядок сервисы, возможно тебе и этот класс нее понадобиться

2024-05-20 19:21 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    public void deleteComment(CommentDto commentDto) {
- затащи сюда проверки из валидатора и последовательно посмотри на операции.
у тебя ведь dtoToComment используется, а к чему, если ты все равно потом получаешь энтити из бд уже и удаляешь его?
(проверь еще, вдруг тебе подойдет deleteById, тогда и кода меньше будет, но только проверь как это нам по бизнес-логике и потесть локально)

- этот метод и остальные требуют доработок. Начни с того, чтобы вернуть из валидатора проверки сюда и последовательно проверь операции, увидишь лишние проверки, например, NO_POST_IN_DB.

2024-05-24 17:09 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public Post getPostById(long id) {
ok

2024-05-24 17:10 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/service/CommentServiceValidator.java
> +public class CommentServiceValidator {
ok

2024-05-24 17:10 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    public void deleteComment(CommentDto commentDto) {
ok

2024-05-26 11:38 UTC, Sabina-Vishnya requested changes

2024-05-26 11:38 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/mapper/CommentMapper.java
> +    List<CommentDto> commentsToCommentsDto(List<Comment> comments);
для объектов toDto и toModel, или toEntity (для дто свой, для модели свой)
для списков toDtoList и аналогично для модели
подробнее именно такие методы можно не писать, сам маппер принадлежит комментарием и ее содержит каких-то еще методов

2024-05-26 11:38 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +    private Long id;
id необязательный?
ты его в сервисе проверяешь тогда зачем?

2024-05-26 11:38 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    private void checkPostId(long id) {
@min аннотация есть, посмотри, мб ее можно будет использовать

2024-05-29 11:12 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/mapper/CommentMapper.java
> +    List<CommentDto> commentsToCommentsDto(List<Comment> comments);
ok

2024-05-29 11:39 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    private void checkPostId(long id) {
ok

2024-05-31 09:46 UTC, VadimShibanov commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +    private Long id;
ok

2024-06-01 22:19 UTC, Sabina-Vishnya approved these changes

2024-06-01 22:20 UTC, Sabina-Vishnya commented
вернула, чтобы не висело в ревью, а так аппрув, вливай)

2024-06-02 14:47 UTC, VadimShibanov commented
> вернула, чтобы не висело в ревью, а так аппрув, вливай)
ok

2024-06-02 14:49 UTC, merged