Система постов
CorporationX/post_service pull request #437
Opened 2024-05-17 22:27 UTC by NadirCianid

2024-05-26 09:04 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .filter(post -> post.getAuthorId().equals(userId))
Я думаю фильтр лишний, учитывая что ты уже проверяешь, что пользователь существует - checkUserExistence, после чего фильтруешь findByAuthorId(userId)

2024-05-26 09:04 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .filter(post -> post.getProjectId().equals(projectId))
См. коммент выше

2024-05-26 11:05 UTC, Sabina-Vishnya requested changes

2024-05-26 11:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +        if (postDto.getId() == null) {
почему не аннотацией?

2024-05-26 11:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +    private void checkAuthorPresence(PostDto postDto) {
тот же вопрос

2024-05-26 11:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +public class PostController {
без ResponseEntity всяких почему-то
и @ExceptionHandler - про это уроки есть на платформе

2024-05-26 11:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private final LikeRepository likeRepository;
зачем тут два неиспользуемых репозитория?

2024-05-26 11:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .toList();
в нескольких местах дублирование, избавляемся от этого

2024-05-26 11:05 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void checkPostMatchingWithSystem(PostDto postDto, Post postToBeUpdated) {
что-то можно утащить в аннотации, даже условно сервисного слоя, чтобы разделять так
но не писать только именно Post энтити в параметрах вместе с дто, а брать именно поле (выходит параметр второй можеет быть лонг какой-нибудь, а первых дто)

про аннотации ты знаешь, давай кастомные начнем делать
только проверяй работоспособность и не забудь через постман покидать запросов, чтобы убедиться, что аннотация кастомная и любая другая, работает и отстреливает ошибкой, в случае кривых данных

2024-05-28 22:54 UTC, NadirCianid commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +        if (postDto.getId() == null) {
Потому что это поле не всегда должно быть NonNull. Только при обновлении

2024-05-28 22:55 UTC, NadirCianid commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +    private void checkAuthorPresence(PostDto postDto) {
здесь поля могут быть null, но только один любой из двух

2024-05-29 09:14 UTC, NadirCianid commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void checkPostMatchingWithSystem(PostDto postDto, Post postToBeUpdated) {
я пока не понимаю, как эту логику можно реализовать через аннотации, если аннотации задаются на уровне класса, где у меня не будет доступа к тем данным с которыми надо сверяться

2024-05-29 22:34 UTC, Sabina-Vishnya approved these changes
и тесты

2024-06-01 17:14 UTC, Sabina-Vishnya commented
верну, чтобы не болталось в ревью, а когда вольешь в done уже перекинешь

2024-06-04 21:08 UTC, Sabina-Vishnya requested changes

2024-06-04 21:08 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/post/PostVerifier.java
> +class PostVerifier {
Ну вот коммит сообщает о том, что ты тесты написал, а по факту, еще и рефакторинг сделал)
почему бы не указать это в коммите или отдельной таской тогда не сделать? 

И метод verifyPostMatchingWithSystem подрефачить бы, а то длинный, какие-то проверки обобщить и вынести в приватный метод с параметрами.
Еще можно подумать над тем, чтобы что-то вынести в метод, но в модель уже унести, из каких-то проверок.  Немного в ООП стиле сделать, тогда похудеет класс, но это если получится, тут в целом можно это сделать, а так хотя бы просто метод подрефачить

2024-06-04 21:08 UTC, Sabina-Vishnya commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +
отступ лишний

2024-06-04 21:08 UTC, Sabina-Vishnya commented on src/test/java/faang/school/postservice/util/TestData.java
> +    public List<Post> getDraftsOfUser() {
подобные методы вызывают метод returnPost, который билд содержит, дальше делают билд уже без метода, потому что другие значения нужны объекту - это излишни, тогда в чем смысл метода returnPost?
можно один метод в параметрами сделать и тогда ты будешь вызывать условный createPost(var 1, var 2, var 3) с какими-то параметрами, куда будешь уже нужное значение класть

также всякие LocalDateTime повторяются, это может быть константами и вызываться там, где нужно
под константы можно завести отдельный класс, чтобы разделять, а можно пока в этот пихать, но тогда понамшено будет и со временем сильнее разрастется

2024-06-06 21:59 UTC, Sabina-Vishnya approved these changes
нормас, вливай

2024-06-06 21:59 UTC, Sabina-Vishnya commented on src/test/java/faang/school/postservice/util/TestData.java
> +    public List<Post> getDraftsOfUser() {
награмождать тестовый класс тоже не стоит прям, этот метод и ниже с List.of можно было не делать, а просто List.of и твой returnPostCreatedByUser использовать в тестовом классе, но это так, можно не править

2024-06-06 21:59 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/post/PostVerifier.java
> +class PostVerifier {
эх, название Verifier во всех валидаторах всё таки смущает меня и не очень о валидаторе говорит будто, но это вкусовщина скорее, вливали уже с Verifier, так что норм

2024-06-06 22:11 UTC, merged