Получить всех пользователей, которым понравился пост или комментарий
CorporationX/post_service pull request #439
Opened 2024-05-18 22:23 UTC by NadirCianid

2024-05-24 18:36 UTC, p1maf requested changes

2024-05-24 18:36 UTC, p1maf commented on src/main/java/faang/school/postservice/exception/like/LikeOperatingExceptionMessage.java
> +    }
Лишний код. Можно добавить аннотацию @Getter и @AllArgsConstructor

2024-05-24 18:36 UTC, p1maf commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +        List<Long> usersLikedPost = likes.stream().map(Like::getUserId).distinct().toList();
Кажется, что distinct лишнее ибо пользователь может поставить только 1 лайк

2024-05-25 09:32 UTC, p1maf approved these changes

2024-05-26 11:43 UTC, Sabina-Vishnya requested changes
отлично, правь форматирование еще общее перед пушем
и давай уже добавлять обработчики исключений по красоте

2024-05-26 11:43 UTC, Sabina-Vishnya commented on src/main/resources/application.yaml
> +  port: 8085
а зачем ты этот файлик каждый раз изменяешь и пушишь на всех?)

2024-05-26 11:43 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +    private <T> T getLikedObject(CrudRepository<T, Long> repository, long likedObjectId, LikeOperatingExceptionMessage exceptionMessage) {
давай просто метод немного форматнем, чтобы не растягивался
```
 private <T> T getLikedObject(CrudRepository<T, Long> repository,
                                 long likedObjectId,
                                 LikeOperatingExceptionMessage exceptionMessage) {
        return repository.findById(likedObjectId)
            .orElseThrow(() -> new LikeOperatingException(exceptionMessage.getMessage()));
    }
```

2024-05-28 22:43 UTC, NadirCianid commented on src/main/resources/application.yaml
> +  port: 8085
забываю убирать его

2024-05-29 22:31 UTC, Sabina-Vishnya approved these changes
гуд!
тесты

2024-06-01 17:14 UTC, Sabina-Vishnya commented
тоже самое, верну, чтобы не болталось в ревью)

2024-06-02 14:12 UTC, Sabina-Vishnya approved these changes

2024-06-02 20:42 UTC, merged