BJS2-6977
CorporationX/post_service pull request #467
Opened 2024-05-28 13:47 UTC by DadyaVolodya

2024-06-04 02:07 UTC, pablo023 requested changes
Почитай про то, как работают топики в редисе. Отвяжи свой код и объекты от редиса, и построй логику, используя обычные объекты, и разные топики в редисе.

2024-06-04 02:07 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/redis/AuthorInRedis.java
Нам не нужен отдельный дто для помещения его в редис. Работаем с сущностью User, и его дто, если нужны.

2024-06-04 02:07 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/redis/PostInRedis.java
Аналогично, как и выше. Не нужен отдельный дто для редиса.

2024-06-04 02:07 UTC, pablo023 commented on src/main/java/faang/school/postservice/repository/redis/RedisAuthorRepository.java
Это нам тоже не нужно. Мы не сохраняем в базу ничего в рамках задачи этой.

2024-06-04 02:07 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
Отсюда убираем всё лишнее, и рефакторим в соответствии с комментариями выше. Юзер идет в топик редиса после сохранения поста.

2024-06-04 02:07 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        sendAuthorInCashRedis(postInRedisDto);
Это переделываем. Комменты выше.

2024-06-04 02:07 UTC, pablo023 commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +    private RedisAuthorRepository redisAuthorRepository;
Нам этот репозиторий вообще не нужен. Тут переделать надо.

2024-06-04 02:07 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void sendAuthorInCashRedis(PostInRedisDto postInRedisDto) {
У тебя дифферинциация должна происходить на уровне топиков редиса. То есть, в редисе должны быть разные топики, куда поступают объекты, или что угодно вообще - и кэшируются. Не на уровне сервисного кода должна пролегать эта разница.

2024-06-17 16:10 UTC, DadyaVolodya commented on src/main/java/faang/school/postservice/model/redis/AuthorInRedis.java
@Data
@Builder
@AllArgsConstructor
@RedisHash(value = "PostInRedis")
public class PostInRedis implements Serializable {

    @Id
    private long id;
    private PostDto post;
    @TimeToLive
    private long expiration;
    @Version
    private long version;
}
Тоесть типо такого будет кэшироваться?

2024-06-18 10:03 UTC, DadyaVolodya commented on src/main/java/faang/school/postservice/repository/redis/RedisAuthorRepository.java
Мы сохраняем в редис используя стандартные крудоские методы репозиторием.

2024-06-18 10:04 UTC, DadyaVolodya commented
> Почитай про то, как работают топики в редисе. Отвяжи свой код и объекты от редиса, и построй логику, используя обычные объекты, и разные топики в редисе.

Мы используем редис кжш , а не отправляем эвенты в топики

2024-06-18 10:06 UTC, DadyaVolodya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void sendAuthorInCashRedis(PostInRedisDto postInRedisDto) {
Каким образом в топиках что-то должно кэшироваться ? в топикии просто отпраляется эвент который получает косюмер. А в редис это складывается как в ноэскюль базу

2024-06-18 10:09 UTC, DadyaVolodya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void sendAuthorInCashRedis(PostInRedisDto postInRedisDto) {
k v хранилище, где по ключю стринговому можно достать что угодно, и для отправления в кэш и взаимодействия как раз нужны сервис по кэширонию , и на базе этого мы строим сервис по выдачи ленты новостей

2024-07-01 10:09 UTC, merged