Решение задачи BJS2-6541 Система лайков
CorporationX/post_service pull request #478
Opened 2024-06-03 14:47 UTC by RickHammerson

https://faang-school.atlassian.net/browse/BJS2-6541?atlOrigin=eyJpIjoiNTdmNWNiOWVmMzEyNDVjNTkwNzE1YWNkN2IzYmE5MmIiLCJwIjoiaiJ9

2024-06-08 21:51 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(likeRepository.findById(likeId)).orElseThrow(
Я думаю обертка Optional излишне, т.к. findById уже вернет Optional<Like>

2024-06-08 21:51 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(userClient.getUser(userId)).orElseThrow(
Тут также избыточен Optional, т.к. в getUser ты получишь или userId или null

2024-06-08 21:51 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/validation/like/post/SimultaneousPostLikeValidator.java
> +        return getPostById(dto.getPostId()).getComments()
имхо, но я бы вынес dto.getPostId и getUserId отдельно для читаемости, как ты сделал ниже

2024-06-08 21:51 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/validation/like/post/SimultaneousPostLikeValidator.java
> +            throwAlreadyExistsException(String.format("User with id %d can't like post and comment simultaneously"));
Забыл добавить dto.getUserId() в конце

2024-06-08 21:51 UTC, AlexHor230 commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeAnnotationValidator.java
> +public interface PostLikeAnnotationValidator {
Для чего хочешь его использовать?

2024-06-09 08:58 UTC, RickHammerson commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeAnnotationValidator.java
> +public interface PostLikeAnnotationValidator {
Это спец маркерный интерфейс для отдельных проверок по аннотациям валидаций по типу @NotNull, @Size

У меня одна сущность, но валидирую по разному в двух контроллерах

2024-06-09 08:58 UTC, RickHammerson commented on src/main/java/faang/school/postservice/validation/like/post/SimultaneousPostLikeValidator.java
> +            throwAlreadyExistsException(String.format("User with id %d can't like post and comment simultaneously"));
Да, ты прав

2024-06-09 08:59 UTC, RickHammerson commented on src/main/java/faang/school/postservice/validation/like/post/SimultaneousPostLikeValidator.java
> +        return getPostById(dto.getPostId()).getComments()
Да, можно вынести

2024-06-09 15:43 UTC, RickHammerson commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(likeRepository.findById(likeId)).orElseThrow(
Да, ты прав

2024-06-09 15:44 UTC, RickHammerson commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(userClient.getUser(userId)).orElseThrow(
А тут непонятно, что вернется, так что оставляю

2024-06-11 23:20 UTC, Sabina-Vishnya requested changes
Замечания небольшие оставила, надо поправить.

Комменты мне увидела, можно удалять, отвечая на вопрос - норм сюда и +- стратегия, но честно говоря читается не слишком очевидно (это субъективно), в том числе из-за названий и расположений в пакетах как-будто. 
Можно было бы как-то упростить, пока в голову пришло что-то из серии приблуд спринга, типа аннотации профиль(это гуглить лучше) или какую-нибудь фабрику валидаторов сделать, прописав условия, добавить мб енам, который будет имена для этих реализаций содержать, но это вкусовщина скорее, реализовать можно по-разному. Кажется лишь, что для текущей логики, хватило бы более простого и примитивного решения, а так вполне годно и оооочень круто, что решил это затащить!

Еще, мб интересно будет на досуге, чекни прикольную статью на хабре, как два программиста хлеб пекли называется кажется, если не видел такую, там о теме паттернов (не техничка совсем). Паттерны круто знать, но везде их пихать, грубо говоря, не всегда нужно. Это если что не к тому, что ты тут это сделал зря - вовсе нет, просто к теме про паттерны вспомнилась статья забавная)
А так, можешь оставить, только подумай над названиями, расположением классов, дублированием. Можно еще завтра вкинуть, на созвоне в семь часов, этот код прям и поболтать об этом, мнения разные послушать и тд, ну а так, ты молодчина!

2024-06-11 23:20 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/service/like/CommentLikeService.java
> +    //TODO: Заменить на использование сервиса, когда зальют в мастер
тудухи советую с именем своим писать в коде (ник/имя), чтобы потом всем было понятно, кто это будет делать и тебе легче вспомнить

2024-06-11 23:20 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(likeRepository.findById(likeId)).orElseThrow(
забыл поправить видимо
findById и так опшинал вернет, а ниже использование стринг формата некорректно, символа %d не хватает

2024-06-11 23:20 UTC, Sabina-Vishnya commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(userClient.getUser(userId)).orElseThrow(
учти это при написании тестов просто

2024-06-14 09:19 UTC, RickHammerson commented on src/main/java/faang/school/postservice/validation/like/post/PostLikeValidator.java
> +        Optional.ofNullable(likeRepository.findById(likeId)).orElseThrow(
Да

2024-06-16 21:08 UTC, merged