Система постов
CorporationX/post_service pull request #544
Opened 2024-07-13 18:28 UTC by kpzxpf

2024-07-25 02:24 UTC, pablo023 requested changes

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +    }
Ну это не validateAuthorId, а checkIfAuthorExists

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        return postMapper.toDto(post);
Transactional? В базу же идем.

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postServiceValidator.validatePublishPost(post ,postDto);
(post, postDto) *

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostDto publishPost(PostDto postDto) {
Transactonal?

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +
Забыл обновить, что апдейтед сейчас, LocalDateTime.now()

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
Transactional?

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostDto deletePost(Long postId) {
Transactional?

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +
Лишняя пустая строчка.

2024-07-25 02:24 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .orElseThrow(() -> new EntityNotFoundException("Post not found")));
Какой пост нат фаунд? Айди надо включить в эксепшен. И вообще логировать это надо. Добавь тут логгер везде, где надо. Аннотация Slf4j

2024-07-25 11:27 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +
На updatedAt стоит аннотация @UpdateTimestamp, он обновляется автоматически

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postServiceValidator.validatePublishPost(post ,postDto);
поправил

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +    }
поправил

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +        return postMapper.toDto(post);
добавил

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostDto publishPost(PostDto postDto) {
добавил

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +        postRepository.save(post);
добавил

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostDto deletePost(Long postId) {
добавил

2024-07-25 12:02 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +
поправил

2024-07-25 12:04 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/PostService.java
> +                .orElseThrow(() -> new EntityNotFoundException("Post not found")));
добавил

2024-08-02 23:49 UTC, pablo023 approved these changes

2024-08-02 23:49 UTC, merged