черновик
CorporationX/post_service pull request #550
Opened 2024-07-16 12:52 UTC by cirill98

2024-07-19 18:07 UTC, raukaztaev commented on src/test/java/faang/school/postservice/service/comment/CommentServiceTest.java
> +        Long postId = 1L;
postId лучше вынести в поле класса, а то ты его создаешь в каждом тесте

2024-07-20 07:35 UTC, cancion2able requested changes

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/controller/ApiPath.java
> +    public static final String COMMENT = "/comment";
Будь готов к первому мердж конфликту :) либо я буду готовиться, в зависимости от того, кто первый смерджится

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +@RequestMapping(ApiPath.COMMENT)
Для всех последующих эндпоинтов можно в константы тоже закинуть плейсхолдер с /{id}. Глаголы можно убрать, потому что они уже описаны в HTTP методе.

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/validation/dto/DtoValidation.java
> +public final class DtoValidation {
Здесь нам тоже стоит прийти к одному названию DtoValidationConstraints, чтобы просто разрешить конфликт и объединить все константы вместо того, чтобы плодить два отдельных класса.

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +            throw new NullPointerException("Пользователь с таким ID не найден");
Уместней будет если мы в таких случаях будем выбирать EntityNotFoundException

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        commentRepository.save(comment);
Комменты могут сыпаться с большой скоростью. Полезно будет, если мы предусмотрим здесь обработку ошибок с просьбой повторить попытку написания коммента или указанием на то, что пользователь делает неправильно.

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    public CommentDto addCommentService(Long id, CommentDto commentDto) {
Названия методов вводят в смятение немного. Сервис тут уже не при делах, нам стоит описывать логику, которая происходит с комментами

2024-07-20 07:35 UTC, cancion2able commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            return new NullPointerException("Поста по такому id не существует");
Тоже обрати внимание на тип исключения

2024-07-20 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    public ResponseEntity<CommentDto> updateCommentController(@PathVariable Long id,
не обязательно называть методы "Controller"
так же обрати внимание на поле Long id, это на сколько я понимаю идентификатор поста, такое же поле у тебя есть в CommentDto, postId либо оставь одно из них, либо добавь проверку на их равенство, но лучше как мне кажется иметь один идентификатор в одном месте

2024-07-20 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    public List<CommentDto> getCommentsService(Long id) {
getCommentsForPost

2024-07-20 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        Comment comments = findCommentInPost(id, commentDto);
можно добавить условие, что так мы ищем комент только если в commentDto отсутствует id
так же сюда можно докинуть проверку "на дурака", что если у нас есть commentDto.id и commentDto.postId то соответственно проверять, что комментарий с таким идентификатором есть у поста, указанного в dto

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    private void validateAuthorExists(long authorId) {
так же на будущее, лучше разбивать проверку пользователя и выбрасывание исключения на разные уровни, т.е. отдельно вынести сервис проверки юзера, и уже отдельно сервис отвечающий за генерацию исключений, потому что в дальнейшем может понадобится логика без прерывания операции и тогда придется пилить её через try catch блоки, что не способствует упрощению логики

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            return new NullPointerException("Поста по такому id не существует");
поправь тип исключения, NullPointerException лучше не использовать в такой логике, можно лучше EntityNotFoundException

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +            log.error(ExceptionMessages.POST_NOT_FOUND);
почему проверяется юзер а выбрасывается POST_NOT_FOUND?

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +            log.error(ExceptionMessages.POST_NOT_FOUND);
так же вынеси эту проверку в отдельный сервис, скорее всего её часто будут переиспользовать

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        commentRepository.deleteById(comments.getId());
у тебя же в dto передается идентификатор комментария, зачем искать его через пост и потом еще сравнивать по контенту?

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        Comment comment = commentRepository.findAllByPostId(commentDto.getPostId()).stream()
у тебя в commentDto есть id комментария, можно получать комент по нему и уже его изменять если такой есть, слишком переусложнил логику

2024-07-27 19:23 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            return new NullPointerException("Поста по такому id не существует");
так же обрати внимание на то, что не все серверы могут поддерживать разные кодировки, по этому русского языка стоит в ошибках избегать

2024-07-28 07:44 UTC, cirill98 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            return new NullPointerException("Поста по такому id не существует");
Тесты у меня ожидают именно NullPointerException)) надо логику переписывать, чтобы другое исключение выпало

2024-07-28 07:44 UTC, cirill98 commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        Comment comments = findCommentInPost(id, commentDto);
"можно добавить условие, что так мы ищем комент только если в commentDto отсутствует id" у меня по валидации поле postId в CommentDto не может быть пустым, а id я здесь поставил, потому что по условию он должен быть в пар-ре метода

2024-07-28 07:44 UTC, cirill98 commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        commentRepository.deleteById(comments.getId());
логика была, чтобы провести валидацию. т.е. быть уверенным, что мы удаляем нужный коммент. Потом просто перевожу обратно в ДТО и возвращаю.
Если я без валидации, просто буду удалять по id, то что метод будет возвращать?

2024-07-28 07:44 UTC, cirill98 commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +            log.error(ExceptionMessages.POST_NOT_FOUND);
В какой сервис вынести? создать отдельный класс валидации и туда этот метод положить?

2024-07-28 07:44 UTC, cirill98 commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    private void validateAuthorExists(long authorId) {
Метод нужно вынести в класс валидации в отдельном пакете? И нужен класс для общих исключений?

2024-07-28 08:48 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    private void validateAuthorExists(long authorId) {
да, в отдельный пакет, можно положить рядом с UserServiceClient, можно создать исключение с текстовкой "user {id} not found in user service", которое будет использоваться только при неуспешном получении пользователя

2024-07-28 08:54 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        commentRepository.deleteById(comments.getId());
это уже по сути не твоя проблема, пользователь должен решать какой комментарий он хочет удалить, искать его по посту и проверять по контенту не имеет смысла, очень много лишних действий происходит, идея возвращать dto удаленного комментария в целом хороша, но получать его лучше по идентификатору, упрости логику и будет хорошо

2024-07-28 17:21 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/validation/comment/AuthorExistsValidation.java
> +public class AuthorExistsValidation implements CommentValidator{
почему AuthorExistsValidation имплементирует  CommentValidator?
как то не логично получается
Так же проблема в том, что у валидаторов может быть разная логика валидации бизнес параметров и соответственно разные поля под это бизнес поведение и либо всем придется имплементировать один метод который принимает только объект CommentDto, (что еще одно замечание, в выделенном функционале отсутствует гибкость имплиментации), и выделять под разные сценарии разные валидаторы, либо все забьют на это и будут пилить валидаторы без интерфейса

2024-07-28 17:21 UTC, egorbarzenkov commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    private void validateAuthorExists(long authorId) {
так, ты вынес валидатор в отдельный объект, но все равно оставил валидацию в сервисе, недоделка получается?

2024-07-30 17:13 UTC, egorbarzenkov approved these changes

2024-07-30 17:14 UTC, merged