BJS2-15603 - Система альбомов постов
CorporationX/post_service pull request #572
Opened 2024-07-18 18:31 UTC by ravshanbekn

+ Создал AlbumController, AlbumService
+ Создал Filter'ы
+ Создал ErrorResponse и GlobalExceptionHandler
+ Покрыл весь код unit-тестами

2024-08-03 23:45 UTC, pablo023 requested changes
Почти что хорошо, но чет косяк со смешением ответственности репозиторного слоя и валидации - это прям плохо. Поправь это, раздели ответственности, и можно мержнуть

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +            errorResponse.put(fieldError.getField(), fieldError.getDefaultMessage());
Что это такое вообще? Зачем мы создаем мапу, которая из себя стак трейс представляет?

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/validator/AlbumValidator.java
> +    public Album validateAlbumExistence(long albumId) {
Такое обычно boolean. Типа, если есть - тру, нет - фолс

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/validator/AlbumValidator.java
> +    public void validateAlbumBelongsToAuthor(long authorId, Album album) {
Ну тут тоже булеан обычно

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        Post postToAdd = postValidator.validatePostExistence(postId);
Чет нет. Не должен валидатор пост возвращать по айдишке. Это уже какая-то ответственность репозитория на валидатор легла. Так не делаем. Валидатор - только валидирует.

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        Album album = albumValidator.validateAlbumExistence(albumId);
Опять тут репозиторная логика в валидаторе.

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        return getFilteredAlbumDtoList(allMatchedAlbums, albumFilterDto);
Не надо метод под создание дто из списка делать. Возвращаешь просто список, который тут нашел, и мапаешь прям тут в дто

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        Album album = albumValidator.validateAlbumExistence(albumId);
Опять репозторная логика

2024-08-03 23:45 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    public AlbumDto updateAlbum(long albumId, AlbumDto albumDto) {
Как будто бы тут пропускаешь шаг обновить еще updatedAt поля

2024-08-04 09:24 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +            errorResponse.put(fieldError.getField(), fieldError.getDefaultMessage());
Это handler для неправильной dto-шки которая на  вход поступает. 
Данный handler возвращает map, где ключи-названия неправильных полей, ключи-причина по которым они неправильные

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    public AlbumDto updateAlbum(long albumId, AlbumDto albumDto) {
Исправил

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        Album album = albumValidator.validateAlbumExistence(albumId);
Исправил

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        return getFilteredAlbumDtoList(allMatchedAlbums, albumFilterDto);
Хорошо

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        Album album = albumValidator.validateAlbumExistence(albumId);
Исправил

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        Post postToAdd = postValidator.validatePostExistence(postId);
Исправил

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/validator/AlbumValidator.java
> +    public void validateAlbumBelongsToAuthor(long authorId, Album album) {
Хорошо

2024-08-16 10:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/validator/AlbumValidator.java
> +    public Album validateAlbumExistence(long albumId) {
Хорошо

2024-08-17 19:11 UTC, merged