Feature bjs2 15595
CorporationX/post_service pull request #583
Opened 2024-07-20 21:15 UTC by shade2903

2024-07-21 12:24 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/exception/EntityNotFoundException.java
> +        super(message);
По моему, такой exception есть в 
jakarta.persistence.EntityNotFoundException;

2024-07-21 12:30 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment.setUpdatedAt(LocalDateTime.now());
По моему, hibernate автоматически обновляет

2024-07-21 12:35 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    }
@ ResponseStatus был бы уместен, я считаю

2024-07-21 12:37 UTC, ravshanbekn reviewed
Как по мне, написано хорошо

2024-07-22 09:11 UTC, shade2903 commented on src/main/java/faang/school/postservice/exception/EntityNotFoundException.java
> +        super(message);
Ок.  Согласен, если такой есть лучше его переиспользовать. Заменил на jakarta.persistence.EntityNotFoundException;

2024-07-22 09:12 UTC, shade2903 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment.setUpdatedAt(LocalDateTime.now());
Согласен. Просто хотел перестраховатся. Сейчас увидел аннотацию на сущности, да это лишняя операция. Убрал.

2024-07-22 09:12 UTC, shade2903 commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    }
Ок. добавил

2024-07-25 02:15 UTC, pablo023 requested changes
Надо поправить чутка

2024-07-25 02:15 UTC, pablo023 commented on src/main/java/faang/school/postservice/mapper/CommentMapper.java
> +    List<CommentDto> entitiesToDtos(List<Comment> projectList);
А тут он подхватит логику сеттинга айдишек?

2024-07-25 02:15 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentValidator.existUser(commentDto.getId());
Ты тут вытаскиваешь айдишник не пользователя, а из дтошки тащишь просто айди

2024-07-25 02:15 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
Надо бы тут пост тащить из базы, ему в список комментов добавлять этот коммент, и сохранять в базу.

2024-07-25 02:15 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
return comments.stream()
               .sorted(Comparator.comparing(Comment::getCreatedAt).reversed())
               .map(commentMapper::entityToDto)
               .collect(Collectors.toList());

2024-07-29 20:13 UTC, shade2903 reviewed
подправил баги.

2024-07-29 20:13 UTC, shade2903 commented on src/main/java/faang/school/postservice/mapper/CommentMapper.java
> +    List<CommentDto> entitiesToDtos(List<Comment> projectList);
Добавил @Mapping(source = "post.id", target = "postId")

2024-07-29 20:13 UTC, shade2903 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentValidator.existUser(commentDto.getId());
Поправил.

2024-07-29 20:13 UTC, shade2903 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
Поправил, думал может так быстрее будет.

2024-07-29 20:13 UTC, shade2903 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
Исправил.

2024-08-03 01:20 UTC, pablo023 approved these changes

2024-08-03 01:20 UTC, merged