Feature bc 4235.  Comment system
CorporationX/post_service pull request #59
Opened 2023-08-01 16:25 UTC by ipavelbel

Задачу сначала разбил на подзадачи, в итоге удалил подзадачи и делал всё задание в одной ветке feature. 
ссылка на задачу в Jira: https://faang-school.atlassian.net/browse/BC-4235

2023-08-02 20:38 UTC, tarrasoff approved these changes
Небольшие корректировки, поэтому апрув)

2023-08-06 08:00 UTC, InnMish requested changes

2023-08-12 06:57 UTC, InnMish requested changes

2023-08-15 08:46 UTC, InnMish approved these changes

2023-08-15 08:57 UTC, merged