BJS2-15597
CorporationX/post_service pull request #629
Opened 2024-07-26 15:50 UTC by YPG0

2024-08-03 23:27 UTC, pablo023 requested changes

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        validator.validAddLikeToPost(likeDto.getPostId());
Ты просто валидируешь айдишку. Это вообще делается аннотацией Positive над полем id в дто, но раз уж так захотел сделать - validateLikeDtoId этот метод должен называться.

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        LikeDto createLike = likeService.addLikeToPost(likeDto);
Не createLike, а likePost

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(createLike);
Аннотация RestController сама маппит твои ответы в ResponseEntity, нет смысла это ещё так указывать. Просто вызываешь из сервиса метод, который дто должен вернуть тебе.

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        return ResponseEntity.ok("Like successfully delete from post");
Аннотацией ResponseStatus можешь это делать, будет проще и чище

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        validator.validAddLikeToComment(likeDto.getCommentId());
validateCommentId..

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/mapper/LikeMapper.java
> +    Like toLike(LikeDto likeDto);
toEntity

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    private final LikeServiceValidator validator;
Какой validator?

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/validator/LikeServiceValidator.java
> +        });
This what? 

Has already been liked*

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.save(like);
Transactional?

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.deleteByPostIdAndUserId(postId, userId);
Transactional?

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.save(like);
Transactional?

2024-08-03 23:27 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.deleteByCommentIdAndUserId(commentId, userId);
Transactional?

2024-08-05 15:16 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.deleteByCommentIdAndUserId(commentId, userId);
+

2024-08-05 15:16 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.save(like);
+

2024-08-05 15:16 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.deleteByPostIdAndUserId(postId, userId);
+

2024-08-05 15:16 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeRepository.save(like);
Добавил. Я тогда еще не знал об этом. Потом только увидел у кого-то

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/validator/LikeServiceValidator.java
> +        });
Исправил

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    private final LikeServiceValidator validator;
понял - likeServiceValidator

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/mapper/LikeMapper.java
> +    Like toLike(LikeDto likeDto);
+

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        validator.validAddLikeToComment(likeDto.getCommentId());
Перенес валидацию в дто

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        return ResponseEntity.ok("Like successfully delete from post");
Поправил

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body(createLike);
Переделал

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        LikeDto createLike = likeService.addLikeToPost(likeDto);
+

2024-08-05 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +        validator.validAddLikeToPost(likeDto.getPostId());
Переделал на валидацию в дто

2024-08-07 07:29 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Like was not found using the passed identifier"));
точно такой же код у тебя ниже есть 
вынеси в отдельный метод и переиспользуй

2024-08-07 07:29 UTC, InnMish commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    }
Я бы тут не писала этот метод и не зашивала вообще обработку FeignException 
Если пользователь не будет найден, у тебя userService Эту ошибку бросит - что пользователь не найдет 
а вот feign ошибка тебе прилетит, если именно в фейне что-то случится
но она и так прилетит, но ошибка эта будет совсем не про пользователя. Это будет что-то такое, о чем пользователю знать не надо, а надо разбираться разработчикам 
Поэтому в целом норм практика прямо в основном методе дернуть строчку userServiceClient.getUser(userId); и получить юзера

2024-08-07 16:58 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Like was not found using the passed identifier"));
Он похож но другой в этом поиск поста и принимает id поста, а там (70,71 строчка) идет поиск комментария и принимает id комментария. Придется в метод передавать какой метод дергать, id поста/коммента, id юзера 
Хуже не станет?

2024-08-07 17:03 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    }
Понял, поправил

2024-08-08 01:52 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/LikeService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Like was not found using the passed identifier"));
Да, станет, не нужно эту проверку выполнять. Но вообще, сделать здесь кое-что надо, а именно - оба эти метода в отдельный класс валидатор, и там проверять это

2024-08-08 01:53 UTC, pablo023 commented
У тебя здесь CI сломался, и надо вынести проверки из сервиса в валидатор. Сделай, пожалуйста, и посмотри почему CI падает.

2024-08-08 22:05 UTC, merged