Система хэштегов к постам
CorporationX/post_service pull request #640
Opened 2024-07-28 20:37 UTC by kpzxpf

2024-08-15 22:53 UTC, pablo023 requested changes
Мне кажется, ты тут можешь довести до ума

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        log.info("Project ID " + projectId + " validated successfully: " + projectId);
Лучше использовать String.format(), чтобы не выполнять конткатенацию строк. Красивее выглядит, если там не 100500 строк складывать надо

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/post/PostResponse.java
В твоем случае, это - дто

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/post/Post.java
Миграцию надо написать для изменения таблицы.

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/hashtag/HashtagResponse.java
Тоже дто ведь. В model храним сущности, которые являются проекцией таблиц в бд. А это - это просто класс для того, чтобы принимать и отдавать. Это и есть дто - data transfer object.

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/hashtag/HashtagRequest.java
Аналогично, дто

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/hashtag/HashtagRequest.java
И навалил опять тут ломбока слишком много, убери лишнее

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/hashtag/Hashtag.java
Миграцию написать забыл под эту сущность.

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/model/hashtag/Hashtag.java
> +@AllArgsConstructor
Тоже лишнее

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
Надо создать кастомные эксепшены здесь, а не перебрасывать runtime просто

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
> +    }
У тебя этот метод так написан, что ты подразумеваешь, что он не пустой. А если он в итоге окажется пустой, то будет NPA. Нужно обработать это

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
> +                .index("post")
Магическая строка. Вынеси в константу, или энам.

2024-08-15 22:53 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
> +                .build();
Сюда было бы неплохо добавить пагинацию, а то как найдешь миллион постов, эххх

2024-08-27 22:11 UTC, kpzxpf commented on src/main/java/faang/school/postservice/validator/PostServiceValidator.java
> +        log.info("Project ID " + projectId + " validated successfully: " + projectId);
ок

2024-08-27 22:11 UTC, kpzxpf commented on src/main/java/faang/school/postservice/model/post/PostResponse.java
понял

2024-08-27 22:11 UTC, kpzxpf commented on src/main/java/faang/school/postservice/model/post/Post.java
хорошо

2024-08-27 22:11 UTC, kpzxpf commented on src/main/java/faang/school/postservice/model/hashtag/HashtagResponse.java
понял

2024-08-27 22:12 UTC, kpzxpf commented on src/main/java/faang/school/postservice/model/hashtag/Hashtag.java
> +@AllArgsConstructor
ок

2024-08-27 22:12 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
понял

2024-08-27 22:14 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
> +    }
ок

2024-08-27 22:14 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
> +                .build();
хорошо

2024-08-27 22:14 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/elasticsearchService/ElasticsearchService.java
> +                .index("post")
ок

2024-08-28 03:35 UTC, merged