Добавление картинок к посту
CorporationX/post_service pull request #646
Opened 2024-07-29 19:27 UTC by kpzxpf

2024-08-08 22:39 UTC, pablo023 requested changes
Тут многое не по солид, это надо исправлять. Когда ты всё исправишь и протестишь - поставь со мной звонок, и покажи мне, как это работает - будем смотреть что идёт в с3, что идет в базу, и тд.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/ResourceController.java
> +    public ResponseEntity<String> addImages(
У нас тут MultipartFile, что говорит о том, что грузим один файл к посту. Было бы лучше назвать uploadImage / addImage

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/ResourceController.java
> +    public ResponseEntity<String> addImage(
Названия методов перепутал в общем. Кстати, тебе не нужно оборачивать в ResponseEntity, если ты используешь аннотацию RestController, она объекы в JSON сама маппит. И ещё - не стрингу надо возвращать, а всё таки какое-то дто.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/CustomMultipartFile.java
> +    }
А зачем это? Это ведь RequiredArgsConstructor просто.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +    private int MaxSizeSquare;
Это с маленькой буквы должно начинаться.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +                    (width > maxWidthHorizontal && height > maxHeightHorizontal && width > height)) {
Дублируешь проверку условий. Вот так проще:

if (width > maxWidthHorizontal) {
    if (height <= maxHeightHorizontal || (height > maxHeightHorizontal && width > height)) {
.................
    }

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +            } else {
Окей, используем библиотеку thumbnailator, она крутая, потому что сама по себе заботится о пропорциях изображения. Это значит, что если мы укажем ей новый размер только по одной оси — ширине или высоте — она автоматом подгонит другую ось так, чтобы картинка не исказилась. Норм тема, не придется самим математику разводить. Но в нашем коде есть момент, который стоит уточнить. Смотри, когда мы используем Thumbnails.of(), мы передаем туда maxWidthHorizontal и maxHeightHorizontal, типа максимально возможные ширина и высота для горизонтальных картинок. Библиотека по дефолту сохраняет пропорции, это значит, что она сама решит, до каких размеров сжать картинку, чтобы она влезла в наши ограничения и при этом не стала выглядеть как салат из пикселей. Только вот проблема: код не ясно показывает, что мы всегда хотим сохранять пропорции, особенно когда картинка превышает и по ширине, и по высоте максимально допустимые значения. Мне тяжело словами объяснить, что я хочу тут увидеть, посмотри как я это вижу кодом

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +            } else {
public MultipartFile resizeImage(MultipartFile file) throws IOException {
        BufferedImage originalImage = ImageIO.read(file.getInputStream());
        if (originalImage == null) {
            throw new IOException("Unsupported image format");
        }

        if (needsResizing(originalImage)) {
            ByteArrayOutputStream resizedImageOutputStream = new ByteArrayOutputStream();
            BufferedImage resizedImage = applyResize(originalImage);
            ImageIO.write(resizedImage, "jpg", resizedImageOutputStream);
            byte[] resizedImageBytes = resizedImageOutputStream.toByteArray();
            return createMultipartFile(file, resizedImageBytes);
        }
        return file;
    }

    private boolean needsResizing(BufferedImage image) {
        return image.getWidth() > maxWidthHorizontal || image.getHeight() > maxHeightHorizontal ||
               image.getWidth() > maxSizeSquare || image.getHeight() > maxSizeSquare;
    }

    private BufferedImage applyResize(BufferedImage originalImage) {
        int width = originalImage.getWidth();
        int height = originalImage.getHeight();
        int newWidth, newHeight;

        double aspectRatio = (double) width / height;
        if (aspectRatio > 1) { 
            newWidth = maxWidthHorizontal;
            newHeight = (int) (maxWidthHorizontal / aspectRatio);
        } else {
            newHeight = maxHeightHorizontal;
            newWidth = (int) (maxHeightHorizontal * aspectRatio);
        }

        if (newWidth > maxSizeSquare || newHeight > maxSizeSquare) {
            newWidth = newHeight = maxSizeSquare;
        }

        return Thumbnails.of(originalImage)
                         .size(newWidth, newHeight)
                         .asBufferedImage();
    }

    private MultipartFile createMultipartFile(MultipartFile originalFile, byte[] resizedImage) {
        return new CustomMultipartFile(
                originalFile.getName(),
                originalFile.getOriginalFilename(),
                originalFile.getContentType(),
                resizedImage
        );
    }
}

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                    return new EntityNotFoundException("Post " + postId + " not found");
Можно добавить свое исключение. Чтобы не выполнять конкатенацию строк через плюсик, можно использовать String.format(...)

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                    return new EntityNotFoundException("Post " + postId + " not found");
В целом, это лучше вынести в getPost()

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        });
Вот это лучше в отдельный класс валидатор, и пусть валидирует список изображений, чтобы тут этой простыни не было.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        return ResponseEntity.ok("Resources added successfully");
Не нужно это возвращать. Разработчику http 200 будет достаточно. Лучше построй тут дто какой-нибудь, и его верни

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                });
Дублируешь этот код. Вынеси в метод приватный getPost

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        resourceServiceValidator.checkingThereEnoughSpaceInPostToImage(post.getResources().size(), 1);
Это в отдельный класс валидатор, и не используй магических чисел.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        return ResponseEntity.ok("Resource added successfully");
Выше комментил это, не нужно.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                });
Уже комментил

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    public InputStream downloadResource(Long resourceId) {
Как-то ну так себе инпут стрим возвращать. Преобразуй к файлу, и возвращай файл.

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/s3/S3ServiceImpl.java
> +        objectMetadata.setContentType(file.getContentType());
В приватный метод

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/s3/S3ServiceImpl.java
> +            objectMetadata.setContentType(file.getContentType());
В приватный метод

2024-08-08 22:39 UTC, pablo023 commented on src/main/java/faang/school/postservice/validator/ResourceServiceValidator.java
> +    private final static Set<String> SUPPORTED_IMAGE_TYPES = Set.of("image/png", "image/jpeg", "image/jpg");
В проперти

2024-08-09 11:45 UTC, kpzxpf commented on src/main/java/faang/school/postservice/controller/ResourceController.java
> +    public ResponseEntity<String> addImage(
ок

2024-08-09 11:46 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/CustomMultipartFile.java
> +    }
поправил

2024-08-09 11:47 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +    private int MaxSizeSquare;
исправил

2024-08-09 11:48 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +            } else {
понял

2024-08-09 11:48 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                    return new EntityNotFoundException("Post " + postId + " not found");
вынес

2024-08-09 11:49 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        });
ок

2024-08-09 11:49 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        return ResponseEntity.ok("Resources added successfully");
хорошо

2024-08-09 11:49 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                });
ок

2024-08-09 11:55 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        resourceServiceValidator.checkingThereEnoughSpaceInPostToImage(post.getResources().size(), 1);
хорошо

2024-08-09 11:55 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        return ResponseEntity.ok("Resource added successfully");
ок

2024-08-09 11:56 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    public InputStream downloadResource(Long resourceId) {
понял

2024-08-09 11:56 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/s3/S3ServiceImpl.java
> +        objectMetadata.setContentType(file.getContentType());
хорошо

2024-08-09 11:56 UTC, kpzxpf commented on src/main/java/faang/school/postservice/service/s3/S3ServiceImpl.java
> +            objectMetadata.setContentType(file.getContentType());
хорошо

2024-08-09 11:56 UTC, kpzxpf commented on src/main/java/faang/school/postservice/validator/ResourceServiceValidator.java
> +    private final static Set<String> SUPPORTED_IMAGE_TYPES = Set.of("image/png", "image/jpeg", "image/jpg");
понял

2024-08-10 02:34 UTC, pablo023 commented
34 коммента, но насколько же оно лучше выглядит)

2024-08-10 16:34 UTC, merged

2024-08-10 16:34 UTC, pablo023 commented
Молодец)