BJS2-15644
CorporationX/post_service pull request #659
Opened 2024-08-02 13:18 UTC by YPG0

2024-08-08 02:05 UTC, pablo023 requested changes
Нет реализации pub/sub. Меняя сущность, всегда надо писать liquibase миграцию - sql файлик, который обновит сущность в базе, добавит туда поле новое.

2024-08-09 10:01 UTC, YPG0 commented
реализацию pub/sub взял из 15642 они через 1 и тот же топик работают. liquibase миграцию добавил

2024-08-10 02:37 UTC, pablo023 requested changes

2024-08-10 02:37 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/ban/BanService.java
Ну вот это опять тут бан сервис. Это юзер сервис должно быть

2024-08-10 02:37 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/ban/AuthorBanner.java
Вот это тоже мне непонятно. Это тоже юзер сервис

2024-08-12 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/ban/BanService.java
У бана за комментарий и бана за пост одинаковые проверки кого банить и сборка BanEventa. Подумал в сервисах работать с репозиторием для сборки map, а потом передать уже в отдельный метод который будет для них одинаковый. Разобрать обратно каждому в свой сервис?

2024-08-12 15:17 UTC, YPG0 commented on src/main/java/faang/school/postservice/service/ban/AuthorBanner.java
По заданию требовалось "1. В post_service создать бин AuthorBanner. Добавить в него метод, который будет запускаться каждый день по cron выражению из конфигурации application.yaml.".

2024-08-12 22:12 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/ban/AuthorBanner.java
Хорошо, тут я понял.

2024-08-12 22:14 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/ban/BanService.java
Это прямо сейчас они одинаковые, а в дальнейшем они могут быть разными. Прямо сейчас комментарий можно забанить только за контент, а в посте могут быть ресурсы - видео, аудио, картинки, также могут быть альбомы, у которых могут быть неуместные названия. Поэтому - да, лучше тут разнести эту логику отдельно.

2024-08-15 22:31 UTC, merged