still not work
CorporationX/post_service pull request #676
Opened 2024-08-08 07:08 UTC by GevorgSogomonian

2024-09-06 02:00 UTC, pablo023 requested changes
И давай это в юзер сервис, и там ещё конфликты не забудь подфиксить

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        if (file.getSize() > 5 * 1024 * 1024) {
Вот это вот - в application.yaml

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        ByteArrayOutputStream largeOutputStream = resizeService.squeezeImageOrLeave(originalImage, 1080);
1080 - также в конфиги, и в этот класс через вэлью подтянуть надо

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +            throw new RuntimeException(e);
Это что? Обработать надо.

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +    public ByteArrayOutputStream squeezeImageOrLeave(BufferedImage originalImage, int maxSize) {
maxSize должен быть не тут, а в конфигах

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/avatar/AvatarController.java
> +    public ResponseEntity<byte[]> downloadAvatar(@RequestBody String key) {
Аннотация RestController, заворачивает всё сама в ResponseEntity.

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        ByteArrayOutputStream smallOutputStream = resizeService.squeezeImageOrLeave(originalImage, 170);
170 - в конфиги

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +            throw new IllegalArgumentException("File size exceeds 5 MB");
А всю валидацию - в отдельный метод

    Value("...")
    private static final long MAX_FILE_SIZE;

    public void validateFile(MultipartFile file) {
        if (file.getSize() > MAX_FILE_SIZE) {
            throw new IllegalArgumentException("File size exceeds 5 MB");
        }
    }

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +
Куда-то в отдельный метод, который будет заниматься процессингом изображения.

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +    public void saveAvatar(long userId, MultipartFile file) {
Тут совсем не по солид написал

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +    public void saveAvatar(long userId, MultipartFile file) {
Я думаю тут надо Transactional, тк старый аватар может недоудалиться, и если упадет процесс - будет какая-то каша потом.

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        }
В отдельный метод. Перемешиваешь тут ответственности.

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        }
Вот это вот проще сделать через InputStreamResource. Тут вообще метод в 5 строк пишется этот весь, надо переделать. Чем больше кода - тем хуже код, его тяжелее читать, он дольше компилится, в нем больше ошибок.

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +        }
try {
          Thumbnails.Builder<BufferedImage> thumbnailBuilder = Thumbnails.of(originalImage)
                  .outputFormat("png")
                  .keepAspectRatio(true);
      
          if (originalWidth > maxSize || originalHeight > maxSize) {
              thumbnailBuilder.size(maxSize, maxSize);
          } else {
              thumbnailBuilder.scale(1);
          }
      
          thumbnailBuilder.toOutputStream(resizedImage);
      } catch (IOException e) {
          throw new RuntimeException(e);
      }

Так же проще?

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/s3/MinioS3Client.java
> +            ByteBuffer byteBuffer = ByteBuffer.wrap(file.getBytes());
Врапать не обязательно, S3 умеет напрямую работать с потоком файла ,без конвертации в байт буфер

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/s3/MinioS3Client.java
> +            ByteBuffer byteBuffer = ByteBuffer.wrap(file.getBytes());
Плюс ты его и не закрыл ещё

2024-09-06 02:00 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/s3/MinioS3Client.java
> +            ByteBuffer byteBuffer = ByteBuffer.wrap(file.getBytes());
public Resource uploadFileToS3(MultipartFile file, String folder) {
          long fileSize = file.getSize();
          String key = generateFileKey(folder, file.getOriginalFilename());
      
          try (InputStream inputStream = file.getInputStream()) {
              s3Client.putObject(PutObjectRequest.builder()
                                  .bucket(bucketName)
                                  .key(key)
                                  .contentType(file.getContentType())
                                  .build(),
                      RequestBody.fromInputStream(inputStream, fileSize));
          } catch (S3Exception | IOException e) {
              log.error("Failed to upload file: {}", e.getMessage());
              throw new FileUploadException("Failed to upload file to S3", e);  // You can define your custom exception
          }
      
          return Resource.builder()
                  .key(key)
                  .type(file.getContentType())
                  .name(file.getOriginalFilename())
                  .size(fileSize)
                  .build();
      }
      
      private String generateFileKey(String folder, String originalFilename) {
          return String.format("%s/%d%s", folder, System.currentTimeMillis(), originalFilename);
      }

2024-09-11 06:51 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +    public void saveAvatar(long userId, MultipartFile file) {
Исправил

2024-09-11 06:59 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        if (file.getSize() > 5 * 1024 * 1024) {
Исправил

2024-09-11 07:03 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +            throw new RuntimeException(e);
Исправил

2024-09-11 07:08 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        ByteArrayOutputStream smallOutputStream = resizeService.squeezeImageOrLeave(originalImage, 170);
Исправил

2024-09-11 07:09 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        ByteArrayOutputStream largeOutputStream = resizeService.squeezeImageOrLeave(originalImage, 1080);
Исправил

2024-09-11 07:16 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +            throw new IllegalArgumentException("File size exceeds 5 MB");
Исправил

2024-09-11 07:28 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +
Исправил

2024-09-11 07:35 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        }
Исправил

2024-09-11 08:08 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/controller/avatar/AvatarController.java
> +    public ResponseEntity<byte[]> downloadAvatar(@RequestBody String key) {
Исправил

2024-09-11 08:09 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/AvatarService.java
> +        }
Исправил

2024-09-11 08:12 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +    public ByteArrayOutputStream squeezeImageOrLeave(BufferedImage originalImage, int maxSize) {
Теперь maxSize в сервисе подтягиваем через @Value

2024-09-11 08:16 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/resource/ResizeService.java
> +        }
Согласен, исправил

2024-09-11 08:31 UTC, GevorgSogomonian commented on src/main/java/faang/school/postservice/service/s3/MinioS3Client.java
> +            ByteBuffer byteBuffer = ByteBuffer.wrap(file.getBytes());
Исправил

2024-09-12 05:03 UTC, merged