BJS2-15660
CorporationX/post_service pull request #692
Opened 2024-08-15 07:09 UTC by YPG0

Аналитика лайков для постов

2024-08-16 20:58 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/config/redis/like/LikePostPublisher.java
> +    @Autowired
А почему их через @ Autowired, а не через конструктор?

2024-08-16 21:04 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
>      }
Не лучше ли делать это в service?

2024-08-16 21:05 UTC, ravshanbekn commented on src/main/java/faang/school/postservice/mapper/LikeEventMapper.java
> +    }
Нельзя тут через MapStruct перекладывать?

2024-08-16 21:06 UTC, ravshanbekn reviewed
Выглядит хорошо

2024-08-19 17:22 UTC, YPG0 commented on src/main/java/faang/school/postservice/mapper/LikeEventMapper.java
> +    }
Вообще можно но тут мало полей и не все автоматически сделаются. Мне было проще руками напрямую сделать

2024-08-19 17:23 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
>      }
Делаю это отдельно что бы логика сбора аналитики не мешала ставить сами лайки. А не в отдельном методе сервиса потому что там подготовка eventa к отправки и сама отправка его, раз класс Publisher за это отвечает то там и делал

2024-08-19 17:23 UTC, YPG0 commented on src/main/java/faang/school/postservice/config/redis/like/LikePostPublisher.java
> +    @Autowired
Убрал Autowired конкретной логики в нем не было, настроение было его использовать

2024-08-25 01:12 UTC, pablo023 requested changes

2024-08-25 01:12 UTC, pablo023 commented on src/main/java/faang/school/postservice/config/redis/like/LikePostPublisher.java
> +public class LikePostPublisher implements MessagePublisher {
У нас может быть много публикаторов разных. На мой взгляд, нам бы подошло тут использование абстрактного класса, в котором собрана вся общая логика, а наследующие классы будут отличаться только бином топика, по сути. Сильно можем сократить одинаковый код на будущее.

2024-08-25 01:12 UTC, pablo023 commented on src/main/java/faang/school/postservice/config/redis/like/LikePostRedisConfig.java
В данном случае, ты завязался на лайках. Ты создаешь конфигурацию редис публикатора эксклюзивно для лайков. Лучше сделать одну для всех, и просто добавлять сюда бины для топиков. Иначе, нам придётся создавать вот такой публикатор, фабрику коннекшенов, и темплейт для каждого публикатора, который мы напишем. А для чего нам столько? У нас вполне может один конфиг это всё делать, и нам больше одного темплейта бина не нужно.

2024-08-25 01:12 UTC, pablo023 commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
>      }
Я согласен, что этому не место здесь. Как минимум - у тебя в сервисной логике может произойти что-то - вылететь эксепшен, или сам сервис может сдохнуть. А эвент у тебя создастся и отправится. Так не подойдет, к сожалению. Эвент должен гарантированно следовать за выполнением логики, проще всего было бы перенести отправку в сервис.

2024-08-25 01:12 UTC, pablo023 commented on src/main/java/faang/school/postservice/mapper/LikeEventMapper.java
> +    }
Мапстракт умеет умно апдейтить, Паша как-то скидывал, прочитай вот тут: https://mapstruct.org/documentation/stable/reference/html/#updating-bean-instances

2024-08-25 01:30 UTC, pablo023 commented on src/main/java/faang/school/postservice/config/redis/like/LikePostPublisher.java
> +    @Autowired
Не используй его) Даже в доке по спрингу есть об этом - это плохой способ внедрения зависимостей. https://dev.to/felixcoutinho/you-should-stop-using-spring-autowired-p8i тут вот тоже можно почитать

2024-08-29 17:23 UTC, YPG0 commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
>      }
Перенес вызов в сервис

2024-08-29 17:25 UTC, YPG0 commented on src/main/java/faang/school/postservice/mapper/LikeEventMapper.java
> +    }
Сделал мапстрактом

2024-08-29 17:27 UTC, YPG0 commented on src/main/java/faang/school/postservice/config/redis/like/LikePostRedisConfig.java
Поправил

2024-08-29 18:06 UTC, YPG0 commented on src/main/java/faang/school/postservice/config/redis/like/LikePostPublisher.java
> +public class LikePostPublisher implements MessagePublisher {
Я пытался но немного не хватало доработки. Сейчас через абстрактный сделано

2024-08-30 22:47 UTC, merged