All love achievement
CorporationX/post_service pull request #713
Opened 2024-08-25 12:41 UTC by GevorgSogomonian

in progress

2024-09-06 02:33 UTC, pablo023 requested changes
Почисти, исправь конфликты, и вмерж

2024-09-06 02:33 UTC, pablo023 commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +//    }
Вот это убери наверное, раз не нужно оно?

2024-09-11 13:57 UTC, GevorgSogomonian commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +//    }
Исправил

2024-09-12 05:07 UTC, pablo023 commented
Конфликты не исправил. Исправь, и вмерж сам, и задачу кинь в done.

2024-09-12 05:58 UTC, merged