Feature bjs2 16070 publish like post event
CorporationX/post_service pull request #733
Opened 2024-09-10 03:32 UTC by grisatkac

https://faang-school.atlassian.net/browse/BJS2-16070

2024-09-12 05:11 UTC, pablo023 requested changes

2024-09-12 05:11 UTC, pablo023 commented on src/main/java/faang/school/postservice/service/CommentService.java
> +                new NotFoundEntityException("Not found comment by id: " + likeDto.getCommentId()));
Такие обработки мы абсолютно всегда пишем через класс-валидатор, и пишем обработчик исключений. Никогда это не пишем вот так. И в жизни никогда так не пиши

2024-09-14 21:50 UTC, grisatkac commented on src/main/java/faang/school/postservice/service/CommentService.java
> +                new NotFoundEntityException("Not found comment by id: " + likeDto.getCommentId()));
> Такие обработки мы абсолютно всегда пишем через класс-валидатор, и пишем обработчик исключений. Никогда это не пишем вот так. И в жизни никогда так не пиши

это я решал какие-то конлфикты, когда вмерживал изменения в свою ветку
видимо из-за этого показало, что код мой, но как я понял он никиты, потому этот метод используется в местах, где никита писал

2024-09-14 21:53 UTC, grisatkac commented on src/main/java/faang/school/postservice/service/CommentService.java
> +                new NotFoundEntityException("Not found comment by id: " + likeDto.getCommentId()));
> Такие обработки мы абсолютно всегда пишем через класс-валидатор, и пишем обработчик исключений. Никогда это не пишем вот так. И в жизни никогда так не пиши

сейчас вынесу валидацию

2024-09-15 01:43 UTC, merged