BJS2-27034 Система постов
CorporationX/post_service pull request #742
Opened 2024-09-17 14:10 UTC by cemeh666

2024-09-17 18:17 UTC, amilosh commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    private final PostMapper mapper;
мне больше нравится когда полное название 
PostMapper postMapper;

поскольку это не влияет на выполнение кода, а чисто code style
то можно спросить у Димы, как он скажет

2024-09-17 18:20 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +public class PostDto {
Если то dto используется только чтобы вернуть данные на фронт
то я использовал
ResponsePostDto или PostResponseDto

чтобы с первого взгляда было видно, для чего дто-ха используется и не искать, где она в коде для чего ипользуется

2024-09-17 18:21 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/CreatePostRequestDto.java
> +public class CreatePostRequestDto {
Я просто CreatePostDto или PostCreateDto использовал

2024-09-17 18:22 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/CreatePostRequestDto.java
> +    @NotBlank(message = "Message can't be blank or empty")
Post content can't be blank or empty
или
Cotent of the post can't be blank or empty

2024-09-17 18:24 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/CreatePostRequestDto.java
> +    @Length(max = 4096, message = "Maximum number of characters 4096 chairs")
Maximum number of characters is 4096 chars/symbols

2024-09-17 18:27 UTC, amilosh commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto createPost(@Valid @RequestBody CreatePostRequestDto requestDto) {
CreatePostRequestDto requestDto
я предпочитаю, когда название параметра - конкреное, что оно делает
то есть
CreatePostRequestDto createPostRquestDto

это хоть и длиннее, но как-то более понятнее
хотя может это чисто дело привычки

2024-09-17 18:29 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +    private Integer projectId;
У сущности Post это Long поля

2024-09-17 18:30 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/CreatePostRequestDto.java
> +    private Integer projectId;
У сущности Post это Long поля

2024-09-17 18:31 UTC, amilosh commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        Post result = postService.create(post);
Я использовал
createdPost

2024-09-17 18:38 UTC, amilosh commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
extends ResponseEntityExceptionHandler

можешь проверить без этого экстенда
вроде и без него работает, но я не уверен

2024-09-17 18:40 UTC, amilosh commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +            throw new ValidationException("specify either authorId or projectId to create a post");
С большой буквы
Для единообразия

2024-09-17 18:45 UTC, amilosh commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        throw new ValidationException("User id=%s not exist".formatted(userId));
Здесь
https://github.com/CorporationX/user_service/pull/1401
можешь посмотреть класс
ApplicationException

если понравится такой подход - то можешь заиспользовать

2024-09-17 18:46 UTC, amilosh commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        } catch (RuntimeException ignore) {
Exeption ignore
а о там может проверяемая SQLExeption упасть
и тогда RuntimeException не споймает

2024-09-17 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return post;
Ещё так можно
return postRepository.save(post);
метод save возвращает сохраненную сущность

но это на вкус и цвет

2024-09-17 18:56 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return postRepository.findByIdAndNotDeleted(id).orElseThrow(PostNotFoundException::new);
PostNotFoundException
желательно в exeption message передать id поста, чтобы потом можно было отследить

2024-09-17 18:57 UTC, amilosh commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +
тут и в нижнем методе залогируй exception.getMessage()

2024-09-17 18:59 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            throw new PostPublishedException();
тоже добавь id поста в exception message

2024-09-17 19:01 UTC, amilosh commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Ещё вот так можно сделать
@ResponseStatus(HttpStatus.NO_CONTENT)
    public void deletePost(@PathVariable Long postId) {
        postService.delete(postId);
    }

но это на вкус и цвет

2024-09-17 19:07 UTC, amilosh commented on src/main/java/faang/school/postservice/mapper/post/PostMapper.java
> +    default List<PostDto> listEntitiesToListDto(List<Post> posts) {
List<PostDto> toDtos(List<Post> posts);

так маппер тоже понимает что делать
(если PostDto toDto(Post post); определено)

2024-09-17 19:10 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +    private PostService postService;
Мы голосовали, чтобы начала моки, а внизу @InjectMocks

2024-09-17 19:13 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +    void testSuccessCreate() {
вроде на портале было, что нужно так делать
test<Название метода>_<Кейс который тестируем>

testCreate_Sucess

2024-09-17 19:22 UTC, kripersh27 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +public class PostController {
Можно добавить сразу аннотации сваггера, чтобы сразу с ними учиться писать)

2024-09-17 19:22 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .toList();
Можно фильтрацию и сортировку в отдельный приватный метод вынести

2024-09-18 06:37 UTC, cemeh666 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto createPost(@Valid @RequestBody CreatePostRequestDto requestDto) {
сокращаю названия по заветам Димы

2024-09-18 06:42 UTC, cemeh666 commented on src/main/java/faang/school/postservice/dto/post/CreatePostRequestDto.java
> +public class CreatePostRequestDto {
тут именно **Request** приходит от клиента, поэтому и в названии Request

2024-09-18 06:44 UTC, cemeh666 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        Post result = postService.create(post);
**postService** как бы намекает, что `create `будет **Post**

2024-09-18 06:48 UTC, cemeh666 commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler extends ResponseEntityExceptionHandler {
да. без него тоже работает

2024-09-18 06:50 UTC, cemeh666 commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        throw new ValidationException("User id=%s not exist".formatted(userId));
интересно!

2024-09-18 06:52 UTC, cemeh666 commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +        } catch (RuntimeException ignore) {
тут Http запрос в другой сервис происходит. с БД никак не работает метод

2024-09-18 06:53 UTC, cemeh666 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return postRepository.findByIdAndNotDeleted(id).orElseThrow(PostNotFoundException::new);
так пользователь и так предаёт id и он понимает какой не найден

2024-09-18 06:55 UTC, cemeh666 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return postRepository.findByIdAndNotDeleted(id).orElseThrow(PostNotFoundException::new);
обычно логируется запрос и в логи попадает путь по которому обратились, статус ответа и можно будет найти все 404 ответы и посмотреть по каким урлам они были

2024-09-18 06:57 UTC, cemeh666 commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +
про логирование не было задачи

2024-09-18 07:01 UTC, cemeh666 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
да. нормально работает

2024-09-18 07:03 UTC, cemeh666 commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +    void testSuccessCreate() {
кажется вкусовщина

2024-09-18 07:03 UTC, cemeh666 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +public class PostController {
нужно было быстро задачу закрыть. на это не было времени, да и свагер на этом проекте вроде ещё не подключен

2024-09-18 07:04 UTC, cemeh666 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .toList();
она только тут используется. луче в одном месте концентрированно хранить

2024-09-18 07:06 UTC, cemeh666 commented on src/main/java/faang/school/postservice/mapper/post/PostMapper.java
> +    default List<PostDto> listEntitiesToListDto(List<Post> posts) {
что-то не понимает
![image](https://github.com/user-attachments/assets/68119f9a-d3f5-4d72-905a-f921da21c9fd)

2024-09-18 07:06 UTC, cemeh666 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return postRepository.findByIdAndNotDeleted(id).orElseThrow(PostNotFoundException::new);
добавил

2024-09-18 19:17 UTC, 20cognosce requested changes

2024-09-18 19:17 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping
Patch

2024-09-18 19:17 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/{postId}/publish")
posts/publish/{id}

2024-09-18 19:17 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        }
Не нравится мне такой дизайн
Сделай лучше два метода либо по автору, либо по проекту

2024-09-19 06:29 UTC, cemeh666 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/{postId}/publish")
не согласен.
`/post/{id}/publish`
читается как 
> пост с id таким то опубликовать

чем `/posts/publish/{id}`

> посты опубликовать с id таким то

2024-09-19 18:38 UTC, 20cognosce requested changes

2024-09-19 18:38 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping
Patch

2024-09-19 18:38 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PatchMapping("/{postId}/publish")
?
Put

2024-09-19 20:14 UTC, 20cognosce approved these changes

2024-09-19 20:14 UTC, merged