Initial commit for BJS2-27414
CorporationX/post_service pull request #764
Opened 2024-09-19 16:11 UTC by soulasphyxia

2024-09-19 16:28 UTC, soulasphyxia commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
пока что только позитивные тесты, тк не разобрался, как тестировать контроллеры с аннотациями валидации, типа @Positive, вроде передаю отрицательный id, а вроде в тесте пишет, что 200, хотя когда в постмане дергаю, то 400 :(((

2024-09-20 03:15 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
Порекомендовал бы userId тоже в сервис передать, пока что UserServiceClient не работает, но в итоге ты всё равно там будешь его вызывать и нужен будет userId))

2024-09-20 03:18 UTC, ArstanSubanov approved these changes
Отлично) Недочётов вроде не нашёл) Только тебе походу придётся подождать нас с Максимом)

2024-09-20 03:32 UTC, SharkB38 approved these changes

2024-09-20 09:14 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
я уже использую userId в сервисе через userContext, который получает его через хедер, я просто не знаю как лучше сделать, передавать userId в сервис из requestHeader, или уже в сервисе получать его из хедера как я сейчас сделал

2024-09-20 09:16 UTC, soulasphyxia commented
забыл написать, что не сделал 5 пункт (жду систему постов), и вот взаимодействие с userService(тоже жду), пока прошу проверить на эту итерацию какие недочеты, чтобы я уже с новыми пунктами исправил и эти недочеты.

2024-09-20 09:37 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
Да, ты прав, я не посмотрел, что UserHeaderFilter записывает в userContext значение из хэдера) Думаю, твой вариант правильнее, так как переменная userId используется в нескольких сервисах и не нужно в каждом методе его передавать, а сразу брать из контекста)

2024-09-20 16:16 UTC, mysosnovskaya requested changes

2024-09-20 16:16 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +                      Long commentId){}
Здесь стиль получился не единообразным по сравнению с другими рекордами)

2024-09-20 16:16 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +}
Для полноты картины нужно ещё добавить обработку Throwable с 500 статусом

2024-09-20 16:16 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/like/LikeServiceImpl.java
> +public class LikeServiceImpl implements LikeService {
Может логов добавим? Или ты по какой-то причине не стал этого делать?

2024-09-20 16:16 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
А, вот как ты сделал. Тогда хэдер здесь не нужен. Есть вот этот класс
https://github.com/CorporationX/post_service/blob/hydra-master-stream6/src/main/java/faang/school/postservice/config/context/UserHeaderFilter.java
который из переданного запроса берет хэдер с именем x-user-id и проставляет его в контекст. Этот класс можно подебажить, посмотреть, как работает) Вообще должно всё корректно работать, если ты добавишь нужный хэдер в запрос (это можно сделать в постмане). Если что-то не работает - пиши в чат)

2024-09-20 16:16 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
Юнит тестами статус код не протестируешь. Валидацию на аннотациях лучше всего тестировать так, как это сделал Арстан в своём ПРе:
https://github.com/CorporationX/project_service/pull/619

2024-09-20 16:31 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
да, там хедер не нужен, я делал так уже, просто я не уверен, что в таком случае если пользователь не передал хедер, то все не сломается... протестирую это

2024-09-20 19:19 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/service/like/LikeServiceImpl.java
> +public class LikeServiceImpl implements LikeService {
добавлю, конечно!

2024-09-26 15:56 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
я решил оставить аннотацию @RequestHeader, даже при учете того, что userId мы никуда не передаем и  равно получаем через userContext, потому что тогда, если пользователь не поставил хэдер, то вылетит сообщение, по типу "Required request header 'x-user-id' for method parameter type Long is not present", а если без аннотации, то там просто пишет, что вылетело NPE и непонятно, что с этим делать, на мой взгляд.

2024-09-26 16:07 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/controller/like/LikeController.java
> +        return likeService.removeLikeOnComment(commentId);
я все же решил оставить аннотацию @RequestHeader("x-user-id") Long userId, и передавать его в методы, потому что без этой аннотации непонятно в какой момент сообщать клиенту о том, что он забыл передать хедер, а эта аннотация делает это за нас.

2024-09-26 16:28 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +                      Long commentId){}
не совсем понял, можете привести пример пожалуйста?

2024-09-26 19:35 UTC, mysosnovskaya requested changes

2024-09-26 19:35 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
Что-то я не увидела тестов на валидацию

2024-09-26 19:35 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +                      Long commentId){}
Да, здесь у тебя `){}`, а например в PostDto: 
```
) {
}
```

2024-09-26 19:35 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +public interface PostService {
Это не твои изменения, их не должно быть в твоем ПРе

2024-09-27 07:20 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +public interface PostService {
да, я понимаю, но, для того чтобы можно было замержить, я сделал ребейз, или я слишком рано его сделал?

2024-09-27 09:24 UTC, soulasphyxia commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
Как я понял, у Арстана в тестах тестируются аннотации, которые навешиваются в классе дто. у меня же дто только возвращается, поэтому тесты, которые написал Арстан, мне не подходят, я проверил. Или я ошибаюсь? Потому что я хотел протестировать аннотацию @Positive, которая вешается на requestParam, это возможно протестировать юнит-тестами?

2024-09-27 20:39 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +public interface PostService {
Ребейз как-то некорректно прошел, файлы задублировались. Надо будет разобраться с этим. В данный момент тебе нужно из твоей ветки удалить лишние коммиты (будь аккуратен - сохрани копию обязательно).

2024-09-27 20:49 UTC, mysosnovskaya requested changes

2024-09-27 20:49 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
Да, как Арстан сделать не получится. Такое только через mockMvc. Посылаешь некорректные данные и ожидаешь 400 в ответ)

2024-09-28 04:11 UTC, soulasphyxia commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
я так и сразу пытался делать :(, у меня почему то когда я, например посылаю запрос POST /likes/posts/-2, то возвращается 200, хотя в постмане такой запрос возвращает, как и должен, 400. я пробовал добавлять setControllerAdvice(new GlobalExceptionHandler()), добалял там всякие аннотации, но не работает, буду писать в хелп

2024-09-28 04:31 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +public interface PostService {
так, ну вроде починилось, и даже ничего не потерялось, и конфликты порешались

2024-09-29 05:41 UTC, soulasphyxia commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +public class LikeControllerTest {
получилось!!

2024-09-29 17:06 UTC, mysosnovskaya approved these changes
Удали закомментированный код и можешь мержить и закрывать задачу)

2024-09-29 17:06 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/controller/like/LikeControllerTest.java
> +//        mockMvc = MockMvcBuilders.standaloneSetup(likeController)
Удалить нужно, если это лишнее)

2024-09-29 18:07 UTC, merged