Post system done
CorporationX/post_service pull request #776
Opened 2024-09-20 12:51 UTC by MamadjonovKO

2024-09-20 18:02 UTC, mrkorolev reviewed
"Ждем продолжение")

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/PostService.java
> +        }
Можно было не писать проверку в else if - и так понятно из проверок выше, что исполнение дойдет сюда только если один из них не null (просто else).

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/PostService.java
> +        if (Objects.nonNull(post.getAuthorId())) {
Конечно дело вкусовщины, но мне кажется лучше проверять через isNull - без отрицания логически проще понять твою идею.

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +@RequestMapping("/post")
Мне кажется лучше коллекцию описывать, множественное число - posts

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PostMapping("/create")
Лучше не использовать глаголы в url, если они относятся к элементу коллекции с которой работает контроллер (можно просто /draft)

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/publish/{id}")
Лучше в порядке url сначала определить пост, с которым работаешь, а потом действие, которое с ним выполняешь (/posts/{id}/publish)

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/update")
По смыслу лучше поставить /edit (и так понятно, что PutMapping делает update)

2024-09-20 18:02 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @DeleteMapping("/delete/{id}")
Я бы поставил PutMapping - пока ты ничего не удаляешь из БД, а просто помечаешь записи для удаления в будущем

2024-09-21 07:46 UTC, Peregruzochka reviewed
Мне понравилось, как ты добавил методы в entity, чтобы их можно было изменять)

2024-09-21 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +@Data
Вроде как если не делаем проверку на Equals и HashCode, то можно просто поставить гетеры/сеттеры и нужный конструктор

2024-09-21 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
О, прикольно, я не заходил в экспериментальные фичи lombok`а)
Правда не понятно законно так делать или нет?)

2024-09-21 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public Post createDraftPost(Post post) {
Тут вроде тоже нужен `@Transactional`

2024-09-21 07:46 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/PostService.java
> +        userContext.setUserId(post.getAuthorId());
А для чего вообще используется user context?

2024-09-22 08:01 UTC, MamadjonovKO commented on src/main/java/faang/school/postservice/service/PostService.java
> +        userContext.setUserId(post.getAuthorId());
> А для чего вообще используется user context?

Как я понял, UserContext нужен для того чтобы хранить информацию о пользователе (в этом случае его ID) на протяжении всего выполнения одного HTTTP запроса

2024-09-23 09:54 UTC, mrkorolev reviewed
Все ок

2024-09-23 09:54 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/delete/{id}")
Можно сразу /{id} - понятно, что тут происходит. Так хорошо делать когда есть конфликт (метод с точно таким же url и Http методом, у тебя не тот случай, все хорошо :)

2024-09-23 09:54 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/user/{userId}/drafts")
Хорошо, но можно лучше: /drafts, а userId передавать как RequestParam - так, по-моему, понятней

2024-09-23 09:54 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/project/{projectId}/drafts")
также можно kebab case использовать в url: /project-id

2024-09-23 20:35 UTC, 20cognosce requested changes

2024-09-23 20:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/delete/{id}")
Delete mapping

2024-09-23 20:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/edit")
Patch mapping

2024-09-23 20:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PutMapping("/edit")
posts/edit/id
posts/publish/id
posts - get
posts/id - delete
posts?user-id=123 - get

меняй все эти пути

2024-09-23 20:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Post.java
> +    }
что?
Почему ты в pojo логику реализуешь?

2024-09-23 20:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    List<Post> findPublishedByProjectId(long projectId);
Можно не писать ручные query, а по имени метода дать спрингу самому сформировать запрос

2024-09-23 20:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public Post updatePost(Post post) {
id поста отдельно
кроме контента, больше ничего не обновляется?
Зачем тогда целиком объект мапить туда-сюда

2024-10-02 04:49 UTC, merged