BJS2-27223 Получить всех пользователей, которым понравился пост или коммент
CorporationX/post_service pull request #780
Opened 2024-09-21 06:03 UTC by vinogor

есть вопрос - см. UserDto

2024-09-23 20:39 UTC, mikhailov26 requested changes

2024-09-23 20:39 UTC, mikhailov26 commented on src/main/java/faang/school/postservice/util/CustomValidator.java
Ознакомиться с лекциями 8 спринта, и отрефакторить

2024-09-23 20:39 UTC, mikhailov26 commented on src/main/java/faang/school/postservice/dto/user/UserDto.java
Лекции

2024-09-24 05:05 UTC, vinogor commented on src/main/java/faang/school/postservice/util/CustomValidator.java
лекции смотрю, пока не очень понял что именно отрефакторить

2024-09-25 18:15 UTC, merged