BJS2-27409 Система постов
CorporationX/post_service pull request #783
Opened 2024-09-21 12:24 UTC by ArstanSubanov

2024-09-21 15:20 UTC, soulasphyxia approved these changes

2024-09-21 15:21 UTC, soulasphyxia commented
круто написано!

2024-09-21 20:33 UTC, wmwmaks commented on build.gradle.kts
> +    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.3")
это отдельной задачей, наверное, нужно сделать)

2024-09-21 20:33 UTC, wmwmaks commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +        @JsonInclude(JsonInclude.Include.NON_NULL)
что-то новое😅

2024-09-21 20:39 UTC, wmwmaks commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        Post post = getPost(id);
Чисто гипотетически не может быть ситуации, что поста с таким id нет? И нужно ли эту ситуацию обрабатывать?
Как и в остальных методах get, update. Что думаешь?

2024-09-21 20:42 UTC, wmwmaks approved these changes
Присоединяюсь, крутой код. Я ничего не нашел, хотя старался)

2024-09-22 08:27 UTC, SharkB38 commented
Когда вырасту хочу писать код как Арстан

2024-09-22 08:27 UTC, SharkB38 approved these changes

2024-09-22 09:12 UTC, ArstanSubanov commented on build.gradle.kts
> +    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.3")
Да, просто он нужен был мне в контроллере) Думаю, пока я буду делать изменения в моём ПР, Асылхан уже смержит в мастер ветку)

2024-09-22 18:31 UTC, mysosnovskaya requested changes

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto publishThePost(@Positive
Как-то так исторически сложилось, что артикли в названиях классов/методов/полей/переменных не употребляют. Поэтому просто publishPost

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PatchMapping("/publish/{postId}")
/posts/{postId}/publish

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @PatchMapping("/update/{postId}")
/posts/{postId}

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    @GetMapping("/unpublished-by-authorId/{authorId}")
Эти четыре метода поиска в идеале нужно объединить в один) Тут тебе помогут query params. Оставляю на подумать как задачку со звездочкой, подробно расписывать не буду)

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +            UserDto userDto = userClient.getUser(request.authorId());
Круто, что используешь клиентов 👍

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +            throw new IllegalArgumentException("Post is already published with id: " + id);
На мой взгляд IllegalArgumentException это о другом) Это когда в качестве аргумента в метод передали что-то невалидное. Например, ожидалось неотрицательное целое число, а пришло -10. А у тебя с аргументом метода всё нормально, туда пришло какое-то число, мы начали с ним работу. Я бы создала своё исключение для этого) Хотя можешь оставить и так, это не критично и бывает по-разному

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        Post post = postRepository.findByIdAndDeletedFalse(id);
А может было бы лучше, если бы findByIdAndDeletedFalse возвращал Optional<Post>?

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    @Scheduled(fixedRate = 600000)
Ого =) Это интересно. На самом деле среди методов сервиса это теряется. И если вдруг появится другая реализация сервиса, то про это могут забыть. Как думаешь, не лучше ли вынести это в отдельный класс-планировщик?

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        postRepository.saveAll(posts);
Можно ещё лог добавить, сколько постов обновлено. Можно даже их id записать

2024-09-22 18:31 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/validation/OnlyPostCreator.java
> +public @interface OnlyPostCreator {
Круто!

2024-09-23 17:12 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/controller/PostController.java
> +        return postService.getPostsByCreatorAndPublishedStatus(creatorId, creator, publishStatus);
Сначала хотел сделать также как мы делали фильтры и здесь передать какой-нибудь дто, а потом снова проверять на наличие не пустых полей и т.д. Но захотелось сделать именно через RequestParam и использовать уже написанный мною код, хоть и не по SOLID, но для практики и разнообразия сделал так)

2024-09-24 17:59 UTC, mysosnovskaya requested changes

2024-09-24 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostPublisher.java
> +    @Scheduled(cron = "${post.publisher.scheduler.cron}")
Этот параметр должен появиться в application.yaml, чтобы у других членов команды код запускался)

2024-09-24 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostPublisher.java
> +@Service
Тут лучше Component подойдет, т.к. этот класс не является сервисом

2024-09-24 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostPublisher.java
> +        log.debug("Published {} posts", posts.size());
Я бы сначала сохранила, а потом написала сообщение об этом)

2024-09-24 17:59 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    public List<PostDto> getPostsByCreatorAndPublishedStatus(Long creatorId,
Ок, пусть остается так, но в будущем если вдруг добавятся ещё параметры, то нужно будет переделать под общую структуру. То есть данный код хорош для текущих требований и мы можем это в таком виде оставить, но как только мы поймем, что этот метод расширяется, то и название метода нужно будет менять, и параметры, и реализацию, чтобы код становился гибче)

2024-09-24 18:14 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/PostPublisher.java
> +    @Scheduled(cron = "${post.publisher.scheduler.cron}")
В application.yaml у всех есть этот параметр, я оттуда взял потому что этот параметр уже добавили, сам я не писал его)

2024-09-24 18:16 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    public List<PostDto> getPostsByCreatorAndPublishedStatus(Long creatorId,
Да, если в будущем будет возможность расширения, то я изменю)

2024-09-24 19:20 UTC, mysosnovskaya approved these changes

2024-09-24 19:21 UTC, merged