BJS2-26093: Система лайков
CorporationX/post_service pull request #792
Opened 2024-09-22 07:49 UTC by lowerKamaCase

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +@RequestMapping("/likes")
добавить версионирование

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  @Autowired
используй requiredArgsConstructor вместо autowired, если добавятся еще сервисы над каждым будет @Autowired ставить, а так одной аннотацией обходимся

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +@Data
Используются все внутренние аннотации? Если нет то data убираем и оставлям только то что используется.

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/post/PostDto.java
> +@Data
аналогично предыдущей дто

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    if (likeDto.getPostId() != null) {
лучше разбить на 2 метода один для постов другой для комментов

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +public class LikeDto {
Разбей LikeDto на LikeCommentDto и LikePostDto

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  @Autowired
А вот и пример множественного Autowired, если хочешь дальше писать Autowired, то делай через конструктор.

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  private LikeService likeService;
final

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  private CommentRepository commentRepository;
все final

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            throw new IllegalArgumentException("Like already exists");
это вынести в валидатор

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +      Like like = Like.builder()
почему не через маппер?

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            throw new IllegalArgumentException("Like already exists");
аналогично в валидатор

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +      Like like = Like.builder()
аналогично почему не через маппер

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  public void addLike(LikeDto likeDto) {
где проверки что юзер существует в системе?

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    @NotNull(message = "User ID не может быть null")
а отрицательный может быть?

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private long id;
а эта переменная используется?

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    if (likeDto.getPostId() != null) {
тоже разбей на 2 метода

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +      likeRepository.deleteByPostIdAndUserId(likeDto.getPostId(), likeDto.getUserId());
где проверки что пост/коммент существует + что юзер существует

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
это вообще к чему и где используется, если не используется то зачем он
ну и раз  написал, то где тесты на него

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +  @Autowired
аналогично

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +          int likeCount = likeRepository.findByPostId(post.getId()).size();
если это post сервис, почему тут likeRepo  ?

2024-09-22 11:04 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +    return new PostDto(post.getId(), post.getContent(), post.getAuthorId(), post.getProjectId(), likeCount);
это в маппер

2024-09-22 11:04 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +      likeDto.setUserId(1L);
циферы в переменую класса вынеси

2024-09-22 11:04 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +      LikeDto likeDto = new LikeDto();
у тебя этот likeDto в каждом тесте инициируется, используй @beforeEach

2024-09-22 11:04 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +      when(likeRepository.findByPostIdAndUserId(likeDto.getPostId(), likeDto.getUserId())).thenReturn(Optional.empty());
вышел за 80 символов

2024-09-22 11:04 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +      verify(likeRepository).save(any());
так же добавляем verify для postRepository и likeRepository

2024-09-22 11:04 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +      verify(likeRepository).save(any());
тоже добавляем верифай, и в следующих тестах тоже

2024-09-22 11:08 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  private PostRepository postRepository;
так же если это like сервис, почему тут PostRepo
и снизу тоже по поводу commentRepo

2024-09-24 14:18 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +@RequestMapping("/likes")
добавил

2024-09-24 14:19 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  @Autowired
поправил

2024-09-24 14:19 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +@Data
убрал дата, указал геттер сеттер

2024-09-25 17:24 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    if (likeDto.getPostId() != null) {
done

2024-09-25 18:03 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  private PostRepository postRepository;
потому что лайк можно поставить посту и комменту

2024-09-25 18:22 UTC, lowerKamaCase commented on src/test/java/faang/school/postservice/service/LikeServiceTest.java
> +      when(likeRepository.findByPostIdAndUserId(likeDto.getPostId(), likeDto.getUserId())).thenReturn(Optional.empty());
поправил. но вообще это бы линтером как-то правит, а не вручную.
надо бы обсудить это на планнинге

2024-09-25 20:10 UTC, mysosnovskaya requested changes
На будущее очень прошу отвечать на все комментарии с кросс-ревью: либо вносить соответствующие изменения, либо в ответе аргументированно ответить, почему считаешь правильным оставить свою текущую реализацию. В этом и есть один из плюсов кросс-ревью: научиться конструктивно общаться с другими разработчиками, доносить до них свои аргументы, анализировать и обосновывать свой код. Часто когда мы пишем код, то какие-то строчки пишем просто потому что где-то так видели или привыкли так писать или просто потому что так работает. А вопросы на кросс-ревью мотивируют посмотреть на свой же код с другой стороны и обосновать принятые решения. Это очень прокачает твои скиллы, потому что писать код - это одно, а говорить о коде (и о программировании в целом) - это другое)

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  @PostMapping("/post/{postId}")
По правилам проектирования rest урлов, здесь ничего не должно быть. Мы работаем с лайками (поэтому /api/v1/likes - верно), а остальная информация для POST (создания) должна прийти в теле запроса (в твоем случае внутри LikeDto должен прийти postId). А в теле запроса может прийти либо postId, либо commentId (можно сделать entityId + поле-перечисление POST или COMMENT). На крайний случай можно сделать два разных метода (но эта практика хуже): POST /api/v1/likes/to-post и POST /api/v1/likes/to-comment. Я рекомендую использовать первый вариант

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    return ResponseEntity.ok().build();
Мы не используем ResponseEntity, т.к. в нем нет необходимости. По умолчанию ответ и без него будет 200 OK. Да и в целом ResponseEntity это ненужная обертка над респонсом. Так что убирай её везде)
А также POST запрос должен возвращать созданный объект, т.к. при создании лайку присваивается id и фронт должен об этом айди узнать (и в delete методах нужно его использовать, об этом напишу ниже)

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  @DeleteMapping("/post/{postId}")
Здесь должно быть либо @DeleteMapping("/{likeId}") - т.к. у лайка есть айди, который его однозначно идентифицирует. либо @DeleteMapping, а в теле запроса вся необходимая информация (аналогично запросу на создание: entityId + POST/COMMENT + userId). Либо если решишь всё-таки делать по два эндпоинта на создание, то тогда на удаление должно быть аналогично (но без идентификаторов postId и commentId в урле - они только в теле)

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  public ResponseEntity<?> removeLikeFromPost(@PathVariable Long postId, @Valid @RequestBody LikeDto likeDto) {
здесь можно просто public void

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +public class LikeDto {
Согласна с тем, что нужны разные dto. Я в контроллере предложила другую идею, но разделить этот класс на два других (dto-запрос и dto-ответ) всё равно будет необходимо.

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  @Autowired
Согласна, лучше через конструктор

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  private CommentRepository commentRepository;
Согласна

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/LikeService.java
> +          .orElseThrow(() -> new IllegalArgumentException("Post not found"));
В сообщении об ошибке должна быть идентифицирующая информация - в данном случае id поста, который не удалось найти

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            throw new IllegalArgumentException("Like already exists");
Тоже нужна идентифицирующая информация (id юзера и поста)

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/LikeService.java
> +      Like like = Like.builder()
Согласна, через маппер будет лучше

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
Это есть в требованиях к задаче)

2024-09-25 20:10 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
На этот класс тоже тесты нужны

2024-10-01 05:27 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  @PostMapping("/post/{postId}")
поправил

2024-10-01 05:27 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    return ResponseEntity.ok().build();
доне

2024-10-01 05:27 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +  @DeleteMapping("/post/{postId}")
сделано

2024-10-01 05:29 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private long id;
нет, но нужно ли убирать айдишник?

2024-10-01 05:30 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  @Autowired
сделал через RequiredArgsConstructor, Autowired убрал

2024-10-01 05:31 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +  private CommentRepository commentRepository;
доне

2024-10-01 05:38 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            throw new IllegalArgumentException("Like already exists");
сделано

2024-10-01 05:43 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +      Like like = Like.builder()
сделано

2024-10-01 05:47 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    if (likeDto.getPostId() != null) {
оставил один, так как удаление происходит по айди.
сейчас весь метод это
```
public void removeLike(Long likeId) {
        likeRepository.deleteById(likeId);
    }
    ```

2024-10-01 06:12 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/LikeService.java
> +      likeRepository.deleteByPostIdAndUserId(likeDto.getPostId(), likeDto.getUserId());
спасибо, добавил

2024-10-01 07:07 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +public class LikeDto {
разделил на дто-запрос и дто-ответ

2024-10-01 07:16 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
done

2024-10-01 07:19 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/PostService.java
> +          int likeCount = likeRepository.findByPostId(post.getId()).size();
такие требования к задаче - "Далее нужно поправить логику PostService для включения информации о лайках в логике методов, возвращающих опубликованные посты пользователя или проекта. "

2024-10-01 09:35 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +          int likeCount = likeRepository.findByPostId(post.getId()).size();
@lowerKamaCase я тут намекнул на вынос like в LiskeService, сейчас у тебя Post занимается 2мя вещами постами и лайками

2024-10-01 09:40 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +          int likeCount = likeRepository.findByPostId(post.getId()).size();
а и в likeService обращение к postRepository, будет циклическая зависимость, если не сможешь как-то логику разбить руками, можно оставить или на крайняк внедрить через @Autowired ( но не уверен)

2024-10-02 12:53 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/PostService.java
> +    return new PostDto(post.getId(), post.getContent(), post.getAuthorId(), post.getProjectId(), likeCount);
done

2024-10-02 13:02 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/PostService.java
> +          int likeCount = likeRepository.findByPostId(post.getId()).size();
убрал likeRepository из зависимостей. оказалось, можно проще сделать, заменил на post.getLikes().size()

2024-10-02 19:18 UTC, mysosnovskaya requested changes
Осталось совсем мелочи поправить и будем закрывать задачу) Обязательно обрати внимание на конфликт в ПРе, с ним я смержить не могу. Нужно поправить

2024-10-02 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/LikeService.java
> +            likeRepository.save(like);
Эта строчка дублируется, можно её вынести за пределы if-else

2024-10-02 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
В классе стиль не соблюден, используй ctrl + alt + L для автоматического форматирования

2024-10-02 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +        .map(post -> {
`.map(post -> postMapper.toResponseDto(post, post.getLikes().size()))`

2024-10-02 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +        .collect(Collectors.toList());
.toList()

2024-10-02 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/validator/like/LikeValidator.java
> +    public void validateLikeForPost(Long postId, Long userId) {
Я бы в названии явным образом указала, что проверяется именно существование. А то в данный момент из названия не очевидно, что именно валидируется

2024-10-02 19:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +public class LikeController {
Вот теперь контроллер отлично выглядит)

2024-10-05 19:01 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
а можно ли автоформатирование сделать действительно автоформатированием и снять с разработчика ответственность?
я пользуюсь вскод, а не идеей.
по моему, автоформатирование обычно на этапе коммита происходит, и руками самому ничего делать не надо

2024-10-06 03:09 UTC, mysosnovskaya requested changes
Один комментарий (с переименованием метода в LikeValidator) не исправлен. После него точно смержу)

2024-10-06 03:09 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +public class PostService {
Нет, за нас никто код не форматирует. Обычно есть линтеры, которые проверяют стиль и подсказывают, где и что нужно исправить, но исправляет только сам разработчик

2024-10-06 03:09 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/validator/like/LikeValidator.java
> +    public void validateLikeForPost(Long postId, Long userId) {
Не исправлено

2024-10-06 03:21 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/validator/like/LikeValidator.java
> +    public void validateLikeForPost(Long postId, Long userId) {
сделал validateLikeForPostExists и validateLikeForCommentExists

2024-10-06 03:31 UTC, mysosnovskaya approved these changes

2024-10-06 03:32 UTC, merged