Система видимости альбомов 26857
CorporationX/post_service pull request #807
Opened 2024-09-23 08:07 UTC by Peregruzochka

2024-09-23 09:19 UTC, mrkorolev reviewed
Удачи с новой таской)

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +    }
Как будто бы можно все это в один метод вынести, а всю фильтрацию делать в методах сервиса. Сейчас точно не возьмусь сказать, как бы это выглядело)

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/mapper/album/AlbumMapper.java
> +    default List<Long> mapToLongList(List<Post> posts){
mapToIdList, mapToIds - так, мне кажется, лучше

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/model/Album.java
>      @JoinTable(name = "post_album", joinColumns = @JoinColumn(name = "album_id"), inverseJoinColumns = @JoinColumn(name = "post_id"))
Духота, но можно отформатировать для читаемости (посмотри как они это с другими сузностями делают):

    @JoinTable(name = "post_album", 
            joinColumns = @JoinColumn(name = "album_id"), 
            inverseJoinColumns = @JoinColumn(name = "post_id"))

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +            SELECT a.* FROM album a
Зачем здесь сокращенное имя (a)? У тебя нативный запрос (не JPQL), и нет вложенных запросов, которые используют это сокращенное имя, и нет сложных join'ов

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +            SELECT uwa.user_id FROM users_with_access uwa
Тот же самый вопрос

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +            SELECT a.id FROM album a
Дважды использовал -мб реально причина есть, а я не знаю)

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +    List<Long> findAlbumIdsWithUserAccess(Long userId);
Во всех методах выше примитивный long - определись либо с объектом, либо с примитивом

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    }
По сути повторяются - тот же совет, что в контроллере

2024-09-23 09:19 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +        if (!existStatus) {
Можно прямо в if - без переменной, по сути разницы нет (душним)

2024-09-23 09:19 UTC, mrkorolev commented on src/main/resources/db/changelog/changeset/post_V005_users_with_access.sql
> +    id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
PRIMARY KEY = UNIQUE + NOT NULL (нужен ли тут UNIQUE в конце, хз)

2024-09-23 09:19 UTC, mrkorolev commented on src/main/resources/db/changelog/changeset/post_V005_users_with_access.sql
> +    CONSTRAINT fk_album_id FOREIGN KEY (album_id) REFERENCES album(id) ON DELETE CASCADE
Можно так, как они это делают - а можно короче (в одну строчку, сам смотри как удобней):

album_id bigint NOT NULL REFERENCES album(id) ON DELETE CASCADE

2024-09-23 09:43 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    }
Я следовал заданию
Таков путь

2024-09-23 15:34 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +                                   @RequestParam long userId) {
Думаю порядок параметров нужно сделать последовательным

2024-09-23 15:34 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +                                        @RequestParam long userId) {
Порядок параметров

2024-09-23 15:36 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +    }
У меня ментор говорила, что лучше в мапере методы называть конкретизируя в какую сущность или в какую dto происходит превращение
так же toDto -> toAlbumDto
с toEntity тоже самое, слишком абстрактно
мало ли какие появятся в будущем методы

2024-09-23 15:40 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +    public void deleteAlbum(@PathVariable("album-id") long albumId, @RequestParam long userId) {
Я бы сверху повесил бы анyотацию
@ResponseStatus(HttpStatus.NO_CONTENT) // Возвращает 204 статус, если операция прошла успешно

2024-09-23 15:51 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/model/AlbumStatus.java
> +public enum AlbumStatus {
AlbumPrivacy или AlbumVisibility
чтобы внести ясность

2024-09-23 15:56 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/model/AlbumStatus.java
> +    SOME_USERS,     //1
название SOME_USERS наводит на мысль что сервер будет передавать список пользователей, потому как есть неопределенность в названии статуса
но судя по фильтру, этих пользователей ты достаешь из БД
назови тогда ALLOWED USERS или TRUSTED USERS или что-то в этом роде

2024-09-23 16:03 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +    }
я бы создал Enum с возможными вариантами получения альбомов и эти методы объединил

2024-09-26 20:31 UTC, 20cognosce requested changes
Лишнее убираем и переделываем

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/ControllerAdvice.java
> +    // Validator exceptions, based on convention chosen by the team
Зачем бессмысленные комментарии

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/ControllerAdvice.java
> +    @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
Можно было сделать 1 метод, и параметризировать только тип ошибки и статус код ответа, много одинакового кода в этих обработчиках

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Album.java
> +    @Enumerated(EnumType.ORDINAL)
? Почему не EnumType.String, смысл?

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Album.java
> +    @Column(name = "user_id")
Что здесь намешано? Как оно относится к 
private List<Long> userWithAccessIds = new ArrayList<>();

Объясни что ты тут делаешь

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Album.java
> +    private List<Long> userWithAccessIds = new ArrayList<>();
Ты хранишь в Альбоме список всех пользователей, кто к нему имеют доступ
???

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Album.java
> +    private List<Long> userWithAccessIds = new ArrayList<>();
То есть альбом решает, кто его может смотреть типо? 
Логическая связь нелогическая совершенно

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/AlbumVisibility.java
> +    ALL             //3
bruh

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +public interface AlbumRepository extends JpaRepository<Album, Long> {
? Что это за мода

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +    List<Long> findAlbumIdsWithUserAccess(Long userId);
Почему твои методы только с айдишниками работают и на запрос и на ответ
Делай нормально

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +public interface PostRepository extends JpaRepository<Post, Long> {
Опять фетишисты

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/album_status_executor/AlbumAllExecutor.java
> +    }
Что это

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    }
Ну это трэшанина ваще
Что за фильтры, зачем ты их насоздавал, в задачи ни слова про фильтры

Нужно добавить настройку видимости для каждого альбома. Т.е. альбом, созданный определенным пользователем может быть доступен:
Всем пользователям
Только его подписчикам
Только выбранным автором пользователям
Только автору

Где весь этот функционал, вообще не прозрачно где это происходит

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/AlbumController.java
> +    }
Да, обобщить эти три метода в один

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Album.java
> +    private List<Long> userWithAccessIds = new ArrayList<>();
Отдельной сущностью эту таблицу делай

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    }
Сделай мне в контроллере один метод - getAllAvailableAlbums(long userId) {}

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    }
Который собирает по 4-м приватным методам все id альбомов, подпадающие под условия для пользователя
И затем собирает из них уникальные, после чего делает findAll(List<<Long>> albumIds) {}

2024-09-26 20:31 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/AlbumService.java
> +    }
Фильтры / экзекьюторы - это порнография какая-то

2024-09-26 20:33 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/AlbumRepository.java
> +    List<Long> findAlbumIdsWithUserAccess(Long userId);
Это нормально
Только имена переделай более на более понятные

И в репе альбома - работа с альбомами
В репе юзера - работа с юзером

2024-09-27 11:17 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/model/Album.java
> +    @Column(name = "user_id")
@20cognosce
Альбомы с типом "Доступные только определенным пользователям"
Должны иметь информацию о том, каким пользователям они доступны.
Для этого я сделал таблицу "users_with_access" и с помощью этого поля я как раз передаю в БД/достаю из БД информацию об этих пользователях

2024-09-29 08:56 UTC, 20cognosce approved these changes

2024-09-29 08:56 UTC, merged