Система комментариев
CorporationX/post_service pull request #819
Opened 2024-09-24 11:35 UTC by SharkB38

2024-09-24 14:21 UTC, aassylkhan approved these changes
Вроде все классно написано. Валидация и сортировка хорошо написаны. Побольше exception наверно надо добавить. Например при поиске поста.

2024-09-24 15:01 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/CommentServiceImpl.java
> +    }
> Вроде все классно написано. Валидация и сортировка хорошо написаны. Побольше exception наверно надо добавить. Например при поиске поста.
Вот тут проверяю же, потом через сервис постов будет. Или ты про другое?

2024-09-24 16:51 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +@RequestMapping("/posts/{postId}")
Не уверен что так делают) По крайней мере мне было сложнее читать код, нужно было в каждом методе держать в голове что там есть postId)

2024-09-24 16:52 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +    public CommentDto updateComment(@PathVariable @Positive Long commentId,
В этом методе и методе deleteComment не передаётся postId? /postId/comments/commentId?

2024-09-24 17:03 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/dto/comment/CommentCreateUpdateDto.java
> +) {
Мне кажется, что группы лучше использовать когда создаёшь один дто для всех запросов, в принципе ты мог в CommentDto то же самое написать и поставить над id аннотацию @Null при создании или обновлении) Всё равно при обновлении используется только поле content)

2024-09-24 17:05 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/dto/comment/CommentCreateUpdateDto.java
> +        String content,
Тут можно ещё аннотацию @Size добавить, там в задании вроде нужно чтобы коммент не был больше 4096 символов вроде)

2024-09-24 17:06 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException {
EntityNotFoundException вроде есть в jakarta.persistence?

2024-09-24 17:10 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/CommentServiceImpl.java
> +    }
Крутая реализация сортировки)) Нужно узнать у Маши как это можно сделать не создавая Map в конструкторе, а то из-за этого тебе пришлось вручную инжектить зависимости(

2024-09-24 17:12 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/CommentServiceImpl.java
> +        Comment savedComment = commentRepository.save(comment);
В принципе, можно не создавать savedComment, метод save обновить id у comment, его же потом можно вернуть)

2024-09-24 17:18 UTC, ArstanSubanov approved these changes
Хорошо сделал)) Добавил свои комментарии, если что могу ошибаться)

2024-09-24 17:21 UTC, SharkB38 commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +@RequestMapping("/posts/{postId}")
Да, тут надо подумать не знаю как лучше сделать

2024-09-24 17:22 UTC, SharkB38 commented on src/main/java/faang/school/postservice/dto/comment/CommentCreateUpdateDto.java
> +) {
Посмотрю, подумаю, может действительно один дто оставить

2024-09-24 17:25 UTC, SharkB38 commented on src/main/java/faang/school/postservice/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException {
А я думал все свое пишут, вот и я пишу с первого спринта, а оказывается у всех с jakarta исключение

2024-09-24 17:27 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/CommentServiceImpl.java
> +    }
Мне Маша и посоветовала так сделать в прошлой задаче, не знаю, может сюда не подходит этот способ

2024-09-24 18:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/CommentServiceImpl.java
> +    }
Ааа, тогда ок) Но если задумаешь избавиться от этого конструктора, то можно например вынести эту мапу в отдельный класс и там её создавать, а сюда просто инжектить с помощью RequiredArgsConstructor)

2024-09-26 20:06 UTC, mysosnovskaya requested changes

2024-09-26 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/CommentController.java
> +@RequestMapping("/posts/{postId}")
Так делают, но мне тоже читаемее, когда postId в каждом методе. Тут нет строго правила, мне оба варианта подойдут

2024-09-26 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +        @Null(groups = {Create.class, Update.class}, message = "Id not required")
Если я всё правильно помню про группы, то здесь их можно не писать. @Validated(Create.class) проверит все валидации с группой Create и все без группы. Или по какой-то причине ты думаешь, что лучше их оставить?

2024-09-26 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +public record CommentDto(
В данной ситуации согласна с одним dto, пусть остается. Очень круто, что вы с Арстаном увидели эту ситуацию, когда один dto оправдан. Повторю то, что уже говорила: есть разные решения и каждое из них хорошо подходит под какие-то определенные ситуации. И нам важно уметь эти ситуации замечать и принимать подходящие решения. Вот в этом ПР это отлично получилось) Молодцы! 👍

2024-09-26 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/SortingField.java
> +public enum SortingField {
SortingBy может быть?

2024-09-26 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentServiceImpl.java
> +    //неудобно через postService пока так оставлю
Это ок

2024-09-26 20:06 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/sort/SortingApplierExecutorsMap.java
> +public class SortingApplierExecutorsMap extends HashMap<SortingOrder, Map<SortingField, CommentSortingStrategy>> {
Вот это да!) Идея отличная! Молодец 👍 Предложу улучшения: сейчас в сервисе неочевидно использование этого класса. Может быть в этот класс добавим метод get(SortingOrder sortingOrder, SortingField sortingField), чтобы было однозначно понятно, как этим классом пользоваться? И если думать дальше: то сейчас кто-то снаружи может что угодно в мапу положить или даже удалить из неё. Тогда я бы лучше не наследовала, а сделала отдельное финальное поле с immutable мапой (и вложенной тоже immutable), а здесь оставила бы один метод get, как предложила выше. И тогда вообще красота будет)

К слову обо всём этом, погугли про "композиция или наследование", много разных статей вылезает. Вот ты сделал через наследование, а я предлагаю композицию.

2024-09-27 05:49 UTC, SharkB38 commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +        @Null(groups = {Create.class, Update.class}, message = "Id not required")
Когда не писал не работало, не проверялись валидации без групп

2024-09-29 17:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +        @Null(groups = {Create.class, Update.class}, message = "Id not required")
Значит я не правильно помню =)

2024-09-29 17:16 UTC, mysosnovskaya approved these changes
Аппрув ставлю, исправь мелочи и можешь сам смержить и закрыть задачу. 
Хотелось бы отдельно тесты похвалить - очень хорошие, понятные, с высоким покрытием - супер!)

2024-09-29 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +    //неудобно через postService пока так оставлю
Комментарий можно удалить

2024-09-29 17:16 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +        CommentSortingStrategy sortingApplier = sortingStrategiesAppliers.getExecutor(
метод называется getExecutor, переменная называется sortingApplier, а тип переменной - CommentSortingStrategy. Надо разобраться с названиями) Предлагаю:
```
CommentSortingStrategy sortingStrategy = sortingStrategies.getStrategy(...);
sortingStrategy.apply(post.getComments());
```

2024-09-29 17:16 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/dto/comment/CommentDtoTest.java
> +class CommentDtoTest {
Молодец, что написал тесты на валидацию 👍

2024-09-29 17:41 UTC, merged