Система лайков feature bjs2 26845
CorporationX/post_service pull request #821
Opened 2024-09-24 15:53 UTC by lexus-74

Реализация задания "Система лайков". Пока без тестов

2024-09-24 21:20 UTC, mrkorolev reviewed
Ждем тесты)

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        }
1. Ты сначала проверяешь репозиторий лайков для определенного поста. А что если этого поста нет? Я бы поменял эти проверки местами, так логичнее.
2. Прочитай про метод orElseThrow() и orElse() у Optional, здесь очень хорошо подходит.
3. Старайся использовать более осознанные классы исключений (runtime слишком обобщенно). Я предлагал команде вообще выбрать определенные исключения и оперировать только ими, но меня пока игнорит большинство ))
4. Можно убрать логирование, все это попадет в controller advice. Кстати, Олег написал что уже его добавил, и можно его не писать, проверь в дискорде chatting)

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        likeList.add(newLike);
Ты же с ссылками работаешь - можно было сделать так (если бы ты его сделал через orElse):
post.getLikes().add(like)

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    public final String SECOND_LIKE = "Second like is denied";
Я бы вынес в `@UtilClass`, из ломбока, и положил в пакет на одном уровне с сервисом (school.faang.post_service.util).

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +@RequestMapping("api/v1/likes")
Я видел что так задание написано, но лично мое мнение - условие некорректно, не по REST (@20cognosce поправь если что). Когда ставится/убирается лайк, это должно происходить в контроллере коллекции для которой этот лайк предназначен. Тогда endpoint'ы имеют гораздо больше смысла: post/3/like, comment/11/like, post/6/unlike - и с точки фронтенда это гораздо проще. А контроллер для лайков делает это вся очень нетривиальным, url'ы становятся запутанней. Но ладно, работаем с тем, что есть... 

RequestMapping: /api/v1
addToPost: /posts/:id/like
addToComment:  /comments/:id/like

unlike для соответствующих методов отмены лайка

getLikesForPost: /likes/posts/id - в том случае если будут добавлять лайки по комментарию (как в инсте к примеру), иначе /likes?postId=3 (request param)

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/advice/AdviseController.java
> +@RestControllerAdvice(assignableTypes = {LikeController.class})
Олег уже сделал, после его мержа будет.

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    @GetMapping("/all/{postId}")
/likes?postId=1 (postId в качестве RequestParam). Если вдруг потом и для комментариев будут расширять, то /likes/post/1, /likes/comment/5

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        }
Тоже самое что в друго методе

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    public Like addToComment(Long commentId, Like entity) {
Не стоит называть переменные сущностей entity - можно было toAdd

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    }
Методы валидации лучше в конец класса - так читаемей

2024-09-24 21:20 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        return post.map(value -> value.getLikes().size()).orElse(0);
Вот эту штуку на уровне SQL лучше сделать, это не сложно.

2024-09-25 09:40 UTC, Peregruzochka reviewed
Удоли AdviceController

2024-09-25 09:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/dto/like/LikeDto.java
> +    private LocalDateTime createdAt;
Не совсем понятно зачем нам гонять информацию о том, когда создан like. Тип фронту нет смысла заполнять эту инфу в dto, т.к она будет автоматически создана при добавлении в бд.

2024-09-25 09:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    void deletePostLike(@NonNull @PathVariable Long postId, @RequestParam Long userId) {
Я б назвал: `removeFromPost`, `removeFromComment`
Шоб по аналогии с методами добавления лайков

2024-09-25 09:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    }
Оу ноу
Лучше здесь ничего не мокать
А прописать правильную логику работы твоего сервиса
(взаимодействие с Feign Client)

В нашем случае для тестирования нашего приложения лучше поднять свой мок юзер сервис, который будет возвращать тебе необходимую информацию, которая будет валидна здесь

Либо можно замокать эндпоинты в Postman

2024-09-25 09:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        postRepository.save(post.get());
В тот момент когда ты добавляешь к лайку пост и сохраняешь все в бд, то тебе не нужно после этого добавлять лайк к посту (твой второй save), потому что это cделается автоматически.

2024-09-25 09:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    }
Cначала public методы, потом private методы

2024-09-25 09:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    @Transactional
readOnly = true :)

2024-09-27 19:00 UTC, 20cognosce requested changes

2024-09-27 19:00 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +    @DeleteMapping("/remove/comment/{commentId}")
Не надо в имени пути писать remove, ты итак передаешь http-метод Delete

2024-09-27 19:00 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/LikeController.java
> +@RequestMapping("api/v1")
не просто api/v1
Это контроллер лайков, значит базовый урл для всех его методов должен быть
api/v1/likes
и дальше всё остальное

в пути не должен фигурировать пост, передавай его через квери или в бади

2024-09-27 19:00 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        comment.get().setLikes(likeList);
Можно постоянно не делать comment.get(), а один раз достать уже и дальше работать?

2024-09-27 19:00 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        // Поскольку контроллера для UserService пока нет, создаем заглушку
Добавлять TODO:
иначе следующие поколения так это и не поправят

2024-09-29 08:51 UTC, 20cognosce approved these changes

2024-09-29 08:51 UTC, merged