[Experienced] Система хэштегов к постам BJS2-27037
CorporationX/post_service pull request #826
Opened 2024-09-24 19:54 UTC by sultan-inked

2024-09-25 00:45 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/post/serializable/PostCacheDto.java
> +@ToString
.

2024-09-25 07:20 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/mapper/post/PostMapper.java
>      default List<PostResponseDto> listEntitiesToListDto(List<Post> posts) {
Без реализации разве не отработает? вроде должен

2024-09-25 07:20 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/mapper/post/PostMapperList.java
> +public class PostMapperList {
А это для чего? отдельный класс, чтоб создать лист, используя маппер? а просто в постМаппере метод не сработает?

2024-09-25 07:20 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +        } catch (Exception exception) {
Не знаю, может тут и оправдано. Но на любом собесе, в каждом кросс-ревью про такое надо всегда говорить, что нельзя ловить просто Exception общий. Нужно конкретизировать. Поэтому, у меня от такого глаз дергается)

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +    public List<PostCacheDto> findAllByHashTags(@RequestParam(name = "hash_tag") String hashTag,
Предлагаю PostCacheDto использовать для потрошения спринга, а для возвращения но фронт использовать PostResponseDto. В PostResponseDto добавить недостающие поля из PostCacheDto.

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +            return PONG.equals(pingResponse);
)))

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/model/Post.java
> +    private List<String> hashTags;
Мне идея здесь подсвечивает, что хибернейт не может распарсить json в лист стрингв.
Можно сделать через объект, я так делал
https://github.com/CorporationX/post_service/pull/789/files

А chatGpt пишет, что нужно использовать конвертер
скинул его ответ в личку

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/mapper/post/PostMapperList.java
> +    public List<PostCacheDto> mapToPostCacheDtos(List<Post> posts) {
Это можешь убрать и сделай так:

В PostMapper реализуй
PostCacheDto mapToPostCacheDto(Post post);

А потом следующей строчкой сделай:
`List<PostCacheDto> mapToPostCacheDtos(List<Post> posts);`

Сделай clean build. Mapstruct сам реализует.

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    }
```
    public List<PostCacheDto> findInRangeByHashTag(String hashTag, int start, int end) {
        List<PostCacheDto> postDtos = postCacheService.findInRangeByHashTag(hashTag, start, end);

        if (!postDtos.isEmpty()) {
            return postDtos;
        }

        if (postCacheOperations.isRedisConnected()) {
            String jsonTag = postHashTagService.convertTagToJson(hashTag);
            List<Post> posts = postRepository.findTopByHashTagByDate(jsonTag, numberOfTopInCache);
            List<PostCacheDto> postDtosByTop = postMapperList.mapToPostCacheDtos(posts);
            postCacheService.addListOfPostsToCache(postDtosByTop, hashTag);
            return postDtosByTop.subList(0, Math.min(postDtosByTop.size(), end));
        }

        String jsonTag = postHashTagService.convertTagToJson(hashTag);
        List<Post> posts = postRepository.findInRangeByHashTagByDate(jsonTag, start, end);
        return postMapperList.mapToPostCacheDtos(posts);
    }
```

Вот так можно, но не настаиваю.

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    }
Наверное вынеси в AppConfig
вроде это общая штука, не только для редиса

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/controller/post/RedisExceptionHandler.java
> +
.

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/exception/ErrorResponse.java
> +@JsonInclude(value = JsonInclude.Include.NON_NULL)
сохранил себе

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/exception/redis/RedisErrorMessages.java
> +    public static final String REDIS_TRANSACTION_INTERRUPTED = "Redis transaction interrupted, when trying to save post with id: %s";
до 134 знака ушло
можно перенести

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperationsTries.java
> +
.

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/model/Post.java
> +@Convert(attributeName = "jsonb", converter = JsonBinaryType.class)
А для чего эта штука?

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +
.

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        log.info("Find post with id: {}", id);
очень частая операция
засрем все логи
думаю можно убрать

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +            log.error("Find ids by hash tag in cache failure {}: {}", exception.getClass(), exception.getMessage());
добавь ещё 
by hash tag {}

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +            log.error("Find all post in cache by ids failure {}: {}", exception.getClass(), exception.getMessage());
cache by ids {}
ids.toString() нормально выведится

2024-09-25 23:03 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheService.java
> +public class PostCacheService {
Тут названия методов сбивают с толку.
С английского newPostProcess переводится как новый процесс поста.
deletePostProcess - удалить процесс поста

названия методов должны быть глаголы
можно вот так

executeNewPostProcess - выполнить процесс по созданию новго поста
executeDeletePostProcess - выполнить процесс по удалению поста

2024-09-25 23:03 UTC, amilosh commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/post_V004_post_add_hash_tasg_column.sql
Работает и так, но по докментации ликвибейса должн быть так
post_V004__post_add_hash_tasg_column.sql
то еть после идентификатора - два нижних подчёркивания, а потом название

а в post_V003_resource.sql - просто ошиблись
должно быть так
post_V003__resource.sql

2024-09-25 23:03 UTC, amilosh commented on src/test/java/faang/school/postservice/util/post/PostCacheFabric.java
> +    public static PostCacheDto buildPostCacheDtoForTestMapToPostCacheDto() {
мощь!

2024-09-25 23:03 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/cache/PostCacheServiceTest.java
> +        verify(postCacheOperations, times(NEVER)).addPostToCache(postEmptyTags, postEmptyTags.getHashTags());
Во всех местах:
import static org.mockito.Mockito.never;
verify(postCacheOperations, never()).addPostToCache(postEmptyTags, postEmptyTags.getHashTags());

2024-09-25 23:03 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/cache/PostCacheOperationsTest.java
> +    void testDeletePostOfCacheSuccessfulPrimalTags() {
Я уже ругался то ли  Семёном то ли с Ильёй как тестовые методы называть.
Я раньше тоже вот так слитно писал.
А потом попробовал вот такой подход.
testНазваниеМетода_Результат_ВсякиеУловия
testDeletePostOfCache_Success_PrimalTags
и мне так больше понравился - сразу видно что он тестит

а тут непонятно где название теста заканчивается, какой результат и какие условия - приходится вчитываться
testDeletePostOfCacheSuccessfulPrimalTags

я бы ещё и после test подчёркивание ставил
test_DeletePostOfCache_Success_PrimalTags - вообще чётко видно что тест делает

2024-09-25 23:08 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +        } catch (Exception exception) {
Замечание хорошее. Подниму вопрос на дейли.

2024-09-26 07:30 UTC, sultan-inked commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    }
Ок

2024-09-26 07:40 UTC, sultan-inked commented on src/main/java/faang/school/postservice/exception/ErrorResponse.java
> +@JsonInclude(value = JsonInclude.Include.NON_NULL)
Я у Ивана подсмотрел

2024-09-26 07:40 UTC, sultan-inked commented on src/main/java/faang/school/postservice/exception/redis/RedisErrorMessages.java
> +    public static final String REDIS_TRANSACTION_INTERRUPTED = "Redis transaction interrupted, when trying to save post with id: %s";
ок

2024-09-26 07:47 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        log.info("Find post with id: {}", id);
Да, забыл убрать, я везде ставил что бы отсделить работу, спасибо

2024-09-26 09:07 UTC, sultan-inked commented on src/main/java/faang/school/postservice/model/Post.java
> +@Convert(attributeName = "jsonb", converter = JsonBinaryType.class)
В бд хэш-тэги храняться в формате jsonb, просто json на самом деле со списком хэш тэгов, но отличие от простого чарсета в том, что БД контролирует синтаксис, что бы всегда был как json, и позволяет делать поиск по определнному хэш тэгу, находит все посты с искомым тегом

2024-09-26 09:08 UTC, sultan-inked commented on src/main/java/faang/school/postservice/model/Post.java
> +    private List<String> hashTags;
@Convert(attributeName = "jsonb", converter = JsonBinaryType.class)
@JdbcTypeCode(SqlTypes.JSON)
Позволяют парсить jsonb в список стрингов

2024-09-26 09:08 UTC, sultan-inked commented on src/main/java/faang/school/postservice/model/Post.java
> +    private List<String> hashTags;
У меня все работает

2024-09-26 09:15 UTC, sultan-inked commented on src/main/java/faang/school/postservice/mapper/post/PostMapperList.java
> +    public List<PostCacheDto> mapToPostCacheDtos(List<Post> posts) {
Я сделал отдельный класс, но почему то не парсит, просто нулл ставит в дто, там где должен быть список id:
```java
@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface TestMapping {

    PostCacheDto mapToPostCacheDto(Post post);

    List<PostCacheDto> mapToPostCacheDtos(List<Post> posts);
}
```
Делаю парсинг поста, с заполненными списками, которые надо конвертировать в списки id:
```java
Post post = postRepository.findById(14L).get();
PostCacheDto postCacheDto = testMapping.mapToPostCacheDto(post);
return List.of(postCacheDto);
```
И получаю такой ответ:
```json
{
    "id": 14,
    "content": "Post for testing hiber fetching #java #hibernate #sql #redis",
    "authorId": 1,
    "projectId": null,
    "likesIds": null,
    "commentIds": null,
    "albumIds": null,
    "ad": null,
    "resourceIds": null,
    "published": true,
    "publishedAt": "2024-09-22T02:30:45",
    "scheduledAt": null,
    "deleted": false,
    "createdAt": "2024-09-21T01:07:08",
    "updatedAt": "2024-09-22T02:30:45",
    "hashTags": [
        "java",
        "search",
        "hibernate",
        "sql",
        "redis"
    ]
}
```
А должно быть так, с чем и справляется мой маппер:
```json
{
    "id": 14,
    "content": "Post for testing hiber fetching #java #hibernate #sql #redis",
    "authorId": 1,
    "projectId": null,
    "likesIds": [
        1,
        2
    ],
    "commentIds": [
        1,
        2
    ],
    "albumIds": [
        1
    ],
    "ad": null,
    "resourceIds": [
        1
    ],
    "published": true,
    "publishedAt": "2024-09-22T02:30:45",
    "scheduledAt": null,
    "deleted": false,
    "createdAt": "2024-09-21T01:07:08",
    "updatedAt": "2024-09-22T02:30:45",
    "hashTags": [
        "java",
        "search",
        "hibernate",
        "sql",
        "redis"
    ]
}
```

2024-09-26 09:54 UTC, sultan-inked commented on src/main/java/faang/school/postservice/mapper/post/PostMapperList.java
> +    public List<PostCacheDto> mapToPostCacheDtos(List<Post> posts) {
Убрал в основной маппер

2024-09-26 09:54 UTC, sultan-inked commented on src/main/java/faang/school/postservice/mapper/post/PostMapperList.java
> +public class PostMapperList {
Спасибо, убрал в основной маппер

2024-09-26 09:55 UTC, sultan-inked commented on src/main/java/faang/school/postservice/mapper/post/PostMapper.java
>      default List<PostResponseDto> listEntitiesToListDto(List<Post> posts) {
Оказывается работает, спасибо

2024-09-26 09:56 UTC, sultan-inked commented on src/main/java/faang/school/postservice/controller/post/PostController.java
> +    public List<PostCacheDto> findAllByHashTags(@RequestParam(name = "hash_tag") String hashTag,
Согласен, спасибо, буду обычняй дто возвращать

2024-09-26 10:13 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    }
Да, так лучше, но сейчас оставлю как есть, что бы не тратить время на переделку тестов, учту на будущее спасибо

2024-09-26 10:16 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +        } catch (Exception exception) {
Я просто не понял какие еще исключения может бросить редис помимо RedicConnectionFailure, по этому так сделал, но лечше поменяю на конкретные, спасибо

2024-09-26 10:25 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +        } catch (Exception exception) {
Поменял на конкретный ексепшн

2024-09-26 10:28 UTC, sultan-inked commented on src/test/java/faang/school/postservice/service/post/cache/PostCacheOperationsTest.java
> +    void testDeletePostOfCacheSuccessfulPrimalTags() {
А `@DisplayName` не достаточно что бы было понятно что делает тест? И в стек трейсе он будет отображаться:
```java
@DisplayName("Given post with primal tags and save changes to cache")
```

2024-09-26 10:29 UTC, sultan-inked commented on src/test/java/faang/school/postservice/service/post/cache/PostCacheServiceTest.java
> +        verify(postCacheOperations, times(NEVER)).addPostToCache(postEmptyTags, postEmptyTags.getHashTags());
Спасибо, поменяю, не знал что так можно

2024-09-26 10:32 UTC, sultan-inked commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/post_V004_post_add_hash_tasg_column.sql
Да, точно, слышал об этом, спасибо, поменяют

2024-09-26 10:47 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheService.java
> +public class PostCacheService {
Да, ты прав, изменил

2024-10-04 18:26 UTC, 20cognosce requested changes
Короче в целом ок, но транзакции кривые, не нравится мне их реализация

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        GenericJackson2JsonRedisSerializer serializer = new GenericJackson2JsonRedisSerializer(/*objectMapper*/);
Что за комментарии

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +            WHERE hash_tags @> CAST(:hashTag AS jsonb)
@> Что это за символ, что проверяет условие?

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/hash/tag/PostHashTagService.java
> +public class PostHashTagService {
Ну это не сервис, это парсер / маппер

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/hash/tag/PostHashTagService.java
> +public class PostHashTagService {
Путают названия твоих сервисов связанных с хэштегами и редисом

2024-10-04 18:26 UTC, 20cognosce commented on src/main/resources/application.yaml
> +          multiplier: 2
Тебе точно нужны ретраи?

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +public class RedisConfig {
Где ты тут включил транзакции?

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperationsTries.java
> +    public List<Object> tryToSaveChangesOfPost(PostCacheDto post, String postId, long timestamp, List<String> newTags,
Почему не @Transactional?
ты уверен, что это реально выполняется в транзакции?

У меня сомнения на счет работоспособности этого кода, скинь ссылку, откуда брал

2024-10-04 18:26 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +    public void updatePostOfCache(PostCacheDto post, List<String> primalTags, List<String> updTags) {
Почему тут нет транзакции? Добавляй @Transaction(Mandatory)

2024-10-04 18:30 UTC, 20cognosce commented
Пофикси конфликты и проведи ресерч по транзакциях в редисе, и защити своё решение
https://docs.spring.io/spring-data/redis/reference/redis/transactions.html

Попробуй упростить методы и провести рефакторинг, поменьше try catch

2024-10-06 07:51 UTC, sultan-inked commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +            WHERE hash_tags @> CAST(:hashTag AS jsonb)
Проверят что переданный тэг в формате json содержится в колонке jsonb:
https://www.postgresql.org/docs/9.5/functions-json.html
![Uploading Снимок экрана 2024-10-06 в 12.50.22.png…]()

2024-10-06 08:48 UTC, sultan-inked commented on src/main/resources/application.yaml
> +          multiplier: 2
Если не ретрай, то бесконечный цикл while

2024-10-06 09:07 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperationsTries.java
> +    public List<Object> tryToSaveChangesOfPost(PostCacheDto post, String postId, long timestamp, List<String> newTags,
Ты сам скинул ссылку с таким решением: 
https://github.com/CorporationX/post_service/pull/826#issuecomment-2394342717
Или я снова не правльно понял (
Там тоже транзакция открывается с multi и exec для выполнения, discard если во время транзакции было изменение по отслеживаемым ключам, и ретрай делает новую попытку, все завернуто в сессию при помощи:
```java
redisTemplatePost.execute(new SessionCallback<>() {
```
, что тоже есть в статье по ссылке.
Отслеживание файлов выполняется в вызывающем классе, ретрай добавил что бы избавиться от цикла `while`, сам метод с ретраем пришлось вынести в другой класс, потому что ретрай не работает в том же классе где вызывается.

2024-10-10 15:17 UTC, sultan-inked commented on src/main/resources/application.yaml
> +          multiplier: 2
Убрал ретраи

2024-10-10 15:18 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperationsTries.java
> +    public List<Object> tryToSaveChangesOfPost(PostCacheDto post, String postId, long timestamp, List<String> newTags,
Все переделал, добавил поддержку аннотаци транзакций редиса

2024-10-10 15:18 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheOperations.java
> +    public void updatePostOfCache(PostCacheDto post, List<String> primalTags, List<String> updTags) {
Добавил везде

2024-10-10 15:23 UTC, sultan-inked commented
Полностью изменил редис транзакции, включил поддержку аннотаций.
Теперь, так как посты в кеш хранятся всегда, все изменения в БД в одной транзакции с изменениями в кэш, что бы данные были одинаковые.
Транзакции редиса работаю, проверил, если в процессе сохранения в кэш вылетает исключение то все изменения отменяются.

2024-10-10 15:23 UTC, sultan-inked commented
Так гораздо лучше стало, спасибо!

2024-10-10 22:14 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheProcessExecutor.java
> +    }
Пришлось добавление списком, по новому тэгу которого нет в кэш, запускать асинхронно, иначе не работает транзакция редиса, потому что вызывающий метод `readOnly`, если даже, редис транзакцию, помечаю как `Propagation.REQUIRES_NEW`, не работает, только так, но с другой стороны лучше, клиенту не надо ждать пока произойдет сохранение в кеш, и если даже будет ошибка записи, то ничего плохого не произойдет, запишеться при следующем запросе по тэгу

2024-10-10 22:23 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheProcessExecutor.java
> +    }
Все методы, по обновлению постов, в одной транзакции, для обеспесения консистентности БД и кеш. Проверял, работает, если при сохранении в кеш бросить исключение, то и в БД ничего не записывается

2024-10-10 22:26 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/cache/PostCacheService.java
> +    }
Все методы с `redisTemplatePost.hasKey()` не работают внутри активной транзакции, потому что все команды выполняются списком только в конце, и надо открывать новую транзакцию с `reeadOnly`, иначе не работает

2024-10-11 15:50 UTC, 20cognosce requested changes
Мини правки внеси пожалуйста

2024-10-11 15:50 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/ApplicationConfig.java
> +    @Bean
Имя дай ему

2024-10-11 15:50 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        return template;
А смысл если в рантайме типы дженериков итак стираются
Оставь только Object, к String итак это Object

2024-10-11 15:50 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        return template;
Еще один
реально, смысл? Если очень надо - приватный билдер тут сделай и убери дублирование кода

2024-10-11 15:50 UTC, 20cognosce commented on src/main/java/faang/school/postservice/mapper/post/PostMapper.java
> +//    PostResponseDto toDto(Post post);
Убрать комментарии

2024-10-11 15:50 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +//    @Value("${post.spelling-corrector.batch-size}")
?)

2024-10-11 18:10 UTC, sultan-inked commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        return template;
Сдела приватный

2024-10-11 18:11 UTC, sultan-inked commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +//    @Value("${post.spelling-corrector.batch-size}")
Семен вроде должен был исправить, а то не собирается проект

2024-10-11 18:16 UTC, sultan-inked commented on src/main/java/faang/school/postservice/config/ApplicationConfig.java
> +    @Bean
Вот так имя дать?
```java
@Qualifier("javaTimeModuleObjectMapper")
@Bean
public ObjectMapper javaTimeModuleObjectMapper() {
    ObjectMapper mapper = new ObjectMapper();
    mapper.registerModule(new JavaTimeModule());
    return mapper;
}
```

2024-10-13 19:11 UTC, 20cognosce approved these changes

2024-10-13 19:11 UTC, merged