v1 task: Система комментариев
CorporationX/post_service pull request #838
Opened 2024-09-25 12:46 UTC by Varrankin

2024-09-25 19:19 UTC, Silencemess1ah reviewed
Допилить что не допилено обратить внимание на мелкие помарки + тесты

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    CommentService commentService;
private

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +}
Я бы чуть по другому сделал урлы
/v1/posts/comments/{id} для пост , гет, делит
и /v1/posts/comments для всех комментов 
тобишь выносишь /v1/posts/comments наверх.  для post /{id} ,  put /{id} , delete /{id},  get как над классом

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +public class CommentDto {
конструктор

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    public CommentDto updateComment(@PathVariable long postId, CommentDto commentDto) {
requestBody

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +            throw new DataValidationException("The content contains more than 4096 characters or the content is empty");
пишешь в ошибке Or (или) а ставишь логическое И , && -> ||

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +        postRepository.findById(postId).orElseThrow(() -> new DataValidationException("Post is null"));
Сходил получил юзера а дальше?  Видимо там ловишь ошибку что его нет,
тебе не нужно чтобы валидатор отвечал за такое, скорее нужен метод в сервисе который использует сервис userServiceClient сходит туда и что то вернет, а ты это вставишь уже в валидатор и скажешь да \ нет 
так же у тебя коммент валидатор идет в postRepository,  нужно следующим образом, к CommentService прикручиваешь PostService -> он уже идет в свой репо вытаскивает что надо и отдает комментСервису, дальше в валидатор\используешь

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +        }
Также у комментария есть дата создания. (с) Чисто мое предположение, что просто это поле есть в дто и оно смапиться с энтити, база сама выставит когда коммент создался

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +                new DataValidationException("AuthorId is null"));
Выше писал, через Коммент сервис, идешь в постСервис дергаешь репо получаешь возврашаешь, + дублируешь второй раз поиск автора, как раз один метод из сервиса как перепишешь дернешь, и вроде как findById кидаешь EntityNotFoundException()

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +                new DataValidationException("Comment is null"));
Метод в сервисе дальше сюда на проверку не валидатором в репозиторий

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +                comment.getUpdatedAt() != commentDto.getCreatedAt() &&
comment.getCreatedAt()

2024-09-25 19:19 UTC, Silencemess1ah commented on src/test/java/faang/school/postservice/mapper/CommentMapperTest.java
> +                .updatedAt(LocalDateTime.of(2024, 9, 25, 11, 32))
выноси в константы айДи контенты и тд

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
Комментарий относиться к посту(с)  у тебя в дто нет поста, когда смапил из дто в энтите там null лежит в месте поста и ты его сохраняешь. то что в валидаторе делал надо это вернуть здесь и засетить комменту, после сохранить,  "  Затем CommentService превращает CommentDto в сущность Comment, проставляет этой сущности связь с сущностями Post и сохраняет в БД с помощью CommentRepository. " вот даже в задаче пишут

2024-09-25 19:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
тоже самое приходит дто без поля пост, ты его мапишь и в поле не кладешь Post, 
Если пользователь допустил ошибку в тексте комментария, то он может изменить его. Все остальные данные изменить нельзя, и это важная проверка для бэкенда. (с)  я думаю подход может быть таким, так как проверка полная придеться видимо допиливать полное дто (с айди проекта, лайками и  проч если есть еще поля которые не добавлял выше) получаешь его, и проверяешь что все поля сходяться кроме контента ну и updatedAt видимо тоже не трогаешь так как оно перезапишет все равно, если все сходиться а контент разный пропускаем, но это решение в лоб как вот с первых секунд мне пришло в голову может есть более оптимальные решения

2024-09-26 09:01 UTC, Varrankin commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +}
в get тоже надо  передавать postId и мне не нравиться то что это немного не очевидно кода мы   
 пишем comments/{id} где id это id поста а не комментария, а так "/v1/post/{postId}/comment/{commentId}" понятно что мы обращаемся к посту с id таким то и к комментирую с id таким то

2024-09-26 09:02 UTC, Varrankin commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +}
и еще posts тоже думаю не корректно, потому что мы всегда обращаемся к одному посту а не множеству

2024-09-26 10:51 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +    }
согласен, пропустил этот момент

2024-09-26 13:07 UTC, Varrankin commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +        }
тоже так думаю, но если пишут "Также у комментария есть дата создания. (с) " наверное имеют в виду что на стороне фронта эта дата проставляется. А может и нет и надо убрать это проверку. Пока оставлю, если что на ревю оправят .

2024-09-26 13:31 UTC, Varrankin commented on src/main/java/faang/school/postservice/validator/CommentValidator.java
> +        postRepository.findById(postId).orElseThrow(() -> new DataValidationException("Post is null"));
ты как всегда прав, переделаю

2024-09-26 19:17 UTC, mysosnovskaya requested changes

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    private CommentService commentService;
final?

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    public List<CommentDto> getAllComment(@PathVariable long postId) {
getAllComments (в конце нужна s, т.к. множественно число). В методе сервиса тоже так

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +//    private List<Long> likes;
Если не нужно, то удали

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/mapper/CommentMapper.java
> +//    @Mapping(target = "likes", ignore = true)
Комментарии нужно либо удалить, либо раскомментировать

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentValidator.checkGetCreatedAtForZero(commentDto);
Вообще время создания не должно приходить с фронта. Это может проставить только бэк. Поэтому верно, что createdAt должно быть null в реквесте (а даже если не null, то можно затереть его верным значением)

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        log.info("[{}] Comment successfully saved to DB with ID: {}", "createComment", comment.getId());
Классно логи пишешь 👍

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        Comment OldComment = commentRepository.findById(commentDto.getId()).orElseThrow(() ->
Названия переменных всегда начинаются с маленькой буквы

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    @PutMapping
commentId должен быть в пути

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentRepository.deleteById(commentId);
Тут бы тоже лог добавить)

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +public class CommentService {
На этот класс не хватает тестов

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment = commentRepository.save(comment);
Кажется, ты забыл учесть, что если в commentDto будет заполнено поле id, то здесь будет происходить не создание нового объекта, а обновление (метод save так работает, что если ему передать объект с проставленным id, то это будет обновление объекта по этому id). А это очень опасная ошибка, воспользовавшись которой злоумышленники могут перезатереть нам всю базу своими данными.

2024-09-26 19:17 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +public class CommentDto {
Мне не нравится идея использовать один общий dto на все реквесты и респонсы. Это неудобно и с точки зрения чтения кода, и с точки зрения документирования кода через сваггер, и с точки зрения разработки:
1. Когда я, как сторонний разработчик, читаю твой код, то я вижу, что в реквесте на создания есть поля id, createdAt и updatedAt, которых явно быть не должно. В такой простой ситуации я понимаю, что скорее всего эти поля не будут учитываться, но в более сложной ситуации этого можно и не понять и запутаться.
2. Из-за того, что ты, как разработчик этого кода, думаешь, что в реквесте могут прийти createdAt и updatedAt, ты пишешь лишнюю проверку в коде на это в update метода (хотя на updatedAt эта проверка не нужна). Это ещё ладно. Но вот ты забыл проверить, что в переданном на создание объекте id == null и это привело к критической ошибке (см. мой комментарий в CommentService). И опять повторюсь: это ещё простая ситуация.
3. Ну и про документацию в сваггер. Я не знаю, делал ли у вас кто-то эту задачу и показывал ли её вам, но кратко расскажу: сваггер делает красивую интерактивную документацию всех имеющихся в сервисе эндпоинтов на основе кода. В том числе он расписывает, какие реквесты с какими полями ожидает каждый эндпоинт и какие респонсы возвращает. Этой документацией могут пользоваться фронтенд разработчики, тестировщики, бэкенд разработчики из других команд, если захотят сделать интеграцию с ними. И все их мы будем вводить в заблуждение тем, что в create эндпоинте принимаем на вход вот такой вот объект - с id, createdAt, updatedAt полями. И повторюсь ещё раз: у нас ещё простая ситуация, где по здравому смыслу можно догадаться, что эти поля посылать не нужно. А часто бывает, что здравый смысл не помогает.

Закину этот комментарий к нам в общий чат. Нужно договориться о едином подходе и я очень рекомендую использовать разные dto-классы. В твоем случае их будет три: CreateCommentRequest, UpdateCommentRequest и CommentDto (для респонса)

2024-09-27 08:44 UTC, Varrankin commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    @PutMapping
не совсем понимаю зачем? ты имеешь в виду в методах createComment или updateComment? в createComment у нас в нет id потому что он в бд генерится, а на счет  updateComment думаешь луче передавать в пути? и из ДТО убрать id? почему так лучше в данной ситуации?

2024-09-27 10:10 UTC, Varrankin commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +//    private List<Long> likes;
да, хорошо) просто оставил, думал вдруг ОС придет что, что-то с лайками надо будет делать и я бы просто расскомитил и все

2024-09-27 10:11 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +public class CommentService {
да, как с логикой все ок будет, покрою все тестами

2024-09-27 10:17 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentValidator.checkGetCreatedAtForZero(commentDto);
согласен, меня просто видимо спутали условия: 

Комментарий можно создать. Он не может быть пустым и длиннее 4096 символов. У него обязательно должен быть автор — существующий пользователь. Комментарий обязательно должен относиться к посту. Также у комментария есть дата создания.

подумал что в последнем требовании иметься в виду что оно должно быть обязательно. В общем уберу проверку на null

2024-09-27 10:24 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment = commentRepository.save(comment);
Тут не совсем тебя понял, мы же как раз здесь обновляем а не создаем? и как  злоумышленники могут перезатереть нам всю базу своими данными в данном случае?

2024-09-27 10:25 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        log.info("[{}] Comment successfully saved to DB with ID: {}", "createComment", comment.getId());
спасибо) а то что логи в некоторых местах одинаковые и idea подсвечивает их  это ок? 
![image](https://github.com/user-attachments/assets/beac8170-250c-4dab-81df-e75a675bf08d)

2024-09-27 10:25 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        Comment OldComment = commentRepository.findById(commentDto.getId()).orElseThrow(() ->
знаю) не заметил

2024-09-27 10:44 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentRepository.deleteById(commentId);
Добавил) вопрос возник, нужно ли сейчас писать логи на CommentValidator ? там я выбрасываю исключения, например throw new DataValidationException("immutable data has been changed"); нужно ли это логировать или в общем обработчике исключений это сделать надо?

2024-09-27 10:48 UTC, Varrankin commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +public class CommentDto {
согласен с тобой) исправлю

2024-09-27 15:20 UTC, Varrankin commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +public class CommentDto {
у меня возникли вопросы пока работал с несколькими ДТО: 

1. Нужно ли проверять ДТО которое отдаем в ответе? или проверки все на стороне бд осуществляются и мы уверены что нам придут из бд нужные данные? 
2. как  валидировать примитивные типы? Например у наст есть поле Age типа long, и нам его каким то образом не прислали в JSON при запросе, но проверки на null у нас нет потому что это примитив 
3. как проверить что объект не null с помощью нотации? т.е заменить проверку         if(UpdateCommentRequest == null) {
            throw new DataValidationException("The UpdateCommentRequest is null");
        }

2024-09-27 20:25 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        log.info("[{}] Comment successfully saved to DB with ID: {}", "createComment", comment.getId());
Да, не страшно)

2024-09-27 20:27 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    @PutMapping
Я только про PUT писала, для создания, конечно, не нужно) Так правильно с точки зрения корректного проектирования rest api. Мы всегда обращаемся к какому-то ресурсу и если это какой-то один уже созданный ресурс, то передаем его id в пути. Такие правила проектирования =)

2024-09-27 20:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    @PutMapping("/commentId")
Не хватает фигурных скобок) Так это не PathVariable

2024-09-27 20:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        commentRepository.deleteById(commentId);
Не нужно, ты правильно пишешь - это делается в общем обработчике исключений

2024-09-27 20:37 UTC, mysosnovskaya requested changes
Я на часть твоих комментариев ответила без режима "ревью", пройди по всем вчерашним комментариям, пожалуйста, и посмотри)

2024-09-27 20:37 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment = commentRepository.save(comment);
Это метод "createComment", почему обновляем?
Злоумышленник присылает id = 5, content = "*какой-то злоумышленный контент"".
Ты в метод save передаешь эту информацию, он находит в базе данных комментарий с id = 5 и обновляет его на этот контент из реквеста вместо того, чтобы создать новый. Злоумышленник потом присылает то же самое но с id = 6, потом 7, 8 и так далее. 
Это особенности работы метода save. Если в него передать объект с заполненным id (а у тебя как раз такая ситуация, т.к. маппер берет id из dto и перекладывает его в Comment), то он будет обновлять комментарий с этим id. 
Если ещё остались вопросы - тэгни меня в чате в дискорде, обсудим) Чтобы не ждать до следующего ревью

2024-09-27 20:37 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentDto.java
> +public class CommentDto {
1. Доверяем БД, дополнительно проверять ничего не нужно
2. Переделать его в Long =) Иначе никак, тебе будет 0 приходить, когда его в json нет. Здесь лучше ссылочный тип подойдет
3. Когда ты ставишь аннотацию RequestBody, то она гарантирует, что реквест будет не null (у нее по умолчанию стоит required = true, т.е. тело нужно обязательно)

2024-09-29 12:41 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment = commentRepository.save(comment);
спасибо, я все понял и все исправил уж в данном коммите)

2024-10-02 17:09 UTC, Varrankin commented
@mysosnovskaya Привет) написал тесты, можешь уделить им особое внимание, а то у нас раньше тесты не особо проверяли, хочу понять, вообще норм пишу

2024-10-02 18:54 UTC, mysosnovskaya requested changes
Всё хорошо у тебя с тестами =)

2024-10-02 18:54 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/comment/CommentController.java
> +    @PutMapping("/commentId")
` @PutMapping("/{commentId}")` (фигурные скобки нужны)

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/mapper/CommentMapperTest.java
> +        assertEquals(comment.getAuthorId(), createCommentRequest.getAuthorId());
Можно проверить, что другие поля (например, id) равны null

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    private final long commentId = 1L;
Это всё похоже на константы, поэтому статик и ТАКИЕ_НАЗВАНИЯ

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());
А эта проверка зачем? Можно assertDoesNotThrow сделать)

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        post = mock(Post.class);
А зачем мок? В целом это не ошибка, но и мок здесь не оправдан. Можно просто пустой Post создать через конструктор без параметров

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +        void testCreateCommentWhenUserServiceClientReturnException() {
Такие тесты не особо имеют смысл, конечно) Но пусть будут, тоже не ошибка. Вот testGetAllCommentsWhenListIsEmpty хороший тест, в нем есть смысл

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +        comment = Comment.builder()
Дублирование с созданием commentForDB. Лучше вынести это в отдельный приватный метод

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +        commentDto2 = CommentDto.builder()
Создание CommentDto тоже лучше вынести в приватный метод, а разные параметры (id, даты) - добавить в параметры метода

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +            assertNotNull(commentForDto.getPost());
Лучше эту проверку вниз перенести, ко всем assert

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +            commentService.deleteComment(commentId);
assertDoesNotThrow

2024-10-02 18:54 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    @Mock
Лучше Spy, тогда не придется его в when...thenReturn писать

2024-10-03 10:23 UTC, Varrankin commented on src/test/java/faang/school/postservice/mapper/CommentMapperTest.java
> +        assertEquals(comment.getAuthorId(), createCommentRequest.getAuthorId());
а как проверить id? просто он long и не может быть null, посмотрел что что возвращает маппер, он возвращает в таком случае 0 в id, проверить что id = 0? имеет ли смысл данная проверка?

2024-10-03 10:45 UTC, Varrankin commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    @Mock
тут не совсем понял, ты имеешь в виду перевести моки в Spy? просто как я понимаю, spy создает реальный объект шпион, т.е если мы сделаем их spy и будем вызвать реальные методы репозиториев, то во первых скорей всего тест упадет потому что проект не запущен и нет связи с БД, во вторых мы образуем зависимость теста от другого компонента, что нарушает принцип first. Я пока не разу не встретил ситуации где бы мне пригодился spy, потому что он так или иначе будет зависимость от spy объектов, видимо это нужно в каких то ситуациях или я чего то не понимаю.

2024-10-03 12:56 UTC, Varrankin commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +        void testCreateCommentWhenUserServiceClientReturnException() {
а почему не имеет смысла? как нам проверить что при определенных условиях выбрасываются нужные нам исключения?

2024-10-03 12:57 UTC, Varrankin commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        post = mock(Post.class);
согласен)

2024-10-03 13:12 UTC, Varrankin commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());
я здесь закладывал, чтоб проверить валидацию на корректность, исключение оно может и не выбросить, но и не факт что валидация прошла корректно

2024-10-03 14:53 UTC, Varrankin commented
Исправил тесты, написал тесты на аннотации в ДТО и попробовал написать Параметризованные тесты, но что то пошло не так, вылетает ошибка, что тип нет какого то класса или зависимости, проверял, вроде бы все ок, в общем я его замокал, если не трудно можешь подсказать что делаю не так.

2024-10-03 19:34 UTC, mysosnovskaya requested changes

2024-10-03 19:34 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/mapper/CommentMapperTest.java
> +        assertEquals(comment.getAuthorId(), createCommentRequest.getAuthorId());
А, там примитив. Странно, вообще Long должен быть. Давай в модели Long сделаем и добавим проверку. Потому что с long это некорректно

2024-10-03 19:34 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());
Не поняла, это как?) У тебя входные данные должны гарантировать, что id у comment и updateCommentRequest одинаковые. Тестом мы проверяем работу метода checkingForCompliance, а не то, как ты тесты пишешь =)

2024-10-03 19:34 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +        void testCreateCommentWhenUserServiceClientReturnException() {
java так работает, что если вызываемый метод выкинул какое-то исключение, то вызвавший метод это исключение тоже получит и пробросит дальше, если там нет обработчика. Ты хотел проверить, что FeignException никак не обрабатывается в createComment? Тогда я могу тебе много исключений придумать, которые тоже нужно проверить (NullPointerException, IllegalArgumentException, RuntimeException...). Ты всё равно все возможные исключения не проверишь.
В целом я твою идею понимаю, но такое лучше тестировать не юнит тестами, а интеграционными. Их мы будем проходить позже)

2024-10-03 19:34 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    @Mock
Я писала только про маппер. Для репозиториев, конечно, нет) А с маппером как раз будет хорошо, т.к. тебе не придется делать маппинг самостоятельно руками в тестах

2024-10-03 19:34 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/dto/comment/UpdateCommentRequestTest.java
> +/*   не понимаю почему не работает, можешь подсказать что не так делаю?
А ты пробовал искать по этой ошибке в гугле?)
https://stackoverflow.com/questions/57040675/java-lang-noclassdeffounderror-org-junit-platform-commons-preconditionviolation
Проблема с версиями junit-jupiter библиотек. Тут можно по-разному решать, но самое простое - это проставить всем junit-juptier зависимостям одинаковую (свежую) версию.

2024-10-04 10:30 UTC, Varrankin commented on src/test/java/faang/school/postservice/mapper/CommentMapperTest.java
> +        assertEquals(comment.getAuthorId(), createCommentRequest.getAuthorId());
я в принципе могу, но приметив у нас установлен именно в entity комментария и он по логике не может быть null и создавал его не я, об был в базовой конфигурации сервиса, ты уверена что стоит это делать? 

и почему тебе не нравиться такая проверка? 

assertEquals(comment.getId(), 0);

или если у нас априори id не может быть 0, то может и проверять не стоит

2024-10-04 10:33 UTC, Varrankin commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    @Mock
ааа, я понял) я так раньше делал, но точно не помню, но как будто мне кто то сказал что так не стоит, потому что мы зависим от работы маппера и если он не корректно работает, например в него внесут изменения то и тесты с ним у нас все упадут. Но мне нравиться такая идея

2024-10-04 10:34 UTC, Varrankin commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    @Mock
я тогда оставлю пока так? просто это вроде бы не ошибка, но в следующий раз я не буду мокать маппер и буду его использовать в тестах

2024-10-04 10:51 UTC, Varrankin commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +        void testCreateCommentWhenUserServiceClientReturnException() {
Хорошо, спасибо, лишние тесты удалил) И я правильно понял что testGetAllCommentsWhenListIsEmpty хороший тест, потому что мы проверяем условия при которых мы должны получить такое-то исключение, а других мы вообще ничего не проверяем, с сам решил что будет выбрасываться такое то исключение и проверяю что оно было выброшено

2024-10-04 10:56 UTC, Varrankin commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());
хах, ну да)

2024-10-04 11:10 UTC, Varrankin commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());
хотя, смотри, у нас есть метод  checkingForCompliance в нем есть условие валидации которое должно гарантировать  что id у comment и updateCommentRequest одинаковые, мы просто проверяем что не должно быть выброшено исключений. Я сам знаю что  условие валидации правильное, но предполагаю что оно может работать не корректно, и я стараюсь заложить логику проверки что значит  работать корректно, а корректно тогда, когда id у comment и updateCommentRequest одинаковые  чем и тестирую данной проверкой assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());. Возможно в данном тете это избыточно, но например при каких то сложных условиях может быть такое, что оно работает не совсем так как мы планировали и условие проходит и исключение не выбрасывается но мы и получаем не то что хотели, поэтому я проверял условия что они дают мне именно тот результат который я ожидаю. Пожалуйста, поправь меня если я ошибаюсь

2024-10-04 11:55 UTC, Varrankin commented on src/test/java/faang/school/postservice/dto/comment/UpdateCommentRequestTest.java
> +/*   не понимаю почему не работает, можешь подсказать что не так делаю?
да смотрел, я понял что он почему то ругается на @ValueSource, потому что если ее меняешь на другую, все запускается. Пробовал добавлять    testImplementation ("org.junit.jupiter:junit-jupiter-engine:5.8.2") тесты вообще перестали запускаться

2024-10-04 12:02 UTC, Varrankin commented on src/test/java/faang/school/postservice/dto/comment/UpdateCommentRequestTest.java
> +/*   не понимаю почему не работает, можешь подсказать что не так делаю?
yessss, 

изменил версии 

    testImplementation("org.junit.jupiter:junit-jupiter-api:5.9.2")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.9.2")
    
    и полетело

2024-10-04 12:04 UTC, Varrankin commented on src/test/java/faang/school/postservice/dto/comment/UpdateCommentRequestTest.java
> +/*   не понимаю почему не работает, можешь подсказать что не так делаю?
но этот тест удалил, но все равно был так, для примера

2024-10-04 14:31 UTC, Varrankin commented on src/main/java/faang/school/postservice/service/CommentService.java
> +        comment = commentRepository.save(comment);
тут еще возник вопрос, а что мешает злоумышленникам, воспользоваться методом put и так же затирать данные?

2024-10-04 19:48 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/CommentServiceTest.java
> +    @Mock
Договорились

2024-10-04 19:48 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/mapper/CommentMapperTest.java
> +        assertEquals(comment.getAuthorId(), createCommentRequest.getAuthorId());
Ладно, давай код, написанный до нас, менять не будем. 
Тогда с этой проверкой всё ок. Просто обычно лучше разграничить ситуации, когда пользователь вообще ничего не передал (null) и когда пользователь передал значение (0). В идеале маппер должен сохранить это (null или 0), это разные ситуации. Но у нас из-за примитива это одно и то же) Пусть остается так

2024-10-04 19:48 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/validator/CommentValidatorTest.java
> +        assertEquals(comment.getAuthorId(), updateCommentRequest.getAuthorId());
Я поняла, ты хочешь проверить, что этот метод не изменил твои данные? Т.е. ты в тесте предварительно создал два объекта с одинаковыми id и ты в этом уверен, но вдруг внутри метода эти данные как-то изменятся и исключения не будет, но и метод неправильно отработает? Такая логика? Если да, то это перебор =) Так много каких ситуаций придумать можно) 
Мы тестируем два варианта только: передали объекты с разными id - получили исключение. Передали объекты с одинаковыми id - всё отработало успешно (без исключений). Соответственно пользуемся assertThrow и assertDoesNotThrow, больше ничего не нужно усложнять)

2024-10-04 19:48 UTC, mysosnovskaya approved these changes
Исправь конфликт и можешь сам смержить и закрыть задачу)

2024-10-10 16:17 UTC, merged