BJS2-27060 Upload images to Post
CorporationX/post_service pull request #846
Opened 2024-09-25 21:01 UTC by amilosh

2024-09-26 12:45 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return resourceRepository.save(resource);
Тут результат метода - инсерт в бд, а в вызывающем методе в цикле на каждый файл вызывается этот метод, можно собрать все файлы в коллекцию и отправить их пачкой в бд за один раз

2024-09-26 12:45 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        resources.forEach(this::deleteImageFromPost);
Точно так же, можно пачкой удалить

2024-09-26 12:45 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +@Service
Мне Дима говорил, что аннотация сервис главнее и она должна быть первой над классом

2024-09-26 18:46 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        return resourceRepository.save(resource);
Переделал

2024-09-26 18:47 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        resources.forEach(this::deleteImageFromPost);
Переделал

2024-09-26 18:47 UTC, amilosh commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +@Service
Сделал

2024-09-29 09:18 UTC, 20cognosce requested changes

2024-09-29 09:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public ResponseEntity<byte[]> downloadImage(@PathVariable Long resourceId) {
Почему байтами отдаёте, а не мультипартом?

2024-09-29 09:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +            ByteArrayOutputStream bytesFromResizedImage = ImageProcessingUtils.getByteArrayOutputStream(resizedBufferedImage, contentType);
Ты закрыл поток? Возможна утечка памяти

2024-09-29 09:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +    public Resource uploadFile(MultipartFile file, String folder, ImageRestrictionRule rule) throws IOException {
Чего такой адски длинный метод? Декомпозировать

2024-09-29 09:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void validateImagesToUpload(Long postId, List<MultipartFile> images) {
Можно проверки вынести в отдельный класс

2024-09-29 09:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    private void validateImagesToUpload(Long postId, List<MultipartFile> images) {
Приватный метод выше публичных у тебя, надо наоборот

2024-09-29 09:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            return inputStream.readAllBytes();
Где закрытие потока?

2024-09-29 09:18 UTC, 20cognosce commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
>  public class PostServiceTest {
Маловато тестов

2024-09-29 09:18 UTC, 20cognosce commented on build.gradle.kts
> +    implementation("org.apache.commons:commons-collections4:4.4")
Обязательно проект тянуть кучу левых либ?

2024-10-02 16:32 UTC, amilosh commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +            ByteArrayOutputStream bytesFromResizedImage = ImageProcessingUtils.getByteArrayOutputStream(resizedBufferedImage, contentType);
В самом классе написано, что 
Closing a ByteArrayOutputStream has no effect. 
Или всё равно лучше трай с ресурсами использовать?

2024-10-03 16:11 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +            ByteArrayOutputStream bytesFromResizedImage = ImageProcessingUtils.getByteArrayOutputStream(resizedBufferedImage, contentType);
Что можно закрыть - лучше закрыть

2024-10-03 16:14 UTC, 20cognosce approved these changes

2024-10-03 16:14 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/aws/s3/S3ServiceImpl.java
> +        PutObjectRequest putObjectRequest = new PutObjectRequest(bucketName, key, new ByteArrayInputStream(imageData.getContent()), objectMetadata);
Закрывай потоки...

2024-10-03 16:14 UTC, merged