BJS2-27044 Add album visibility
CorporationX/post_service pull request #858
Opened 2024-09-27 17:30 UTC by amilosh

2024-09-29 15:55 UTC, 20cognosce requested changes

2024-09-29 15:55 UTC, 20cognosce commented on src/main/java/faang/school/postservice/mapper/album/AlbumMapper.java
> +            return null;
Почему не пустой список

2024-09-29 15:55 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/album/Album.java
> +    private AlbumChosenUsers chosenUsers;
Не согласен с таким форматом хранения.
Если у тебя пользователь удаляется / блокируется / еще что-то, как мы связываем этот список с таблицей пользователей.

Никак, тут будет просто неактуальные айдишники лежать

2024-09-29 15:55 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/album/AlbumService.java
> +            album.setChosenUsers(albumChosenUsers);
Ты даже поиска в БД о наличии таких пользователей не выполняешь?

2024-09-29 15:55 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V004__add_columns_to_table_album.sql
> +    ADD COLUMN chosen_users JSONB;
Нет, мне это совсем не нравится
Делай нормальную связующую таблицу с констрейнтами

2024-10-02 21:48 UTC, amilosh commented
post_V004 - проверил
если юзера на будет в users, то нельзя сохранить альбом
и если юзера удалить, то удаляется запись из album_chosen_users

post_V005 и post_V006 - сделал чтобы работало как в post_V004
но плюс если юзер становится active = false

2024-10-03 15:31 UTC, 20cognosce requested changes

2024-10-03 15:31 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V004__add_columns_to_table_album.sql
> +    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
Окей, я надеюсь ты это протестил

2024-10-03 15:31 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V005__add_trigger_check_user_active.sql
> +    FOR EACH ROW
Удалить это

Зачем ты создал целый триггер на уровне базы, чтобы проверить, что пользователь, которого добавляют в альбом активный?

2024-10-03 15:31 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V006__add_trigger_user_became_inactive.sql
> +    EXECUTE FUNCTION delete_album_chosen_users_if_user_became_inactive();
Нет, никакой логики в базе
Делай это всё на уровне приложения

2024-10-03 15:31 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V006__add_trigger_user_became_inactive.sql
> +    EXECUTE FUNCTION delete_album_chosen_users_if_user_became_inactive();
Если не можешь без костылей базу опросить - делай тогда интеграцию по ресту с user_service

2024-10-03 15:31 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V006__add_trigger_user_became_inactive.sql
> +    EXECUTE FUNCTION delete_album_chosen_users_if_user_became_inactive();
Логику на уровне базы невозможно поддерживать, но неё нет тестов, это размазывание ответственности между прикладным сервисом и хранилищем данных

Нужно весомое обоснование чтобы триггеры / функции / процедуры в БД заводить

2024-10-04 18:57 UTC, 20cognosce approved these changes

2024-10-04 18:57 UTC, merged