Добавление картинок к посту 26871
CorporationX/post_service pull request #867
Opened 2024-09-29 14:29 UTC by Peregruzochka

В таске было задание:
_При загрузке если разрешение выше при горизонтальном изображении — 1080×566 пикселей, квадратном — 1080×1080 пикселей, то картинка должна ужиматься. Количество*:* до 10 картинок в одном посте._

Я реализовал это по другому, потому что не хочу ломать соотношение сторон у горизонтальных/вертикальных изображений:
_Перед сохранением оно должно ужиматься так, чтобы самая большая сторона была не более 1080 px_

2024-09-30 06:49 UTC, mrkorolev reviewed
Вкуснота)

2024-09-30 06:49 UTC, mrkorolev commented on build.gradle.kts
> +    implementation("com.amazonaws:aws-java-sdk-s3:1.12.481")
В post-service не было по дефолту aws-sdk? Странно

2024-09-30 06:49 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public ResourceDto addFileToPost(@RequestParam("file") MultipartFile file,
Ты же в postman переменную называешь file? Тогда не нужно в request param в скобках писать то же самое - это делают в том случае, если имена переменных отличаются

2024-09-30 06:49 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/s3/S3AudioService.java
> +public class S3AudioService {
К предъяве о путанице между Minio и S3 - я бы просто сервисы переименовал и все, не вижу смысла переписывать с новой либой. MinioAudioService

2024-09-30 06:49 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/s3/S3AudioService.java
> +        s3client.deleteObject(bucketName, key);
Погоди, а почему нельзя сохранить файл по тому же самому ключу (перезапись)? Или я чего то не понимаю?

2024-09-30 06:49 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/s3/S3VideoService.java
> +public class S3VideoService {
Весь файл практически идентичен S3AudioService. Есть конечно отличия с S3ImageService, Но и там (в основном) тоже самое - мб как то можно это обобщить (а может и нет:)

2024-09-30 06:49 UTC, mrkorolev commented on src/main/java/faang/school/postservice/repository/ResourceRepository.java
> +import org.springframework.data.repository.CrudRepository;
Забыл убрать наверно - когда жмешь на commit and push в идее, она перед пушем (рядом с этой же кнопкой) пишет warnings, по ним ты можешь понять где у тебя остались ненужные импорты.

2024-09-30 11:06 UTC, Peregruzochka commented on build.gradle.kts
> +    implementation("com.amazonaws:aws-java-sdk-s3:1.12.481")
Я человек простой:
Вижу в лекции что надо что-то сделать - делаю:
![image](https://github.com/user-attachments/assets/9f1bb974-b5a7-4e39-adb4-839494180e2d)

2024-09-30 20:59 UTC, Murzin34 reviewed
Сочетание ctrl+alt+M помогает выделить код в отдельный метод. По умолчанию он его иногда static делает, но static всегда можно убрать). Лично мне очень помогает эта фишка и в написании функционала, и в написании тестов. Конечно, не всем по душе, когда public метод использует private метод , который использует private метод и так до бесконечности) но, как по мне, это делает код чище.

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        Post post = postRepository.findById(postId).orElseThrow();
В 3 методах у тебя фигурирует получение Post, можешь выделить это в отдельный метод. Ну обработать исключение. Например в методе оставить `Post post = getPost(postId):`, а в классе:
```
    private Post getPost(Long postId) {
        return postRepository.findById(postId).orElseThrow(() ->
                new FileException("Post with ID: " + postId + " not found"));
    }
```

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        };
Понимаю, что для каждого типа файла нужен свой метод. Я бы лично сделал все в одном сервисе с именами методов на манер addImageFileToStorage, addVideoFileToStorage и т.д.
Ну и т.к. несколько раз используешь этот код, тоже можешь выделить его в отдельный метод. Например: 
```
    private Resource addResource(MultipartFile file, Post post, ResourceType type) {
        return switch (type) {
            case IMAGE -> s3ImageService.addFileToStorage(file, post);
            case AUDIO -> s3AudioService.addFileToStorage(file, post);
            case VIDEO -> s3VideoService.addFileToStorage(file, post);
        };
    }
```
В методе `Resource resource = addResource(file, post, type);`

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                .orElseThrow();
В методе `Resource oldResource = getResource(resourceId, post);`, в классе:
```
    private Resource getResource(Long resourceId, Post post) {
        return post.getResources().stream()
                .filter(res -> res.getId().equals(resourceId))
                .findFirst()
                .orElseThrow(() -> new FileException("Resource with ID: " + resourceId + " not found"));
    }
```

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/service/resource/s3/S3AudioService.java
> +public class S3AudioService {
Имя класса ...Service, а анотация `@Component`. Тут либо `@Service`+ "S3AudioService", либо `@Component`+"S3AudioManager". Я лично за первый вариант.

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/service/resource/s3/S3Config.java
> +    private String secretKey;
Меня душили в свое время, чтобы я создавал новый класс S3Properties, вешал на него аннотацию `@ConfigurationProperties(prefix = "services.s3")`, потом просто `@Configuration`, потом еще и `@Data`, потом имплементировал эту *** в необходимые мне сервисы и конфиги. Хотя при использовании `@Value` можно быстро провалиться в место где эта value инициализирована, а `@ConfigurationProperties` так не умеет. Короче меня вьетнамские флешбэки накрыли и я решил поделиться своей болью) Просто используй `@Value`, но если что будь готов).

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/service/resource/s3/S3Config.java
> +public class S3Config {
`@Configuration` конечно бы лучше лежать в папке config, но тут вопрос на самом деле дискуссионный.

2024-09-30 20:59 UTC, Murzin34 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    }
Мне кажется тут `@PutMapping` не везде нужен. Мне кстати прилетало за то что я использую `@PutMapping`, а не `@PatchMapping`.

2024-10-01 12:07 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        Post post = postRepository.findById(postId).orElseThrow();
Я люблю создавать private методы, чтоб все было распределено по смыслу, но создавать метод, ради одной строчки кода, считаю нецелесообразным)
Да и `orElseThrow()` итак выкидывает исключение `NoSuchElementException`

2024-10-01 12:10 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/s3/S3Config.java
> +    private String secretKey;
![image](https://github.com/user-attachments/assets/cb32947b-1be6-42e0-a538-95b66978a3c4)

2024-10-01 12:12 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/s3/S3Config.java
> +public class S3Config {
Вот на протяжении всей таски он у меня то в сервисе то в конфиге лежит (сам долго не мог определиться), но скорее всего переложу его в config

2024-10-01 12:27 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        };
Изначально это были имплементации одного интерфейса
Но потом я понял, что я тут нигде не надо работаю с абстракциями,  удалил интерфейс, а методы остались

2024-10-01 12:29 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        };
Я много раз использую switch case, но конкретно этот код используется один раз

2024-10-02 10:35 UTC, 20cognosce requested changes

2024-10-02 10:35 UTC, 20cognosce commented on build.gradle.kts
>       */
Какое отношение aws имеет к базе

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    private int maxVideoInPost;
В отдельный класс конфигурации

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    }
Один формат может быть в нескольких списках?
.gif - это image или video?

2024-10-02 10:35 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    max-in-post: 10
в отдельный application-aws.yaml
и снова вопрос, что это за aws на локалхосте?

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        };
Вот эти все свитчи у тебя дублируют код
вынеси в отдельный метод, который принимает тип ресурса и консьюмер, а отдает ресурс

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/s3/S3ImageManager.java
> +public class S3ImageManager {
Если у тебя они все реализуют одинаковые методы, то где общий интерфейс

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/s3/S3ImageManager.java
> +    public Resource addFileToStorage(MultipartFile file, Post post) {
Над всеми публичными методами в S3Manager - @Transactional(MANDATORY)

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/s3/S3ImageManager.java
> +    public Resource addFileToStorage(MultipartFile file, Post post) {
Я кстати не уверен, что S3 поддерживает транзакционность и роллбэки (скорее даже нет), возможно, что смысла в этом тогда все равно нет

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/s3/S3ImageManager.java
> +            return new ByteArrayInputStream(output.toByteArray());
Декомпозировать

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    @Transactional
Сомневаюсь я в этих транзакциях
Лучше будет сохранить новый файл в s3
и в транзакцию вынести только обновление сущности в БД
и потом отдельно, в конце, удалить старую

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        Resource oldResource = post.getResources().stream()
Плохой нейминг для сущности потому что Resource - готовый класс в спринге

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                .filter(res -> res.getId().equals(resourceId))
если у тебя есть resourceId нафига ты его через пост достаешь?

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +                .filter(res -> res.getId().equals(resourceId))
У поста там еще fetchtype eager по ресурсам небось

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    private void validateAmount(List<Resource> resources, int maxInPost, ResourceType resourceType) {
А можно написать функциональный интерфейс и сделать всех валидаторов бинами

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    private void validateAmount(List<Resource> resources, int maxInPost, ResourceType resourceType) {
и просто по списку пройти в цикле .validate()

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    private void validateAmount(List<Resource> resources, int maxInPost, ResourceType resourceType) {
как с фильтрами

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    }
Ну и можно поинтереснее придумать маппинг а не if else

2024-10-02 10:35 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/resource/s3/S3AudioManager.java
> +public class S3AudioManager {
тут и наследование от абстрактного класса ложится хорошо
у тебя много общего между менеджерами

2024-10-02 10:35 UTC, 20cognosce commented on src/test/java/faang/school/postservice/controller/PostControllerTest.java
> +    Long resourceOneId;
где модификаторы

2024-10-02 10:35 UTC, 20cognosce commented on src/test/java/faang/school/postservice/service/resource/ResourceServiceTest.java
> +    }};
модификаторы
List.of

2024-10-02 10:35 UTC, 20cognosce commented on src/test/java/faang/school/postservice/service/resource/s3/S3ImageManagerTest.java
> +}
src/test/java/faang/school/postservice/service/resource/s3/test_image.jpg
что это
почему не в ресурсах

2024-10-02 10:35 UTC, 20cognosce commented on src/test/java/faang/school/postservice/service/resource/s3/S3ImageManagerTest.java
> +        Resource resource = s3ImageManager.addFileToStorage(file, post);
это интеграционный тест уже

2024-10-02 10:35 UTC, 20cognosce commented on src/test/java/faang/school/postservice/controller/PostControllerTest.java
> +    MockMvc mockMvc;
и это

2024-10-02 11:24 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    }
https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_MIME-%D1%82%D0%B8%D0%BF%D0%BE%D0%B2#image:~:text=image/gif%3A%20GIF%20(RFC%202045%20%D0%B8%20RFC%202046)%20%E2%80%94%20%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%20%D1%81%D0%B6%D0%B0%D1%82%D0%B8%D1%8F%20%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B9%20%D1%81%20%D0%BF%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%BE%D0%B9%20%D0%B0%D0%BD%D0%B8%D0%BC%D0%B0%D1%86%D0%B8%D0%B8

2024-10-02 11:29 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +        Resource oldResource = post.getResources().stream()
Так не я это придумал

2024-10-02 12:55 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/s3/S3ImageManager.java
> +    public Resource addFileToStorage(MultipartFile file, Post post) {
Не нашел инфы по поводу транзакционности в S3, там все атомарно и согласовано, но роллбеки не делаются

2024-10-02 20:33 UTC, Peregruzochka commented on src/test/java/faang/school/postservice/controller/PostControllerTest.java
> +    MockMvc mockMvc;
Я мокаю здесь поведение сервиса и просто проверяю отрабатывают энд поинты или нет
Или так не стоит делать?

2024-10-02 20:40 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +    private void validateAmount(List<Resource> resources, int maxInPost, ResourceType resourceType) {
У меня не получилось так сделать, да и не было смысла, потому что в в одном методе мне нужно сделать 2 валидации, в другом только одну.

В итоге я реализовал все через мапу, в которой хранятся валидаторы для определенного типа данных

Таким образом я ушел от switch и постарался сделать все максимально чисто и понятно

2024-10-04 19:11 UTC, 20cognosce approved these changes

2024-10-04 19:11 UTC, merged