feature-bjs2-28851
CorporationX/post_service pull request #876
Opened 2024-09-30 20:57 UTC by nikandpro

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/config/kafka/KafkaProducerConfig.java
> +    public String bootstrapAddress;
Эти проперти должны быть иммутабельными, так что инжекти их лучше через конструктор

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto publish(@PathVariable long id) throws JsonProcessingException {
лучше обработать эксепшн и откинуть кастомный и перехватить его в @ControllerAdvice

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/kafka_redis/kafka/consumer/KafkaCommentConsumer.java
> +    public void listener(String data) {
Кафка умеет десериализовывать сразу в нужный тебе объект
https://habr.com/ru/articles/793134/

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/kafka_redis/kafka/consumer/KafkaCommentConsumer.java
> +    public void listener(String data) {
Ссылка для котлина, но в java тоже самое можно найти

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/kafka_redis/kafka/consumer/KafkaLikeConsumer.java
> +    public void listener(String data) {
тоже самое, не нужен здесь ObjectMapper

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/kafka_redis/kafka/producer/KafkaCommentProducer.java
> +    public void send(String topic, CommentDto commentDto) {
Кафка так же умеет сереализовывать из объекта в стринг

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/main/java/faang/school/postservice/validator/PostValidator.java
> +//        if (authorId == null && projectId == null || authorId != null && projectId != null) {
Это либо удалить, либо доработать

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/test/java/faang/school/postservice/like/LikeServiceTest.java
> +//    void addPostLike() {
?

2024-10-02 17:44 UTC, MaxVodolazhsky commented on src/test/java/faang/school/postservice/like/LikeServiceTest.java
> +//        when(commentService.getComment(anyLong())).thenReturn(commentDto);
?

2024-10-24 21:40 UTC, mysosnovskaya requested changes

2024-10-24 21:40 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaProducerConfig.java
> +    @Value("${spring.data.kafka.topic-name.views}")
А где поле?) И комментарий от Максима здесь не учтен

2024-10-24 21:40 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto publish(@PathVariable long id) throws JsonProcessingException {
Здесь тоже комментарий от Максима не учтен

2024-10-24 21:40 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/redis/service/PostCacheService.java
> +    @Value("{spring.data.redis.post-cache.key-prefix}")
Это не будет работать, здесь не хватает $
Рекомендую протестировать свой код, чтобы иметь уверенность в его работоспособности :)

2024-10-26 14:12 UTC, nikandpro commented on src/main/java/faang/school/postservice/config/kafka/KafkaProducerConfig.java
> +    @Value("${spring.data.kafka.topic-name.views}")
Я не разобрался как сделать, то что Макс написал, в остальном вроде все исправил и проверил, что программа работает

2024-10-26 18:03 UTC, mysosnovskaya approved these changes
Остались мелочи, поправь их и можешь самостоятельно мержить этот ПР)

2024-10-26 18:03 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +import com.fasterxml.jackson.core.JsonProcessingException;
Импорт лишний остался)

2024-10-26 18:03 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/kafka/KafkaProducerConfig.java
> +    public KafkaProducerConfig(@Value("${spring.data.kafka.bootstrap}")String bootstrapAddress) {
Максим имел в виду вообще все проперти из этого класса, а не только bootstrapAddress. И по стилю: сначала идут все поля, а потом конструктор. Сейчас поля оказались ниже конструктора)

2024-11-05 10:25 UTC, merged