BJS2-27264 - AI орфография
CorporationX/post_service pull request #882
Opened 2024-10-01 14:06 UTC by dmitridorje

Реализовал интеграцию со сторонним сервисом проверки орфографии/автокоррекции текста https://textgears.com/api. Обновляются еще не опубликованные посты. Коррекция текстов выполняется по расписанию один раз в сутки. После проверки для соответствующих постов проставляется флаг сompletedSpellCheck. Также реализована функция пакетной асинхронной обработки этих постов для случаев большого количества постов, требующих проверки правописания. 
Если возникнет желание потестить, то можно поменять настройки spell-checker: scheduler: cron: в application.yml. Однако стоит учесть, что бесплатный ключ рассчитан на 500 запросов, а я в ходе работы над таской уже израсходовал больше ста.

2024-10-07 16:01 UTC, mikhailov26 requested changes
В целом отлично, но есть нюансы: 1) аннотация
2) т.к мы уже почти спецы прошу добавить директорию dto в model
3) в дериктории service сделать пакет impl, добавить в корень интерфейс сервиса, имплементацию в impl
4) если будет время/возможность попробовать сделать 
post_V_005_BJS2-27264_add_spellcheck_completed_to_post.sql в виде xml (Это так для общего развития, пункты выше обязательны к выполнению)

2024-10-07 16:01 UTC, mikhailov26 commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +@EnableRetry
Немного не понял зачем она тут

2024-10-08 16:44 UTC, dmitridorje commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +@EnableRetry
См. класс SpellCheckService в этом ПР: в нем я обращаюсь по RestTemplate к стороннему ресурсу и с помощью retry пытаюсь, так сказать, проактивно реагировать на ситуации возможных неполадок связи ит.д. Или я вовсе неверно понял назначение этой аннотации?

2024-10-10 18:25 UTC, mikhailov26 approved these changes

2024-10-10 18:25 UTC, merged