BJS2-26709 Проверка постов на оскорбительный контент
CorporationX/post_service pull request #884
Opened 2024-10-01 17:34 UTC by ostermal7

2024-10-07 20:40 UTC, mikhailov26 requested changes
Иерархия

2024-10-07 20:40 UTC, mikhailov26 commented on src/main/java/faang/school/postservice/service/post/async/PostServiceAsyncImpl.java
> +    @Async("fixedThreadPools")
Разобрались с сочетанием @Transactional и @Async?

2024-10-07 20:40 UTC, mikhailov26 commented on src/main/resources/db/changelog/changeset/post_V005_verification.sql
Если будет время попробуй миграцию написать через xml, так для общего развития

2024-10-07 20:41 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/post/async/PostServiceAsyncImpl.java
> +    @Async("fixedThreadPools")
В целом, вроде, да, но мб в четверг пару уточнений сделаем у тебя)

2024-10-08 05:10 UTC, ostermal7 commented
рефактор сделал, миграцию через xml попробую на будущих изменениях в бд произвести, а то тут рефакторы и тд, не хочется задерживать мердж

2024-10-10 18:09 UTC, mikhailov26 approved these changes

2024-10-10 18:10 UTC, mikhailov26 commented
конфликты, любимые конфликты

2024-10-11 18:31 UTC, merged