BJS2-26701 Публикация постов по расписанию
CorporationX/post_service pull request #888
Opened 2024-10-02 06:41 UTC by VitoS1C

2024-10-02 10:04 UTC, 108ardev reviewed
Попозже доревьююю

2024-10-02 10:04 UTC, 108ardev commented on src/main/java/faang/school/postservice/config/threadPool/ThreadPoolConfig.java
> +    public ExecutorService FixedThreadPool() {
метод с большой буквы у тебя :/

2024-10-02 10:14 UTC, VitoS1C commented on src/main/java/faang/school/postservice/config/threadPool/ThreadPoolConfig.java
> +    public ExecutorService FixedThreadPool() {
Упс!

2024-10-02 10:48 UTC, ostermal7 commented on src/main/java/faang/school/postservice/config/threadPool/ThreadPoolConfig.java
> +        return Executors.newFixedThreadPool(10);
число так не передавай, тяни через ямл лучше

2024-10-07 17:29 UTC, mikhailov26 requested changes
В целом хорошо, просьба отрефакторить иерархию по типу, как написал в дискорде. 
И второе, точно ли нам нужны @Transactional в postService, просто из контекста методов мы не меняем состояние бд?

2024-10-07 17:29 UTC, mikhailov26 commented on src/main/java/faang/school/postservice/service/post/PostServiceImpl.java
> +    @Transactional
При том условии, что мы не меняем состояние бд можем не юзать @Transactional

2024-10-07 17:47 UTC, VitoS1C commented on src/main/java/faang/school/postservice/service/post/PostServiceImpl.java
> +    @Transactional
Ok, убираю

2024-10-10 18:03 UTC, mikhailov26 commented
реши конфликты и можешь мержить

2024-10-11 08:10 UTC, merged