BJS2-27082 [Experienced] Бан пользователя
CorporationX/post_service pull request #889
Opened 2024-10-02 08:29 UTC by vestmen

2024-10-02 18:39 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    public void publishingUsersForBan() {
Я бы вынес логику публикации из Сервиса в другой класс, например, в АвторБаннер. Т.е. в Сервисе сделать метод только по выборке нужных юзеров, а уже в АвторБаннере полученный лист отправлять. Так выглядит более логично вроде. Сервис отвечает только за работу с сущностями(достать, сохранить, удалить и т.п.), он не должен что-то публиковать куда-то. Так у тебя сделано в юзерСервисе: там листенер слушает события и вызывает у себя метод сервиса, который уже банит юзеров. Если надо будет поменять источник сообщений, например, тебе не надо будет лезть в ЮзерСервис, ты только изменишь листенер, или даже добавишь новый. То же самое здесь в ПостСервисе. Чтобы добавить, поменять, удалить источники сообщений, делаешь это в классе, ответственном именно за это, а не полезешь менять метод ПостСервиса.
ИМХО, я б так сделал

2024-10-02 20:10 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/banner/AuthorBanner.java
> +
Минус строчку

2024-10-02 20:10 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    public void publishingUsersForBan() {
Согласен с Иваном

2024-10-02 20:10 UTC, sultan-inked commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/post_V004_alter_post.sql
`post_V004__alter_post`, здесь так же как в юзер-сервис, тоже сделай пожалуйста 005, у меня уже есть 004, еще не смержено

2024-10-02 20:10 UTC, sultan-inked commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: db/changelog/changeset/post_V004_alter_post.sql
`post_V003_resource` тоже надо переименовать  на `post_V003__resource`, кто то до нас не правильно сделал, я у себя переименовал уже

2024-10-04 08:44 UTC, vestmen commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    public void publishingUsersForBan() {
Согласен, так логичнее будет

2024-10-06 11:40 UTC, 20cognosce requested changes
Тестов побольше

В остальном норм

2024-10-06 11:40 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/RedisMessagePublisher.java
> +    private final StringRedisTemplate redisTemplate;
Почему ты отправляешь только id, так еще и в стринговом формате

Сделай более сложное, составное сообщение с разными параметрами

2024-10-06 11:40 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> rejectedPosts = postRepository.findAllByVerificationStatus(REJECTED);
Можно оптимизировать это и не вытаскивать все rejected посты, а сразу вытаскивать юзеров, у которых их больше 5?

2024-10-06 11:40 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    schedule: "0 0 0 * * ?"
это какая частота?

3-ий ноль - это день, получается ты хотел раз в сутки, но нулевого дня нет
сейчас это похоже на ошибку, должно быть 0 0 * * *

Перепроверь

2024-10-06 11:40 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    schedule: "0 0 0 * * ?"
Это кажется слишком редко, сделай каждый 5 минут хотя бы

2024-10-08 13:51 UTC, vestmen commented on src/main/java/faang/school/postservice/publisher/RedisMessagePublisher.java
> +    private final StringRedisTemplate redisTemplate;
По условию так)

2024-10-08 13:52 UTC, vestmen commented on src/main/resources/application.yaml
> +    schedule: "0 0 0 * * ?"
0 0 * * * это каждый час, 0 0 0 * * раз в сутки в 00:00, по условию

2024-10-08 14:40 UTC, vestmen commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> rejectedPosts = postRepository.findAllByVerificationStatus(REJECTED);
Переделал

2024-10-09 17:58 UTC, 20cognosce approved these changes
Конфликты правь и мёрдж

2024-10-10 10:10 UTC, merged