BJS2-26708 Проверка комментариев на оскорбительный контент
CorporationX/post_service pull request #891
Opened 2024-10-02 14:46 UTC by ostermal7

2024-10-07 20:34 UTC, mikhailov26 requested changes
Всё как всегда булочно, отрефактори иерархию, как сегодня писал. И если тайминг позволит задумайся над кешем, в данном случае не то чтобы он сильно необходим, но лишним не будет

2024-10-07 20:34 UTC, mikhailov26 commented on src/main/resources/badWords.txt
Сильно, нечего добавить)

2024-10-08 05:03 UTC, ostermal7 commented
Рефактор сделал, а на кэш, боюсь, сейчас времени нет с тем объёмом, который упал на сервисе нотификаций

2024-10-10 18:08 UTC, mikhailov26 commented
Конфликты, что делать знаешь)

2024-10-10 18:08 UTC, mikhailov26 approved these changes

2024-10-11 19:01 UTC, merged