Добавление картинок к посту BJS2-26117
CorporationX/post_service pull request #892
Opened 2024-10-02 15:22 UTC by segaTk

2024-10-02 20:17 UTC, GusevVrn reviewed
По библиотекам, я у Влада видел еще в каком-то одном из первом видео и сейчас мне Маша указала на это что такой импорт:
import ...* - плохо т.к. по code check style потом может не пройти
https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcard-imports
называется Disable wildcard impors, посмотри там надо 999 в 2х окошках проставить. И как раз свои классы что ты сейчас правишь пройдись через ctrl + shift + O
p.s. в самих классах на это указывать не буду

И вопрос по методам, ты везде пишешь images, для всех остальных файлов получается надо будет свой класс писать? Почему бы просто не работать с абстрактными файлами. Мы все равно наружу выдаем байты.

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @DeleteMapping("{id}")
Слеш

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +@RequestMapping("api/v1/resources")
по сути {id} сюда можно вынести

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/user/UserDto.java
> -    private String email;
куда email дел?

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/delete/DeleteService.java
> +public interface DeleteService {
По названию наверное лучше убрать service и добавить что-то другое (FileDeletion), и можно его сделать @FunctionalInterface.

Вообще идея нравится, но по структуре сейчас получается что этот интерфейс создан только для S3. 
Я за то чтобы сделать немного по другому:
storage -> 
(папка) intefrace 
(папка) S3 (в нем уже имплементить эти интерфейсы)
Убрать ПАПКИ под каждое действие и сделать один общий S3Service класс который implements Delete, Upload, Download.

Либо сделтаь 1 интерфейс с методами download, upload, delete и его имплементить.
Оставлю на комментирование Маши, т.к. я тот еще архитектор.

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/delete/DeleteService.java
> +    void deleteImage(String key);
по названию, мы же можем работать не только с изображениями

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +
красава, только удали отступ, обычно документация прям над методом пишется

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/post/ImageValidator.java
> +public class ImageValidator {
валидатор не в своей директории

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = keys.stream().map((key) -> Resource.builder().key(key).build()).toList();
после stream() каждый метод с новой строки

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = keys.stream().map((key) -> Resource.builder().key(key).build()).toList();
аналогично, ну и билдер кстати тоже легче читается когда поля с новой строки

2024-10-02 20:17 UTC, GusevVrn commented on src/main/resources/application.yaml
> +myapp:
переменную как-то понятнее переименовать

2024-10-02 20:17 UTC, GusevVrn commented on src/test/java/faang/school/postservice/PostImagesServiceAppTests.java
> +class PostImagesServiceAppTests {
верни как было

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +            for (byte[] imageBytes : bytes) {
как-то ты жестко переделал) это очень близко от того что я тебе предлагал.

Зачем тебе получать список байт в bytes и работать и ними?
Сделай цикл for(MultipartFile image : images)
ты тогда сможешь metadata.setContentType взять из image и расширение для файла оставить из image.  (переименовать оригинальное название файла с сохранением расширения)

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +                    s3Client.putObject(bucketName, fileName, inputStream, metadata);
inputStream же можно заменить на new ByteArrayInputStream(imageBytes)

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +                    return s3Client.getUrl(bucketName, fileName).toExternalForm();
а зачем тебе работать с url? можно же просто хранить ключ

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +                    var metadata = new ObjectMetadata();
лично мое мнение var это от лукавого
я вот этот код буду каждый день смотреть, мне этот var ни о чем не говорит. если сразу написать ObjectMetadata будет лучше.
Вот в каком-нибудь файле конфигурации который один раз настроил и больше туда не суешься var - ok.
Но опять же, это лично мое мнение, т.к. я так привык. Не переделывай.

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +            List<String> urls = new ArrayList<>();
вот эти ulrs, куда дальше этот список идет?

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +                    String url = future.get();
Вроде если future не завершил свое выполнение, ты тут ерунду получишь. И дальше пойдешь.

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +        return List.of();
возвращаешь пустой список?

2024-10-02 20:17 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +    public List<String> uploadImages(List<MultipartFile> images) {
Я бы разбил этот метод.
Оставил его принимать файлЫ, но сохранение одного файла вынес в отдельный метод

2024-10-03 06:56 UTC, segaTk commented on src/main/java/faang/school/postservice/dto/user/UserDto.java
> -    private String email;
вернул

2024-10-03 07:10 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/delete/DeleteService.java
> +public interface DeleteService {
Хорошо, переименовал и добавил аннотацию. По расположению пока так оставлю, возможно удаление можно будет потом расширить, удалять не по одному ключу, а целый список, или не картинки, а другие объекты.

2024-10-03 07:11 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/delete/DeleteService.java
> +    void deleteImage(String key);
Переименовал

2024-10-03 07:13 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +
Спасибо, хорошо =)

2024-10-03 07:20 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/ImageValidator.java
> +public class ImageValidator {
С другой стороны, если оставляю в одном пакете с постом, появляется возможность использовать модификатор доступа protected

2024-10-03 07:23 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = keys.stream().map((key) -> Resource.builder().key(key).build()).toList();
А мне почему-то понравилось писать в одну строчку : ) так код смотрится иначе да и помещается вроде

2024-10-03 07:27 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = keys.stream().map((key) -> Resource.builder().key(key).build()).toList();
Полностью согласен, особенно когда много полей, здесь решил оставить так как один ключ в билдере

2024-10-03 07:31 UTC, segaTk commented on src/main/resources/application.yaml
> +myapp:
хорошо

2024-10-03 07:33 UTC, segaTk commented on src/test/java/faang/school/postservice/PostImagesServiceAppTests.java
> +class PostImagesServiceAppTests {
Видиом идея подтянула, хорошо

2024-10-03 08:04 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +            for (byte[] imageBytes : bytes) {
Точно

2024-10-03 08:05 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +                    s3Client.putObject(bucketName, fileName, inputStream, metadata);
с файлом уже да) getImputStream, точно, спасибо

2024-10-03 08:07 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +                    String url = future.get();
Дальше ошибка выскочит

2024-10-03 08:08 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +            List<String> urls = new ArrayList<>();
Для контроля потоков

2024-10-03 08:08 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +        return List.of();
; D

2024-10-03 08:12 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadImagesS3ServiceImpl.java
> +    public List<String> uploadImages(List<MultipartFile> images) {
Спасибо, переделал для файлов в целом, в самом таске речь шла за картинки, круто, что класс теперь универсальный, по поводу разбить его - пока так оставлю

2024-10-03 08:20 UTC, segaTk commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @DeleteMapping("{id}")
есть

2024-10-03 08:21 UTC, segaTk commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +@RequestMapping("api/v1/resources")
да, пусть пока там будут)

2024-10-03 09:46 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = keys.stream().map((key) -> Resource.builder().key(key).build()).toList();
мы индусы, нам за объем платят =)

2024-10-03 20:12 UTC, mysosnovskaya requested changes

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/s3config/S3Config.java
> +    @Value("${services.s3.endpoint}")
Лучше вынести это в отдельный класс, помеченный аннотацией ConfigurationProperties

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @PostMapping("/{id}/add")
add не надо писать. POST уже говорит о том, что это создание/добавление

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @PatchMapping("/{id}/update")
update не нужно писать. PATCH уже говорит о том, что это обновление

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/model/Post.java
> +import lombok.*;
Было правильно, это изменение не нужно

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/model/Resource.java
> +import lombok.*;
Было правильно, это изменение не нужно

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/delete/FileDeletion.java
> +public interface FileDeletion {
А зачем этот интерфейс нужен?

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/ImageValidator.java
> +    protected void changeFileDimension(MultipartFile image) {
Это никак не относится к валидации -> это не ответственность валидатора -> нужно вынести в отдельный класс

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/upload/UploadFilesS3ServiceImpl.java
> +    public List<Resource> uploadFiles(List<MultipartFile> files) {
Очень большой метод получился, нужно его декомпозировать (выделить его части в отдельный приватные методы с понятными названиями)

2024-10-03 20:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/upload/UploadService.java
> +public interface UploadService {
Не понимаю смысла интерфейса. Какие ещё предполагаются реализации? По-моему логичнее будет сделать интерфейс (или абстрактный класс), отвечающий за работу с файлами (с upload, download, delete методами) и сделать его реализацию, в которой файлы будут находиться в s3. Тогда можно предположить, что может быть другая реализация, например, с хранением файлов в файловой системе. Или ещё где-то) 
А в твоей текущей реализации можно upload сделать в s3, а delete сделать в файловой системе =)

2024-10-04 05:32 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/ImageValidator.java
> +    protected void changeFileDimension(MultipartFile image) {
Хорошо

2024-10-04 05:32 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/delete/FileDeletion.java
> +public interface FileDeletion {
На будущее, вдруг захотим целый список для поста удалять

2024-10-04 05:34 UTC, segaTk commented on src/main/java/faang/school/postservice/config/s3config/S3Config.java
> +    @Value("${services.s3.endpoint}")
хорошо

2024-10-04 05:50 UTC, segaTk commented on src/main/java/faang/school/postservice/model/Resource.java
> +import lombok.*;
Это @Data убрал, сущность наследуется от JpaRepository

2024-10-04 05:51 UTC, segaTk commented on src/main/java/faang/school/postservice/model/Post.java
> +import lombok.*;
Это @Data убрал, сущность наследуется от JpaRepository

2024-10-04 06:52 UTC, segaTk commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @PostMapping("/{id}/add")
Хорошо, поправил

2024-10-04 06:52 UTC, segaTk commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @PatchMapping("/{id}/update")
исправил

2024-10-04 07:14 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadFilesS3ServiceImpl.java
> +    public List<Resource> uploadFiles(List<MultipartFile> files) {
Блок try на 30 строк, где поэтапно написана главная логика метода, set resources вынес)

2024-10-04 07:15 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/upload/UploadService.java
> +public interface UploadService {
Убрал)

2024-10-04 19:38 UTC, mysosnovskaya requested changes

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/AppProperties.java
> +    @Value("${services.s3.endpoint}")
Нужно подробнее почитать про ConfigurationProperties. Во-первых, в эту аннотацию выносится общий префикс для параметров. Во-вторых, аннотации Value не нужны

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    public void addImages(@PathVariable Long id,
Не понимаю, здесь id - это postId? Если так, то сейчас оно в урле выглядит как айди ресурса: /resources/{id} - это пусть до ресурса под заданным айди. А в твоем случае это не так. должно быть /posts/{id} (и конечно, в соответствующем контроллере). Аналогично для Patch, а вот с delete вроде всё ок)

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    public void uploadPostImages(Long id, List<MultipartFile> images) {
Тут id лучше переименовать в postId

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    public void updatePostImages(Long id, List<MultipartFile> images) {
Тут id лучше переименовать в postId

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    public void deleteImage(Long id) {
Тут id лучше переименовать в resourceId

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +      Optional<Resource> resource = resourceRepository.findById(id);
Чуть стиль поплыл)

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/ChangerDimension.java
> +public class ChangerDimension {
DimensionChanger (обычно имя класса - это существительное, а все дополнения к этому существительному пишутся ПЕРЕД ним, такие правила английского =))

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +public class UploadFilesS3Service {
Я всё равно не понимаю, зачем разделять delete и upload. Они используют один и тот же клиент, один и тот же bucketName, объединены одной логикой (работа с s3). Мне такое разделение кажется нелогичным. Я предлагаю переделать, но если у тебя есть какая-то аргументация, то давай обсудим)

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/DeleteFileS3Service.java
> +            log.error("Delete Service. Delete file: {} to bucket: {}", key, bucketName);
Так, в лог мы ошибку напишем, но пользователю всё равно 200 вернется, т.к. классе PostImagesService методе deleteImage всё будет выглядеть так, как будто отработало успешно. Так нельзя, это неправда

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +            ExecutorService executorService = Executors.newFixedThreadPool(files.size());
Нам точно нужно каждый раз при вызове метода uploadFiles создавать новый тред пул? Может быть лучше сделать его бином и переиспользовать?

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                Future<String> future = executorService.submit(() -> {
Создание этой Future можно вынести в отдельный приватный метод, а потом здесь всё красиво стримом сделать (преобразовать` List<MultipartFile>` в `List<Future<String>>`)

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                    log.error("One of the thread ended with exception. Reason: ", e);
Логгирование ошибок должно происходить в Global Exception Handler. Так что нам здесь достаточно просто сгенерировать новое исключение, но в него обязательно нужно передать исходное исключение e

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +            log.error("Error uploading images to Object Storage. Reason:", e);
Это тоже нельзя так просто оставлять. Метод дальше продолжит своё выполнение, вызовет setResources и вообще всё будет выглядеть так, будто бы всё успешно. А о том, что что-то случилось, узнает только разработчик и то, если заглянет в логи. А мы без необходимости в логи не смотрим)

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +     return setResources(files);
Стиль неверный, не хватает отступа. И ниже после setResources лишний пробел

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +        } return resources;
return должен быть на новой строке

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +    private List<Resource> setResources (List<MultipartFile> files) {
По-моему название метода некорректное. Это скорее mapToResources (преобразование). А сейчас он называется так, будто мы какие-то ресурсы в какой-то set передем

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        deleteImageS3Service.deleteFile(resource.getName());
А нам в базе данных ничего не нужно удалить?

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
А не проще ли сделать setResources(resources)?

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
Ну и кстати старые ресурсы тогда тоже надо удалить и из базы данных, и из s3, а новые наоборот сохранить в базу данных

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        postRepository.save(post);
А ты проверял, точно ли эта строка сохраняет ещё и ресурсы в базу данных? Там же для них отдельная таблица

2024-10-04 19:38 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @PatchMapping("/{id}")
У тебя сейчас сервис реализовал так, будто бы здесь PUT. Поясняю: PUT означает полную замену того, что было раньше, на то, что сейчас передали в эндпоинт (у тебя сейчас так и есть)

2024-10-05 06:44 UTC, segaTk commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    public void addImages(@PathVariable Long id,
Хорошо, спасибо, перенёс в другой контроллер

2024-10-05 06:47 UTC, segaTk commented on src/main/java/faang/school/postservice/controller/post/ResourceController.java
> +    @PatchMapping("/{id}")
Точно

2024-10-05 06:51 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        postRepository.save(post);
Да, сохраняет список, а при обновлении пришлось размер сделать через BigInteger, потому что Jpa выбрасывал исключение

2024-10-05 06:55 UTC, segaTk commented on src/main/java/faang/school/postservice/service/resource/ResourceService.java
> +      Optional<Resource> resource = resourceRepository.findById(id);
Поправил)

2024-10-05 06:56 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    public void uploadPostImages(Long id, List<MultipartFile> images) {
Хорошо

2024-10-05 06:59 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                    log.error("One of the thread ended with exception. Reason: ", e);
Согласен

2024-10-05 07:01 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +            log.error("Error uploading images to Object Storage. Reason:", e);
Хорошо) Добавил исключение

2024-10-05 07:01 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +     return setResources(files);
Поправил

2024-10-05 07:03 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +    private List<Resource> setResources (List<MultipartFile> files) {
Согласен, немного неверное название, исправил

2024-10-05 07:04 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +        } return resources;
теперь там

2024-10-05 07:50 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +public class UploadFilesS3Service {
Согласен, про объединяющие факторы, но в дальнейшем, если мы захотим расширить класс, добавить например метод удалить все ресурсы сразу, или например не по одному, а списком, или например добавится логика по загрузке, общий класс будет достаточно большим, и тогда придём к решению о его разделении)

2024-10-05 07:50 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
да, просто до этого была немного другая логика с байтами, исправлю

2024-10-05 07:50 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    public void deleteImage(Long id) {
Хорошо

2024-10-05 07:50 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
Из базы удаляю, а вот в облаке может пусть лежат? потом можно будет вернуть, если случайно удалили

2024-10-05 07:50 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        deleteImageS3Service.deleteFile(resource.getName());
добавил метод

2024-10-05 07:51 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/ChangerDimension.java
> +public class ChangerDimension {
Да, точно, бывает =)))

2024-10-05 08:36 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +            ExecutorService executorService = Executors.newFixedThreadPool(files.size());
Каждый поток создается для каждого объекта, количество потоков ограничено количеством файлов в листе

2024-10-05 08:56 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                Future<String> future = executorService.submit(() -> {
Пытался тоже красиво через стрим при работе с коллекцией листов сеттить поля в объект, в итоге остановился на таком цикле, красота требует жертв

2024-10-05 10:16 UTC, segaTk commented on src/main/java/faang/school/postservice/config/AppProperties.java
> +    @Value("${services.s3.endpoint}")
Сделал

2024-10-05 10:55 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/DeleteFileS3Service.java
> +            log.error("Delete Service. Delete file: {} to bucket: {}", key, bucketName);
Исправил, пробросил исключение

2024-10-05 15:28 UTC, mysosnovskaya requested changes

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +public class UploadFilesS3Service {
Вот когда придем, тогда и разделим. А вдруг этого никогда не случится? Программисты не любят реализовывать код "на будущее". Если нет явного аргумента, зачем это нужно сейчас, то значит это не нужно. А уж как будет в будущем - в будущем и узнаем, и подрефакторим. Мы не пытаемся предсказать и предугадать, как будет. Всё равно не угадаем и будет вообще что-то иное. Предложу другой возможный вариант событий: кроме s3 нам понадобится иметь реализацию с другим хранилищем (ну пусть это будет файловая система). Тогда было бы намного логичнее, если бы у тебя был интерфейс FileService с методами upload, download, delete и двумя реализациями: S3Service и FileSystemService. А в твоей текущей реализации такое делать будет неудобно (может случиться такое, что одновременно будут использоваться DeleteFileS3Service и UploadFileToFileSystemService). Готова обсудить голосом, если нужно) Но я настаиваю на объединении. Аргументация "а вдруг в будущем будет так" не годится)

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                Future<String> future = executorService.submit(() -> {
Не поняла) Для начала давай вынесем в приватный метод - это точно нужно для повышения читаемости кода

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                    log.error("One of the thread ended with exception. Reason: ", e);
Нет, в Global Exception Handler должно быть полностью всё логирование (и сообщение об ошибке, и стектрейс). На то он и обработчик ошибок - он должен единообразно обрабатывать (и следовательно логировать) все исключения. Поэтому в RuntimeException необходимо передать красивое сообщение (какое ты сейчас в логи пишешь) и исходное исключение `e`, а также позаботиться о том, чтобы в Global Exception Handler всё корректно залоггировалось.
Это актуально для всех мест, где у тебя log.error + throw new

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +            return resources;
А зачем здесь return делать? Так у нас цикл for всегда будет отрабатывать только одну итерацию и завершаться. По-моему это не то, что мы здесь хотели бы)

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        resourceService.deleteResource(resourceId);
Лучше сначала обновить информацию в базе данных, а потом удалить из s3, и всё это сделать в транзакции. Да, по логике это странно, но тут нужно учесть тразнакционность:
- в текущей реализации может возникнуть такая ситуация: файл из s3 удалился успешно, а в базу данных по какой-либо причине изменения внести не удалось. Как следствие мы получаем не консистентное состояние. 
- если же поменять порядок местами, то: сначала идем в базу данных, а затем в s3. И если из s3 по какой-либо причине файл удалить не удалось, то мы получим исключение, а т.к. оно вылетит внутри транзакции, то все изменения, внесенные в базу данных, откатятся

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
А можешь описание ошибки показать?

2024-10-05 15:28 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
А из базы где удаляешь? Не вижу
По s3 - ок, это надо с аналитиком обсуждать. Нужно учитывать, что они будут место занимать, и скорее всего много, а нам за это деньги платить) Я бы удалила, но если тебе не хочется, давай оставим. Тут нет правильного и неправильного)

2024-10-05 15:37 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        resourceService.deleteResource(resourceId);
Точно, спасибо

2024-10-05 15:50 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +            return resources;
да, всё верно продублировал(

2024-10-06 02:54 UTC, mysosnovskaya requested changes
Не вижу ответов / исправлений на мои вчерашние комментарии, кроме двух

2024-10-06 08:28 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +public class UploadFilesS3Service {
хорошо

2024-10-06 08:39 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
org.springframework.orm.jpa.JpaSystemException: A collection with cascade="all-delete-orphan" was no longer referenced by the owning entity instance: faang.school.postservice.model.Post.resources] with root cause
каскадное удаление

2024-10-06 08:40 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        post.getResources().removeAll(postResources);
хорошо)

2024-10-06 08:40 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +                    log.error("One of the thread ended with exception. Reason: ", e);
Понял, хорошо, поправлю

2024-10-06 22:32 UTC, mysosnovskaya requested changes

2024-10-06 22:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            Future<String> future = executorService.submit(() -> {
Нужно вынести в отдельный приватный метод, как писала раньше

2024-10-06 22:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        postRepository.save(post);
Здесь та же самая история: сначала в базу идем, потом в s3 + транзакция

2024-10-06 22:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = S3Service.uploadFiles(images, postId);
Здесь тоже сначала в базу данных сохраняем, потом в s3 + транзакция

2024-10-06 22:41 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        postRepository.save(post);
тогда можно заново два сервиса переписать

2024-10-06 23:15 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            Future<String> future = executorService.submit(() -> {
вынес

2024-10-07 06:56 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = S3Service.uploadFiles(images, postId);
Если загрузка файла происходит асинхронно, это может усложнить управление транзакциями. Транзакции обычно подразумевают синхронный подход, поэтому вам нужно будет тщательно продумать архитектуру.

2024-10-07 13:05 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/UploadFilesS3Service.java
> +public class UploadFilesS3Service {
Собирайте вместе всё, что изменяется по одной причине и в одно время. Разделяйте всё, что изменяется в разное и по разным причинам.

2024-10-08 00:42 UTC, mysosnovskaya requested changes

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            executorService = Executors.newFixedThreadPool(10);
Если у тебя executorService это бин, который подставляется в класс через Autowired, то здесь не нужно его инициализировать. Нужно использовать то, что есть

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            executorService.shutdown();
И закрывать не нужно, т.к. им будут пользоваться другие методы (т.к. это бин, он не одноразовый)

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            Future<String> future = executorService.submit(() -> putObjectsToS3(file));
Почему решил запускать так, а не через CompleatableFuture.runAsync?

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        List<Resource> resources = S3Service.uploadFiles(images, postId);
Всё верно. Забыла, что uploadFiles асинхронный внутри)

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        postRepository.save(post);
Из-за асинхронности uploadFiles, конечно, не получится уже сделать так, как я предлагала. А где отправка повторяется при ошибке? Не увидела такого в коде

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    private final S3Service S3Service;
название поля должно начинаться с маленькой буквы

2024-10-08 00:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            throw new RuntimeException("ERROR upload file");
Нужно ещё прокинуть исходное исключение.
И ещё обрати внимание, как логируется это исключение. Обычно исключения перехватываются через GlobalExceptionHandler (когда происходит вызов эндпоинта), но т.к. этот метод выполняется асинхронно в другом потоке, то нужно убедиться, кто залоггирует эту ошибку. А логи нужны обязательно, чтобы мы потом могли разобраться с проблемой

2024-10-08 01:01 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            Future<String> future = executorService.submit(() -> putObjectsToS3(file));
Изначально думал, что он более гибкий оказалось не так, спасибо

2024-10-08 01:17 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +        postRepository.save(post);
Подумаю как это реализовать

2024-10-08 01:27 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            executorService = Executors.newFixedThreadPool(10);
исправил

2024-10-08 01:51 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            executorService.shutdown();
убрал

2024-10-08 01:56 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostImagesService.java
> +    private final S3Service S3Service;
исправил

2024-10-08 02:00 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +            throw new RuntimeException("ERROR upload file");
Хорошо

2024-10-08 20:50 UTC, mysosnovskaya approved these changes

2024-10-08 20:50 UTC, merged