BJS2-27077   [Experienced] Проверка постов на оскорбительный контент
CorporationX/post_service pull request #898
Opened 2024-10-03 15:05 UTC by ilu23ilu23

Добавлена функциональность проверки постов на оскорбительный контент

2024-10-03 15:54 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +    @Transactional
Async и Transactional же не сработает, т.к. метод вызывается внутри другого метода этого же класса. Проксирование не сработает. Нужно, по идее, выносить в отдельный класс этот метод

2024-10-04 12:11 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +    @Transactional
GPT согласен с Иваном:
*Да, комментарий верный. Проблема в том, что аннотации @Async и @Transactional полагаются на механизм проксирования Spring, который работает только при вызове методов через прокси-объект (то есть извне самого класса).*
*Когда вы вызываете метод, аннотированный @Async или @Transactional, из другого метода того же класса, Spring не применяет прокси для этого вызова, потому что это внутренний вызов. Поэтому ни асинхронность, ни транзакционность не будут работать.*

2024-10-04 12:15 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +    @Transactional
Да, я уже переделываю, спасибо, ребят)
Лекцию у Влада не досмотрел и не узнал об этом

2024-10-08 11:45 UTC, 20cognosce requested changes

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/QuartzConfig.java
> +public class QuartzConfig {
Можно спокойно без него обойтись

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/QuartzConfig.java
> +                .forJob(moderationJobDetail())
Ты создаешь два инстанса
Один - бин, второй - вызовом метода

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/model/Post.java
> +    private VerificationPostStatus verificationStatus = VerificationPostStatus.UNVERIFIED;
Не понял, почему ты на уровне приложения чет присваиваешь

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    List<Post> findUnverifiedPosts();
А можно не писать запросы на каждый метод, а юзать спринговый нейминг методов, по которым Spring Data сама составит query

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationDictionary.java
> +        try (InputStream inputStream = getClass().getResourceAsStream("/forbidden-words.txt");
не txt
json, csv

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationDictionary.java
> +        try (InputStream inputStream = getClass().getResourceAsStream("/forbidden-words.txt");
Используй спринговый класс для чтения из ресурсов, не пиши столько лишнего кода

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationDictionary.java
> +        try (InputStream inputStream = getClass().getResourceAsStream("/forbidden-words.txt");
ClassPathResource или ResourceUtil.getFile

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationDictionary.java
> +        try (InputStream inputStream = getClass().getResourceAsStream("/forbidden-words.txt");
Почему не в конструкторе?

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationJob.java
> +    @Autowired
Autowired нежелательно

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +public class ModerationPostService {
Сколько у тебя сервисов, почему так много?
Достаточно 3 - джоба, словарь, модератор

Джоба берет все неверифицированные посты, отправляет по подсписку асинхронно в модератор, модератор с помощью словаря в транзакции проверяет каждый пост из подписка, всё

Чем лишние бины городить - убирай тогда @Async и через тред пул в джобе сделай

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +        sublists.forEach(moderationAsyncService::moderatePostsSublistAsync);
Ты внутри транзакции вызываешь асинхронный метод, зачем тебе транзакция, если в ней ничего не обновляется, она фактически рид онли

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +        sublists.forEach(moderationAsyncService::moderatePostsSublistAsync);
moderatePostsSublistAsync выполняется в другом потоке и вообще без транзакции

2024-10-08 11:45 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationPostService.java
> +        sublists.forEach(moderationAsyncService::moderatePostsSublistAsync);
Переделать всё

2024-10-08 11:45 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V005_alter_post.sql
> +    ADD COLUMN verification_status VARCHAR(50) NOT NULL DEFAULT 'UNVERIFIED';
Вот ты же итак дефолтное назначаешь, нафига в энтити присвоение

2024-10-08 11:45 UTC, 20cognosce commented on src/main/resources/forbidden-words.txt
> +anotherbadword
Сделай больше слов, и выбери реальные
Но более менее приличные

fool
idiot
stupid
retard

Вот так достаточно

Русские слова тоже нужны, на двух языках проверяй

2024-10-08 18:01 UTC, kripersh27 commented on src/main/java/faang/school/postservice/config/QuartzConfig.java
> +public class QuartzConfig {
Хотелось попробовать

2024-10-08 18:33 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/post/ModerationDictionary.java
> +        try (InputStream inputStream = getClass().getResourceAsStream("/forbidden-words.txt");
Пост конструкт гарантирует, что бин и зависимости будут полностью инициализированы перед тем, как произойдет загрузка слов из файла, и если вдруг ошибка будет какая-то, то конструктор сломается

2024-10-09 17:48 UTC, 20cognosce requested changes
Пул потоков поправь и можешь мерджить

2024-10-09 17:48 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationJob.java
> +        ExecutorService executorService = Executors.newFixedThreadPool(threadPoolSize);
Почему ты на каждое срабатывание джобы новый экзекьютор создаешь...

2024-10-09 17:48 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationJob.java
> +            }
Да зачем, пусть работает в течение всего рантайма

2024-10-09 17:48 UTC, 20cognosce commented on src/main/resources/forbidden-words.json
> +[
😂

2024-10-09 17:48 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ModerationJob.java
> +            }
Ты ведь если сабмитишь подсписок, и все потоки заняты, то там будет очередь тасок и они будут просто ждать свободного потока

2024-10-09 20:33 UTC, 20cognosce approved these changes

2024-10-10 18:02 UTC, merged