Добавление картинок к посту
CorporationX/post_service pull request #899
Opened 2024-10-03 16:06 UTC by SharkB38

Жду ваших предложений по улучшению и замечаний!

2024-10-03 16:09 UTC, SharkB38 commented
Тесты потом поправлю, когда новые буду писать

2024-10-04 04:10 UTC, ArstanSubanov approved these changes
Отлично написал) Оставил свои комментарии)

2024-10-04 04:10 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto createPost(@Valid @ModelAttribute PostCreationRequest request) {
Интересно) С @ModelAttribute всё работает? Не знал, что так можно сделать)

2024-10-04 04:10 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/dto/post/request/PostCreationRequest.java
> +        List<MultipartFile> filesToAdd
Предложил бы всё таки проверять кол-во файлов в сервисе и там бросать исключение в случае, если превысили лимит, а максимальное кол-во файлов хранить в properties, как думаешь?)

2024-10-04 04:10 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    private void addResourcesToPost(List<MultipartFile> filesToAdd, Post post) {
Я бы ещё посоветовал пересмотреть методы, мне кажется тут излишняя декомпозиция, этот метод вызывается только в updatePostResources, а updatePostResources только в update. Думаю, не было бы проблем всё это в update перенести)

2024-10-04 04:10 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        if (request.filesToDeleteIds() != null) {
Может для проверки на null сделать отдельный метод? Чтобы принимал список и возвращал boolean, что список не пустой например, тогда можно было бы только в методах create, update и remove перед вызовом методов проверять что список не пустой и избавиться от проверки что список не пустой в каждом методе) Но, всё на твоё усмотрение)

2024-10-04 04:10 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/resource/ResourceServiceImpl.java
> +        var sizeExceededMessages = files.stream()
Это не совет, а скорее просьба. Было бы читабельнее, если бы ты писал тип, а не var, так как пока я до конца не прочитаю stream, я не знаю что за тип он вернёт. И в будущем, когда ты через var вернёшь какой-нибудь класс из встроенной библиотеки, будет не очевидно что это за класс, какие методы в нём есть)

2024-10-04 04:13 UTC, SharkB38 commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto createPost(@Valid @ModelAttribute PostCreationRequest request) {
Да все работает, по другому не передать и файлы и дто, а потом понял что так можно файлы в сам дто засунуть

2024-10-04 04:15 UTC, SharkB38 commented on src/main/java/faang/school/postservice/dto/post/request/PostCreationRequest.java
> +        List<MultipartFile> filesToAdd
Сделал так потому что проще, но макс размер вынесу в конфиг

2024-10-04 04:19 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/resource/ResourceServiceImpl.java
> +        var sizeExceededMessages = files.stream()
А кто вообще, что думает по поводу применения var?  Где можно применить, и стоит ли вообще его применять? Давайте обсудим

2024-10-05 16:42 UTC, mysosnovskaya requested changes
У тебя супер-классная работа! Я предположу, что ты знаком с моими комментариями на другие ПРы? Если да, то это очень здорово и спасибо тебе за ответственный подход к работе 👍 Написала небольшие предложения и в следующий раз ещё раз внимательно всё посмотрю)

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/s3/S3Config.java
> +@Component
Здесь лучше Configuration подходит

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/s3/S3Params.java
> +@ConfigurationProperties(prefix = "services.s3")
Молодец!)

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public PostDto createPost(@Valid @ModelAttribute PostCreationRequest request) {
Классно!

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/post/request/PostUpdatingRequest.java
> +        List<Long> filesToDeleteIds,
Молодец, что реализовал именно так 👍 Частая практика

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
>      @PutMapping("/{postId}")
То, как у тебя сейчас выглядит PostUpdatingRequest, это Patch, а не Put

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public record ResourceDto() {
Так и должно быть пустым?

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/resource/ResourceObjectResponse.java
> +        InputStream content,
InputStream это хорошо 👍

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        if (resourcesCountAfterUpdate > 10) {
10 надо вынести в конфиг

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/resource/ResourceServiceImpl.java
> +        resourceRepository.saveAll(resources);
Обрати внимание:
https://github.com/CorporationX/project_service/pull/679#discussion_r1782425067

2024-10-05 16:42 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/resource/ResourceServiceImpl.java
> +    private Resource initResource(String fileKey, Long size, String name, String type, Post post) {
Очень хорошо, что вынес это в отдельный метод 👍

2024-10-05 18:28 UTC, SharkB38 commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public record ResourceDto() {
Я хотел возвращать ресурсы но не придумал как это делать, наверное лучше в PostDto?

2024-10-05 18:29 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        if (resourcesCountAfterUpdate > 10) {
Проглядел

2024-10-05 18:53 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/resource/ResourceServiceImpl.java
> +        resourceRepository.saveAll(resources);
В удаление добавил, а тут забыл

2024-10-05 19:03 UTC, SharkB38 commented on src/main/java/faang/school/postservice/controller/PostController.java
>      @PutMapping("/{postId}")
По идее до этого, когда обновлялся текст поста, это тоже Patch? Если я правильно понял разницу у нас почти везде update это Patch?

2024-10-06 00:44 UTC, SharkB38 commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public record ResourceDto() {
Точнее вопрос в том, возвращать ключ из S3 или само изображение? Или может мне нужны методы в контроллере навроде getAllResourcesFromPost(Long postId) и getResource(Long resourceId)?

2024-10-08 19:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
>      @PutMapping("/{postId}")
Да, до этого тоже Patch был. А вообще у вас и PUT встречается, но чаще как будто бы PATCH, да)

2024-10-08 19:13 UTC, mysosnovskaya reviewed
Конфликт ещё надо поправить)

2024-10-08 19:13 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/resource/ResourceDto.java
> +public record ResourceDto() {
Вообще лучше вернуть ключ в PostDto, тогда фронт ещё отдельно придет за ресурсом (тогда нужны доп эндпоинты)

2024-10-08 19:13 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +            throw new IllegalArgumentException("Can't add more than 10 resources to post with id %d"
10 надо заменить на maxFilesCount

2024-10-09 17:53 UTC, mysosnovskaya approved these changes

2024-10-09 17:53 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/PostController.java
> +    public ResponseEntity<List<byte[]>> getPostResourcesById(@Positive @PathVariable Long postId) {
Вообще я думала, что если в PostDto возвращается список из ID ресурсов, то фронт должен прийти за ресурсами с этими ID. Иначе какой смысл возвращать список ID в PostDto?) 
Поставлю аппрув, можешь поправить (удалить из PostDto поле resources) и иам смержить и закрыть

2024-10-10 02:34 UTC, merged