Публикация постов по расписанию
CorporationX/post_service pull request #900
Opened 2024-10-03 17:28 UTC by Alginin

…ю на определённые дату и время.

2024-10-06 09:02 UTC, Peregruzochka reviewed
very good!

2024-10-06 09:02 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/scheduled/ScheduledPostPublisher.java
> +    @Scheduled(cron = "0 * * * * ?")
вынеси его в yaml

2024-10-06 09:02 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/config/scheduled/ThreadPoolConfig.java
> +        return Executors.newFixedThreadPool(10);
Это значение тоже лучше вынести в yaml

2024-10-06 09:02 UTC, Peregruzochka commented on src/test/java/faang/school/postservice/PostServiceTest.java
> +import static org.assertj.core.api.Assertions.assertThat;
Неиспользуемые импорты

2024-10-09 18:08 UTC, 20cognosce requested changes

2024-10-09 18:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/PostService.java
> +        for (int i = 0; i < posts.size(); i += batchSize) {
По-другому разбивай, посмотри у Андрея либа была удобная

2024-10-09 18:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/PostService.java
> +        int batchSize = 1000;
Это в конфиги

2024-10-09 18:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/PostService.java
> +                postRepository.saveAll(newPost);
Какая тут нафиг транзакция, если это исполняется в другом потоке
Убери @Transactional

Попробуй в джобе сразу вызывать @Async метод для подсписка
И в нём вызывай saveAll, если один метод saveAll вызывается, то @transactional не нужен

2024-10-09 18:08 UTC, 20cognosce commented on src/test/java/faang/school/postservice/PostServiceTest.java
> +    @Test
Где тесты, что это за халтура)))

2024-10-09 18:08 UTC, 20cognosce commented on src/test/java/faang/school/postservice/PostServiceTest.java
> +    @Test
По-настоящему подними контекст и проверь, что джоба отрабатывает на тестовых постах в БД

2024-10-13 10:44 UTC, Alginin commented on src/test/java/faang/school/postservice/PostServiceTest.java
> +    @Test
Я этот тест сделал еле как. А по "настоящему поднять" это нужно интеграционный тест сделать?

2024-10-14 20:44 UTC, 20cognosce approved these changes
Норм

2024-10-18 12:07 UTC, 20cognosce approved these changes

2024-10-18 12:07 UTC, merged