feature-BJS2-26145: Проверка постов на оскорбительный контент
CorporationX/post_service pull request #903
Opened 2024-10-04 03:38 UTC by StepnovaVarvara

Пока без теста на PostService

2024-10-04 11:07 UTC, GusevVrn reviewed
проверил без тестов

2024-10-04 11:07 UTC, GusevVrn commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    private final List<String> dictionary;
Объясни почему List выбрала?

2024-10-04 11:07 UTC, GusevVrn commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public ModerationDictionary(List<String> dictionary) {
нужен ли тут конструктор?

2024-10-04 11:07 UTC, GusevVrn commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    private void createDictionary() {
ну наверное initDictionary, а вообще и просто init() подойдет

2024-10-04 11:07 UTC, GusevVrn commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +            post.setVerified(!containsSwearWord);
у тебя класс словаря занимается установкой значений в post.

Я бы весь этот метод по другому реализовал (вообще странно тестить, когда мою идентичную таску не проверили и я сделал по другому =))
готов послушать других, по предложениям к реализации.

у тебя алгоритм по проверке contains - O(n*m), можно попробовать выйти на более оптимальный

ну и лочить весь метод только на работу с постами не уверен что хорошая идея, т.к. у меня комменты, по сути те же комменты можно было бы в этом методе проверять

2024-10-04 11:07 UTC, GusevVrn commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    List<Post> findReadyToVerified();
посмотри есть ли в Jpa возможность написать метод без Query - типо findПожалуйстаПолеУсловие

2024-10-04 11:07 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/PostService.java
> +            List<Post> subList = unverifiedPost.subList(i, Math.min(unverifiedPost.size(), i + sublistLength));
А вот это зачем?

2024-10-04 11:07 UTC, GusevVrn commented on src/main/resources/application.yaml
> +      count: 5
ты Executor Service объявляешь на всю программу, а настройки для него лежат в модерации

2024-10-04 11:07 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/post_V001__initial.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
Мож я как-то не так прочитал, уже не первый раз вижу что меняют изначальные файлы.
Если я прогоню этот v001, а потом подтяну твои изменения и запущу программу, он прогонит v001 файл еще раз?

2024-10-04 11:07 UTC, GusevVrn commented on src/main/resources/moderation/dictionary.txt
> +шоколад
ну что это такое, начали так хорошо, а потом скатились до шоколада))

2024-10-04 16:04 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public ModerationDictionary(List<String> dictionary) {
Этот конструктор для теста, без него не получалось тест написать

2024-10-04 16:05 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    private void createDictionary() {
Да, ты прав, init лучше, спасибо!

2024-10-04 16:19 UTC, StepnovaVarvara commented on src/main/resources/db/changelog/changeset/post_V001__initial.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
Я думала об этом. Сначала сделала как ты сказал и ликвибейз заворчал на меня, но после перезапуска инфры все отлично заработало) Решила оставить так, потому что у нас как бы проект ток пишется и в БД еще ничего нет

2024-10-04 16:20 UTC, StepnovaVarvara commented on src/main/resources/moderation/dictionary.txt
> +шоколад
Решила закончить на хорошей ноте))

2024-10-04 16:24 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/PostService.java
> +            List<Post> subList = unverifiedPost.subList(i, Math.min(unverifiedPost.size(), i + sublistLength));
А у меня по заданию нужно разбить общий список на подсписки, длина которых определена в ямле, и давать эти подсписки потокам

2024-10-04 18:06 UTC, Silencemess1ah reviewed
![like 300x300](https://github.com/user-attachments/assets/92def2de-d925-4976-b507-92aaf9a3496f)
Гут!

2024-10-04 18:06 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +            post.setVerified(!containsSwearWord);
unverifiedPostS (!), ну да я согласен по логике метода searchSwearWords ищем матюки, а в итоге принимаем пачку постов устанавливаем их и отдаем обратно, на более оптимальный не приходит пока ничего в голову возможно дальше по ходу ревью дойдет что-то

2024-10-04 18:06 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +            post.setVerified(!containsSwearWord);
Ну короче прочитал задачу, да выносить в пост сервис это по хорошему, как он есть и в основном методе вызывать, насчет логики сделать это быстрее придумал такой вариант ; вместо List<String> для словаря использовать Set это заодно и проверит уникальность если были дубликаты при составлении файла, и скорость доступа повысит, есть в куче ? да нет и погнали сеты нужные

2024-10-05 10:35 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    private final List<String> dictionary;
я тут уже немножко поменяла)) Переделала на Set, но често говоря не совсем понимаю в чем проблемс с List, тк сильно это нам жизнь не облегчит

2024-10-05 11:59 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +            post.setVerified(!containsSwearWord);
Супер комменты! Большое спасибо, переделала)

2024-10-05 13:11 UTC, StepnovaVarvara commented on src/main/resources/application.yaml
> +      count: 5
Хорошо, поправила

2024-10-05 15:37 UTC, mysosnovskaya requested changes
У тебя супер-крутая работа получилась, но, пожалуйста, разберись с миграциями) После этого я ещё раз посмотрю всё внимательно.

2024-10-05 15:37 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/post_V001__initial.sql
> +    updated_at timestamptz DEFAULT current_timestamp,
Нет, так дело не пойдет) Сложность задачи как раз в том, чтобы разобраться с миграциями. Что это такое, для чего используется и как применять. Поэтому тебе обязательно нужно сделать отдельную миграцию. Если хочется, то можем поговорить об этом голосом на следующем созвоне)

2024-10-06 06:31 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostService(@Value("${post.moderation.sublist.length}") Long sublistLength,
Маша, у меня вот тут вопросик появился -  я конструктор такой делаю, тк без него у меня в тестах поле, значение которого должно подтянуться из app.yaml, все время равно 0. Вот этого момента можно как-то избежать? А то получается, что был красивый код, а я своими конструкторами всю красоту испортила

2024-10-06 07:37 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostService(@Value("${post.moderation.sublist.length}") Long sublistLength,
Может application-test.yaml создать? И там описать тоже самое, чтоб тесты оттуда данные подтягивали

2024-10-06 22:57 UTC, mysosnovskaya requested changes

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private void initDictionary() {
Я бы предложила сделать это в конструкторе:
```
public Dictionary( @Value("${post.moderation.dictionary.file-path}") String filePath) {
...
}
```

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +                dictionary.add(line.toLowerCase().trim());
А у тебя dictionary не null?

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    List<Post> findReadyToVerified();
Должно быть можно, но это выходит за рамки задания. Поэтому исправлять необязательно, хотя было бы круто)

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostService(@Value("${post.moderation.sublist.length}") Long sublistLength,
А конструктор от ломбока не подходит?

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +                    postRepository.save(post);
Лучше собрать все посты в кучку и потом все вместе сохранить через saveAll - так будет эффективнее, т.к. будет меньше запросов к базе данных

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public Map<Long, Boolean> searchSwearWords(Map<Long, String> unverifiedContent) {
Очень сложно понять, что такое `Map<Long, String>` и `Map<Long, Boolean>` и что этот Boolean возвращает. То ли true - всё ок, то ли true - содержит недопустимый контент. Может быть было бы лучше передать сюда список постов и сразу проставить им verified, а метод сделать void?

2024-10-06 22:57 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    @Value("${post.moderation.dictionary.file-path}")
В идеале в конструктор этого класса должен приходить сразу готовый `Set<String>`, чтобы иметь возможность брать слова из разных источников: например, из стороннего сервиса. Так класс будет гибче и проще в тестировании. Сейчас при тестировании ты вообще игнорируешь то, что данные берутся из файла)

2024-10-07 16:05 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +                dictionary.add(line.toLowerCase().trim());
Перепроверила, точно не null

2024-10-07 16:06 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    @Value("${post.moderation.dictionary.file-path}")
Попробовала сделать оба поля через конструктор. Работает

2024-10-07 16:07 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private void initDictionary() {
Метод инит убрала и сделала просто через конструктор

2024-10-07 16:18 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public Map<Long, Boolean> searchSwearWords(Map<Long, String> unverifiedContent) {
Блин, я так сделала в первый раз)) Но ребята сделали мне замечание в части того, что метод не универсальный и зациклин только на постах. Мне прям понравилось это замечание!) Соответственно я переделала метод, чтобы можно было проверять контент не только в постах, а и еще в комментариях и тд. Не очень хочу его менять, но как скажешь))

2024-10-07 16:22 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/PostService.java
> +                    postRepository.save(post);
Согласна, переделала!

2024-10-07 16:34 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private void initDictionary() {
Начала проверять и с конструктором не работает) Оставила как было))

2024-10-07 17:00 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostService(@Value("${post.moderation.sublist.length}") Long sublistLength,
Не могу это побороть! Не работает ни через AllArgsConstructor, ни через application-test.yaml

2024-10-08 01:23 UTC, mysosnovskaya requested changes
Нужно разобраться с тем, почему не работает код в каком-то другом варианте. Лучше не оставлять его таким просто потому, что так работает, а по-другому - нет. На будущее: в комментариях лучше сразу подробно описывай, почему не работает и как ты это видишь, так мы быстрее сможем разобраться с причиной)

2024-10-08 01:23 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private void initDictionary() {
Почему не работает? Какая ошибка?

2024-10-08 01:23 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +                dictionary.add(line.toLowerCase().trim());
А кто его инициализирует? Ломбок?

2024-10-08 01:23 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public Map<Long, Boolean> searchSwearWords(Map<Long, String> unverifiedContent) {
Обобщения не должны мешать пониманию кода. Если хочется прям красиво обобщить, тогда нужно сделать интерфейс Verifyible с методами по работе с полями verified и verifiedAt и в этот метод принимать `List<Verifyible>`. А дальше всё как я выше написала)

2024-10-08 01:23 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/PostServiceTest.java
> +    @InjectMocks
Если ты самостоятельно в BeforeEach создаешь postService, то эта аннотация не нужна

2024-10-08 01:23 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/PostService.java
> +    public PostService(@Value("${post.moderation.sublist.length}") Long sublistLength,
Я не понимаю, почему не работает через AllArgsConstructor, если ты в тесте делаешь
`postService = new PostService(SUBLIST_LENGTH, postMapper, postRepository, moderationDictionary, executor);`
Какая ошибка и на каком этапе?

2024-10-08 12:03 UTC, StepnovaVarvara commented on src/test/java/faang/school/postservice/service/PostServiceTest.java
> +    @InjectMocks
Машаааа, получилось! Больше не буду портить всем код))

2024-10-08 12:05 UTC, StepnovaVarvara commented
> Нужно разобраться с тем, почему не работает код в каком-то другом варианте. Лучше не оставлять его таким просто потому, что так работает, а по-другому - нет. На будущее: в комментариях лучше сразу подробно описывай, почему не работает и как ты это видишь, так мы быстрее сможем разобраться с причиной)

Сделала!) Проблема решалась одной строчкой, капец!)

2024-10-08 21:14 UTC, mysosnovskaya requested changes
Я увидела только одно исправление - в тесте, а я ещё жду исправлений по searchSwearWords и initDictionary. Ну либо вопросы/аргументы против)
И не забудь конфликт поправить

2024-10-09 03:52 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private void initDictionary() {
Не работал, тк dictionary был final, без final все работает. Честно говоря, я не поняла зачем я это переделывала... Логика в том, что типо зачем нам постконстракт, если есть конструктор, через который мы можем это сделать или как??

2024-10-09 03:58 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +                dictionary.add(line.toLowerCase().trim());
Видимо, да. Когда он final, тогда не null

2024-10-09 18:31 UTC, StepnovaVarvara commented
> Я увидела только одно исправление - в тесте, а я ещё жду исправлений по searchSwearWords и initDictionary. Ну либо вопросы/аргументы против) И не забудь конфликт поправить

Маш, по поводу searchSwearWords - я написала, что не очень хочу менять, но поменяла) По initDictionary - поменяла, но не поняла почему этот вариант лучше, чем тот, который был до

2024-10-09 20:19 UTC, mysosnovskaya requested changes

2024-10-09 20:19 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private Set<String> dictionary;
Должно работать с final, если ты сделаешь инициализацию этого поля в конструкторе (dictionary = new ...). А то сейчас ломбок для него сеттер добавит, а это может привести к ошибкам

2024-10-09 20:19 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private String filePath;
Это поле для чего-то нужно? По-моему оно нужно только для инициализации dictionary, поэтому как поле его выделять не нужно, достаточно в конструкторе с ним поработать

2024-10-09 20:19 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    public Dictionary(@Value("${post.moderation.dictionary.file-path}") String filePath, Set<String> dictionary) {
Да, я не понимаю, зачем нужен PostConstructor и зачем хранить поле filePath. Это усложнения, которые пока для меня не аргументированы.

2024-10-09 20:19 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +            throw new RuntimeException("Failed to read file", ex.getCause());
Хорошо было бы имя файла добавить в сообщение об ошибке

2024-10-09 20:19 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public List<Post> searchSwearWords(List<Post> unverifiedPosts) {
Я тебе предлагала сделать красивый вариант, который будет обобщенным (не только для постов) и будет понятным:
https://github.com/CorporationX/post_service/pull/903#discussion_r1791056738
Т.е. я поддерживаю твое желание сделать обобщенное, но с `Map<Long, String>` так оставлять нельзя. Поэтому я предлагала другой вариант. Теперь я настоятельно рекомендую реализовать именно его, т.к. это как раз то, что ты хотела, только правильно оформленное)

2024-10-12 10:33 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private Set<String> dictionary;
Поняла, сделала

2024-10-12 10:49 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +            throw new RuntimeException("Failed to read file", ex.getCause());
Добавила

2024-10-12 14:27 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/ModerationDictionary.java
> +    public List<Post> searchSwearWords(List<Post> unverifiedPosts) {
Переделала, вроде бы правильно тебя поняла)

2024-10-12 14:29 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    private String filePath;
Очень необычно, но смысл я поняла

2024-10-12 14:29 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Dictionary.java
> +    public Dictionary(@Value("${post.moderation.dictionary.file-path}") String filePath, Set<String> dictionary) {
Переделала

2024-10-12 18:36 UTC, mysosnovskaya requested changes
Красота!) Ещё чуть-чуть поработаем над интерфейсом и закроем задачу

2024-10-12 18:36 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Verifyible.java
> +public interface Verifyible {
Verifiable кажется правильно)

2024-10-12 18:36 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/moderation/Verifyible.java
> +    void setVerificationValue(boolean result);
Почему бы не назвать эти методы стандартно:
```
    void setVerified(boolean verified);
    void setVerifiedDate(LocalDateTime verifiedDate);
    String getContent();
```
Тогда и ломбоковские методы должны отработать, не придется их заново имплементировать

2024-10-12 19:03 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Verifyible.java
> +public interface Verifyible {
Переделала

2024-10-12 19:09 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/moderation/Verifyible.java
> +    void setVerificationValue(boolean result);
Сделала

2024-10-13 14:21 UTC, mysosnovskaya approved these changes

2024-10-13 14:21 UTC, merged