AI орфография BJS2-26888
CorporationX/post_service pull request #905
Opened 2024-10-04 15:11 UTC by Peregruzochka

2024-10-06 09:11 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/config/context/YandexSpellerConfig.java
> +public class YandexSpellerConfig {
для удобства я бы поместил не в директорию context, а на уровень выше в config

2024-10-06 09:11 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +        StringBuilder correctedText = new StringBuilder(text);
Алгоритм очень расточительный получился
Для каждого изменения будет внутри перекопирование происходить в StringBuilder.
можно было сделать его сперва пустым и последовательно копировать слова, которые без ошибок, а как только встретилась опечатка, достать ее из checkers и вставить в StringBuilder

2024-10-06 09:11 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +    private String addParamToUrl(String param, String value, String url) {
в качестве удобство чтения я бы расположил входные параметры в последовательности той, как будет выглядеть url --->
url, param, value;


а еще метод прикольный и полезный,  его можно вынести в utils куда-нибудь
и вместо передачи String param, String value, передавать 
Map<String, String> params
Но это по желанию)'

2024-10-06 09:11 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +    public List<SpellCheckerDto> recoverCheckText(RestClientException exception, String text) {
Не нужен метод получается?

2024-10-06 09:11 UTC, DankeVilletti commented
Пару дней назад сделал комментарии и не отправил получается 😅

2024-10-06 16:19 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +    public List<SpellCheckerDto> recoverCheckText(RestClientException exception, String text) {
Оу ноу, этот метод запускаются, после того, как заканчиваются попытки после `@Retryable`, а exception все равно выбрасывается

2024-10-09 20:30 UTC, 20cognosce requested changes
В целом чисто, но и кода не много

2024-10-09 20:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/YandexSpellerConfig.java
> +        return new YandexSpeller(url, new RestTemplate());
Можно было бы и бином создать специальный RestTemplate для Яндекса

2024-10-09 20:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/SpellCheckerDto.java
> +    private List<String> s;
Не экономь на буквах

2024-10-09 20:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/PostService.java
> +                String correctedText = yandexSpeller.correctText(text, checkers);
Прошу на дейли провести демо этой фичи

2024-10-09 20:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +        StringBuilder correctedText = new StringBuilder(text);
При оптимизации / утечке памяти опасен не размер стрингов, а их количество

2024-10-09 20:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +        StringBuilder correctedText = new StringBuilder(text);
Если по одному слову вычленять и перекопировать - наоборот это просадка по памяти была бы дикая

2024-10-09 20:30 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/tools/YandexSpeller.java
> +        return url + param + "=" + value;
Вот это шляпа полная
Поищи класс UriBuilder в спринге

2024-10-09 20:30 UTC, 20cognosce commented on src/main/resources/application.yaml
> +      cron: "0 0 0 * * ?" # every day in 00:00
Пользователь заходит на следующий день и его пост
"babygirl" превращается в "baby gorilla"

Давай каждую минуту, сколько за сутки постов накопится

Иначе эта фича тупо никогда не будет запускаться в проекте

2024-10-09 20:30 UTC, 20cognosce commented on src/test/java/faang/school/postservice/PostServiceTest.java
> +    public void testCorrectAllDraftPosts_Success() {
Че так мало тестов

2024-10-10 13:26 UTC, Peregruzochka commented
Добавил поле в таблицу, о том что пост проверен
Раз в минуту достаю из базы непроверенные посты

2024-10-10 17:28 UTC, 20cognosce approved these changes

2024-10-10 17:28 UTC, merged