BJS2-26136 - Проверка комментариев на оскорбительный контент
CorporationX/post_service pull request #911
Opened 2024-10-04 22:16 UTC by GusevVrn

Осталось переработать x-user-id для хедера
Добавить тесты ModeratorService, OffensiveDictionaryService, OffensiveWordsDictionary

2024-10-05 21:19 UTC, Silencemess1ah reviewed
Огонь, я пытался докопаться, но не нашел до чего

2024-10-06 16:26 UTC, GusevVrn commented
Поправил хедеры, возможно что-то на запутанном но это самое оптимальное до чего додумался.
Изначально брал url и разбивал его сплитом через ":" но сильно код получится прибитый.
Так не совсем оптимально O(n*m) - но зато в 5 строчек и через contains точно будем уверенны в том входит сервис в url или нет)

2024-10-06 23:08 UTC, mysosnovskaya requested changes

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/client/FeignUserInterceptor.java
> +        headerMapping.put("x-user-id", () -> String.valueOf(userContext.getUserId()));
x-user-id было бы хорошо в константу вынести)

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +    private static final Set<String> offensiveDictionary = new CopyOnWriteArraySet<>();
Почему статик?

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +    public static void addWordsInDictionary(List<String> newWords) {
addWordsToDictionary

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +            Path path = Paths.get(Objects.requireNonNull(getClass().getClassLoader()
В идеале данный класс не должен зависеть именно от файла, т.к. теоретически данные для словаря могут быть взяты откуда угодно (например, из стороннего сервиса). И тогда будет лучше, если этот класс просто в конструктор примет `Set<String>`

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/ContentModeratorScheduler.java
> +        moderatorService.moderateCommentsContent().join();
А зачем делать moderateCommentsContent асинхронным, если ты его всегда используешь синхронно?

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/OffensiveDictionaryScheduler.java
> +    //@Scheduled(cron = "${dictionary.offensive.remote.scheduler.cron}")
Если не нужно - нужно удалить

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    public void verify(Comment comment, boolean isVerified) {
Название метода некорректное. Оно говорит о том, что этот метод проверят комментарий, а по факту это не так

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        saveComment(comment);
Сохранять комментарии по одному не эффективно, подумай, можно ли их сохранять сразу пачкой через saveAll

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/dictionary/OffensiveDictionaryService.java
> +    private void updateRussianOffensiveWords() {
Обязательно подумай про обработку ошибок. Здесь нас Global Exception Handler не спасет, т.к. методы вызываются не по http. Это общее замечание для всех методов, вызываемых не по http, а через джобу по расписанию.
Пока достаточно просто залоггировать ошибку. На реальных проектах были бы оповещения на почту/в телеграмм

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/moderator/ModeratorService.java
> +                            @Qualifier("cachedExecutor") ExecutorService executorService) {
А зачем Qualifier? У тебя же есть Primary над бином

2024-10-06 23:08 UTC, mysosnovskaya commented on src/main/resources/dictionary/offensive-words.yaml
> +Варя запретила мне писать сюда слова
=)

2024-10-07 11:10 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +    private static final Set<String> offensiveDictionary = new CopyOnWriteArraySet<>();
У меня такая логика что весь этот класс утильный. И методы ниже тоже статические чтоб этот класс не инжектить никуда.
Если я статик убираю то статические методы ругаются.

2024-10-07 11:11 UTC, GusevVrn commented on src/main/java/faang/school/postservice/scheduler/ContentModeratorScheduler.java
> +        moderatorService.moderateCommentsContent().join();
Короче, какая идея: 
Проверять раз в день не оч. Я сделал проверку комментариев каждый час после завершения предыдущего, чтоб задвоения в работе не было. 
Мы запускаем по расписанию, в отдельном же потоке? Вот, этот поток запустил moderateCommentsContent - но чтоб следующую проверку сделать через час, нам необходимо дождаться завершения работы

2024-10-07 11:11 UTC, GusevVrn commented on src/main/java/faang/school/postservice/scheduler/OffensiveDictionaryScheduler.java
> +    //@Scheduled(cron = "${dictionary.offensive.remote.scheduler.cron}")
По заданию надо было cron использовать, я его сюда зарядил, словарь можно и раз в день обновлять. Просто неудобно проверять, добавил initialDelay для проверки как работает и забыл убрать.

2024-10-07 11:11 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/dictionary/OffensiveDictionaryService.java
> +    private void updateRussianOffensiveWords() {
Тут именно про глобальный handler listener запросы feign или достаточно того как я сделал?

2024-10-07 11:16 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +            Path path = Paths.get(Objects.requireNonNull(getClass().getClassLoader()
Не могу допетрить. Я сделал так чтобы у нас был изначальный какой-то список слов, а потом уже наполнение - придет не придет/ обновится не обновится, нам уже все равно.
Если я инициализацию убираю. В чем разница будет, я делаю еще один бин, где инициализирую список начальных слов. Дергаю метод addWords и все. Просто именно инициализацию выношу.
Потом если решим инициализировать не через ресурсы, а через feign к примеру, делать отдельный бин, .. получаем список изначальных слов и вызываем addWords.
Просто больше свободы будет что ли. А если у нас вообще слова вдруг не инициализируются.

2024-10-08 00:56 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +    private static final Set<String> offensiveDictionary = new CopyOnWriteArraySet<>();
А что плохого в инжекте?) У тебя кстати аннотация Component висит)

2024-10-08 01:11 UTC, mysosnovskaya requested changes

2024-10-08 01:11 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/dictionary/OffensiveWordsDictionary.java
> +            Path path = Paths.get(Objects.requireNonNull(getClass().getClassLoader()
А какой смысл в изначальном пустом списке слов? Я предлагаю здесь добавить конструктор (можно через ломбок):
```
public OffensiveWordsDictionary(Set<String> offensiveDictionary) {
...
}
```
Затем создать бин типа `Set<String>`, который бы создавался из файла. Так будет правильнее с точки зрения зависимостей частей кода друг от друга, чтобы у тебя не была "прибита гвоздями" реализация именно через файл. Если нам потребуется когда-то обновить то, откуда мы берем слова, то мы просто добавим новый бин `Set<String>` и будем пользоваться им. Да даже если никогда не добавим, чисто логически данный класс никак не должен зависеть от файла. Он всего лишь словарь и ему неважно, откуда взялись слова. Single responsibility :)

2024-10-08 01:11 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/ContentModeratorScheduler.java
> +        moderatorService.moderateCommentsContent().join();
Это я поняла, но имеет ли смысл делать moderateCommentsContent асинхронным тогда? Пусть будет синхронным. Как будто бы смысл его асинхронности теряется из-за этого join

2024-10-08 01:11 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    public void setVerifyToComment(Comment comment, boolean isVerified) {
А эту логику точно надо в сервис выносить? Как-то слишком мелко для сервиса (даже в базу данных обращения нет). Может оставить его там, где он нужен? Приватным методом

2024-10-08 01:11 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/dictionary/OffensiveDictionaryService.java
> +    private void updateRussianOffensiveWords() {
Я бы не останавливалась только на FeignException. Могут возникнуть какие угодно исключения, хоть с базой данных, хоть NPE. Каждое из них обязательно должно быть как минимум залоггировано

2024-10-08 17:16 UTC, GusevVrn commented on src/main/java/faang/school/postservice/scheduler/ContentModeratorScheduler.java
> +        moderatorService.moderateCommentsContent().join();
давай так, я тебя чуть понял, что нету в этом смысла если мы все равно ждем тут завершения

2024-10-08 17:19 UTC, GusevVrn commented
Там 2 теста где runAsync, я шаблон накидал, но он не проходит, просто в одном сервисе где обновление словаря дергает асинхронно и все, в другом сервисе в принципе аналогичная ситуация. Даже идей нету

2024-10-08 21:07 UTC, mysosnovskaya requested changes

2024-10-08 21:07 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/ContentModeratorScheduler.java
> +        log.info("moderateComments() - finish");
Теперь ты убрал join для moderateCommentsContent и вот эта строчка в логах появится раньше, чем по факту завершится модерация. Я думала, что moderateCommentsContent вообще не делать асинхронным, раз ты нигде этим не пользуешься. Или здесь сделать так, чтобы логирование произошло только тогда, когда модерация завершится. Но без join)

2024-10-08 21:07 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/moderator/ModeratorServiceTest.java
> +    void test() {
Этот тест не компилируется, не могу посмотреть

2024-10-08 21:07 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/dictionary/OffensiveDictionaryServiceTest.java
> +    void whenFeignRuAndEngReturnSmthThenUpdateDictionary() {
Здесь, во-первых, лучше сделать так, чтобы updateOffensiveDictionary вернул `CompletableFuture<Void>` (вспомни, как две в одну запаковать), и здесь сделать join, а во-вторых, мокнутый ExecutorService не дает CompletableFuture запуститься. Вместо мока создай реальный и подставь его в OffensiveDictionaryService

2024-10-08 21:07 UTC, mysosnovskaya commented on src/test/java/faang/school/postservice/service/dictionary/OffensiveDictionaryServiceTest.java
> +    void whenFeignRuAndEngReturnSmthThenUpdateDictionary() {
Думаю, во втором тесте была такая же проблема из-за мокнутоно тред пула)

2024-10-08 21:08 UTC, mysosnovskaya commented
И конфликт не забудь поправить)

2024-10-09 17:02 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/moderator/ModeratorServiceTest.java
> +    void test() {
Он продолжает надо мной издеваться, когда я по отдельности их запускаю все нормально когда вместе начинаю гонять то проверяет слова 2 раза вместо 4, то передает false вместо true.
Изменение типа executor не повлияло никак.
все эти тесты последнее время заставляют задуматься об умственных способностях

2024-10-09 20:45 UTC, mysosnovskaya requested changes

2024-10-09 20:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/moderator/ModeratorService.java
> +        log.info("moderateCommentsContent() - finish");
Ты запускаешь задачи асинхронно (через executorService.execute), нигде не дожидаешься их окончания, а выводишь в лог "moderateCommentsContent() - finish" - это неправда. Из-за этого и тест не работает: тест завершается быстрее, чем проставляется TRUE в комментарий. Вот с этим нужно что-то делать. В тесте если ты перед 
`assertEquals(Boolean.TRUE, comment.isVerified());`
поставишь `Thread.sleep(2000);`, то всё сработает, но это, конечно, костыль. Подумай, как это всё сделать правильно)

2024-10-10 19:08 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/moderator/ModeratorService.java
> +        log.info("moderateCommentsContent() - finish");
Мдеееее

2024-10-10 19:16 UTC, mysosnovskaya approved these changes

2024-10-10 19:17 UTC, merged