Cerberus master stream6 bjs2 26702 user ban
CorporationX/post_service pull request #912
Opened 2024-10-04 23:53 UTC by DenysDovgan

2024-10-05 09:34 UTC, ostermal7 reviewed
Тесты не смотрел, т.к. много чего поменять надо. Логку verified бери из таски, которая на ревью, т.к. она уже прописана, а написанная тобой идет в конфликт с ней. Все переменные всегда должны определяться в конфиг файле, а не внутри классов.
Изера часть пока не сморел

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        // Using StringRedisSerializer for keys
их вообще лучше убрать, я случайно оставил изначально)

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        return new ChannelTopic("ban-commenters-by-id");
название топика в ямл, в таски просят его назвать user_ban

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/scheduler/CommenterBanner.java
> +    private final CommentServiceImpl commentService;
не имплементация, а интерфейс

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/scheduler/CommenterBanner.java
> +    private final int unverifiedCommentsLimit = 5;
все переменный в конфиг файл

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/scheduler/CommenterBanner.java
> +    }
нарушение solid. У этот класс должен отвечать только за запуск по расписанию, остальная логика в сервисе

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/scheduler/CommenterBanner.java
> +        );
сомнительная конструкция из сервиса с сервисом внутри)

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +                .toList();
плохое решение. Если у тебя будет полтора миллиона комментов, то ты их все будешь тащить из базы, а потом фильтровать?

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +    }
зачем этот метод? Да еще и в интерфейса его определять

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/hashtag/HashtagServiceImpl.java
> +    public List<Hashtag> processHashtags(Post post) {
зачем ты его публичным сделал?

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +
зачем пробел?

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/user/UserIdsPublisher.java
> +package faang.school.postservice.service.user;
этот класс не в сервис пакет, а в пакет publisher

2024-10-05 09:34 UTC, ostermal7 commented on src/main/java/faang/school/postservice/service/user/UserIdsPublisher.java
> +    }
Ты должен передавать не непонятно какой объект, а конкретную эвент реализацию (посмотри видос влада, он там объясняет)

2024-10-05 09:34 UTC, ostermal7 commented on src/main/resources/db/changelog/changeset/post_V005_addcommentcolumn.sql
> +ALTER TABLE comment ADD COLUMN verified boolean DEFAULT false NOT NULL;
Почему ты делаешь так? Ты ломаешь полностью логику моей таски, тебе надо было брать логику с нее. Надо исправить

2024-10-05 09:34 UTC, ostermal7 commented on src/main/resources/db/drop.sql
> +DROP TABLE IF EXISTS posts_hashtags;
сомнительное изменение, лучше оставь как есть

2024-10-05 13:49 UTC, DenysDovgan commented on src/main/java/faang/school/postservice/service/hashtag/HashtagServiceImpl.java
> +    public List<Hashtag> processHashtags(Post post) {
![image](https://github.com/user-attachments/assets/cd0ff56a-e47c-4db4-9de6-1e6be8f8863d)

2024-10-05 13:49 UTC, DenysDovgan commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +
Случайно

2024-10-05 14:06 UTC, DenysDovgan commented on src/main/resources/db/changelog/changeset/post_V005_addcommentcolumn.sql
> +ALTER TABLE comment ADD COLUMN verified boolean DEFAULT false NOT NULL;
Так у тебя Пост а у меня Комменты

2024-10-05 15:34 UTC, ostermal7 commented on src/main/resources/db/changelog/changeset/post_V005_addcommentcolumn.sql
> +ALTER TABLE comment ADD COLUMN verified boolean DEFAULT false NOT NULL;
там есть и таска на комменты, я обе сделал

2024-10-07 08:29 UTC, ostermal7 commented
Ты проверял как работает редис? Он падает

2024-10-07 20:26 UTC, mikhailov26 requested changes
В целом всё хорошо, проведи рефакторинг по шаблону, который в дс писал

2024-10-07 20:26 UTC, mikhailov26 commented on src/main/java/faang/school/postservice/service/hashtag/HashtagServiceImpl.java
> +    public List<Hashtag> processHashtags(Post post) {
Всё верно транзакционные методы не могут быть приватными

2024-10-10 18:00 UTC, merged