BJS2-27273 - [Experienced] Проверка постов на оскорбительный контент
CorporationX/post_service pull request #913
Opened 2024-10-05 09:58 UTC by dmitridorje

2024-10-07 16:20 UTC, mikhailov26 requested changes
Переделать по требованиям из сообщения в дискорде

2024-10-12 11:45 UTC, dmitridorje commented
> Переделать по требованиям из сообщения в дискорде

Создал интерфейс PostService, его реализацию в пакете /impl, и разрешил возникшие конфликты бинов и имён.

2024-10-13 12:34 UTC, mikhailov26 approved these changes

2024-10-13 12:34 UTC, mikhailov26 commented
решаем конфликты и мержим

2024-10-14 13:42 UTC, merged