BJS2-27035 Система лайков
CorporationX/post_service pull request #914
Opened 2024-10-05 12:20 UTC by evgenywork

2024-10-05 14:20 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +    }
Много похожих методов
Можно создать одно своё общее кастомное исключение с общей структурой, от него наследовать свои исключения(со своими названиями и статусами), и его же передавать в параметр@ExceptionHandler, при этом вместо трех, оставить только один метод

2024-10-12 14:31 UTC, evgenywork commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +    }
Спасибо , сделал . Оказывается уже было универсальное исключение

2024-10-14 20:13 UTC, 20cognosce requested changes

2024-10-14 20:13 UTC, 20cognosce commented on env.example
> +ENV_JDBC_PASSWORD=pass
Надеюсь ты проверил, что твой local профиль не аффектит тех, кто остается на дефолтных настройках

2024-10-14 20:13 UTC, 20cognosce commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
А можно обобщить все хэндлеры, ну дублирование кода в большинстве случаев
Вам надо просто мапить класс ошибки на респонс статус и описание, все остальное одинаково ведь

2024-10-14 20:13 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/album/AlbumService.java
> +                    .map(UserResponseShortDto::getId).toList().contains(userId);
Выглядит костыльно

2024-10-14 20:13 UTC, 20cognosce commented on src/main/java/faang/school/postservice/validator/UserValidator.java
> +            userServiceClient.getUser(userId);
Не понял, а если тебе сервер отдает 400/500 но у тебя не выпадает эксепшена при запросе
Ты хоть проверь по существу, что юзер реально есть, что ответ не пустой там

2024-10-14 20:13 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +            throw new RecordAlreadyExistsException(
Прям ошибку кидать не кажется жестко? Ну нажал еще раз, ну ладно

2024-10-14 20:13 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +    @Transactional
readonly = true

2024-10-14 20:13 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +        }
Аналогично

2024-10-15 07:50 UTC, evgenywork commented on src/main/java/faang/school/postservice/validator/UserValidator.java
> +            userServiceClient.getUser(userId);
как раз в catch я это и делаю , я тестировал все работает , как надо. 
я только проверяю если такого юзера нет , то лучше сообщить об этом.

2024-10-15 07:52 UTC, evgenywork commented on env.example
> +ENV_JDBC_PASSWORD=pass
естественно. он переписывает главный кофиг если сделать билд или в идее добавить параметр локал

2024-10-15 07:54 UTC, evgenywork commented on src/main/java/faang/school/postservice/exception/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Да , согласен . я это фиксил уже , просто этот коммит видно потерял

2024-10-15 08:19 UTC, evgenywork commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +    @Transactional
не понял , я же создаю лайк. 
если ты про эту строчку `Post post = postService.findPostById(postId);` , то в PostService она в readonly = true

2024-10-15 08:22 UTC, evgenywork commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +            throw new RecordAlreadyExistsException(
Я же не клиенту ее напрямую кидаю , я кидаю фронту , так как он ожидает от меня ответ , 200 я думаю не корректно отсылать .  на фронт будет приходить такой ответ `CONFLICT(409, HttpStatus.Series.CLIENT_ERROR, "Conflict"),` , а фронт уже решит , показывать или не показывать .

2024-10-15 08:23 UTC, evgenywork commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +        }
выше, для поста отписал

2024-10-15 08:28 UTC, evgenywork commented on src/main/java/faang/school/postservice/validator/UserValidator.java
> +            userServiceClient.getUser(userId);
я этот вопрос поднимал на одном из совещаний , как Иван реализовал `UserServiceErrorDecoder` он сказал , что не знает и просто скопировал откуда то, там вся логика по обработке ошибок , когда мы работаем через FeignClient. поэтому , если ты посмотришь ниже там в блоке catch идет отлов ошибке на то что ответ 404 и клиент работает , просто юзера с таким ID нет. А все остальные кейсы просто дальше прокидываем в else. там будет как раз 500я. тестировал все работает.

2024-10-18 11:59 UTC, 20cognosce approved these changes

2024-10-18 12:00 UTC, merged