BJS2-27078 AI орфография
CorporationX/post_service pull request #919
Opened 2024-10-05 15:03 UTC by cemeh666

2024-10-05 15:37 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +    @Retryable(retryFor = {RepeatableServiceException.class}, backoff = @Backoff(delay = 2000, multiplier = 2))
Магические числа тут, можно в апликейшн убрать

2024-10-05 15:37 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +        if (statusCode > 500) {
В константу вынести лучше

2024-10-05 15:37 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/client/external/spelling/YandexSpellerClient.java
> +        URI uri = UriComponentsBuilder.fromHttpUrl(serviceUrl)
Построение uri лучше вынести в отдельный метод, вдруг потом добавлять или корректировать что-то нужно будет

2024-10-05 15:37 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/client/external/spelling/YandexSpellerClient.java
> +            if (statusCode >= 400 && statusCode < 500) {
Магические числа

2024-10-05 15:37 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +    public void startCheckAISpellingPosts() {
Объемный метод, который отвечает за несколько задач сразу, лучше разделить

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +    }
Не знаю где как принято, я обычно видел, что всякие бины в @Configuration классах объявляются.

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +    private final PostService postService;
можно пустую строку оставить, чтобы константы от бинов визуально отделить

2024-10-05 18:51 UTC, amilosh commented on src/main/resources/application.yaml
> +      cron: "0 0 0 * * *"
допиши плиз камент как вот сверху, типа каждый день в 00 минут 00 секнд

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +                    Sort.by("id").ascending());
из php наверное такой синтаксис
в джава обычно всё в одну строку пишут
я например уже так привык, и когда вижу несколько строк - непривычно. а в одну строку сразу привычно становится

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            }
да, тожt думаю что можно в приватный

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            draftPosts = postRepository.findDraftsPaginate(pageable);
там вытягиваются посты с p.published = false
а какое flow опубликования постов?
пост может стать published = true до того, как будет проверка?

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +                .queryParam("text", text)
(String url, String text)
чтобы параметры слева направо в порядке использования шли

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsCorrectResponse.java
> +    private Integer error_code;
этот сервис возвращает json с полем error_code?
если получится быстро, попробуй загуглить чтобы поле в Java было по конвенции errorCode

@КакаятоАннотация   // которая мапит error_code из джейсона в errorCode
private Integer errorCode;

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +        if (statusCode > 500) {
Поискать, эта 500 должнна быть в каких-то спрингоdых константах или енамах
типа HttpRsponse
Internal_server_error, 500

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +            throw new DontRepeatableServiceException();
Сверху где ворнинг - норм
А тут я бы пустую строку убрал
Для меня

log.error(...);
throw new ...;

как одним атомарным блоком идёт, потому что везде используется

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +            throw new DontRepeatableServiceException();
Или есть ещё подход когда throw new DontRepeatableServiceException("Сервис корректировки вернул ошибку {}");

а exeption.getMessage() логируешь уже в controller advice

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +        return lang;
return TextGearsLang.fromString(response.getResponse().getLanguage());

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/SpellingCorrectionService.java
> +        if (lang.equals(TextGearsLang.RU)) {
енамы через равно можно проверять
+ в статический импорт вынести
 if (lang == RU)) {

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +            throw new DontRepeatableServiceException();
а всё
дальше по коду увидел
ты там просто логируешь

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsCorrectResponse.java
> +    private boolean status;
можешь объяснить, что то за булевский status?

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLang.java
> +        }
TextGearsLang.values() - из этой штуки можно статическю Map сделать
и тогда всякий раз не по TextGearsLang.values() пробегаться, а из мапы по ключу брать

2024-10-05 18:51 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/spelling_corrector/yandex_speller/YandexSpellerCorrectResponse.java
> +    private List<String> s;
это яндекс так возврщает?
я если честно не люблю сокращения

2024-10-05 18:51 UTC, amilosh commented on src/main/resources/application.yaml
> +        auth-token: secret-key
secret-key - это такой и есть?
или ты здесь настоящий замокал?

2024-10-05 18:51 UTC, amilosh commented on src/test/java/faang/school/postservice/scheduler/PostCorrectorTest.java
> +    @Mock
строка

2024-10-05 18:51 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +        List<Post> posts = List.of(findedPost);
foundPost

2024-10-05 18:51 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/SpellingCorrectionServiceTest.java
> +        verify(textGearsClient, times(0)).correctText(content);
times(0)
never() там где-то в мокито есть

2024-10-06 11:05 UTC, cemeh666 commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +    }
видел такое у других просто. интересно, что Дима скажет

2024-10-06 11:08 UTC, cemeh666 commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +                .queryParam("text", text)
не понял, что ты имеешь в виду

2024-10-06 11:11 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            draftPosts = postRepository.findDraftsPaginate(pageable);
в теории может

2024-10-06 11:12 UTC, cemeh666 commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsCorrectResponse.java
> +    private boolean status;
status : true, // false in case of checking error

2024-10-06 11:19 UTC, cemeh666 commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLang.java
> +        }
так же удобнее. если новое значение добавлю, не нужно будет мапу дополнять

2024-10-06 11:25 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +    public void startCheckAISpellingPosts() {
почему объёмный? запрашивает посты и передаёт их в сервис на корректировку

2024-10-06 11:27 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            }
что именно?

2024-10-06 11:27 UTC, cemeh666 commented on src/main/java/faang/school/postservice/dto/spelling_corrector/yandex_speller/YandexSpellerCorrectResponse.java
> +    private List<String> s;
да. он самый

2024-10-06 11:28 UTC, cemeh666 commented on src/main/resources/application.yaml
> +        auth-token: secret-key
замокал конечно)

2024-10-08 01:34 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +        if (statusCode >= HttpStatus.INTERNAL_SERVER_ERROR.value()) {
HttpStatus.INTERNAL_SERVER_ERROR

в статический импорт можно свернуть

2024-10-08 01:38 UTC, amilosh commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            }
весь этот try catch
но там ещё pageable испоьзуюся, в общем чтение когда не улучшим
закрывай conversation

2024-10-08 01:41 UTC, amilosh commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            draftPosts = postRepository.findDraftsPaginate(pageable);
можно было бы булеаны поставить, что пост проверен на ошибка, на контент и тп.п и только когда все true - только тогда паблишить
но это не в рамках этой задачи

2024-10-08 01:42 UTC, amilosh commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +                .queryParam("text", text)
имею ввиду, что в uri идёт url/text
и чтобы в методе makeUri(String url, String text) параметры шли тоже в таком порядке
типа слева направо

2024-10-08 01:43 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsCorrectResponse.java
> +    private boolean status;
понял

2024-10-08 01:50 UTC, amilosh commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLang.java
> +        }
если новое значение енама, то всё равно перебилживать надо
и мапка создастся заново

private static final Map<String, Status> ENUM_MAP = new HashMap<>();
static {
        for (Status s : values()) {
            ENUM_MAP.put(s.name(), s);
        }
    }


public static TextGearsLang fromString(String lang) {
       return ENUM_MAP.get(lang);
    }

2024-10-09 20:52 UTC, 20cognosce requested changes

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/PostServiceApp.java
> +    }
Ну да, стрёмно выглядит
Возможно, это работает, потому что @SpringBootApplication внутри включает в себя @Configuration

Но вынести это надо. И дай рестТемплейту специфичное имя под его задачу

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/SpellingCorrectionService.java
> +    public String getCorrectedContent(String content) {
Прошу тебя провести демо на дейли по этой фиче

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLangDetectResponse.java
> +    private Integer error_code;
Обязателен ли snake_case
Jackson нормально ведь его мапит к стандартному CamelCase

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLang.java
> +        }
Мне вообще кажется, есть готовый метод для этого
.valueOf что ли, 

Ну не знаю, допустим

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +    private final static String LANG_DETECTOR_ENDPOINT = "/detect";
В конфиги

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/client/external/spelling/TextGearsClient.java
> +
Можно пустые строки не оставлять)

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/client/external/spelling/YandexSpellerClient.java
> +public class YandexSpellerClient {
Тебе не кажется, что нужно выделить общий интерфейс на две реализации

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +    private final static int BATCH_SIZE = 1000;
В конфиги

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            draftPosts = postRepository.findDraftsPaginate(pageable);
Хорошее замечание
Тогда нужно доработать публикацию, чтобы без проверки нельзя было опубликовать

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            draftPosts = postRepository.findDraftsPaginate(pageable);
Вот у меня вопрос по этому методу.
У нас 2000 драфтов.
Ты вытащил первые 1000.

У нас долго идет их проверка, и пришло время джобе сработать второй раз

И ты вытащишь те же 1000 драфтов, или произойдет наслоение и будет условно 500 старых и 500 новых

Поправь это

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            offset++;
А, ты так сделал
Ну... костыльное решение

Если приложение перезапустится - фиг мы узнаем, где было начало, а где конец

Сделай на уровне БД флаг у драфта или сортировку по дате какой-нибудь

Или нам в принципе пофиг, возвращаемый результат всегда одинаковый будет и даже если два раза обновим, скорректированный контент такой же

2024-10-09 20:52 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +                postService.correctPosts(draftPosts);
У нас и так всё try-catch обложено, сколько можно))

2024-10-09 20:52 UTC, 20cognosce commented
Не забудь подготовить демо на 5 минут

2024-10-10 06:54 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            draftPosts = postRepository.findDraftsPaginate(pageable);
они отсортированы по id, так что возьмутся новые

2024-10-10 07:15 UTC, cemeh666 commented on src/main/java/faang/school/postservice/service/post/SpellingCorrectionService.java
> +    public String getCorrectedContent(String content) {
а что конкретно нужно рассказать?

2024-10-10 07:51 UTC, cemeh666 commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLangDetectResponse.java
> +    private Integer error_code;
если ставить просто **errorCode**, а вернётся **error_code**, то будет значение null
![image](https://github.com/user-attachments/assets/b967d9fe-8caa-43f1-960e-de80b97b25dc)

2024-10-10 07:57 UTC, cemeh666 commented on src/main/java/faang/school/postservice/dto/spelling_corrector/text_gears/TextGearsLang.java
> +        }
valueOf есть конечно, но мы не можем доверять вводу, так как если придёт значение, которого у нас нем, то будет IllegalArgumentException, а тут при таком раскладе будет дефолтное значение

2024-10-10 07:59 UTC, cemeh666 commented on src/main/java/faang/school/postservice/client/external/spelling/YandexSpellerClient.java
> +public class YandexSpellerClient {
а зачем?

2024-10-10 08:06 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            offset++;
по задаче вообще всё равно. я понимаю, что в реальной жизни это не очень решение, но может тут упор на, то что драфты могут менять и нужно их изменённые ещё раз прогонять

2024-10-10 08:43 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +                postService.correctPosts(draftPosts);
это если совсем что-то экстраординарное вылезет

2024-10-10 08:45 UTC, cemeh666 commented on src/main/java/faang/school/postservice/scheduler/PostCorrecter.java
> +            offset++;
сделал сравнение по датам, чтобы одно и тоже не проверялось

2024-10-10 12:17 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/SpellingCorrectionService.java
> +    public String getCorrectedContent(String content) {
Продемонстрировать работу

2024-10-10 12:19 UTC, 20cognosce approved these changes

2024-10-10 12:19 UTC, 20cognosce commented on src/main/java/faang/school/postservice/client/external/spelling/YandexSpellerClient.java
> +public class YandexSpellerClient {
Затем, что методы одинаковые
Классы реализуют одинаковый функционал

2024-10-10 12:19 UTC, 20cognosce commented
Конфликты

2024-10-10 13:26 UTC, merged