Проверка постов на оскорбительный контент
CorporationX/post_service pull request #926
Opened 2024-10-06 17:55 UTC by RuslanIovlev

тест на сервис еще не дописал

2024-10-06 18:07 UTC, RuslanIovlev commented
Не знаю насколько верно
делал подобное впервые, сильно не ругайте)

2024-10-06 23:20 UTC, SharkB38 approved these changes

2024-10-06 23:20 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        }
https://github.com/CorporationX/user_service/pull/1648#discussion_r1789290910 смотри какая штука есть. Еще бы переименовать countPostsInThread в batchSize или вроде того

2024-10-06 23:20 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    public void verifyPosts(List<Post> posts) {
Тут мб метод приватным сделать? Или планируется его где то еще вызывать?

2024-10-06 23:20 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/pool/PoolConfig.java
> +}
Тоже наверное можно один пул использовать с Арстаном и Виталей, но не уверен. Посмотрим что Маша об этом думает

2024-10-06 23:21 UTC, SharkB38 commented
Хорошая работа!

2024-10-07 07:30 UTC, ArstanSubanov approved these changes
Круто) Оставил свои рекомендации)

2024-10-07 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/dictionary/ModerationDictionary.java
> +    public void init() throws IOException {
Думаю, будет лучше ошибку сразу же словить, так как init вызывается автоматически, её ты нигде по идее не вызовешь и не обработаешь, и try без catch используешь, хотя там же можешь и обработать)

2024-10-07 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/pool/PoolConfig.java
> +}
Соглашусь, но если хочешь свой пул, то лучше параметры в константы наверное)

2024-10-07 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        if (posts.isEmpty()) {
Мне кажется проверка на то, что список пуст - излишняя, так как если список пуст, цикл не запустится)

2024-10-07 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    public void verifyPosts(List<Post> posts) {
Асинхронный метод не рекомендуется вызывать в том же классе, насколько я помню. Это вроде связано с тем, что Spring создаёт proxy-объекты для методов, с аннотацией async, чтобы запустить отдельный поток для этого метода. Но если метод вызывается в том же классе, то вызов получается в обход proxy-объекта, из-за этого этот метод выполнится в том же потоке, что и метод, который вызывает его)

2024-10-07 07:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +            postRepository.save(post);
Также порекомендовал бы сделать saveAll)

2024-10-07 10:10 UTC, RuslanIovlev commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        if (posts.isEmpty()) {
Тоже над этим думал, согласен с тобой, уберу

2024-10-08 20:18 UTC, mysosnovskaya requested changes

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/pool/PoolConfig.java
> +}
Да, лучше один пул)

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dictionary/ModerationDictionary.java
> +    Set<String> forbiddenWords = new HashSet<>();
Модификаторы потерялись

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dictionary/ModerationDictionary.java
> +    Resource dictionaryResource;
Это поле нужно только для инициализации? Тогда почему бы не сделать такой конструктор:
```
public ModerationDictionary@Value("${post.moderator.scheduler.dictionary.file}") Resource dictionaryResource() {
... forbiddenWords = ...
}
```
А это поле dictionaryResource вообще удалить. 
И в целом мне не очень нравится, что ModerationDictionary так жестко "прибит гвоздями", что он берется именно из файла. Но в твоем случае как будто бы можно так оставить, потому что если мы начнем выносить логику чтения слов из файла, то в этом классе вообще ничего не останется и он будет довольно бессмысленным)

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    @Query("SELECT p FROM Post p WHERE p.verified_date = null AND p.deleted = false")
На будущее (сейчас необязательно): если предполагается, что постов может быть много, то тогда лучше доставать их из базы данных пачками (используя limit или pageable)

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    private int countPostsInThread;
Я бы переименовала, postBatchSize можно

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        ListUtils.partition(posts, countPostsInThread).forEach(this::verifyPosts);
Хорошо было бы добавить логи, сколько вообще постов найдено

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +                post.setVerified(false);
Здесь тоже setVerifiedDate нужно сделать. Это в целом общая строчка, поэтому её можно за пределы if-else вынести

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +            postRepository.save(post);
Согласна

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/sheduler/ModerationScheduler.java
> +        postService.moderatePosts();
Подумай про обработку ошибок. У нас, например, может база данных отвалиться. Могут и другие ошибки случиться. Нужно это хотя бы залоггировать)

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    count-posts-in-thread: "100"
Почему 100 -  это строчка?

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +      cron: "0 0 * * *"
Будет хорошо подписать комментарий, что этот крон означает

2024-10-08 20:18 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/post_V004_ad_verified.sql
> +ALTER TABLE post
Молодец 👍

2024-10-16 19:40 UTC, mysosnovskaya reviewed
И ещё конфликты не забудь пофиксить)

2024-10-16 19:40 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    private int POSTS_MAX_SIZE = 1000;
Если это константа, то она должна быть final static и в самом верху класса. Но я вообще вынесла бы это значение в конфиг) Так будет лучше

2024-10-16 19:40 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        while (true) {
Вот это я не поняла) У тебя же всё равно метод по расписанию будет выполняться довольно часто, вот там и найдутся все посты. Зачем while (true)?

2024-10-16 19:40 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/async/PostServiceAsyncImpl.java
> +public class PostServiceAsyncImpl implements PostServiceAsync {
Я бы не стала в название выносить Async - это особенности реализации уже. Назови как-то типа PostContentVerifier или может что-то лучше придумаешь)

2024-10-17 19:00 UTC, mysosnovskaya approved these changes

2024-10-17 19:01 UTC, merged