Ai орфография
CorporationX/post_service pull request #930
Opened 2024-10-08 08:13 UTC by SharkB38

2024-10-08 09:04 UTC, ArstanSubanov approved these changes
Всё круто) 👍

2024-10-08 09:13 UTC, wmwmaks approved these changes
Круто. Используется столько всего, что я не знаю. Мне бы хотелось, чтобы подобные сложные задачи как-нибудь презентовались кратко. Что и как делается из нового. Было бы круто. Только не знаю, как это удобно сделать.

2024-10-08 09:28 UTC, SharkB38 commented
> Круто. Используется столько всего, что я не знаю. Мне бы хотелось, чтобы подобные сложные задачи как-нибудь презентовались кратко. Что и как делается из нового. Было бы круто. Только не знаю, как это удобно сделать.

Клевая идея, но я тоже не знаю как это сделать. Может в следующий раз в описании пра напишу, что нового использовал в решении

2024-10-08 20:41 UTC, mysosnovskaya requested changes

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +    @Qualifier("getCorrectorClient")
get в названии бина не пишут, бин выражается существительным. Поэтому просто correctorClient

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +            Map.entry("en", "en-US"),
Как будто бы это не здесь должно быть =) Подумай, что с этим можно сделать. Думаю, было бы хорошо это вообще через конфиг брать

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +        Mono<ApiResponse<LanguageResponse>> monoResponse = correctorClient.get()
Для correctorClient лучше выделить отдельный класс. Т.к. сейчас PostCorrector и корректирует, и делает вызов стороннего сервиса сам. Клиенты принято выносить в отдельные классы)

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +                    () -> new CorrectorApiException("Doesn't have dialect for this language"));
this language - это какой? Нужно добавить

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +    @Retryable(
Круто с Retryable 👍

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +            maxAttempts = 3,
Только все вот эти настройки я бы вынесла в application.yaml

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +            throw new CorrectorApiException("Can't check text for errors");
Добавить бы конкретики какой-то из response. Что там есть? Статус код? Может описание какое-то?

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +    private CheckResponse getCheckingNonEnglishTextResult(String content, String language) {
Название не очень понятное, вот это getChecking. Имелось в виду getCheckResponseForNonEnglishText? А если я сюда английский language передам, то всё сломается?

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/post/corrector/ApiResponse.java
> +        boolean status,
Там только такая информация? Ничего больше получить нельзя?

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/post/corrector/ApiResponse.java
> +public record ApiResponse<T extends Response>(
С дженериком и интерфейсом Response классно получилось 👍

2024-10-08 20:41 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/CorrectorScheduler.java
> +        List<Post> posts = postRepository.findAllNotPublishedPosts();
Нужно подумать про обработку ошибок. Хотя бы залоггировать. А то если мы не залоггируем, то эта информация нигде не сохранится (например, если база данных отвалилась). Здесь global exception handler не поможет, он работает только на http запросы

2024-10-09 02:31 UTC, SharkB38 commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +    private CheckResponse getCheckingNonEnglishTextResult(String content, String language) {
Не сломается, просто для английского есть авто коррекция ошибок, одним запросом

2024-10-09 02:33 UTC, SharkB38 commented on src/main/java/faang/school/postservice/dto/post/corrector/ApiResponse.java
> +        boolean status,
Оказывается есть, для обработки ошибок, добавлю, исправлю

2024-10-10 03:24 UTC, SharkB38 commented on src/main/java/faang/school/postservice/api/PostCorrector.java
> +        Mono<ApiResponse<LanguageResponse>> monoResponse = correctorClient.get()
Я не уверен как правильно разделить

2024-10-10 19:30 UTC, mysosnovskaya requested changes

2024-10-10 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/client/CorrectorClient.java
> +    private Map<String, String> dialects;
Эта мапа должна быть в PostCorrector

2024-10-10 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/client/CorrectorClient.java
> +    public String getContentLanguageDialect(String content) {
Метод должен вернуть ApiResponse<LanguageResponse> (по сути то, что получил от стороннего приложения), а вся обработка этого объекта - в PostCorrector

2024-10-10 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/client/CorrectorClient.java
> +    public String getCorrectedNonEnglishText(String content, String language) {
Это всё в PostCorrector, клиент не должен таким заниматься. Клиент только вызывает другой сервис и возвращает его ответ

2024-10-10 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/client/CorrectorClient.java
> +        ApiResponse<AutoCorrectionResponse> apiResponse = monoResponse.block();
Здесь аналогично первому методу

2024-10-10 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/api/client/CorrectorClient.java
> +    private CheckResponse getCheckResponseForNonEnglishText(String content, String language) {
Здесь аналогично первому методу

2024-10-10 19:30 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/post/corrector/ApiResponse.java
> +        int error_code,
Лучше по джавовому поля называть) А для того, как это в json написано, использовать аннотацию JsonProperty

2024-10-12 14:50 UTC, mysosnovskaya approved these changes

2024-10-12 14:50 UTC, merged