- redisConfig + publisher v.1
CorporationX/post_service pull request #932
Opened 2024-10-08 20:20 UTC by Silencemess1ah

- redisConfig
- publisher

2024-10-15 20:05 UTC, GusevVrn reviewed
По названию PR - у тебя же всегда было с этим ок, чего сейчас поменял? Пусть будет так, но хотя бы номер таски прикрепи чтоб потом было удобно искать.

А ты запускал, у меня не хочет чет

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/redis/RedisPropertiesConfiguration.java
> +    @Value("${data.redis.channel.like-events}")
т.к. тут будет много топиков, надо переделать чтоб для каждого топика не надо было @Value проставлять

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/like/LikeEventDto.java
> +@Data
Опять дата(

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, LikeEventDto> redisTemplate() {
А нам точно надо для каждого ивента отдельный темплейт?

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +    private final ChannelTopic topic;
а у тебя сюда точно заинжектится топик?

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
мож сделать тогда глобальный бин и его один раз сконфигурить?

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +            redisTemplate.convertAndSend(topic.getTopic(), message);
а почему бы вообще не отправить прям весь объект?

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +            throw new RuntimeException(e);
+ логи добавить на error

2024-10-15 20:05 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        if(like.getPost() != null){
а может это вынести в отдельный метод, куда ты будешь передавать EventType, я так понимаю что он дальше разрастется, и сюда будем добавлять if(like.getComment != null ....)

2024-10-15 20:05 UTC, GusevVrn commented on src/main/resources/application.yaml
> +        like-events: like-events
ну тут снизу уже есть топик, надо к такому же виду привести ( добавить name )

2024-10-16 08:31 UTC, Silencemess1ah commented
> По названию PR - у тебя же всегда было с этим ок, чего сейчас поменял? Пусть будет так, но хотя бы номер таски прикрепи чтоб потом было удобно искать.
> 
> А ты запускал, у меня не хочет чет

Запускал только комментил все из блока addLike практически, много проверок пока все добавишь по базам чтоб проходило пол дня убьешь, отправляет, принимает постит в базу если говорим о логике паб-саб

2024-10-16 08:32 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, LikeEventDto> redisTemplate() {
Сделать абстрактное Dto и его передавать, а всех в наследнички?

2024-10-16 08:32 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +    private final ChannelTopic topic;
Дыа, позже гляну что можно сделать

2024-10-16 08:33 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
Тут подробнее, бин на паблиш метод? И где его разместить?

2024-10-16 08:33 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +            redisTemplate.convertAndSend(topic.getTopic(), message);
В другом ПРе ответил кучу ошибок ловил возможно после рефактора получиться все

2024-10-16 08:48 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, LikeEventDto> redisTemplate() {
Не, я в плане RedisTemplate<String, ИВЕНТ> redisTemplate() у тебя для каждого ивента будет свой темплейт?
Т.е. для каждого нового канала нам надо будет снова писать 
```
    @Bean
    public RedisTemplate<String, NewEvent> redisTemplate() {
```

2024-10-16 08:49 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +        objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
не, бин на objectMapper где ты его сконфигуришь и во все паблишеры будешь просто его передавать

2024-10-16 11:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, LikeEventDto> redisTemplate() {
Всё понял - неуч, переделал <String, Object> чтоб не плодить

2024-10-17 18:21 UTC, mysosnovskaya reviewed
Вы с Варей одно и то же сделали?)
https://github.com/CorporationX/post_service/pull/950
Созвонитесь и обсудите, как вы из этой ситуации будете выходить. Важно, чтобы в конечном варианте были и нужные тебе изменения, и нужные Варе

2024-10-17 18:21 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/redis/RedisProperties.java
> +        private Channel calculations_channel;
Так не пойдет) В java всегда поля называются, используяТолькоCamelCase

2024-10-17 19:43 UTC, Silencemess1ah commented
> Вы с Варей одно и то же сделали?) #950 Созвонитесь и обсудите, как вы из этой ситуации будете выходить. Важно, чтобы в конечном варианте были и нужные тебе изменения, и нужные Варе

В смысле одно и тоже? Ну конфиг получился почти один в один просто я отправляю для аналитики она для нотификаций, ну поправим при мерже конфликты там по сути одно и тоже разве что канал чуть по другому или название переменной, всё будет чики пуки

2024-10-18 15:43 UTC, mysosnovskaya commented
> > Вы с Варей одно и то же сделали?) #950 Созвонитесь и обсудите, как вы из этой ситуации будете выходить. Важно, чтобы в конечном варианте были и нужные тебе изменения, и нужные Варе
> 
> В смысле одно и тоже? Ну конфиг получился почти один в один просто я отправляю для аналитики она для нотификаций, ну поправим при мерже конфликты там по сути одно и тоже разве что канал чуть по другому или название переменной, всё будет чики пуки

И Варя, и ты добавляете в post_service отправку события при лайке. Т.е. это вопрос не только о конфигурации редиса, но и о dto, и о коде в LikeService и в целом всё остальное. По сути если это сделает Варя, то тебе делать фактически ничего не нужно (ну только если тебе в dto чего-то не будет хватать, то это подправить).

Кстати, вот и конфликты приехали (я смержила Варин ПР) и они далеко не только в конфиге редиса)

2024-10-18 23:20 UTC, Silencemess1ah commented
> Кстати, вот и конфликты приехали (я смержила Варин ПР) и они далеко не только в конфиге редиса)

В итоге: решаю конфликты можно мержить? Чтобы и мое и ее все работало?

2024-10-19 14:10 UTC, mysosnovskaya commented
> > Кстати, вот и конфликты приехали (я смержила Варин ПР) и они далеко не только в конфиге редиса)
> 
> В итоге: решаю конфликты можно мержить? Чтобы и мое и ее все работало?

Да, но я бы после решения конфликтов хотела ещё раз поревьювить. Поэтому, пожалуйста, не делай мерж самостоятельно, а отправь на повторное ревью)

2024-10-20 19:15 UTC, mysosnovskaya requested changes
Давай ещё раз внимательно поработаем над изменениями в коде, который делала Варя. Мне очень жаль, что ты не обратил должного внимания на мой первый комментарий, когда я писала, что вы с Варей делаете одно и то же и вам нужно договориться. По сути тебе нужно было просто добавить два поля в ивент и JavaTimeModule в objectMapper. Ну ладно, это в любом случае хороший опыт) И очень круто, что потренируемся правильно работать с кодом из мастер ветки, не делая в нем никаких лишних изменений

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/redis/RedisProperties.java
> +        private Channel likeEventsChannel;
Если что-то уже было в мастере, то меняем этот существующий код только в случае реальной необходимости. Есть ли аргумент для этого переименования? Нельзя переписывать код только по тому, что тебе так больше нравится. Поэтому если аргумент есть, то напиши, я подумаю. Если нет, то верни обратно. Готова обсудить этот момент голосом. Но в целом я про это и говорила, когда писала про ПР Вари -  нужно было поревьювить и если ты с чем-то был не согласен (с тем же неймингом), то нужно было внести предложение.

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/like/LikeEventDto.java
> +public class LikeEventDto implements Serializable {
С dto аналогично. Берем то dto, которое было в мастере. Его удалять нельзя. Его можно только доработать.

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/mapper/like/LikeMapper.java
> +import org.mapstruct.Mapper;
Почему это переехало?)

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +public class LikeEventPublisher implements MessagePublisher<LikeEventDto> {
Разве у Вари в ПРе не было подобного класса? Зачем новый? Нужно доработать существующий, если он чем-то не подходит.

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +                .eventType(EventType.POST_LIKE)
Почему ты решил делать это через поле eventType, а не через разные топики? Т.е. ты можешь лайки по постам слать в один топик, а просмотры постов - в другой. И никакого пересечения между ними не будет

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +        likeEventsChannel:
Ну и к этому изменению у меня тоже соответственно вопрос. Нельзя так просто переименовывать топики в мастер ветке. На них уже могут быть подписаны другие сервисы (даже других команд, о существовании которых ты можешь не подозревать). И нельзя просто одним днем делать переименование топика. Это критичное изменение, к которому нужно долго готовиться и много с кем договариваться, чтобы не получилось так, что мы релизим код с новым именем топика, а куча других микросервисов перестают корректно работать, т.к. всё ещё слушают старый топик, а про новый даже ничего не знают.

2024-10-20 19:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +        if (like.getPost() != null) {
С этим изменением я соглашусь, но всё равно такое должно отлавливаться на этапе ревью, а не меняться в своем ПРе)

2024-10-20 20:58 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/config/redis/RedisProperties.java
> +        private Channel likeEventsChannel;
Аргумент в том что мы передаем сообщения в общий канал лайков - о том что лайкнули пост, коммент, проект не важно если так делать каждый канал для любого действия для лайка с ума сойдем в этих каналах, я и обобщил чтоб потом не ковыряться и искать где мы что неправильно написали...

2024-10-20 21:00 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/dto/like/LikeEventDto.java
> +public class LikeEventDto implements Serializable {
Логика в чем, делаем одно и тоже, так же обобщил для всех лайков, возможно надо было написать abstract LikeEventDto и уже от них отпочковываться мне и ей

2024-10-20 21:00 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/mapper/like/LikeMapper.java
> +import org.mapstruct.Mapper;
Не помню, если честно сначала думал смапить из лайка наши дто потом понял что мне некуда подставить EventType решил через билдер сделать не заметил что съехало

2024-10-20 21:02 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/publisher/like/LikeEventPublisher.java
> +public class LikeEventPublisher implements MessagePublisher<LikeEventDto> {
Был и он был в сервисе, вроде все завозим в publisher/ENTITY/EntityPublisher, он один в один только опять же обобщенный

2024-10-20 21:07 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +                .eventType(EventType.POST_LIKE)
Я чет вообще запутался от этого вопроса, в моем понимании - Like это лайк, View это вью, и не важно к посту они, к комментарию и так далее, like post, like comment  -> like_channel , post view comment view profile view -> view_channel

2024-10-20 21:09 UTC, Silencemess1ah commented on src/main/resources/application.yaml
> +        likeEventsChannel:
Да согласен, критичное изменение, опять же хотел обобщить канал

2024-10-20 21:15 UTC, Silencemess1ah commented
> Давай ещё раз внимательно поработаем над изменениями в коде, который делала Варя. Мне очень жаль, что ты не обратил должного внимания на мой первый комментарий, когда я писала, что вы с Варей делаете одно и то же и вам нужно договориться. По сути тебе нужно было просто добавить два поля в ивент и JavaTimeModule в objectMapper. Ну ладно, это в любом случае хороший опыт) И очень круто, что потренируемся правильно работать с кодом из мастер ветки, не делая в нем никаких лишних изменений

Я все честно отрефакторил как я видел это на тот момент, учел все ее нюансы чтобы обобщить в единое, многие ответы на комменты выше об этом говорят, я протестил свою логику и ее, в целом проведена большая работа чтоб это все поднять и увидеть корректную работу end to end, потому что банально когда я вижу энд поинт в UserClientService который не работает а уже смержено по 3 ПРа в проекте у меня возникает закономерный вопрос, как люди тестили свои реализации если оно уже на этом этапе валиться, когда что-то не мапиться из заявленного падает по причине кривых реализаций, в общем я учел многое все ЧЕСТНО оттестил через запросы в постмане и проверил что ничего нигде не падает из ее в первую очередь реализации ну и + к своей, делал на совесть так сказать, а то звучит как будто я враг народа(

2024-10-20 21:15 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +        if (like.getPost() != null) {
В общем завтра вечером проведу рефактор из комментов выше, тебя услышал!

2024-10-23 16:09 UTC, mysosnovskaya reviewed
> Я все честно отрефакторил как я видел это на тот момент, учел все ее нюансы чтобы обобщить в единое, многие ответы на комменты выше об этом говорят, я протестил свою логику и ее, в целом проведена большая работа чтоб это все поднять и увидеть корректную работу end to end, потому что банально когда я вижу энд поинт в UserClientService который не работает а уже смержено по 3 ПРа в проекте у меня возникает закономерный вопрос, как люди тестили свои реализации если оно уже на этом этапе валиться, когда что-то не мапиться из заявленного падает по причине кривых реализаций, в общем я учел многое все ЧЕСТНО оттестил через запросы в постмане и проверил что ничего нигде не падает из ее в первую очередь реализации ну и + к своей, делал на совесть так сказать, а то звучит как будто я враг народа(

Прости, пожалуйста, если с моей стороны мои комментарии прозвучали грубо. На самом деле правда в работе программиста очень много скрытого, мы часто не видим, как много труда каждый из нас вкладывает в выполнение задачи. У нас в команде правда есть проблема, что в мастер ветке часто оказывается незапускаемый код. Будем решать! С помощью интеграционных тестов. Спасибо тебе за то, что добросовестно тестируешь свой код и по пути исправляешь баги, оказавшиеся в мастере. Это правда огромный труд. 
Что касается ПРа - логику я поняла. Я предложила всё-таки разделить топики на разные, но если тебе уже не хочется этим заниматься, то давай оставим так, тогда можешь мержить. Твой вариант тоже имеет место быть, в данной ситуации ничего критичного в нем нет.

И ещё одна просьба от меня: когда к задаче относятся несколько ПРов, то они должны мержиться вместе. Я специально поставила аппрув на втором ПРе, но мержить не стала. Так как возможно, в этом, ещё открытом, ПРе понадобились бы какие-то изменения, которые коснулись бы другого ПР, а он уже смержен)

2024-10-23 16:09 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/redis/RedisProperties.java
> +        private Channel likeEventsChannel;
Поняла. Но вообще чаще делают разные топики, если подразумевается разная обработка ивентов. Так мы разделяем логику. А вдруг будут другие микросервисы, которым важны лайки именно по постам - зачем им слушать всё остальное и отфильтровывать? И в целом в условии задачи указано 

> Сообщение о новом просмотре профиля отправляется в **новый** топик Redis из post_service.

Подход с одним топиком тоже имеет место: когда обработка одинаковая или мы уверены, что всем слушателям этого топика всегда нужны будут все ивенты, которые мы собираемся туда слать. Но в данном случае я бы всё равно делала разные)

2024-10-26 18:08 UTC, mysosnovskaya approved these changes

2024-10-26 18:08 UTC, merged