Feature BJS2 26138 Публикация постов по расписанию
CorporationX/post_service pull request #937
Opened 2024-10-09 21:16 UTC by segaTk

2024-10-10 19:32 UTC, GusevVrn requested changes
Я не понял идею, типо кидаем в редис потом его же читаем этим сервисом?
Ты чет перемудрил, за редис лайк, но убирай его)

Тебе по задачке просто надо публиковать посты в бд (обновление сущности), не вижу публикации. ...Publisher это не редисовский паблишер.

2024-10-10 19:32 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/properties/RedisProperties.java
> +    private String name;
судя по текущим настройкам name не заполнится

2024-10-11 11:45 UTC, segaTk commented on src/main/java/faang/school/postservice/config/properties/RedisProperties.java
> +    private String name;
подкорректировал

2024-10-11 19:32 UTC, mysosnovskaya requested changes

2024-10-11 19:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +    private String generationUniqueName() {
Зачем это переименование? Было верно, был глагол

2024-10-11 19:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    public void savePostBySchedule(List<Post> posts) {
А если сохранение постов будет не по расписанию, то будет ещё один метод? Не очень понимаю, зачем в названии метода "BySchedule". Достаточно просто "savePosts"

2024-10-11 19:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB.get().forEach(post -> post.setPublished(true));
А какой смысл делать вызов getAllPostsNotPublished асинхронным, если ты всё равно здесь дожидаешься его окончания через get()?

2024-10-11 19:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/ScheduledPostPublisher.java
> +    public void publish(String message) {
А это где используется?

2024-10-12 06:02 UTC, segaTk commented on src/main/java/faang/school/postservice/service/S3/S3Service.java
> +    private String generationUniqueName() {
Да, согласен, сначала убирал этот метод в предыдущем комите, потом вернул и видимо ошибся немного

2024-10-12 06:03 UTC, segaTk commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    public void savePostBySchedule(List<Post> posts) {
Точно, хорошо

2024-10-12 06:04 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/ScheduledPostPublisher.java
> +    public void publish(String message) {
уже не используется, удалю

2024-10-12 06:08 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB.get().forEach(post -> post.setPublished(true));
такая задача и такие условия... думаю это связано с тем, что постов достаточно много, но таким образом мы ускорим процесс

2024-10-12 18:15 UTC, mysosnovskaya requested changes

2024-10-12 18:15 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB.get().forEach(post -> post.setPublished(true));
Так, поясни, где здесь ускорение?

2024-10-12 18:25 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB.get().forEach(post -> post.setPublished(true));
Хорошо, что еще не так здесь, чтобы сразу понимать?

2024-10-13 14:32 UTC, mysosnovskaya requested changes
Надо ещё поразбираться с асинхронностью и правилами публикации, сейчас логика кода неверная

2024-10-13 14:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB = postsFromDBFuture.get(2, TimeUnit.SECONDS);
Есть гарантия, что за 2 секунды результат должен прийти? Бывают запросы к базе данных, которые выполняются дольше)
И у меня опять вопрос: какой здесь смысл в асинхронности, если ты запустил отдельный поток и тут же ждешь его окончания? Ты никакой полезной работы в это время не делаешь, просто ждешь. Никакого ускорения здесь не будет

2024-10-13 14:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +     * Получаем список постов один раз, чтобы избежать многократного вызова get().
Комментарий не нужен, логика метода понятна из кода)

2024-10-13 14:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +    public void checkPostToPublish() {
В условии задачи есть такое:
`Разбить общий список всех полученных постов на подсписки, скажем, по 1000 постов и каждый подсписок будет публиковать в отдельном потоке. `
У тебя такого не вижу

2024-10-13 14:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB.parallelStream().forEach(post -> post.setPublished(true));
Та ты вообще всем выставишь published = true, а надо только тем, у которых getPublishedAt().isAfter(now), разве нет?
Я если честно не очень понимаю, почему мы ищем посты, у которых дата ПОСЛЕ сегодня. А вдруг пост запланирован на публикацию через неделю? А мы его сейчас опубликуем. Разве это корректно?

2024-10-13 14:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +        CompletableFuture.runAsync(() -> {
А здесь в чем суть асинхронности? Это же просто операция сохранения всех постов в базу данных, она что в этом же потоке, что в другом, будет выполняться одинаково долго

2024-10-13 14:32 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB = postsFromDBFuture.get(2, TimeUnit.SECONDS);
У тебя в PostRepository вот такое условие стоит: p.scheduledAt <= CURRENT_TIMESTAMP
То есть там будут все посты, которые ДО текущего момента. Тогда у тебя здесь в коде никогда не будет ни одного поста с датой публикации ПОСЛЕ сегодня, т.к. база данных такие просто не отдает по условию

2024-10-13 14:57 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB.parallelStream().forEach(post -> post.setPublished(true));
Почему? Вот же в условии if указано, что если указано время now, то выставляется флаг true, а в проверке boolean, мы проходимся по списку и находим эти посты, где дата публикации "now". И дальше этот список сохраняется в БД, поэтому и будут дергаться посты и проверяться каждую минуту, как написано в условии

2024-10-13 15:00 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +    public void checkPostToPublish() {
А ещё в условии задачи, написано или 10, где в конфигурации ExecutorService, выставлены эти параметры, вот мы здесь и получаем эти списки в отдельных потоках

2024-10-13 15:04 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +     * Получаем список постов один раз, чтобы избежать многократного вызова get().
убрал)

2024-10-13 15:09 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +        CompletableFuture.runAsync(() -> {
Суть в улучшении производительности, если количество списков будет достаточно большим, то явно асинхронно операция будет выполняться быстрее

2024-10-13 15:22 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB = postsFromDBFuture.get(2, TimeUnit.SECONDS);
Смысл асинхронности в увеличении производительности, так как постов может быть очень много и ещё у меня в задании это было написано, цитировании указал в комментарии ниже.
Время ожидания здесь указывается, чтобы потоки не блокировали друг друга, если время ожидания дольше, то  поток закроется, хорошо выставлю пол минуты, чтобы не потерять запрос.

2024-10-13 15:35 UTC, segaTk commented on src/main/java/faang/school/postservice/config/scheduler/PostPublisher.java
> +            postsFromDB = postsFromDBFuture.get(2, TimeUnit.SECONDS);
Немного неправильно написал в доке что посты будут опубликованы в будущем, исправил. Пост будет опубликован в момент когда Sheduler вызовет этот список и найдёт пост, а вызывать этот список он будет каждую минуту, далее, будет проверка еще раз, на всякий случай, мало-ли что там в списке, всякое бывает, и где указана дата публикации "сейчас" пост опубликуется.

2024-10-21 18:37 UTC, mysosnovskaya approved these changes
Вот теперь асинхронность применена верно) Логично и понятно, зачем она здесь

2024-10-21 18:37 UTC, merged