BJS2-26114: Обработчик исключений
CorporationX/post_service pull request #938
Opened 2024-10-10 03:29 UTC by lowerKamaCase

2024-10-11 13:30 UTC, Varrankin commented
1. Нет логов, в каждом ExceptionHandler должен быть лог, не забудь в логах стектрейс исключения передать 
2. Надо предусмотреть еще ConstraintViolationException это вторая ошибка которая может вылететь при использовании Bean Validation, ты одну MethodArgumentNotValidException обработал. Посмотри в этой статье https://struchkov.dev/blog/ru/spring-boot-validation/
3. а зачем тебе постоянно в  ResponseEntity передавать  HttpStatus? он же у тебя и так передаться в  @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
4. Посмотри на счет объединения хендлеров, например можно объединить в один   @ExceptionHandler: @ExceptionHandler(AmazonS3Exception.class), @ExceptionHandler(FileS3Exception.class)
5. И думаю еще можно, если самому интересно, попробовать передать доп. параметры, например url или время запроса и т.д

2024-10-11 14:09 UTC, lowerKamaCase commented
поправил ПР по всем пунктам

2024-10-11 19:45 UTC, mysosnovskaya requested changes

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    private static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);
А чем логгер от ломбока не подходит?

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        for (FieldError error : ex.getBindingResult().getFieldErrors()) {
Отлично, что сделал такую "умную" обработку 👍

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public Map<String, String> handleValidationExceptions(MethodArgumentNotValidException ex, HttpServletRequest request) {
Я всё-таки предпочитаю возвращать dto здесь. `List<ValidationError>`, где `ValidationError` состоит из полей `field` и `description`. Так код станет понятнее)

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public String handleServletException(ServletException ex, HttpServletRequest request) {
Просто String мы не возвращаем, т.к. его не получится представить в формате json. Обязательно нужно завести отдельный dto класс (например, ErrorResponse) с нужными полями и здесь возвращать его. Актуально для всех методов

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
А почему ServletException это BAD_REQUEST?

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public String handleCloudExceptions(RuntimeException ex, HttpServletRequest request) {
Как предлагал Дима - одинаковую обработку разных исключений нужно объединить в один метод. Например, у тебя легко объединятся handleIOException, handleCloudExceptions и handleRuntimeException. Тебе в целом достаточно оставить только handleRuntimeException для INTERNAL_SERVER_ERROR. Тогда получится, что все исключения, которые не попали под остальные варианты, попадут в handleRuntimeException  со статусом INTERNAL_SERVER_ERROR

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.PAYLOAD_TOO_LARGE)
Класс 👍 Очень радует, что ты поразбирался с разными кодами и применил такой экзотичный вариант =) Это здорово!

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public Map<String, Object> handleGeneralException(Exception ex, HttpServletRequest request) {
В чем принципиальное отличие этого метода от handleRuntimeException?

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public Map<String, Object> handleGeneralException(Exception ex, HttpServletRequest request) {
И возвращать тут тоже лучше dto

2024-10-11 19:45 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        logger.error("IOException at {}: {}", request.getRequestURI(), ex.getMessage(), ex);
Нет смысла в логах прописывать класс исключения, он и без этого там будет) Нужно добавить что-то более человекопонятное, можно какую-то стандартную фразу типа "Exception occurred while handle request"

2024-10-12 03:06 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        for (FieldError error : ex.getBindingResult().getFieldErrors()) {
это подкол?))

2024-10-12 03:13 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    private static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);
подходит, поправил

2024-10-12 03:20 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public Map<String, String> handleValidationExceptions(MethodArgumentNotValidException ex, HttpServletRequest request) {
поправил

2024-10-12 03:34 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public String handleCloudExceptions(RuntimeException ex, HttpServletRequest request) {
объединил

2024-10-12 03:39 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public Map<String, Object> handleGeneralException(Exception ex, HttpServletRequest request) {
хмм, объединил их в один метод. сейчас есть только handleGeneralException

2024-10-12 03:39 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public Map<String, Object> handleGeneralException(Exception ex, HttpServletRequest request) {
поправил

2024-10-12 03:43 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        logger.error("IOException at {}: {}", request.getRequestURI(), ex.getMessage(), ex);
поправил

2024-10-12 18:12 UTC, mysosnovskaya requested changes

2024-10-12 18:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        for (FieldError error : ex.getBindingResult().getFieldErrors()) {
Нет) С MethodArgumentNotValidException не так-то просто работать, нужно ещё достать из него нужные поля через цикл, вот поэтому и пишу, что круто, что не просто взял e.getMessage, а вот так вот реализовал, по-умному)

2024-10-12 18:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        log.error("VException occurred while handling request at {}: {}", request.getRequestURI(), ex.getMessage(), ex);
Лишняя буква в начале сообщения

2024-10-12 18:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public ErrorResponse handleServletException(ServletException ex, HttpServletRequest request) {
А почему он не обрабатывается в handleGeneralException?

2024-10-12 18:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public ErrorResponse handleConstraintViolationException(ConstraintViolationException ex, HttpServletRequest request) {
Кстати, это исключение тоже обрабатывается "по-умному". Посмотри ex.getConstraintViolations(), там тоже можно вытащить поле и описание ошибки, т.е. также возвращать `List<ValidationError>`

2024-10-12 18:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    @ExceptionHandler({ IOException.class, FileS3Exception.class, AmazonS3Exception.class, RuntimeException.class, Exception.class })
Здесь достаточно написать Throwable и все остальные исключения автоматически (из-за наследования) тоже попадут в этот метод. Все не нужно перечислять

2024-10-12 18:12 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/error/ErrorResponse.java
> +    private int status;
Думаю, в статусе нет смысла, он же и так вернется в респонсе благодаря аннотации ResponseStatus

2024-10-13 05:43 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    @ExceptionHandler({ IOException.class, FileS3Exception.class, AmazonS3Exception.class, RuntimeException.class, Exception.class })
поправил

2024-10-13 05:44 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/dto/error/ErrorResponse.java
> +    private int status;
убрал статус

2024-10-13 05:47 UTC, lowerKamaCase commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +    public ErrorResponse handleConstraintViolationException(ConstraintViolationException ex, HttpServletRequest request) {
спасибо, поправил

2024-10-13 14:34 UTC, mysosnovskaya approved these changes

2024-10-13 14:34 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/controller/global/GlobalExceptionHandler.java
> +        log.error("VException occurred while handling request at {}: {}", request.getRequestURI(), ex.getMessage(), ex);
Ещё актуально. У тебя в начале сообщения в логе лишняя буква V образовалась. Удали и будем мержить)

2024-10-14 20:34 UTC, merged