BJS2-27084 Публикация постов по расписанию
CorporationX/post_service pull request #940
Opened 2024-10-10 14:01 UTC by IvanTsegelnyuk

2024-10-11 22:04 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +    @Value("${post.publisher.sub-list-size}")
Пустой строчкой отделить можно

2024-10-11 22:04 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                    post.setPublishedAt(LocalDateTime.now());
Не знаю насколько требовательна эта операция
LocalDateTime.now()
надо гуглить.

Но если вдруг она отнимает много ресурсов, то можно вынести в переменную до forEach.

2024-10-11 22:04 UTC, amilosh commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +                .toList();
Мне кажется это очень частая функция и есть уже написанные решения с самыми оптимальными алгоритмами.
Мажешь погуглить
split the list into sublists
думаю в какой-нибудь apache или google guava будет.

2024-10-11 22:04 UTC, amilosh commented on src/main/resources/application.yaml
> +          batch_size: 50
Не нашел в коде, где используется.

2024-10-11 22:04 UTC, amilosh commented on src/test/java/faang/school/postservice/config/PostThreadPoolConfigTest.java
> +
лишняя строка

2024-10-11 22:04 UTC, amilosh commented on src/test/java/faang/school/postservice/config/PostThreadPoolConfigTest.java
> +    private final Integer postPoolSize = 10;
private static final Integer POST_POOL_SIZE = 10;
первой строчкой после класса

2024-10-11 22:04 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/PostServiceTest.java
> +//        ReflectionTestUtils.setField(postService, "subListSize", SUB_LIST_SIZE);
закомментированный код

2024-10-11 22:04 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/ScheduledPostPublisherTest.java
> +    private static final Integer SUB_LIST_SIZE = 2;
первой строчкой

2024-10-11 22:04 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/ScheduledPostPublisherTest.java
> +
лишняя строчка

2024-10-11 22:04 UTC, amilosh commented on src/test/java/faang/school/postservice/service/post/ScheduledPostPublisherTest.java
> +
лишняя строка

2024-10-12 20:10 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                    post.setPublishedAt(LocalDateTime.now());
Перенес

2024-10-12 20:19 UTC, IvanTsegelnyuk commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +                .toList();
Переписал вообще по-другому. 
Но отвечу на твой коммент. Конкретно тут я бы не стал искать какие-то сторонние библиотеки, т.к. метод в пару строк, понятный для чтения. Его я, кстати, не сам написал, загуглил.  Вариант со сторонней библиотекой буду иметь в виду, но не тут. Если б мы точно стали работать с миллиардными записями и увидели прирост в производительности между этим методом и гугловой библиотекой, то ок, поменяем. Но это надо тестить

2024-10-12 20:23 UTC, IvanTsegelnyuk commented on src/main/resources/application.yaml
> +          batch_size: 50
Это не нужно никуда подтягивать через Value или еще как-то. Если это свойство есть в application.yaml, то Хибер начинает в своих запросах использовать батчи при последовательных вставках/обновлениях. По крайней мере, я так понял. И в тестах обновление 100 тыс. записей с этими строчками и без них на моем компе стабильно отличается в 20 секунд всегда. Поэтому сделал вывод, что работает так

2024-10-16 08:08 UTC, sultan-inked commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +            post.setPublished(true);
Дима мне писал что лучше всегда явно вызывать метод `save()`, и не стоит пологаться на `@Trancastional`

2024-10-16 08:08 UTC, sultan-inked commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +                    for update skip locked limit :limit
`for update skip locked` интересно, незнал что так можно

2024-10-18 16:08 UTC, 20cognosce requested changes

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/dto/post/CreatePostRequestDto.java
> +    @NotNull
Ты уверен, что это будет работать просто так?
Хибернейтовский валидатор настроен уже в спринге?

Проверь и отпиши

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +                    for update skip locked limit :limit
Зачем ты управляешь транзакциями на уровне SQL?

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        log.info("Загрузка постов для публикации");
Не писать логи на русском
И этот лог бесполезный - ты в нём ничего не логируешь, только говоришь, что попал в эту строчку кода

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    @Transactional
Что тут происходит

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> posts = postRepository.findReadyToPublishSkipLocked(postPublishBatchSize);
И тут

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +    @Scheduled(cron = "${post.publisher.scheduler.cron}")
У тебя Scheduled метод сам по себе выполняет уже в отдельном потоке асинхронно
зачем тебе еще один Async над postService?

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/PostThreadPoolConfig.java
> +}
Тебе не надо это всё
В пропертях настрой спринговый шедулер

spring.task.scheduling.pool.size=10

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    @Transactional
Async убрать

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> posts = postRepository.findReadyToPublishSkipLocked(postPublishBatchSize);
Транзакцией управлять через спринг
Убери это всё в sql

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        List<Post> posts = postRepository.findReadyToPublishSkipLocked(postPublishBatchSize);
Может задать ей isolation SERIALIZABLE, если прям боишься за аномалии

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +        int countOfTasks = countOfTasks(readyToPublishCount);
Доставать число - это какая-то шляпа
Вытаскивай лучше список ID и с помощью ListUtil разбей на подсписки

2024-10-18 16:08 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +    List<Post> findReadyToPublishSkipLocked(Integer limit);
Ты еще в этом методе принимаешь limit
А сортировку ты потерял, так можешь вытащить один и тот же пост дважды

на список ID переделай

2024-10-18 16:08 UTC, 20cognosce commented on src/test/java/faang/school/postservice/config/PostThreadPoolConfigTest.java
> +class PostThreadPoolConfigTest {
Жиденькие тесты какие-то
Напиши интеграционный тест который ожидает срабатывание джобы и содержимое базы проверяет
Наши умельцы CI вроде уже прикрутили

2024-10-18 16:10 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    @Transactional
А, если ты хочешь каждый батч асинхронно выполнять

Тогда просто засабмить таски в экзекьютор сервис асинхронно внутри джобы, с этими аннотациями нужно дополнительные бины создавать, чтобы они срабатывали

Когда две сразу на одном методе - сомневаюсь в работе

2024-10-20 22:19 UTC, IvanTsegelnyuk commented
![Безымянный](https://github.com/user-attachments/assets/f085b1b1-213b-400d-972f-671e3fc3e96a)
Решил показать, как в текущей реализации работают потоки. То есть по шедулеру (scheduling-ivan1) запускается метод, а в нем уже идет распараллеливание по Async (postExecutorPool), который создается в конфиге.
Transactional совместно с Async тут так же работает, т.к. если захардкодить ошибку по id в методе процессинга подсписка постов в одном из потоков (т.е. написать в стриме if (post.getId() == какой-то id) throw new RuntimeException("test"), то именно этот батч не отработает, то есть все записи, которые были в этом батче, так и останутся в базе с published = false.
Если у нас 100 тыс постов и размер батча = 10000, то после выполнения метода 90000 постов будут c published = true, а 10000 с published = false.
https://www.baeldung.com/spring-transactional-async-annotation - тут вроде написано, то асинк с транзакшнл использовать норм, если у тебя это работает и ты +- понимаешь, для чего ты так делаешь.
По поводу select for update skip locked подумал, и согласен, возможно в этой задаче прям лочить записи при обработке может быть избыточным, а может даже лишним и мешающим работе, т.к. на время обработки батча лочатся строки из этого батча, и, соответственно, никакие операции с постами в это время делать нельзя, даже чтение, насколько я понимаю. Насколько это критично и где какие ошибки могут из-за этого вылезть при огромном количестве пользователей приложения - я оценить не могу. Возможно именно skip locked лучше заменить на загрузку сначала списка id неопубликованных постов, и потом без всяких локов разбить список на подсписки, выгружать эти подсписки постов в потоках и обрабатывать. 
И еще вопрос. Если доставать число из базы (как у меня сделано) - это шляпа типа, а доставать список Id-шников - это почему не шляпа? И в том и в том подходе мы делаем один запрос к базе, достаем что-то отличное от самой сущности или списка сущностей (поста или постов). Где грань шляпы/ не шляпы? За какими данными можно обращаться в бд, а за какими точно не надо? Типа со списком Id гипотетически можно больше операций придумать, чем просто с каким-то числом?

2024-10-21 17:35 UTC, mighty-mhsl commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +    @Transactional
Я почитал про это. Оказалось, что в современном Spring сработают вдвоем, если у них стоит один и тот же механизм прокси. Например, оба используют CGLIB и одни и те же настройки проксирования при создании бинов. 

Хотя у меня по началу тоже вызвало сомнение, что вдвоем заведутся

Тем не менее нужно понимать, что транзакция в этом случае привязывается к асинхронному потоку. Если здесь вылетит исключение, то транзакция откатится, но исключение это не будет обработано нашим GlobalExceptionHandler, т.к. поток другой

О чем точно нужно позаботиться в таком случае: реализовать бин AsyncUncaughtExceptionHandler. Это спринговый класс, вроде, через который можно сделать обработку исключений из асинхронных задач. Надо про него почитать только немного

2024-10-21 17:38 UTC, mighty-mhsl commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +    @Scheduled(cron = "${post.publisher.scheduler.cron}")
Я так понимаю, что идея была запустить джобу, но поскольку она будет обрабатывать потенциально большой объем данных, то распараллелить эту обработку дополнительно. Поэтому мы пытаемся тут в цикле дергать сервис, на котором @Async

2024-10-21 18:08 UTC, mighty-mhsl commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +                    for update skip locked limit :limit
Интэрэсно...

По сути говорим две вещи:

1. Те, что селектим - блокируем
2. Те, что уже заблочены - ПРОПУСКАЕМ

Понимаю стремление запретить вносить изменения во время публикации поста по расписанию. А также не забирать одни и те же посты в обработку еще раз при работе нескольких потоков. Но тут есть пара проблем:

1. Если юзер меняет пост, а тот заблочен в БД, то юзер будет ждать загрузку, пока строчка не разблокируется. Когда это произойдет? Вопрос. Может и быстро, если у нас батчи небольшие и мы им флажок всего меняем. В принципе вероятнее всего, что будет достаточно быстро, а сценариев таких будет не много

2. Мы можем скипнуть публикацию поста по расписанию, если вообще другая транзакция повесила на него лок. Не наш другой поток публикации, а вообще любое обновление этого поста, которое в то же время произошло. И тогда пост вообще не будет опубликован. Тем не менее, если джоба запускается часто, то они опубликуются быстро потом. 

Пытаюсь думать о потенциальных проблемах, но не могу каких-то жестких обнаружить, а преимущества - вижу. Не просто на несколько потоков, но даже на несколько машин параллельных масштабируется

2024-10-21 18:08 UTC, mighty-mhsl commented on src/main/java/faang/school/postservice/service/post/ScheduledPostPublisher.java
> +        int countOfTasks = countOfTasks(readyToPublishCount);
Я соглсен с Димой тут:

Конкретно в этой ситуации разницы нет: брать число или список id - так или иначе селект в БД
Но вот когда мы будем в отдельном асинхронном потоке делать еще один селект для выбора самих постов, то прямо сейчас этот селект работает через лимит, скипая заблокированные посты. При большом наборе данных такой селект по лимиту будет выполнять линейный поиск по таблице, отсчитывая этот лимит строк. Если таблица большая и популярная - это может быть дольше обычного в некоторых ситуациях

Но если бы мы делали запрос по конкретным id, то наше получение постов было бы всегда быстрым

2024-10-27 15:05 UTC, 20cognosce approved these changes

2024-10-27 15:07 UTC, merged