BJS2-26203 - Created publisher for new published comment
CorporationX/post_service pull request #949
Opened 2024-10-11 21:25 UTC by GusevVrn

Сервис и тест задвоился, увидел после того как начал тестировать, поправил в этом PR

2024-10-15 06:32 UTC, Silencemess1ah reviewed
Все вроде в порядке

2024-10-15 06:32 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/dto/comment/CommentEventDto.java
> +import lombok.*;
Завернулось (

2024-10-15 06:32 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
>  public class CommentService {
Мож в дебаг все инфо сообщения?

2024-10-15 06:32 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
>  public class CommentService {
Ну или половину точно можно всякие промежуточные действия

2024-10-15 06:32 UTC, Silencemess1ah commented on src/test/java/faang/school/postservice/service/comment/CommentServiceTest.java
>  class CommentServiceTest {
Настолько расходилось что проще было с нуля переписать все тесты на сервис?

2024-10-15 18:18 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
>  public class CommentService {
Мне кажется на ключевые моменты только надо

2024-10-15 18:18 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/comment/CommentServiceTest.java
>  class CommentServiceTest {
Там Димка залил такой же сервис, я его тесты сюда влил.

2024-10-17 18:55 UTC, mysosnovskaya requested changes

2024-10-17 18:55 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/moderator/ModeratorService.java
> +                .forEach(comment -> CompletableFuture.runAsync(() -> {
Прикольно, но в целом послать сообщение в кафку это очень быстрая операция, так что не вижу большого смысла делать это асинхронно) Тут ведь тоже время тратится на создание CompletableFuture, поиск и назначение потока и так далее

2024-10-17 18:55 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/moderator/ModeratorService.java
> +                    CommentEventDto commentEventDto = CommentEventDto.builder()
Я бы вынесла это в отдельный метод, а может быть и в маппер?

2024-10-17 18:55 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/comment/CommentEventDto.java
> +    private long userId;
Это автор комментария, а authorId - это автор поста? Может быть так и назвать поля? commentAuthorId и postAuthorId

2024-10-19 14:20 UTC, mysosnovskaya approved these changes

2024-10-21 18:33 UTC, mysosnovskaya commented
Пофикси конфликты и можешь сам смержить оба ПРа

2024-10-21 21:34 UTC, merged