Unicorn master stream6 feature bjs2 26194
CorporationX/post_service pull request #950
Opened 2024-10-12 04:13 UTC by StepnovaVarvara

2024-10-12 20:09 UTC, GusevVrn reviewed
А ты запускала это все?
Можешь не отвечать, если пойдешь комментарии править, поймешь о чем я.

2024-10-12 20:09 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    private String likePostTopic;
Все переменные можно в отдельный класс вынести

2024-10-12 20:09 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/event/LikePostEvent.java
> +@Data
Тебе все аннотации из даты нужны?

2024-10-12 20:09 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +@Slf4j
Ну чисто по красоте можно было пирамидкой добавить

2024-10-12 20:09 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +            log.error("Failed to send notification with likePostEvent - {}. {}", likePostEvent.toString(), ex.getMessage());
за 80 символов вылезла

2024-10-12 20:09 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/publisher/LikePostEventPublisher.java
> +            String message = objectMapper.writeValueAsString(event);
не уверен по поводу стринга, дождемся Маши)
я прям object и передаю. 
Если ты где прочитала что это хороший подход то дай ссылку

2024-10-12 20:09 UTC, GusevVrn commented on src/test/java/faang/school/postservice/service/like/LikeServiceTest.java
> +    @Mock
мы вроде как между моками оставляем промежутки, а ты их убрала)

2024-10-13 05:35 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    private String likePostTopic;
Можно, ток я не оч понимаю зачем, типо так красивенько будет или как?

2024-10-13 05:37 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +@Slf4j
Теперь красивенько!)

2024-10-13 05:46 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +            log.error("Failed to send notification with likePostEvent - {}. {}", likePostEvent.toString(), ex.getMessage());
Поменяла

2024-10-13 05:48 UTC, StepnovaVarvara commented on src/test/java/faang/school/postservice/service/like/LikeServiceTest.java
> +    @Mock
Овер дофика места занимает просто

2024-10-13 05:54 UTC, StepnovaVarvara commented
> А ты запускала это все? Можешь не отвечать, если пойдешь комментарии править, поймешь о чем я.

Да, запускала конечно. У меня все падает на отправке сообщения в EmailService и видимо ошибка в нем. Хотя когда я его тестила, то все прекрасно работало! Я пока хз в чем проблемс...

2024-10-13 13:43 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/dto/event/LikePostEvent.java
> +@Data
Не все, но так меньше строк просто

2024-10-13 13:45 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/publisher/LikePostEventPublisher.java
> +            String message = objectMapper.writeValueAsString(event);
Я попробовала сделать с object и у меня упала ошибка с json форматом

2024-10-17 18:04 UTC, mysosnovskaya requested changes

2024-10-17 18:04 UTC, mysosnovskaya commented on build.gradle.kts
> -    implementation("com.amazonaws:aws-java-sdk-s3:1.12.772")
Почему эта зависимость удалена?

2024-10-17 18:04 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +                new RedisStandaloneConfiguration(redisProperties.getHost(), redisProperties.getPort());
Спринг может сам взять хост и порт из application.yml, попробуй) Я такое же Паше писала в его ПРе

2024-10-17 18:04 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +            log.error("Failed to send notification with likePostEvent: {}. {}",
Стектрейс обязательно должен быть залоггирован

2024-10-17 18:22 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +                new RedisStandaloneConfiguration(redisProperties.getHost(), redisProperties.getPort());
Хмм.. Интересно

2024-10-17 18:26 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/like/LikeService.java
> +            log.error("Failed to send notification with likePostEvent: {}. {}",
Не очень пока в этом разбираюсь

2024-10-17 18:30 UTC, StepnovaVarvara commented on build.gradle.kts
> -    implementation("com.amazonaws:aws-java-sdk-s3:1.12.772")
Блин, это не уверена, что я ее удалила. Но помню, что когда пыталась запустить проект, то зависимость амазона не работата и пришлось добавлять другую, чтобы все скомпилировалось

2024-10-18 15:33 UTC, mysosnovskaya approved these changes

2024-10-18 15:33 UTC, merged