BJS2-27102 Анализ комментариев
CorporationX/post_service pull request #955
Opened 2024-10-12 20:42 UTC by ilu23ilu23

Функциональность отправки в топик редиса информации о комментарии при его сохранении в бд.

2024-10-13 07:22 UTC, evgenywork commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        template.setDefaultSerializer(new StringRedisSerializer());
А ты тестировал , что все работает с этой строкой `template.setDefaultSerializer(new StringRedisSerializer());`?
Я недавно настраивал редис и делал такую настройку 
```
template.setKeySerializer(new StringRedisSerializer());
template.setValueSerializer(new GenericJackson2JsonRedisSerializer());
```
так как key не стринг , а сложный объект.

2024-10-13 07:22 UTC, evgenywork commented on src/main/java/faang/school/postservice/publisher/AbstractEventPublisher.java
> +            redisTemplate.convertAndSend(topic.getTopic(), jsonEvent);
Понял , значит ты здесь в стрингу конвертировал, тогда верхний коммент для информации

2024-10-13 07:22 UTC, evgenywork commented on src/main/java/faang/school/postservice/publisher/AbstractEventPublisher.java
> +            log.error("Failed to convert event to json");
Почему здесь не логируешь трейс jsonProcessingException, как внизу (exception)?

2024-10-13 08:35 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        template.setDefaultSerializer(new StringRedisSerializer());
Да, я постманом тестирвал, всё в аналитик сервис доставляется и сохраняется.

2024-10-13 17:11 UTC, evgenywork commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +        template.setDefaultSerializer(new StringRedisSerializer());
Да , я потом увидел , что ты все в стрингу конвертируешь, дальше отписал это )) этот коммент не стал удалять , вдруг ты не знал про такую настройку

2024-10-13 17:41 UTC, sultan-inked reviewed
:eyes:

2024-10-16 21:18 UTC, 20cognosce requested changes

2024-10-16 21:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/client/UserServiceClient.java
> +@Primary
А какие еще есть?

2024-10-16 21:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        if (!post.getAuthorId().equals(comment.getAuthorId())) {
Не понял, что это за условие такое

2024-10-16 21:18 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +            commentEventPublisher.publishCommentEvent(event);
Переделай пожалуйста через аннотацию и аспект, вынеси это из основного кода

2024-10-16 21:18 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V004_alter_post.sql
> -ADD COLUMN verified_date TIMESTAMPTZ;
Почему вы это удалили, я не понял? Как тогда AI орфография работать будет?

2024-10-17 11:57 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/client/UserServiceClient.java
> +@Primary
Там мок клиента есть

2024-10-17 12:02 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        if (!post.getAuthorId().equals(comment.getAuthorId())) {
проверка на то, что разные пользователи создали пост и комментарий

2024-10-17 12:02 UTC, ilu23ilu23 commented on src/main/resources/db/changelog/changeset/post_V004_alter_post.sql
> -ADD COLUMN verified_date TIMESTAMPTZ;
Там все нужные ченджлоги на месте

2024-10-17 21:04 UTC, 20cognosce requested changes
Конфликты правим наши любимые

2024-10-17 21:04 UTC, 20cognosce commented on src/main/java/faang/school/postservice/aop/aspects/CommentEventPublishingAspect.java
> +            commentEventPublisher.publishCommentEvent(event);
Это вернуть в сервисы и отсюда вызывать методы сервисов

2024-10-17 21:04 UTC, 20cognosce commented on src/main/java/faang/school/postservice/aop/aspects/CommentEventPublishingAspect.java
> +            commentEventPublisher.publishCommentEvent(event);
Можешь отдельный сервис создать

2024-10-21 20:56 UTC, 20cognosce commented
Конфликты

2024-10-21 20:57 UTC, 20cognosce commented on src/main/java/faang/school/postservice/aop/aspects/CommentEventPublishingAspect.java
> +        }
А можно в аннотации передавать енам, чтобы точно знать, на какой сущности вызывать аспект и вызывать ли вообще

2024-10-22 17:53 UTC, ilu23ilu23 commented on src/main/java/faang/school/postservice/aop/aspects/CommentEventPublishingAspect.java
> +        }
В пост сервисе нет такого енама, который обобщал бы все сущности, а если создавать, то каждый раз в него вносить новые типы, мне кажется, как-то не очень

2024-10-22 19:41 UTC, 20cognosce approved these changes

2024-10-22 19:41 UTC, merged