контроллер сделал просто для проверки что все работает (его потом уберу)
CorporationX/post_service pull request #956
Opened 2024-10-13 09:02 UTC by DankeVilletti

2024-10-13 15:44 UTC, Peregruzochka commented on src/main/resources/application.yaml
> +currency:
Перетащи эту инфу в post который на 43 строке
мы тип там все храним

2024-10-13 15:44 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    public CurrencyService(@Value("${currency.api-url}") String apiUrl,
Лучше сделать для этого класса config (`@Configuration`) и в нем уже вставляем значения из yaml

2024-10-13 15:44 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    @Retryable(value = {Exception.class},
1. Аналогично можно вынести эти значения в отдельные поля и конфигурить их в другом классе
2. А что будет если попытки закончатся, а подключение не появится?

2024-10-13 15:44 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +                    if (res.statusCode().is2xxSuccessful()) {
мб вынести это в отдельный метод?

2024-10-13 17:42 UTC, mrkorolev reviewed
Может я не понял задачу, но (в рамках коммента) предположу, что все понял)
Не ясно как ты хочешь работать с обменом (ты используешь только USD)

1) Клиент (фронт/моб) должен уметь передавать эту инфу (request param мб)
2) Тогда нужно определить enum для возможных валют, с точки зрения дизайна это выглядело бы лучше - ну, я так думаю :)

2024-10-13 17:42 UTC, mrkorolev commented on src/main/java/faang/school/postservice/config/http/WebClientConfig.java
> +}
Тут по сути важной инфы 3 строчки (ну от силы 4), это можно было в основной конфигурации положить (PostServiceApp), а вообще как хочешь :)

2024-10-13 17:42 UTC, mrkorolev commented on src/main/java/faang/school/postservice/controller/CurrencyController.java
> +    @GetMapping("/currency")
Currency - одна валюта, я бы назвал exchange-rates

2024-10-13 17:42 UTC, mrkorolev commented on src/main/resources/application.yaml
> +  api-key: "dd32616c8ec9707b977a7895"
exchange-rates-api:
----url:
----key:
----rate-usd:
 
 Дело вкуса, но структура yaml сразу понятнее

2024-10-13 17:42 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +                           @Value("${currency.conversion-rate-usd}") String conversionRateUsd,
А смысл делать для этого всего конструктор, если ты не проверяешь на входные параметры? С таким же успехом можно было делать через `@RequiredArgsConstructor`

2024-10-13 17:42 UTC, mrkorolev commented on src/main/java/faang/school/postservice/config/http/WebClientConfig.java
> +    public WebClient.Builder webClientBuilder() {
Да кстати, к разговору о неактуальности RestTemplate в Spring 6: компании которые используют этот стек (большинство) сидят на Spring Boot 2 (и соответственно Spring 5 это потолок), и в принципе компании не часто мигрируют спринговский софт просто потому, что появилась новая версия (как с JavaScript и Python) - так что я за RestTemplate :)

2024-10-13 17:42 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +        this.apiUrl = generatedUrl(apiUrl,apiKey,conversionRateUsd);
Очень необычный способ валидации (к моему комменту выше), прежде подобного не видел

2024-10-13 17:42 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    }
Надеюсь WebClient того стоил)

2024-10-14 16:30 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/controller/CurrencyController.java
> +    @GetMapping("/currency")
контроллер удалил, по заданию нужно просто достать курс всех валют (контроллер для тестирования был)

2024-10-14 16:30 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/config/http/WebClientConfig.java
> +}
оставил builder для того чтобы другие могли при необходимости добавлять свои настройки в зависимости от нужд

2024-10-14 16:32 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    public CurrencyService(@Value("${currency.api-url}") String apiUrl,
@Peregruzochka Это что еще за best practice?) Откуда?

2024-10-14 16:34 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/config/http/WebClientConfig.java
> +}
Насчет enum
когда будет у кого-то задание сделать функции для манипуляции с валютами можно будет просто без enum запрашивать из redis ключи валют какие есть, плюс минус у разных апи похожие ключи, но все равно так не будет привязки никакой к апи на мой взгляд

2024-10-16 11:02 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    public CurrencyService(@Value("${currency.api-url}") String apiUrl,
@mrkorolev 
Ориентируюсь на замечания к своему коду..

2024-10-18 12:28 UTC, 20cognosce requested changes
Также прошу подготовить демо этой фичи на ретро

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/http/WebClientConfig.java
> +                    if (res.statusCode().is4xxClientError()) {
res.isError
тебе без разницы 400 или 500

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/http/WebClientConfig.java
> +                .defaultHeader(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)  // Заголовки по умолчанию
Не пиши бессмысленные комментарии

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/config/redis/RedisProperties.java
> +
?)

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    }
В чем тут recover? в логе?)

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    }
jdbcTemplate - repository - service
webclient - ? - service

Ты из сервиса jdbcTemplate сразу не вызываешь, правильно
Ты пользуешься интерфейсом репозитория

Вынести в класс, отвечающий за вызов внешних методов апи этой биржи

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +        Map<String, Object> conversionRates = (Map<String, Object>) response.get(conversionRatesFieldName);
И это тоже, тот класс уже должен все распарсить и DTO тебе отдать

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/redis/CurrencyRedisService.java
> +    private final ObjectMapper objectMapper = new ObjectMapper()
Бин создай

2024-10-18 12:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/redis/CurrencyRedisService.java
> +    }
половина строк кода - это логи
два лога оставь, не 4
succes и error

start, end - для чего они нужны?

2024-10-18 12:28 UTC, 20cognosce commented on src/test/java/faang/school/postservice/service/currency/CurrencyRedisServiceTest.java
> +public class CurrencyRedisServiceTest {
Напиши интеграционный тест, который проверяет срабатывание джобы

2024-10-18 15:01 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/service/CurrencyService.java
> +    }
а что еще можно добавить, помимо информатирования админов о неработающей API?

2024-10-18 17:42 UTC, closed without merging