BJS2-27523: Уведомление о получении комментария (Publisher)
CorporationX/post_service pull request #958
Opened 2024-10-13 15:54 UTC by ArstanSubanov

2024-10-14 05:57 UTC, SharkB38 approved these changes

2024-10-14 05:57 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisChannelName.java
> +public class RedisChannelName {
Прикольно

2024-10-14 05:57 UTC, SharkB38 commented on src/main/java/faang/school/postservice/publisher/CommentEventPublisher.java
> +    @Retryable(retryFor = {RuntimeException.class}, backoff = @Backoff(delay = 5000))
Можно в конфиг вынести

2024-10-14 06:12 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisChannelName.java
> +public class RedisChannelName {
Но может RedisChannelNames?

2024-10-14 06:37 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +
Погоди, а где host, port?

2024-10-14 06:38 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    }
Погоди, а где host, port?

2024-10-14 07:37 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +@EnableRetry
А кстати почему здесь а не в классе приложения?

2024-10-14 07:43 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/redis/RedisChannelName.java
> +public class RedisChannelName {
Над неймингом я ещё подумаю, поэтому не стал менять, думал сделать RedisChannelNameParams)

2024-10-14 07:46 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/publisher/CommentEventPublisher.java
> +    @Retryable(retryFor = {RuntimeException.class}, backoff = @Backoff(delay = 5000))
Я просто не совсем уверен, что delay будет меняться)

2024-10-14 07:50 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    }
Как я понял, Spring boot автоматически сконфигурирует redis и сам подставит значения из yaml host и port, просто нужно правильно написать его - spring.data.redis. Ни разу не писал вручную хост и порт, но всё работает)

2024-10-14 07:55 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +@EnableRetry
Я старался по минимуму менять код, который уже написан и в основном добавлял нужные аннотации в свои конфиги которые пишу)

2024-10-14 08:26 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +@EnableRetry
Думаю стоит во всех listener'ах добавить @Retryable, звучит хайпово, думаю можно это обсудить на созвоне. Если все согласятся предлагают эту аннотацию вынести в главный класс приложения

2024-10-14 08:27 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/redis/RedisChannelName.java
> +public class RedisChannelName {
Давай на созвоне тоже обсудим, чтобы у всех единообразно было

2024-10-14 08:30 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/redis/RedisChannelName.java
> +public class RedisChannelName {
Я только за, чтобы у всех было одинаково)

2024-10-14 08:35 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +@EnableRetry
По-хорошему может и стоит вынести, но по сути, как я понял, если в одном из классов с конфигом указаны аннотации @EnableRetry, @EnableAsync или любой Enable, то эти аннотации будут распространяться на всё приложение, но можем обсудить ньюансы на созвоне)

2024-10-15 17:33 UTC, mysosnovskaya requested changes

2024-10-15 17:33 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +@EnableRetry
Да, такие аннотации как правило указываются в главном классе приложения. Так сразу видно, что вообще в приложении используется)

2024-10-15 17:33 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/redis/RedisConfig.java
> +    public RedisTemplate<String, Object> redisTemplate() {
А зачем этот redisTemplate? Мы договорились создавать под каждый тип значения разные темплейты, тогда этот будто бы и не нужен)

2024-10-15 17:33 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/publisher/CommentEventPublisher.java
> +    @Retryable(retryFor = {RuntimeException.class}, backoff = @Backoff(delay = 5000))
Как правило, он не меняется, но и как правило - любые такие настройки выносят в конфиг. Можно воспринимать это правилом хорошего тона)

2024-10-15 17:33 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/publisher/UserBanEventPublisher.java
> +    public UserBanEventPublisher(RedisTemplate<String, Object> redisTemplate,
А, вот он где, с Object. Обновим под установленные правила?

2024-10-17 19:14 UTC, mysosnovskaya approved these changes

2024-10-17 19:14 UTC, merged