add likeEvent publisher
CorporationX/post_service pull request #969
Opened 2024-10-14 17:29 UTC by DankeVilletti

Отправлять событие LikeEvent через LikeEventPublisher в момент, когда пользователь лайкает пост другого пользователя — вызывает соответствующий эндпоинт. В событии содержатся: id поста; id автора; id юзера; который лайкает; дата и время.

2024-10-16 10:59 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/dto/like/PostLikeEventDto.java
> +public class PostLikeEventDto extends AbstractLikeEvent {
Для чего дто нужен класс абстракции?

2024-10-16 10:59 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/publis/publisher/LikeEventPublisher.java
> +        log.info("Send LikeEvent message to NotificationService: {} to channel: {}", message, likeEventChannel);
Ты же с аналитикой работаешь)
А даже если бы и нет, то Publisher не шарит кому именно придет эта инфа
Он только в курсе, что он работает с брокером и все

2024-10-16 10:59 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        //в пост добавляется лайк, но не вижу сохранения поста
рил какие-то технические шоколадки...не понятно...

2024-10-16 10:59 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        publishPostLikeEventToBroker(newLike, post);
Я бы вызвал просто один метод likeEventPublish.publish(newLike)
1. Не совсем понятно для чего ты делаешь методы publishPostLikeEventToBroker здесь и в likeEventPublish
2. В entity like полюбому содержиться инфа о том, к какому посту он относиться

2024-10-16 13:56 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/dto/like/PostLikeEventDto.java
> +public class PostLikeEventDto extends AbstractLikeEvent {
есть еще лайки для комментариев

2024-10-16 14:03 UTC, DankeVilletti commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        publishPostLikeEventToBroker(newLike, post);
Сейчас разобрался с тем какая загрузка сущности Like, она сейчас жадная(по умолчанию), а я думал ленивая, поэтому не хотел неявных запросов при получении idPost, но все ок, не должно быть неявных запросов, поэтому переделаю

2024-10-17 09:05 UTC, MamadjonovKO commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        //в пост добавляется лайк, но не вижу сохранения поста
Это вроде как automatic dirty checking, если я правильно понял вопрос (: 

Когда мы фетчим сущность из бд с помощью Hibernate, он а становится управляемой в рамках текущей транзакции и любые изменения которые вносятся в эту сущность (например добавление лайка к посту), автоматически отслеживаются Hibernate благодаря механизму dirty checking.

https://medium.com/jpa-java-persistence-api-guide/dirty-checking-magic-in-hibernate-how-it-works-and-why-its-important-3cdb422dc4d4

2024-10-18 19:28 UTC, 20cognosce requested changes

2024-10-18 19:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publis/publisher/LikeEventPublisher.java
> +        log.info("Send LikeEvent to Brokers channel: {} , message: {}", message, likeEventChannel);
Почему вне try блока

2024-10-18 19:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        //в пост добавляется лайк, но не вижу сохранения поста
Во-первых, не нужно сетить список, если ты по его ссылке уже добавил лайк
Во-вторых, да, то что написал Коби - так работает хибер, что при закрытии транзакции по изменениям всех сущностей, КОТОРЫЕ ДОСТАЛИ ИЗ БАЗЫ ВО ВРЕМЯ ТРАНЗАКЦИИ выполняет flush изменений, и поэтому сущность поста обновляется. 

Сохраняется ли новая сущность лайка при этом - ну, похоже должна. 

Но я не люблю такие скрытые манипуляции, поэтому прошу всегда явно вызывать метод репозитория.

Комментарии убери.

2024-10-18 19:28 UTC, 20cognosce commented on src/main/resources/application.yaml
> +          name: calculations_channel  # я так понимаю никто не использует?
Для кого ты на ПРе отставляешь комментарии
Спроси в чате канала команды, задай вопрос, ребята ответят

Убери ненужные комментарии из кода

2024-10-18 19:28 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/LikeService.java
> +        //в пост добавляется лайк, но не вижу сохранения поста
Вызов паблишера по ивенту лучше переделать на аннотацию с помощью аспекта, а не модифицировать бизнесовый код

2024-10-21 20:43 UTC, 20cognosce requested changes

2024-10-21 20:43 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publis/aspect/like/LikeEventAspect.java
> +        return result;
Зачем ты первой строчкой объявил result
если в return можно вызывать proceed

Переделай аспект, чтобы он запускался по завершению метода
иначе ты паблишишь событие до того, как оно обработалось.
Твой метод, над которым аспект, упадет и мы отправим в топик бред

2024-10-21 20:43 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publis/publisher/like/LikeEventPublisher.java
> +        String valueAsString;
Что это опять, почему оно здесь

2024-10-21 20:43 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/LikeService.java
> +    @PublishLikeEvent
Лучше переименуй @NotificationEvent и в параметрах аннотации енамом передавай "LIKE"

2024-10-24 20:26 UTC, 20cognosce approved these changes

2024-10-24 20:27 UTC, merged