ban user post
CorporationX/post_service pull request #972
Opened 2024-10-16 14:19 UTC by aassylkhan

2024-10-16 14:36 UTC, SharkB38 requested changes

2024-10-16 14:36 UTC, SharkB38 commented on src/main/java/faang/school/postservice/config/RedisConfig.java
> +package faang.school.postservice.config;
Не знаю чей конфиг, но кому то надо его поправить

2024-10-16 14:36 UTC, SharkB38 commented on src/main/java/faang/school/postservice/scheduler/AuthorBanner.java
> +@EnableRetry
Это я бы перенес в главный класс приложения

2024-10-16 14:36 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    private static final int UNVERIFIED_POSTS_LIMIT = 5;
Это мб в конфиг?

2024-10-16 14:36 UTC, SharkB38 commented on src/main/resources/application.yaml
> +          name: user_ban_channel
Тут тоже чутка подправить надо, https://discord.com/channels/1102662981743030334/1267555771944796171/1295396116313149516

2024-10-16 14:36 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +    private static final int UNVERIFIED_POSTS_LIMIT = 5;
А ну это получается здесь вообще не нужно?

2024-10-16 14:36 UTC, SharkB38 commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        List<Long> authorIds = postRepository.findAuthorIdsToBan(banPostLimit);
Я немного не уверен с прокидыванием вот этого параметра через несколько классов. Может лимит постов в сервисе только оставить?

2024-10-16 14:42 UTC, aassylkhan commented on src/main/java/faang/school/postservice/config/RedisConfig.java
> +package faang.school.postservice.config;
у нас Арстаном один конфиг, по этому в общий перевел

2024-10-16 16:08 UTC, soulasphyxia commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        List<Long> authorIds = postRepository.findAuthorIdsToBan(banPostLimit);
я согласен с Валерой. метод сервиса могут вызывать из разных мест и постоянно туда эту константу передавать как будто не оч, да и давать возможность из вне задавать какой лимит, раз у нас есть определенное правило бана, тоже не есть хорошо(по невнимательности или специально могут передать любое число и все начнет работать не совсем правильно)

2024-10-16 16:15 UTC, soulasphyxia commented on src/main/resources/application.yaml
> +    verify-task-executor:
мне кажется, тут нужна Маша. мы вроде как договорились делать общий тредпул, соответсвенно лучше наверное в конфиге вынести этот тредпул как общий, не относящийся к user_ban. интуиция подсказывает, что тут есть приятное поле thread-name-prefix, на котором в логах наверное удобно смотреть в каком потоке что конкретно сломалось, но я не уверен, попрошу Машу тут ответить

2024-10-16 16:17 UTC, soulasphyxia commented on src/main/resources/db/changelog/changeset/post_V005_update_post_add_verified.sql
> +ALTER TABLE post
я не сильно разбираюсь в миграциях, почему нельзя в уже готовый скрипт добавлять колонки? мне кажется, что в любом случае скрипт отработает корректно, просто интересно почему ты выбрал вариант через ALTER

2024-10-17 03:28 UTC, ArstanSubanov reviewed
Думаю, тебе стоит подождать, пока этот мой ПР: https://github.com/CorporationX/post_service/pull/958 не смержат и себе накатить изменения, там я поменял согласно обсуждению на последнем ретро)

2024-10-17 03:28 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/config/RedisConfig.java
> +package faang.school.postservice.config;
Он сделал как у меня было, до того как мы все договорились о правилах конфига и т.д. Я уже всё исправил в своей задаче)

2024-10-17 03:28 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +                throw new UserBanException("Failed to publish ban event for author ID " + authorId, e);
Я в MessagePublisher уже добавил блок try/catch и повторные вызовы, тут можно убрать)

2024-10-17 03:28 UTC, ArstanSubanov commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        List<Long> authorIds = postRepository.findAuthorIdsToBan(banPostLimit);
Мне Маша в ревью к подобной задаче писала передавать параметр из джобы)

2024-10-17 03:28 UTC, ArstanSubanov commented on src/main/resources/application.yaml
> +    verify-task-executor:
Согласен, этого я не менял, можешь поменять)

2024-10-17 03:28 UTC, ArstanSubanov commented on src/main/resources/db/changelog/changeset/post_V005_update_post_add_verified.sql
> +ALTER TABLE post
В миграции, советуют изменять через новый файл, так как ты можешь отследить все изменения, а также избежать ошибки. Когда в миграцию добавляется новый файл, то у него автоматически в логах сохраняется его id. Когда ты изменишь файл, его id может поменяться и не совпасть с id который хранится в логах и приложение не запустится, нужно будет у всех чистить логи)

2024-10-17 19:22 UTC, mysosnovskaya requested changes

2024-10-17 19:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/config/AsyncConfig.java
> +public class AsyncConfig {
У нас уже был класс TaskExecutorConfig, его нельзя удалять и вместо него подставлять свой. Мы предполагаем, что старый класс уже давно работает в продакшне и работает без ошибок. Поэтому всегда отдаем предпочтение уже гарантированно работающему. Нет смысла писать то же самое заново, но другими словами) Так что верни TaskExecutorConfig

2024-10-17 19:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/repository/PostRepository.java
> +            HAVING COUNT(p.id) > :banPostLimit
Класс 👍 Круто, что ты сделал это не в коде, а через базу

2024-10-17 19:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/scheduler/AuthorBanner.java
> +        postService.banAuthorsWithUnverifiedPostsMoreThan();
Если в названии метода moreThan - значит у метода должен быть параметр, говорящий, больше какого количества должно быть таких постов

2024-10-17 19:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentServiceImpl.java
> +    @Async("commonTaskExecutor")
Надо вернуть

2024-10-17 19:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/impl/PostServiceImpl.java
> +        List<Long> authorIds = postRepository.findAuthorIdsToBan(banPostLimit);
Да, а в джобе уже должен быть параметр. Метод должен быть гибким и иметь возможность банить разное количество авторов) Сервис сам не решает, сколько авторов забанить, - ему об это говорят те, кто его вызвал

2024-10-17 19:25 UTC, mysosnovskaya commented on src/main/resources/db/changelog/changeset/post_V005_update_post_add_verified.sql
> +ALTER TABLE post
Уже использованную миграцию менять категорически нельзя) Миграции - это как коммиты в гите. Ты же не меняешь старый коммит, чтобы сделать фикс, а делаешь новый коммит. Вот и здесь такая же история)

2024-10-21 11:17 UTC, closed without merging