BJS2-26890 - Бан юзера за глиной коммент (ну или как там было не помню, лень проверять)
CorporationX/post_service pull request #978
Opened 2024-10-16 20:27 UTC by mrkorolev

Прочитал Димин коммент относительно публикации списка юзеров, но не понял его. Можно подробней объяснить почему это плохо?

2024-10-20 21:26 UTC, Peregruzochka reviewed
Минус балл за лень
А так мне все понравилось + плюс все очень понятно

2024-10-20 21:26 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    public List<Long> getAuthorIdsToBeBanned() {
Вроде как Transactional

2024-10-20 21:26 UTC, Peregruzochka commented on src/test/java/faang/school/postservice/scheduler/CommentBannerTest.java
> +            verify(publisher, times(1)).publish(id.toString());
а тут нельзя поставить times, равный значению ids.size()?

2024-10-20 21:44 UTC, mrkorolev commented on src/test/java/faang/school/postservice/scheduler/CommentBannerTest.java
> +            verify(publisher, times(1)).publish(id.toString());
Так он же вызывается один раз для каждого аргумента (они должны быть разными)

2024-10-20 21:45 UTC, mrkorolev commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +    public List<Long> getAuthorIdsToBeBanned() {
Так он просто читает, вызов одного метода из репозитория

2024-10-20 21:51 UTC, Peregruzochka commented on src/test/java/faang/school/postservice/scheduler/CommentBannerTest.java
> +            verify(publisher, times(1)).publish(id.toString());
anyLong)

2024-10-20 21:54 UTC, mrkorolev commented on src/test/java/faang/school/postservice/scheduler/CommentBannerTest.java
> +            verify(publisher, times(1)).publish(id.toString());
Такая тема вроде юзается когда у тебя параметры формируются именно в самом тестируемом методе. У меня же они приходят из репозитория. Короче посмотрим)

2024-10-21 20:53 UTC, 20cognosce requested changes

2024-10-21 20:53 UTC, 20cognosce commented on src/main/java/faang/school/postservice/redis/publisher/BanAuthorPublisher.java
> +    public void publish(String message) {
DTO

2024-10-21 20:53 UTC, 20cognosce commented on src/main/java/faang/school/postservice/redis/publisher/MessagePublisher.java
> +    void publish(String message);
DTO

2024-10-21 20:53 UTC, 20cognosce commented on src/main/java/faang/school/postservice/repository/CommentRepository.java
> +        WHERE c.verified = false
Не понял, разве это не енам? PENDING, VERIFIED, REJECTED

Если пользователь только создал 5 постов одновременно, они все еще не проверифицированы

2024-10-21 20:53 UTC, 20cognosce commented on src/main/java/faang/school/postservice/scheduler/CommentBanner.java
> +        authorIdsToBeBanned.forEach(id -> publisher.publish(id.toString()));
Ну мета инфу посылай какую-нибудь, ну что это за язык инопланетян

2024-10-21 20:53 UTC, 20cognosce commented on src/main/resources/db/changelog/changeset/post_V011_add_column_verified_to_comment.sql
> +ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT true;
А кто верифицирует комменты?
Я уже не помню контекста той задачи

Но однозначно, если 5 комментов одновременно написать, у них у всех какой статус будет?

2024-10-26 12:32 UTC, 20cognosce approved these changes

2024-10-26 12:32 UTC, merged