Получение достижения "Писатель"
CorporationX/post_service pull request #979
Opened 2024-10-17 13:26 UTC by Peregruzochka

2024-10-24 20:44 UTC, 20cognosce requested changes

2024-10-24 20:44 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publis/publisher/PostEventPublisher.java
> +        redisTemplate.convertAndSend(postEventChannelName, valueAsString);
то есть ты обернул парсинг в try catch
а отправку сообщения в брокер ты ничем не обернул

приоритеты

2024-10-24 20:44 UTC, 20cognosce commented on src/main/java/faang/school/postservice/service/PostService.java
> +        return savedPost;
Не трогать бизнесовый код, аспект напиши

2024-10-25 11:56 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/publis/publisher/PostEventPublisher.java
> +        redisTemplate.convertAndSend(postEventChannelName, valueAsString);
@20cognosce
А зачем мне оборачивать отправку сообщения?
Если convertAndSend ничего не бросает?

2024-10-26 12:07 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publis/publisher/PostEventPublisher.java
> +        redisTemplate.convertAndSend(postEventChannelName, valueAsString);
Если в его сигнатуре не написано, что он ничего не бросает, это еще не значит, что там нет будет рантайм эксепшеном
попробуй отправить месседж в несуществующий топик, что выдаст? Ничего?

2024-10-26 12:10 UTC, 20cognosce approved these changes

2024-10-26 12:10 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publis/publisher/PostEventPublisher.java
> +        String valueAsString;
Почему это тут висит

2024-10-26 12:10 UTC, merged