Post view publisher done
CorporationX/post_service pull request #980
Opened 2024-10-17 15:41 UTC by MamadjonovKO

2024-10-18 16:05 UTC, Peregruzochka reviewed
У вас какие-то конфликты

2024-10-18 16:05 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/event/PostViewEvent.java
> +public class PostViewEvent {
А почему это не dto?

2024-10-18 16:05 UTC, Peregruzochka commented on src/main/java/faang/school/postservice/service/PostService.java
> +        PostViewEvent event = new PostViewEvent(post.getId(), post.getAuthorId(), viewerId, LocalDateTime.now());
мб стоит формировать dto внутри publisher? а в сам publisher передавать post? мы вроде так с контроллером делали

2024-10-24 20:29 UTC, 20cognosce requested changes

2024-10-24 20:29 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/PostViewEventPublisher.java
> +public class PostViewEventPublisher {
Разве нет никакого абстрактного, от которого унаследоваться?

2024-10-24 20:29 UTC, 20cognosce commented on src/test/java/faang/school/postservice/PostServiceTest.java
> +
И где тесты?)

2024-10-26 12:25 UTC, 20cognosce approved these changes

2024-11-05 20:04 UTC, 20cognosce approved these changes

2024-11-05 20:04 UTC, merged