BJS2-26181  Publisher, RedisConfig for post service
CorporationX/post_service pull request #982
Opened 2024-10-17 20:17 UTC by Silencemess1ah

- Publisher CommentEvent
-  redis config without tests 
- some refactors

2024-10-17 21:03 UTC, GusevVrn reviewed
прям 1 в 1 по документации оракла)))

2024-10-17 21:03 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/redis/RedisProperties.java
> +    private int port;
лишние

2024-10-17 21:03 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/comment/CommentEventPublisher.java
> +        log.debug("Sent message with id : {} in {}", message.getCommentId(),
ну тут в целом можно весь объект передавать, он достаточно маленький
просто в целом читается как будто ты выводишь айдишник сообщения редиса

2024-10-17 21:03 UTC, GusevVrn commented on src/main/java/faang/school/postservice/publisher/comment/CommentEventPublisher.java
> +@Builder
зачем тут так много аннотаций

2024-10-17 21:03 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/EventDto.java
> +public abstract class EventDto {
ну я задумку понял, но ты чет ее не реализовал же

2024-10-17 21:03 UTC, GusevVrn commented on src/main/java/faang/school/postservice/dto/comment/CommentEventDto.java
> +@EqualsAndHashCode(callSuper = true)
а это зачем?

2024-10-17 21:10 UTC, GusevVrn commented
а и с тестами че

2024-10-18 20:18 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/publisher/comment/CommentEventPublisher.java
> +        log.debug("Sent message with id : {} in {}", message.getCommentId(),
Не понял, ты подумал что я стрингу кидаю? Переименую

2024-10-18 20:18 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/publisher/comment/CommentEventPublisher.java
> +@Builder
Ща разберемси

2024-10-18 20:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/dto/EventDto.java
> +public abstract class EventDto {
Удалю

2024-10-18 20:19 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/dto/comment/CommentEventDto.java
> +@EqualsAndHashCode(callSuper = true)
В другом ПРе ответил, уйдет

2024-10-18 20:20 UTC, Silencemess1ah commented
> а и с тестами че

Тесты напишу, пока на ревью кинул посмотреть косяки, сам факт что все работает, тесты щас настрочу с правками сразу и закину на ревью дальше
> прям 1 в 1 по документации оракла))) 

ну че началось то

2024-10-19 14:22 UTC, mysosnovskaya requested changes
Жду фикса конфликтов)

2024-10-19 14:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        return CommentEventDto.builder()
Лучше через маппер)

2024-10-19 14:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/user/UserDto.java
> +    private String phone;
Поясни, зачем это?

2024-10-20 09:29 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/dto/user/UserDto.java
> +    private String phone;
Это сделано потому что в User Service Паша давно делал задачку и добавил кучу полей в UserDto, которых нет в Post Service-ном UserDto, а так как мы ходим туда из (пост -> юзер) и получаем дто он ругается что приходит больше чем есть

2024-10-20 09:30 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        return CommentEventDto.builder()
А лучше почему ? Не генерировать новый объект и отправлять ,а существующий перегнать быстрее и эффективнее?

2024-10-20 19:22 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/comment/CommentService.java
> +        return CommentEventDto.builder()
Ради единообразного подхода и соблюдения стиля проекта. Ну и я не вижу какого-то явного преимущества в билдере в этом случае. А если нет явного аргумента, то по умолчанию используется общепринятый подход в команде

2024-10-20 19:23 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/dto/user/UserDto.java
> +    private String phone;
Необязательно было добавлять новые поля, можно было, например, игнорировать те поля, которые пришли в json, но не сложились в dto. Это отдельно настраивается. Но хорошо, я поняла, пусть будет так)

2024-10-20 19:24 UTC, mysosnovskaya approved these changes

2024-10-20 21:16 UTC, merged