BJS2-27124 Getting the achievement 'Writer'
CorporationX/post_service pull request #996
Opened 2024-10-19 18:00 UTC by amilosh

2024-10-20 11:03 UTC, sultan-inked commented on src/main/java/faang/school/postservice/publisher/PostCreatedEventPublisher.java
> +        Post post = (Post) returnedValue;
Думаешь достаточно просто каст ексепшна, без точной информации почему? Вроде норм, интересно что дима скажет

2024-10-20 11:03 UTC, sultan-inked commented on src/test/java/faang/school/postservice/publisher/PostCreatedEventPublisherTest.java
> +
чтрочка)

2024-10-21 15:13 UTC, amilosh commented on src/main/java/faang/school/postservice/publisher/PostCreatedEventPublisher.java
> +        Post post = (Post) returnedValue;
Я сделал из предположения, что метод createPost всегда будет возвращать Post.
А если кто-то в будущем захочет вернуть что-то другое - пол прилаги придется менять.
Оставил без трйуетчев, чтоб не засорять.

2024-10-24 20:57 UTC, 20cognosce requested changes

2024-10-24 20:57 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/PostViewEventPublisher.java
> +                    });
sendEntityToAnalytics выглядело лучше имхо

2024-10-25 14:49 UTC, amilosh commented on src/main/java/faang/school/postservice/publisher/PostViewEventPublisher.java
> +                    });
Вернул обратно.
Только разделил на два абсракных класса
AbstractEventPublisher - для моего кейса
AbstractEventPublisher - для кейса, который был уже

2024-11-08 18:22 UTC, 20cognosce approved these changes

2024-11-08 18:22 UTC, 20cognosce commented on src/main/java/faang/school/postservice/publisher/PostCreatedEventPublisher.java
> +    @AfterReturning(
Нужно асинхронно вызывать аспект иначе, как показал Ваня, он будет внутри транзакции выполняться

2024-11-08 18:22 UTC, merged

2024-11-14 16:56 UTC, amilosh commented on src/main/java/faang/school/postservice/publisher/PostCreatedEventPublisher.java
> +    @AfterReturning(
Добавил `@Async("redisPublisherAsyncThreadPool")`