feature-BJS2-26161: Анализ просмотров постов (post_service)
CorporationX/post_service pull request #997
Opened 2024-10-19 20:32 UTC by StepnovaVarvara

2024-10-20 12:53 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/jackson/JacksonConfig.java
> +    public ObjectMapper objectMapper() {
а почему object mapper в jackson config?

2024-10-20 12:53 UTC, GusevVrn commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +    ChannelTopic likePostEventTopic() {
делай топики public, я где-то столкнулся с ошибкой, spring не знал какой заинжектить, вот public помог

2024-10-20 12:53 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postViewEventPublisher.publish(postViewEvent);
вынеси в отдельный метод то что ты добавила. для мапинга используй object mapper

2024-10-20 12:53 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/publisher/LikePostEventPublisher.java
> +    public LikePostEventPublisher(RedisTemplate redisTemplate,
убирай конструкторы, назови переменные топика, как они в конфигурации называются

2024-10-20 12:53 UTC, GusevVrn commented on src/main/java/faang/school/postservice/service/publisher/PostViewEventPublisher.java
> +    public PostViewEventPublisher(RedisTemplate redisTemplate,
аналогично

2024-10-20 18:46 UTC, Silencemess1ah commented on src/main/java/faang/school/postservice/service/publisher/LikePostEventPublisher.java
> +    public LikePostEventPublisher(RedisTemplate redisTemplate,
Да, плюсую, все подтянется по именам бинов

2024-10-21 19:52 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/config/redis/RedisConfiguration.java
> +    ChannelTopic likePostEventTopic() {
поняла, спасибочки!)

2024-10-21 19:53 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/publisher/LikePostEventPublisher.java
> +    public LikePostEventPublisher(RedisTemplate redisTemplate,
готово

2024-10-21 19:56 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/publisher/PostViewEventPublisher.java
> +    public PostViewEventPublisher(RedisTemplate redisTemplate,
готово

2024-10-21 20:27 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/config/jackson/JacksonConfig.java
> +    public ObjectMapper objectMapper() {
Мне помог Сережа!)

2024-10-22 17:11 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +        postViewEventPublisher.publish(postViewEvent);
Перенесла

2024-10-22 20:11 UTC, mysosnovskaya requested changes

2024-10-22 20:11 UTC, mysosnovskaya commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .authorId(postAuthorId)
А userId почему не проставляется? Его из контекста можно достать ([UserContext](https://github.com/CorporationX/post_service/blob/unicorn-master-stream6/src/main/java/faang/school/postservice/config/context/UserContext.java))

2024-10-23 17:22 UTC, StepnovaVarvara commented on src/main/java/faang/school/postservice/service/post/PostService.java
> +                .authorId(postAuthorId)
Помогла, спасибочки

2024-10-23 19:09 UTC, mysosnovskaya approved these changes

2024-10-23 19:25 UTC, merged